// Bộ từ vựng ĐỘNG VẬT lớn (dùng cho chủ đề /tu-vung-tieng-anh/dong-vat).
// Gom theo nhóm để dễ tra & tránh trùng. Mỗi từ: en, ipa (giọng Mỹ), vi, emoji.
// Con nào không có emoji riêng dùng 🐾.

import type { VocabWord } from './vocab';

export const ANIMALS: VocabWord[] = [
  // ── Thú cưng & vật nuôi trong nhà ─────────────────────────────
  { en: 'dog', ipa: '/dɔːɡ/', vi: 'con chó', emoji: '🐶', example: 'The dog is running.', exampleVi: 'Con chó đang chạy.' },
  { en: 'puppy', ipa: '/ˈpʌpi/', vi: 'chó con', emoji: '🐶' },
  { en: 'cat', ipa: '/kæt/', vi: 'con mèo', emoji: '🐱', example: 'The cat is sleeping.', exampleVi: 'Con mèo đang ngủ.' },
  { en: 'kitten', ipa: '/ˈkɪtn/', vi: 'mèo con', emoji: '🐱' },
  { en: 'rabbit', ipa: '/ˈræbɪt/', vi: 'con thỏ', emoji: '🐰' },
  { en: 'hamster', ipa: '/ˈhæmstər/', vi: 'chuột hamster', emoji: '🐹' },
  { en: 'guinea pig', ipa: '/ˈɡɪni pɪɡ/', vi: 'chuột lang', emoji: '🐹' },
  { en: 'goldfish', ipa: '/ˈɡoʊldfɪʃ/', vi: 'cá vàng', emoji: '🐠' },
  { en: 'ferret', ipa: '/ˈferɪt/', vi: 'chồn sương', emoji: '🐾' },
  { en: 'gerbil', ipa: '/ˈdʒɜːrbɪl/', vi: 'chuột nhảy', emoji: '🐹' },
  { en: 'canary', ipa: '/kəˈneri/', vi: 'chim hoàng yến', emoji: '🐤' },
  { en: 'budgie', ipa: '/ˈbʌdʒi/', vi: 'vẹt yến phụng', emoji: '🦜' },

  // ── Vật nuôi ở nông trại ─────────────────────────────────────
  { en: 'cow', ipa: '/kaʊ/', vi: 'con bò', emoji: '🐮' },
  { en: 'bull', ipa: '/bʊl/', vi: 'bò đực', emoji: '🐂' },
  { en: 'calf', ipa: '/kæf/', vi: 'con bê', emoji: '🐄' },
  { en: 'ox', ipa: '/ɑːks/', vi: 'con bò kéo', emoji: '🐂' },
  { en: 'buffalo', ipa: '/ˈbʌfəloʊ/', vi: 'con trâu', emoji: '🐃' },
  { en: 'horse', ipa: '/hɔːrs/', vi: 'con ngựa', emoji: '🐴' },
  { en: 'pony', ipa: '/ˈpoʊni/', vi: 'ngựa nhỏ', emoji: '🐴' },
  { en: 'donkey', ipa: '/ˈdɑːŋki/', vi: 'con lừa', emoji: '🫏' },
  { en: 'mule', ipa: '/mjuːl/', vi: 'con la', emoji: '🐴' },
  { en: 'pig', ipa: '/pɪɡ/', vi: 'con lợn', emoji: '🐷' },
  { en: 'piglet', ipa: '/ˈpɪɡlət/', vi: 'lợn con', emoji: '🐖' },
  { en: 'sheep', ipa: '/ʃiːp/', vi: 'con cừu', emoji: '🐑' },
  { en: 'lamb', ipa: '/læm/', vi: 'cừu con', emoji: '🐑' },
  { en: 'goat', ipa: '/ɡoʊt/', vi: 'con dê', emoji: '🐐' },
  { en: 'chicken', ipa: '/ˈtʃɪkɪn/', vi: 'con gà', emoji: '🐔' },
  { en: 'rooster', ipa: '/ˈruːstər/', vi: 'gà trống', emoji: '🐓' },
  { en: 'hen', ipa: '/hen/', vi: 'gà mái', emoji: '🐔' },
  { en: 'chick', ipa: '/tʃɪk/', vi: 'gà con', emoji: '🐤' },
  { en: 'duck', ipa: '/dʌk/', vi: 'con vịt', emoji: '🦆' },
  { en: 'duckling', ipa: '/ˈdʌklɪŋ/', vi: 'vịt con', emoji: '🐥' },
  { en: 'goose', ipa: '/ɡuːs/', vi: 'con ngỗng', emoji: '🦢' },
  { en: 'turkey', ipa: '/ˈtɜːrki/', vi: 'gà tây', emoji: '🦃' },
  { en: 'llama', ipa: '/ˈlɑːmə/', vi: 'lạc đà không bướu', emoji: '🦙' },
  { en: 'alpaca', ipa: '/ælˈpækə/', vi: 'lạc đà Alpaca', emoji: '🦙' },

  // ── Họ mèo lớn ───────────────────────────────────────────────
  { en: 'lion', ipa: '/ˈlaɪən/', vi: 'sư tử', emoji: '🦁' },
  { en: 'tiger', ipa: '/ˈtaɪɡər/', vi: 'con hổ', emoji: '🐯' },
  { en: 'leopard', ipa: '/ˈlepərd/', vi: 'con báo', emoji: '🐆' },
  { en: 'cheetah', ipa: '/ˈtʃiːtə/', vi: 'báo săn', emoji: '🐆' },
  { en: 'jaguar', ipa: '/ˈdʒæɡwɑːr/', vi: 'báo đốm', emoji: '🐆' },
  { en: 'panther', ipa: '/ˈpænθər/', vi: 'báo đen', emoji: '🐆' },
  { en: 'cougar', ipa: '/ˈkuːɡər/', vi: 'sư tử núi', emoji: '🐆' },
  { en: 'lynx', ipa: '/lɪŋks/', vi: 'mèo rừng Lynx', emoji: '🐈' },
  { en: 'bobcat', ipa: '/ˈbɑːbkæt/', vi: 'mèo rừng đuôi cộc', emoji: '🐈' },
  { en: 'panther cat', ipa: '/ˈpænθər kæt/', vi: 'báo hoa mai', emoji: '🐆' },

  // ── Gấu ──────────────────────────────────────────────────────
  { en: 'bear', ipa: '/ber/', vi: 'con gấu', emoji: '🐻' },
  { en: 'polar bear', ipa: '/ˈpoʊlər ber/', vi: 'gấu Bắc Cực', emoji: '🐻‍❄️' },
  { en: 'panda', ipa: '/ˈpændə/', vi: 'gấu trúc', emoji: '🐼' },
  { en: 'grizzly bear', ipa: '/ˈɡrɪzli ber/', vi: 'gấu xám', emoji: '🐻' },
  { en: 'koala', ipa: '/koʊˈɑːlə/', vi: 'gấu túi', emoji: '🐨' },

  // ── Linh trưởng ──────────────────────────────────────────────
  { en: 'monkey', ipa: '/ˈmʌŋki/', vi: 'con khỉ', emoji: '🐵' },
  { en: 'gorilla', ipa: '/ɡəˈrɪlə/', vi: 'khỉ đột', emoji: '🦍' },
  { en: 'chimpanzee', ipa: '/ˌtʃɪmpænˈziː/', vi: 'tinh tinh', emoji: '🐒' },
  { en: 'orangutan', ipa: '/ɔːˈræŋətæn/', vi: 'đười ươi', emoji: '🦧' },
  { en: 'baboon', ipa: '/bæˈbuːn/', vi: 'khỉ đầu chó', emoji: '🐒' },
  { en: 'gibbon', ipa: '/ˈɡɪbən/', vi: 'vượn', emoji: '🐒' },
  { en: 'lemur', ipa: '/ˈliːmər/', vi: 'vượn cáo', emoji: '🐒' },
  { en: 'macaque', ipa: '/məˈkæk/', vi: 'khỉ vàng', emoji: '🐒' },
  { en: 'mandrill', ipa: '/ˈmændrɪl/', vi: 'khỉ Mandrill', emoji: '🐒' },
  { en: 'sloth', ipa: '/slɔːθ/', vi: 'con lười', emoji: '🦥' },

  // ── Thú lớn ăn cỏ ────────────────────────────────────────────
  { en: 'elephant', ipa: '/ˈelɪfənt/', vi: 'con voi', emoji: '🐘', example: 'The elephant is big.', exampleVi: 'Con voi to lớn.' },
  { en: 'giraffe', ipa: '/dʒəˈræf/', vi: 'hươu cao cổ', emoji: '🦒' },
  { en: 'zebra', ipa: '/ˈziːbrə/', vi: 'ngựa vằn', emoji: '🦓' },
  { en: 'rhinoceros', ipa: '/raɪˈnɑːsərəs/', vi: 'tê giác', emoji: '🦏' },
  { en: 'hippopotamus', ipa: '/ˌhɪpəˈpɑːtəməs/', vi: 'hà mã', emoji: '🦛' },
  { en: 'camel', ipa: '/ˈkæml/', vi: 'lạc đà', emoji: '🐫' },
  { en: 'deer', ipa: '/dɪr/', vi: 'con hươu', emoji: '🦌' },
  { en: 'reindeer', ipa: '/ˈreɪndɪr/', vi: 'tuần lộc', emoji: '🦌' },
  { en: 'moose', ipa: '/muːs/', vi: 'nai sừng tấm', emoji: '🫎' },
  { en: 'elk', ipa: '/elk/', vi: 'nai Elk', emoji: '🦌' },
  { en: 'antelope', ipa: '/ˈæntɪloʊp/', vi: 'linh dương', emoji: '🦌' },
  { en: 'gazelle', ipa: '/ɡəˈzel/', vi: 'linh dương Gazelle', emoji: '🦌' },
  { en: 'bison', ipa: '/ˈbaɪsn/', vi: 'bò rừng Bison', emoji: '🦬' },
  { en: 'wildebeest', ipa: '/ˈwɪldɪbiːst/', vi: 'linh dương đầu bò', emoji: '🐃' },
  { en: 'warthog', ipa: '/ˈwɔːrthɔːɡ/', vi: 'lợn rừng châu Phi', emoji: '🐗' },
  { en: 'boar', ipa: '/bɔːr/', vi: 'lợn rừng', emoji: '🐗' },

  // ── Họ chó & cáo ─────────────────────────────────────────────
  { en: 'wolf', ipa: '/wʊlf/', vi: 'chó sói', emoji: '🐺' },
  { en: 'fox', ipa: '/fɑːks/', vi: 'con cáo', emoji: '🦊' },
  { en: 'coyote', ipa: '/kaɪˈoʊti/', vi: 'chó sói đồng cỏ', emoji: '🐺' },
  { en: 'jackal', ipa: '/ˈdʒækl/', vi: 'chó rừng', emoji: '🐺' },
  { en: 'hyena', ipa: '/haɪˈiːnə/', vi: 'linh cẩu', emoji: '🐆' },
  { en: 'dingo', ipa: '/ˈdɪŋɡoʊ/', vi: 'chó hoang Úc', emoji: '🐕' },

  // ── Gặm nhấm & thú nhỏ ───────────────────────────────────────
  { en: 'mouse', ipa: '/maʊs/', vi: 'con chuột nhắt', emoji: '🐭' },
  { en: 'rat', ipa: '/ræt/', vi: 'con chuột cống', emoji: '🐀' },
  { en: 'squirrel', ipa: '/ˈskwɜːrəl/', vi: 'con sóc', emoji: '🐿️' },
  { en: 'chipmunk', ipa: '/ˈtʃɪpmʌŋk/', vi: 'sóc chuột', emoji: '🐿️' },
  { en: 'beaver', ipa: '/ˈbiːvər/', vi: 'hải ly', emoji: '🦫' },
  { en: 'porcupine', ipa: '/ˈpɔːrkjupaɪn/', vi: 'con nhím lông', emoji: '🦔' },
  { en: 'hedgehog', ipa: '/ˈhedʒhɔːɡ/', vi: 'con nhím', emoji: '🦔' },
  { en: 'mole', ipa: '/moʊl/', vi: 'chuột chũi', emoji: '🐾' },
  { en: 'otter', ipa: '/ˈɑːtər/', vi: 'rái cá', emoji: '🦦' },
  { en: 'weasel', ipa: '/ˈwiːzl/', vi: 'chồn', emoji: '🐾' },
  { en: 'badger', ipa: '/ˈbædʒər/', vi: 'lửng', emoji: '🦡' },
  { en: 'raccoon', ipa: '/ræˈkuːn/', vi: 'gấu mèo', emoji: '🦝' },
  { en: 'skunk', ipa: '/skʌŋk/', vi: 'chồn hôi', emoji: '🦨' },
  { en: 'meerkat', ipa: '/ˈmɪrkæt/', vi: 'cầy Meerkat', emoji: '🐾' },
  { en: 'mongoose', ipa: '/ˈmɑːŋɡuːs/', vi: 'cầy mangut', emoji: '🐾' },
  { en: 'bat', ipa: '/bæt/', vi: 'con dơi', emoji: '🦇' },

  // ── Thú độc đáo & thú có túi ────────────────────────────────
  { en: 'kangaroo', ipa: '/ˌkæŋɡəˈruː/', vi: 'chuột túi', emoji: '🦘' },
  { en: 'wallaby', ipa: '/ˈwɑːləbi/', vi: 'chuột túi nhỏ', emoji: '🦘' },
  { en: 'platypus', ipa: '/ˈplætɪpəs/', vi: 'thú mỏ vịt', emoji: '🦫' },
  { en: 'anteater', ipa: '/ˈæntiːtər/', vi: 'thú ăn kiến', emoji: '🐾' },
  { en: 'armadillo', ipa: '/ˌɑːrməˈdɪloʊ/', vi: 'con tê tê Mỹ', emoji: '🐾' },
  { en: 'pangolin', ipa: '/ˈpæŋɡəlɪn/', vi: 'con tê tê', emoji: '🐾' },
  { en: 'wombat', ipa: '/ˈwɑːmbæt/', vi: 'gấu túi mũi trần', emoji: '🐾' },

  // ── Thú biển ─────────────────────────────────────────────────
  { en: 'whale', ipa: '/weɪl/', vi: 'cá voi', emoji: '🐳' },
  { en: 'dolphin', ipa: '/ˈdɑːlfɪn/', vi: 'cá heo', emoji: '🐬' },
  { en: 'orca', ipa: '/ˈɔːrkə/', vi: 'cá voi sát thủ', emoji: '🐋' },
  { en: 'seal', ipa: '/siːl/', vi: 'hải cẩu', emoji: '🦭' },
  { en: 'sea lion', ipa: '/siː ˈlaɪən/', vi: 'sư tử biển', emoji: '🦭' },
  { en: 'walrus', ipa: '/ˈwɔːlrəs/', vi: 'hải mã', emoji: '🦭' },
  { en: 'manatee', ipa: '/ˈmænətiː/', vi: 'bò biển', emoji: '🐋' },
  { en: 'narwhal', ipa: '/ˈnɑːrwɑːl/', vi: 'kỳ lân biển', emoji: '🐋' },

  // ── Cá ───────────────────────────────────────────────────────
  { en: 'fish', ipa: '/fɪʃ/', vi: 'con cá', emoji: '🐟' },
  { en: 'shark', ipa: '/ʃɑːrk/', vi: 'cá mập', emoji: '🦈' },
  { en: 'tuna', ipa: '/ˈtuːnə/', vi: 'cá ngừ', emoji: '🐟' },
  { en: 'salmon', ipa: '/ˈsæmən/', vi: 'cá hồi', emoji: '🐟' },
  { en: 'cod', ipa: '/kɑːd/', vi: 'cá tuyết', emoji: '🐟' },
  { en: 'catfish', ipa: '/ˈkætfɪʃ/', vi: 'cá trê', emoji: '🐟' },
  { en: 'carp', ipa: '/kɑːrp/', vi: 'cá chép', emoji: '🐟' },
  { en: 'trout', ipa: '/traʊt/', vi: 'cá hồi vân', emoji: '🐟' },
  { en: 'eel', ipa: '/iːl/', vi: 'con lươn', emoji: '🐍' },
  { en: 'seahorse', ipa: '/ˈsiːhɔːrs/', vi: 'cá ngựa', emoji: '🐴' },
  { en: 'pufferfish', ipa: '/ˈpʌfərfɪʃ/', vi: 'cá nóc', emoji: '🐡' },
  { en: 'clownfish', ipa: '/ˈklaʊnfɪʃ/', vi: 'cá hề', emoji: '🐠' },
  { en: 'swordfish', ipa: '/ˈsɔːrdfɪʃ/', vi: 'cá kiếm', emoji: '🐟' },
  { en: 'sardine', ipa: '/sɑːrˈdiːn/', vi: 'cá mòi', emoji: '🐟' },
  { en: 'mackerel', ipa: '/ˈmækrəl/', vi: 'cá thu', emoji: '🐟' },
  { en: 'piranha', ipa: '/pəˈrɑːnə/', vi: 'cá piranha', emoji: '🐟' },
  { en: 'stingray', ipa: '/ˈstɪŋreɪ/', vi: 'cá đuối', emoji: '🐟' },
  { en: 'koi', ipa: '/kɔɪ/', vi: 'cá koi', emoji: '🐟' },
  { en: 'guppy', ipa: '/ˈɡʌpi/', vi: 'cá bảy màu', emoji: '🐠' },
  { en: 'anglerfish', ipa: '/ˈæŋɡlərfɪʃ/', vi: 'cá cần câu', emoji: '🐟' },

  // ── Sinh vật biển ────────────────────────────────────────────
  { en: 'octopus', ipa: '/ˈɑːktəpʊs/', vi: 'bạch tuộc', emoji: '🐙' },
  { en: 'squid', ipa: '/skwɪd/', vi: 'con mực', emoji: '🦑' },
  { en: 'cuttlefish', ipa: '/ˈkʌtlfɪʃ/', vi: 'mực nang', emoji: '🦑' },
  { en: 'jellyfish', ipa: '/ˈdʒelifɪʃ/', vi: 'con sứa', emoji: '🎐' },
  { en: 'crab', ipa: '/kræb/', vi: 'con cua', emoji: '🦀' },
  { en: 'lobster', ipa: '/ˈlɑːbstər/', vi: 'tôm hùm', emoji: '🦞' },
  { en: 'shrimp', ipa: '/ʃrɪmp/', vi: 'con tôm', emoji: '🦐' },
  { en: 'starfish', ipa: '/ˈstɑːrfɪʃ/', vi: 'sao biển', emoji: '⭐' },
  { en: 'sea urchin', ipa: '/siː ˈɜːrtʃɪn/', vi: 'nhím biển', emoji: '🐾' },
  { en: 'oyster', ipa: '/ˈɔɪstər/', vi: 'con hàu', emoji: '🦪' },
  { en: 'clam', ipa: '/klæm/', vi: 'con nghêu', emoji: '🦪' },
  { en: 'snail', ipa: '/sneɪl/', vi: 'con ốc sên', emoji: '🐌' },
  { en: 'coral', ipa: '/ˈkɔːrəl/', vi: 'san hô', emoji: '🪸' },

  // ── Bò sát ───────────────────────────────────────────────────
  { en: 'snake', ipa: '/sneɪk/', vi: 'con rắn', emoji: '🐍' },
  { en: 'cobra', ipa: '/ˈkoʊbrə/', vi: 'rắn hổ mang', emoji: '🐍' },
  { en: 'python', ipa: '/ˈpaɪθɑːn/', vi: 'trăn', emoji: '🐍' },
  { en: 'viper', ipa: '/ˈvaɪpər/', vi: 'rắn lục', emoji: '🐍' },
  { en: 'rattlesnake', ipa: '/ˈrætlsneɪk/', vi: 'rắn chuông', emoji: '🐍' },
  { en: 'anaconda', ipa: '/ˌænəˈkɑːndə/', vi: 'trăn Nam Mỹ', emoji: '🐍' },
  { en: 'lizard', ipa: '/ˈlɪzərd/', vi: 'con thằn lằn', emoji: '🦎' },
  { en: 'gecko', ipa: '/ˈɡekoʊ/', vi: 'con tắc kè', emoji: '🦎' },
  { en: 'iguana', ipa: '/ɪˈɡwɑːnə/', vi: 'kỳ nhông', emoji: '🦎' },
  { en: 'chameleon', ipa: '/kəˈmiːliən/', vi: 'tắc kè hoa', emoji: '🦎' },
  { en: 'komodo dragon', ipa: '/kəˈmoʊdoʊ ˈdræɡən/', vi: 'rồng Komodo', emoji: '🦎' },
  { en: 'crocodile', ipa: '/ˈkrɑːkədaɪl/', vi: 'cá sấu', emoji: '🐊' },
  { en: 'alligator', ipa: '/ˈælɪɡeɪtər/', vi: 'cá sấu mõm ngắn', emoji: '🐊' },
  { en: 'turtle', ipa: '/ˈtɜːrtl/', vi: 'con rùa biển', emoji: '🐢' },
  { en: 'tortoise', ipa: '/ˈtɔːrtəs/', vi: 'con rùa cạn', emoji: '🐢' },

  // ── Lưỡng cư ─────────────────────────────────────────────────
  { en: 'frog', ipa: '/frɔːɡ/', vi: 'con ếch', emoji: '🐸' },
  { en: 'toad', ipa: '/toʊd/', vi: 'con cóc', emoji: '🐸' },
  { en: 'tadpole', ipa: '/ˈtædpoʊl/', vi: 'nòng nọc', emoji: '🐸' },
  { en: 'salamander', ipa: '/ˈsæləmændər/', vi: 'kỳ giông', emoji: '🦎' },
  { en: 'newt', ipa: '/nuːt/', vi: 'sa giông', emoji: '🦎' },
  { en: 'axolotl', ipa: '/ˈæksəlɑːtl/', vi: 'kỳ giông Axolotl', emoji: '🦎' },

  // ── Chim thường gặp ──────────────────────────────────────────
  { en: 'bird', ipa: '/bɜːrd/', vi: 'con chim', emoji: '🐦' },
  { en: 'sparrow', ipa: '/ˈspæroʊ/', vi: 'chim sẻ', emoji: '🐦' },
  { en: 'robin', ipa: '/ˈrɑːbɪn/', vi: 'chim cổ đỏ', emoji: '🐦' },
  { en: 'crow', ipa: '/kroʊ/', vi: 'con quạ', emoji: '🐦‍⬛' },
  { en: 'raven', ipa: '/ˈreɪvn/', vi: 'quạ lớn', emoji: '🐦‍⬛' },
  { en: 'pigeon', ipa: '/ˈpɪdʒɪn/', vi: 'chim bồ câu', emoji: '🕊️' },
  { en: 'dove', ipa: '/dʌv/', vi: 'chim bồ câu trắng', emoji: '🕊️' },
  { en: 'seagull', ipa: '/ˈsiːɡʌl/', vi: 'mòng biển', emoji: '🐦' },
  { en: 'swallow', ipa: '/ˈswɑːloʊ/', vi: 'chim én', emoji: '🐦' },
  { en: 'magpie', ipa: '/ˈmæɡpaɪ/', vi: 'chim ác là', emoji: '🐦' },
  { en: 'finch', ipa: '/fɪntʃ/', vi: 'chim sẻ ngô', emoji: '🐦' },
  { en: 'hummingbird', ipa: '/ˈhʌmɪŋbɜːrd/', vi: 'chim ruồi', emoji: '🐦' },
  { en: 'kingfisher', ipa: '/ˈkɪŋfɪʃər/', vi: 'chim bói cá', emoji: '🐦' },
  { en: 'woodpecker', ipa: '/ˈwʊdpekər/', vi: 'chim gõ kiến', emoji: '🐦' },
  { en: 'cuckoo', ipa: '/ˈkuːkuː/', vi: 'chim tu hú', emoji: '🐦' },

  // ── Chim nước & gia cầm hoang ───────────────────────────────
  { en: 'swan', ipa: '/swɑːn/', vi: 'thiên nga', emoji: '🦢' },
  { en: 'peacock', ipa: '/ˈpiːkɑːk/', vi: 'con công', emoji: '🦚' },
  { en: 'pheasant', ipa: '/ˈfeznt/', vi: 'chim trĩ', emoji: '🐦' },
  { en: 'quail', ipa: '/kweɪl/', vi: 'chim cút', emoji: '🐦' },
  { en: 'pelican', ipa: '/ˈpelɪkən/', vi: 'bồ nông', emoji: '🐦' },
  { en: 'flamingo', ipa: '/fləˈmɪŋɡoʊ/', vi: 'chim hồng hạc', emoji: '🦩' },
  { en: 'heron', ipa: '/ˈherən/', vi: 'con diệc', emoji: '🐦' },
  { en: 'stork', ipa: '/stɔːrk/', vi: 'con cò', emoji: '🐦' },
  { en: 'crane', ipa: '/kreɪn/', vi: 'con sếu', emoji: '🐦' },

  // ── Chim săn mồi ─────────────────────────────────────────────
  { en: 'eagle', ipa: '/ˈiːɡl/', vi: 'đại bàng', emoji: '🦅' },
  { en: 'hawk', ipa: '/hɔːk/', vi: 'chim ưng', emoji: '🦅' },
  { en: 'falcon', ipa: '/ˈfælkən/', vi: 'chim cắt', emoji: '🦅' },
  { en: 'owl', ipa: '/aʊl/', vi: 'con cú', emoji: '🦉' },
  { en: 'vulture', ipa: '/ˈvʌltʃər/', vi: 'kền kền', emoji: '🦅' },
  { en: 'condor', ipa: '/ˈkɑːndɔːr/', vi: 'kền kền khoang cổ', emoji: '🦅' },

  // ── Chim đặc biệt & không bay ───────────────────────────────
  { en: 'parrot', ipa: '/ˈpærət/', vi: 'con vẹt', emoji: '🦜' },
  { en: 'parakeet', ipa: '/ˈpærəkiːt/', vi: 'vẹt đuôi dài', emoji: '🦜' },
  { en: 'cockatoo', ipa: '/ˌkɑːkəˈtuː/', vi: 'vẹt mào', emoji: '🦜' },
  { en: 'macaw', ipa: '/məˈkɔː/', vi: 'vẹt đuôi dài Macaw', emoji: '🦜' },
  { en: 'toucan', ipa: '/ˈtuːkæn/', vi: 'chim toucan', emoji: '🦜' },
  { en: 'ostrich', ipa: '/ˈɑːstrɪtʃ/', vi: 'đà điểu', emoji: '🦤' },
  { en: 'emu', ipa: '/ˈiːmjuː/', vi: 'đà điểu Emu', emoji: '🦤' },
  { en: 'penguin', ipa: '/ˈpeŋɡwɪn/', vi: 'chim cánh cụt', emoji: '🐧' },
  { en: 'kiwi', ipa: '/ˈkiːwiː/', vi: 'chim kiwi', emoji: '🐦' },

  // ── Côn trùng ────────────────────────────────────────────────
  { en: 'bee', ipa: '/biː/', vi: 'con ong', emoji: '🐝' },
  { en: 'bumblebee', ipa: '/ˈbʌmblbiː/', vi: 'ong nghệ', emoji: '🐝' },
  { en: 'wasp', ipa: '/wɑːsp/', vi: 'ong bắp cày', emoji: '🐝' },
  { en: 'hornet', ipa: '/ˈhɔːrnɪt/', vi: 'ong vò vẽ', emoji: '🐝' },
  { en: 'ant', ipa: '/ænt/', vi: 'con kiến', emoji: '🐜' },
  { en: 'termite', ipa: '/ˈtɜːrmaɪt/', vi: 'con mối', emoji: '🐜' },
  { en: 'butterfly', ipa: '/ˈbʌtərflaɪ/', vi: 'con bướm', emoji: '🦋' },
  { en: 'moth', ipa: '/mɔːθ/', vi: 'bướm đêm', emoji: '🦋' },
  { en: 'caterpillar', ipa: '/ˈkætərpɪlər/', vi: 'sâu bướm', emoji: '🐛' },
  { en: 'dragonfly', ipa: '/ˈdræɡənflaɪ/', vi: 'chuồn chuồn', emoji: '🪰' },
  { en: 'fly', ipa: '/flaɪ/', vi: 'con ruồi', emoji: '🪰' },
  { en: 'mosquito', ipa: '/məˈskiːtoʊ/', vi: 'con muỗi', emoji: '🦟' },
  { en: 'beetle', ipa: '/ˈbiːtl/', vi: 'bọ cánh cứng', emoji: '🪲' },
  { en: 'ladybug', ipa: '/ˈleɪdibʌɡ/', vi: 'bọ rùa', emoji: '🐞' },
  { en: 'firefly', ipa: '/ˈfaɪərflaɪ/', vi: 'đom đóm', emoji: '✨' },
  { en: 'grasshopper', ipa: '/ˈɡræshɑːpər/', vi: 'châu chấu', emoji: '🦗' },
  { en: 'cricket', ipa: '/ˈkrɪkɪt/', vi: 'con dế', emoji: '🦗' },
  { en: 'locust', ipa: '/ˈloʊkəst/', vi: 'châu chấu di cư', emoji: '🦗' },
  { en: 'cockroach', ipa: '/ˈkɑːkroʊtʃ/', vi: 'con gián', emoji: '🪳' },
  { en: 'mantis', ipa: '/ˈmæntɪs/', vi: 'bọ ngựa', emoji: '🦗' },
  { en: 'cicada', ipa: '/sɪˈkeɪdə/', vi: 'con ve sầu', emoji: '🐛' },
  { en: 'silkworm', ipa: '/ˈsɪlkwɜːrm/', vi: 'con tằm', emoji: '🐛' },

  // ── Nhện & động vật nhiều chân ──────────────────────────────
  { en: 'spider', ipa: '/ˈspaɪdər/', vi: 'con nhện', emoji: '🕷️' },
  { en: 'tarantula', ipa: '/təˈræntʃələ/', vi: 'nhện Tarantula', emoji: '🕷️' },
  { en: 'scorpion', ipa: '/ˈskɔːrpiən/', vi: 'bọ cạp', emoji: '🦂' },
  { en: 'tick', ipa: '/tɪk/', vi: 'con ve', emoji: '🐛' },
  { en: 'centipede', ipa: '/ˈsentɪpiːd/', vi: 'con rết', emoji: '🐛' },
  { en: 'millipede', ipa: '/ˈmɪlɪpiːd/', vi: 'con cuốn chiếu', emoji: '🐛' },
  { en: 'worm', ipa: '/wɜːrm/', vi: 'con giun', emoji: '🪱' },
  { en: 'earthworm', ipa: '/ˈɜːrθwɜːrm/', vi: 'giun đất', emoji: '🪱' },
  { en: 'leech', ipa: '/liːtʃ/', vi: 'con đỉa', emoji: '🪱' },
  { en: 'slug', ipa: '/slʌɡ/', vi: 'sên trần', emoji: '🐌' },

  // ── Khủng long & thời tiền sử ───────────────────────────────
  { en: 'dinosaur', ipa: '/ˈdaɪnəsɔːr/', vi: 'khủng long', emoji: '🦕' },
  { en: 'tyrannosaurus', ipa: '/tɪˌrænəˈsɔːrəs/', vi: 'khủng long bạo chúa', emoji: '🦖' },
  { en: 'triceratops', ipa: '/traɪˈserətɑːps/', vi: 'khủng long ba sừng', emoji: '🦕' },
  { en: 'stegosaurus', ipa: '/ˌsteɡəˈsɔːrəs/', vi: 'khủng long phiến sừng', emoji: '🦕' },
  { en: 'velociraptor', ipa: '/vəˈlɑːsɪræptər/', vi: 'khủng long chân chim', emoji: '🦖' },
  { en: 'pterodactyl', ipa: '/ˌterəˈdæktɪl/', vi: 'thằn lằn bay', emoji: '🦖' },
  { en: 'mammoth', ipa: '/ˈmæməθ/', vi: 'voi ma mút', emoji: '🦣' },

  // ── Con vật trong truyện (mythical) ─────────────────────────
  { en: 'dragon', ipa: '/ˈdræɡən/', vi: 'con rồng', emoji: '🐉' },
  { en: 'unicorn', ipa: '/ˈjuːnɪkɔːrn/', vi: 'kỳ lân', emoji: '🦄' },
  { en: 'mermaid', ipa: '/ˈmɜːrmeɪd/', vi: 'nàng tiên cá', emoji: '🧜‍♀️' },
  { en: 'phoenix', ipa: '/ˈfiːnɪks/', vi: 'phượng hoàng', emoji: '🔥' },
];
