// Bộ từ vựng QUỐC GIA đầy đủ (dùng cho chủ đề /tu-vung-tieng-anh/quoc-gia).
// Gom theo châu lục để dễ tra & không trùng. Mỗi từ: en, ipa (giọng Mỹ), vi, emoji (cờ).

import type { VocabWord } from './vocab';

export const COUNTRIES: VocabWord[] = [
  // ── Châu Á ───────────────────────────────────────────────────
  { en: 'Vietnam', ipa: '/ˌviːetˈnɑːm/', vi: 'Việt Nam', emoji: '🇻🇳' },
  { en: 'China', ipa: '/ˈtʃaɪnə/', vi: 'Trung Quốc', emoji: '🇨🇳' },
  { en: 'Japan', ipa: '/dʒəˈpæn/', vi: 'Nhật Bản', emoji: '🇯🇵' },
  { en: 'South Korea', ipa: '/saʊθ kəˈriːə/', vi: 'Hàn Quốc', emoji: '🇰🇷' },
  { en: 'North Korea', ipa: '/nɔːrθ kəˈriːə/', vi: 'Triều Tiên', emoji: '🇰🇵' },
  { en: 'Thailand', ipa: '/ˈtaɪlænd/', vi: 'Thái Lan', emoji: '🇹🇭' },
  { en: 'Laos', ipa: '/laʊs/', vi: 'Lào', emoji: '🇱🇦' },
  { en: 'Cambodia', ipa: '/kæmˈboʊdiə/', vi: 'Campuchia', emoji: '🇰🇭' },
  { en: 'Myanmar', ipa: '/ˈmjænmɑːr/', vi: 'Myanmar', emoji: '🇲🇲' },
  { en: 'Malaysia', ipa: '/məˈleɪʒə/', vi: 'Malaysia', emoji: '🇲🇾' },
  { en: 'Singapore', ipa: '/ˈsɪŋəpɔːr/', vi: 'Singapore', emoji: '🇸🇬' },
  { en: 'Indonesia', ipa: '/ˌɪndəˈniːʒə/', vi: 'Indonesia', emoji: '🇮🇩' },
  { en: 'Philippines', ipa: '/ˈfɪləpiːnz/', vi: 'Philippines', emoji: '🇵🇭' },
  { en: 'Brunei', ipa: '/bruːˈnaɪ/', vi: 'Brunei', emoji: '🇧🇳' },
  { en: 'Timor-Leste', ipa: '/ˈtiːmɔːr ˈlesteɪ/', vi: 'Đông Timor', emoji: '🇹🇱' },
  { en: 'India', ipa: '/ˈɪndiə/', vi: 'Ấn Độ', emoji: '🇮🇳' },
  { en: 'Pakistan', ipa: '/ˈpækɪstæn/', vi: 'Pakistan', emoji: '🇵🇰' },
  { en: 'Bangladesh', ipa: '/ˌbɑːŋɡləˈdeʃ/', vi: 'Bangladesh', emoji: '🇧🇩' },
  { en: 'Sri Lanka', ipa: '/sri ˈlɑːŋkə/', vi: 'Sri Lanka', emoji: '🇱🇰' },
  { en: 'Nepal', ipa: '/nəˈpɔːl/', vi: 'Nepal', emoji: '🇳🇵' },
  { en: 'Bhutan', ipa: '/buːˈtɑːn/', vi: 'Bhutan', emoji: '🇧🇹' },
  { en: 'Maldives', ipa: '/ˈmɔːldiːvz/', vi: 'Maldives', emoji: '🇲🇻' },
  { en: 'Afghanistan', ipa: '/æfˈɡænɪstæn/', vi: 'Afghanistan', emoji: '🇦🇫' },
  { en: 'Iran', ipa: '/ɪˈrɑːn/', vi: 'Iran', emoji: '🇮🇷' },
  { en: 'Iraq', ipa: '/ɪˈrɑːk/', vi: 'Iraq', emoji: '🇮🇶' },
  { en: 'Saudi Arabia', ipa: '/ˌsaʊdi əˈreɪbiə/', vi: 'Ả Rập Xê Út', emoji: '🇸🇦' },
  { en: 'United Arab Emirates', ipa: '/juˈnaɪtɪd ˈærəb ˈemɪrəts/', vi: 'UAE', emoji: '🇦🇪' },
  { en: 'Qatar', ipa: '/ˈkɑːtɑːr/', vi: 'Qatar', emoji: '🇶🇦' },
  { en: 'Kuwait', ipa: '/kuˈweɪt/', vi: 'Kuwait', emoji: '🇰🇼' },
  { en: 'Bahrain', ipa: '/bɑːˈreɪn/', vi: 'Bahrain', emoji: '🇧🇭' },
  { en: 'Oman', ipa: '/oʊˈmɑːn/', vi: 'Oman', emoji: '🇴🇲' },
  { en: 'Yemen', ipa: '/ˈjemən/', vi: 'Yemen', emoji: '🇾🇪' },
  { en: 'Jordan', ipa: '/ˈdʒɔːrdn/', vi: 'Jordan', emoji: '🇯🇴' },
  { en: 'Lebanon', ipa: '/ˈlebənən/', vi: 'Liban', emoji: '🇱🇧' },
  { en: 'Syria', ipa: '/ˈsɪriə/', vi: 'Syria', emoji: '🇸🇾' },
  { en: 'Israel', ipa: '/ˈɪzreɪl/', vi: 'Israel', emoji: '🇮🇱' },
  { en: 'Palestine', ipa: '/ˈpæləstaɪn/', vi: 'Palestine', emoji: '🇵🇸' },
  { en: 'Turkey', ipa: '/ˈtɜːrki/', vi: 'Thổ Nhĩ Kỳ', emoji: '🇹🇷' },
  { en: 'Cyprus', ipa: '/ˈsaɪprəs/', vi: 'Síp', emoji: '🇨🇾' },
  { en: 'Georgia', ipa: '/ˈdʒɔːrdʒə/', vi: 'Gruzia', emoji: '🇬🇪' },
  { en: 'Armenia', ipa: '/ɑːrˈmiːniə/', vi: 'Armenia', emoji: '🇦🇲' },
  { en: 'Azerbaijan', ipa: '/ˌæzərbaɪˈdʒɑːn/', vi: 'Azerbaijan', emoji: '🇦🇿' },
  { en: 'Kazakhstan', ipa: '/ˌkɑːzɑːkˈstɑːn/', vi: 'Kazakhstan', emoji: '🇰🇿' },
  { en: 'Uzbekistan', ipa: '/ʊzˈbekɪstæn/', vi: 'Uzbekistan', emoji: '🇺🇿' },
  { en: 'Turkmenistan', ipa: '/tɜːrkˈmenɪstæn/', vi: 'Turkmenistan', emoji: '🇹🇲' },
  { en: 'Kyrgyzstan', ipa: '/ˈkɪrɡɪstæn/', vi: 'Kyrgyzstan', emoji: '🇰🇬' },
  { en: 'Tajikistan', ipa: '/tɑːˈdʒiːkɪstæn/', vi: 'Tajikistan', emoji: '🇹🇯' },
  { en: 'Mongolia', ipa: '/mɑːnˈɡoʊliə/', vi: 'Mông Cổ', emoji: '🇲🇳' },

  // ── Châu Âu ──────────────────────────────────────────────────
  { en: 'United Kingdom', ipa: '/juˈnaɪtɪd ˈkɪŋdəm/', vi: 'Anh (Vương quốc Anh)', emoji: '🇬🇧' },
  { en: 'France', ipa: '/fræns/', vi: 'Pháp', emoji: '🇫🇷' },
  { en: 'Germany', ipa: '/ˈdʒɜːrməni/', vi: 'Đức', emoji: '🇩🇪' },
  { en: 'Italy', ipa: '/ˈɪtəli/', vi: 'Ý', emoji: '🇮🇹' },
  { en: 'Spain', ipa: '/speɪn/', vi: 'Tây Ban Nha', emoji: '🇪🇸' },
  { en: 'Portugal', ipa: '/ˈpɔːrtʃəɡl/', vi: 'Bồ Đào Nha', emoji: '🇵🇹' },
  { en: 'Netherlands', ipa: '/ˈneðərləndz/', vi: 'Hà Lan', emoji: '🇳🇱' },
  { en: 'Belgium', ipa: '/ˈbeldʒəm/', vi: 'Bỉ', emoji: '🇧🇪' },
  { en: 'Switzerland', ipa: '/ˈswɪtsərlənd/', vi: 'Thụy Sĩ', emoji: '🇨🇭' },
  { en: 'Austria', ipa: '/ˈɔːstriə/', vi: 'Áo', emoji: '🇦🇹' },
  { en: 'Ireland', ipa: '/ˈaɪərlənd/', vi: 'Ireland', emoji: '🇮🇪' },
  { en: 'Sweden', ipa: '/ˈswiːdn/', vi: 'Thụy Điển', emoji: '🇸🇪' },
  { en: 'Norway', ipa: '/ˈnɔːrweɪ/', vi: 'Na Uy', emoji: '🇳🇴' },
  { en: 'Denmark', ipa: '/ˈdenmɑːrk/', vi: 'Đan Mạch', emoji: '🇩🇰' },
  { en: 'Finland', ipa: '/ˈfɪnlənd/', vi: 'Phần Lan', emoji: '🇫🇮' },
  { en: 'Iceland', ipa: '/ˈaɪslənd/', vi: 'Iceland', emoji: '🇮🇸' },
  { en: 'Poland', ipa: '/ˈpoʊlənd/', vi: 'Ba Lan', emoji: '🇵🇱' },
  { en: 'Czech Republic', ipa: '/tʃek rɪˈpʌblɪk/', vi: 'Séc', emoji: '🇨🇿' },
  { en: 'Slovakia', ipa: '/sloʊˈvɑːkiə/', vi: 'Slovakia', emoji: '🇸🇰' },
  { en: 'Hungary', ipa: '/ˈhʌŋɡəri/', vi: 'Hungary', emoji: '🇭🇺' },
  { en: 'Romania', ipa: '/roʊˈmeɪniə/', vi: 'Romania', emoji: '🇷🇴' },
  { en: 'Bulgaria', ipa: '/bʌlˈɡeriə/', vi: 'Bulgaria', emoji: '🇧🇬' },
  { en: 'Greece', ipa: '/ɡriːs/', vi: 'Hy Lạp', emoji: '🇬🇷' },
  { en: 'Croatia', ipa: '/kroʊˈeɪʃə/', vi: 'Croatia', emoji: '🇭🇷' },
  { en: 'Serbia', ipa: '/ˈsɜːrbiə/', vi: 'Serbia', emoji: '🇷🇸' },
  { en: 'Slovenia', ipa: '/sloʊˈviːniə/', vi: 'Slovenia', emoji: '🇸🇮' },
  { en: 'Bosnia and Herzegovina', ipa: '/ˈbɑːzniə/', vi: 'Bosnia & Herzegovina', emoji: '🇧🇦' },
  { en: 'Montenegro', ipa: '/ˌmɑːntɪˈniːɡroʊ/', vi: 'Montenegro', emoji: '🇲🇪' },
  { en: 'North Macedonia', ipa: '/nɔːrθ ˌmæsɪˈdoʊniə/', vi: 'Bắc Macedonia', emoji: '🇲🇰' },
  { en: 'Albania', ipa: '/ælˈbeɪniə/', vi: 'Albania', emoji: '🇦🇱' },
  { en: 'Ukraine', ipa: '/juˈkreɪn/', vi: 'Ukraine', emoji: '🇺🇦' },
  { en: 'Belarus', ipa: '/ˌbeləˈruːs/', vi: 'Belarus', emoji: '🇧🇾' },
  { en: 'Russia', ipa: '/ˈrʌʃə/', vi: 'Nga', emoji: '🇷🇺' },
  { en: 'Lithuania', ipa: '/ˌlɪθuˈeɪniə/', vi: 'Litva', emoji: '🇱🇹' },
  { en: 'Latvia', ipa: '/ˈlætviə/', vi: 'Latvia', emoji: '🇱🇻' },
  { en: 'Estonia', ipa: '/eˈstoʊniə/', vi: 'Estonia', emoji: '🇪🇪' },
  { en: 'Moldova', ipa: '/mɑːlˈdoʊvə/', vi: 'Moldova', emoji: '🇲🇩' },
  { en: 'Luxembourg', ipa: '/ˈlʌksəmbɜːrɡ/', vi: 'Luxembourg', emoji: '🇱🇺' },
  { en: 'Monaco', ipa: '/ˈmɑːnəkoʊ/', vi: 'Monaco', emoji: '🇲🇨' },
  { en: 'Malta', ipa: '/ˈmɔːltə/', vi: 'Malta', emoji: '🇲🇹' },
  { en: 'Liechtenstein', ipa: '/ˈlɪktənstaɪn/', vi: 'Liechtenstein', emoji: '🇱🇮' },
  { en: 'Andorra', ipa: '/ænˈdɔːrə/', vi: 'Andorra', emoji: '🇦🇩' },
  { en: 'San Marino', ipa: '/sæn məˈriːnoʊ/', vi: 'San Marino', emoji: '🇸🇲' },
  { en: 'Vatican City', ipa: '/ˈvætɪkən ˈsɪti/', vi: 'Vatican', emoji: '🇻🇦' },

  // ── Châu Phi ─────────────────────────────────────────────────
  { en: 'Egypt', ipa: '/ˈiːdʒɪpt/', vi: 'Ai Cập', emoji: '🇪🇬' },
  { en: 'Nigeria', ipa: '/naɪˈdʒɪriə/', vi: 'Nigeria', emoji: '🇳🇬' },
  { en: 'South Africa', ipa: '/saʊθ ˈæfrɪkə/', vi: 'Nam Phi', emoji: '🇿🇦' },
  { en: 'Kenya', ipa: '/ˈkenjə/', vi: 'Kenya', emoji: '🇰🇪' },
  { en: 'Ethiopia', ipa: '/ˌiːθiˈoʊpiə/', vi: 'Ethiopia', emoji: '🇪🇹' },
  { en: 'Ghana', ipa: '/ˈɡɑːnə/', vi: 'Ghana', emoji: '🇬🇭' },
  { en: 'Morocco', ipa: '/məˈrɑːkoʊ/', vi: 'Maroc', emoji: '🇲🇦' },
  { en: 'Algeria', ipa: '/ælˈdʒɪriə/', vi: 'Algeria', emoji: '🇩🇿' },
  { en: 'Tunisia', ipa: '/tuˈniːʒə/', vi: 'Tunisia', emoji: '🇹🇳' },
  { en: 'Libya', ipa: '/ˈlɪbiə/', vi: 'Libya', emoji: '🇱🇾' },
  { en: 'Sudan', ipa: '/suˈdæn/', vi: 'Sudan', emoji: '🇸🇩' },
  { en: 'South Sudan', ipa: '/saʊθ suˈdæn/', vi: 'Nam Sudan', emoji: '🇸🇸' },
  { en: 'Tanzania', ipa: '/ˌtænzəˈniːə/', vi: 'Tanzania', emoji: '🇹🇿' },
  { en: 'Uganda', ipa: '/juˈɡændə/', vi: 'Uganda', emoji: '🇺🇬' },
  { en: 'Angola', ipa: '/æŋˈɡoʊlə/', vi: 'Angola', emoji: '🇦🇴' },
  { en: 'Mozambique', ipa: '/ˌmoʊzæmˈbiːk/', vi: 'Mozambique', emoji: '🇲🇿' },
  { en: 'Zimbabwe', ipa: '/zɪmˈbɑːbweɪ/', vi: 'Zimbabwe', emoji: '🇿🇼' },
  { en: 'Zambia', ipa: '/ˈzæmbiə/', vi: 'Zambia', emoji: '🇿🇲' },
  { en: 'Cameroon', ipa: '/ˌkæməˈruːn/', vi: 'Cameroon', emoji: '🇨🇲' },
  { en: 'Ivory Coast', ipa: '/ˈaɪvəri koʊst/', vi: 'Bờ Biển Ngà', emoji: '🇨🇮' },
  { en: 'Senegal', ipa: '/ˌsenɪˈɡɔːl/', vi: 'Senegal', emoji: '🇸🇳' },
  { en: 'Mali', ipa: '/ˈmɑːli/', vi: 'Mali', emoji: '🇲🇱' },
  { en: 'Madagascar', ipa: '/ˌmædəˈɡæskər/', vi: 'Madagascar', emoji: '🇲🇬' },
  { en: 'Somalia', ipa: '/soʊˈmɑːliə/', vi: 'Somalia', emoji: '🇸🇴' },
  { en: 'Rwanda', ipa: '/ruˈɑːndə/', vi: 'Rwanda', emoji: '🇷🇼' },
  { en: 'Botswana', ipa: '/bɑːtˈswɑːnə/', vi: 'Botswana', emoji: '🇧🇼' },
  { en: 'Namibia', ipa: '/nəˈmɪbiə/', vi: 'Namibia', emoji: '🇳🇦' },
  { en: 'DR Congo', ipa: '/ˈkɑːŋɡoʊ/', vi: 'CHDC Congo', emoji: '🇨🇩' },
  { en: 'Congo', ipa: '/ˈkɑːŋɡoʊ/', vi: 'Congo', emoji: '🇨🇬' },
  { en: 'Chad', ipa: '/tʃæd/', vi: 'Chad', emoji: '🇹🇩' },
  { en: 'Niger', ipa: '/niːˈʒer/', vi: 'Niger', emoji: '🇳🇪' },
  { en: 'Burkina Faso', ipa: '/bɜːrˈkiːnə ˈfɑːsoʊ/', vi: 'Burkina Faso', emoji: '🇧🇫' },
  { en: 'Benin', ipa: '/beˈniːn/', vi: 'Benin', emoji: '🇧🇯' },
  { en: 'Togo', ipa: '/ˈtoʊɡoʊ/', vi: 'Togo', emoji: '🇹🇬' },
  { en: 'Guinea', ipa: '/ˈɡɪni/', vi: 'Guinea', emoji: '🇬🇳' },
  { en: 'Sierra Leone', ipa: '/siˌerə liˈoʊn/', vi: 'Sierra Leone', emoji: '🇸🇱' },
  { en: 'Liberia', ipa: '/laɪˈbɪriə/', vi: 'Liberia', emoji: '🇱🇷' },
  { en: 'Mauritania', ipa: '/ˌmɔːrɪˈteɪniə/', vi: 'Mauritania', emoji: '🇲🇷' },
  { en: 'Gabon', ipa: '/ɡæˈbɔːn/', vi: 'Gabon', emoji: '🇬🇦' },
  { en: 'Malawi', ipa: '/məˈlɑːwi/', vi: 'Malawi', emoji: '🇲🇼' },
  { en: 'Lesotho', ipa: '/ləˈsuːtuː/', vi: 'Lesotho', emoji: '🇱🇸' },
  { en: 'Eswatini', ipa: '/ˌeswɑːˈtiːni/', vi: 'Eswatini', emoji: '🇸🇿' },
  { en: 'Djibouti', ipa: '/dʒɪˈbuːti/', vi: 'Djibouti', emoji: '🇩🇯' },
  { en: 'Eritrea', ipa: '/ˌerɪˈtriːə/', vi: 'Eritrea', emoji: '🇪🇷' },
  { en: 'Burundi', ipa: '/bʊˈrʊndi/', vi: 'Burundi', emoji: '🇧🇮' },
  { en: 'Mauritius', ipa: '/məˈrɪʃəs/', vi: 'Mauritius', emoji: '🇲🇺' },
  { en: 'Gambia', ipa: '/ˈɡæmbiə/', vi: 'Gambia', emoji: '🇬🇲' },
  { en: 'Cape Verde', ipa: '/keɪp vɜːrd/', vi: 'Cabo Verde', emoji: '🇨🇻' },
  { en: 'Seychelles', ipa: '/seɪˈʃelz/', vi: 'Seychelles', emoji: '🇸🇨' },
  { en: 'Comoros', ipa: '/ˈkɑːməroʊz/', vi: 'Comoros', emoji: '🇰🇲' },

  // ── Bắc Mỹ ───────────────────────────────────────────────────
  { en: 'United States', ipa: '/juˈnaɪtɪd steɪts/', vi: 'Mỹ (Hoa Kỳ)', emoji: '🇺🇸' },
  { en: 'Canada', ipa: '/ˈkænədə/', vi: 'Canada', emoji: '🇨🇦' },
  { en: 'Mexico', ipa: '/ˈmeksɪkoʊ/', vi: 'Mexico', emoji: '🇲🇽' },
  { en: 'Cuba', ipa: '/ˈkjuːbə/', vi: 'Cuba', emoji: '🇨🇺' },
  { en: 'Jamaica', ipa: '/dʒəˈmeɪkə/', vi: 'Jamaica', emoji: '🇯🇲' },
  { en: 'Haiti', ipa: '/ˈheɪti/', vi: 'Haiti', emoji: '🇭🇹' },
  { en: 'Dominican Republic', ipa: '/dəˈmɪnɪkən rɪˈpʌblɪk/', vi: 'CH Dominica', emoji: '🇩🇴' },
  { en: 'Panama', ipa: '/ˈpænəmɑː/', vi: 'Panama', emoji: '🇵🇦' },
  { en: 'Costa Rica', ipa: '/ˈkoʊstə ˈriːkə/', vi: 'Costa Rica', emoji: '🇨🇷' },
  { en: 'Guatemala', ipa: '/ˌɡwɑːtəˈmɑːlə/', vi: 'Guatemala', emoji: '🇬🇹' },
  { en: 'Honduras', ipa: '/hɑːnˈdʊrəs/', vi: 'Honduras', emoji: '🇭🇳' },
  { en: 'El Salvador', ipa: '/el ˈsælvədɔːr/', vi: 'El Salvador', emoji: '🇸🇻' },
  { en: 'Nicaragua', ipa: '/ˌnɪkəˈrɑːɡwə/', vi: 'Nicaragua', emoji: '🇳🇮' },
  { en: 'Belize', ipa: '/bəˈliːz/', vi: 'Belize', emoji: '🇧🇿' },
  { en: 'Bahamas', ipa: '/bəˈhɑːməz/', vi: 'Bahamas', emoji: '🇧🇸' },
  { en: 'Barbados', ipa: '/bɑːrˈbeɪdoʊs/', vi: 'Barbados', emoji: '🇧🇧' },
  { en: 'Trinidad and Tobago', ipa: '/ˈtrɪnɪdæd/', vi: 'Trinidad & Tobago', emoji: '🇹🇹' },

  // ── Nam Mỹ ───────────────────────────────────────────────────
  { en: 'Brazil', ipa: '/brəˈzɪl/', vi: 'Brazil', emoji: '🇧🇷' },
  { en: 'Argentina', ipa: '/ˌɑːrdʒənˈtiːnə/', vi: 'Argentina', emoji: '🇦🇷' },
  { en: 'Chile', ipa: '/ˈtʃɪli/', vi: 'Chile', emoji: '🇨🇱' },
  { en: 'Peru', ipa: '/pəˈruː/', vi: 'Peru', emoji: '🇵🇪' },
  { en: 'Colombia', ipa: '/kəˈlʌmbiə/', vi: 'Colombia', emoji: '🇨🇴' },
  { en: 'Venezuela', ipa: '/ˌvenəˈzweɪlə/', vi: 'Venezuela', emoji: '🇻🇪' },
  { en: 'Ecuador', ipa: '/ˈekwədɔːr/', vi: 'Ecuador', emoji: '🇪🇨' },
  { en: 'Bolivia', ipa: '/bəˈlɪviə/', vi: 'Bolivia', emoji: '🇧🇴' },
  { en: 'Paraguay', ipa: '/ˈpærəɡwaɪ/', vi: 'Paraguay', emoji: '🇵🇾' },
  { en: 'Uruguay', ipa: '/ˈjʊrəɡwaɪ/', vi: 'Uruguay', emoji: '🇺🇾' },
  { en: 'Guyana', ipa: '/ɡaɪˈɑːnə/', vi: 'Guyana', emoji: '🇬🇾' },
  { en: 'Suriname', ipa: '/ˈsʊrɪnɑːm/', vi: 'Suriname', emoji: '🇸🇷' },

  // ── Châu Đại Dương ───────────────────────────────────────────
  { en: 'Australia', ipa: '/ɔːˈstreɪliə/', vi: 'Úc', emoji: '🇦🇺' },
  { en: 'New Zealand', ipa: '/nuː ˈziːlənd/', vi: 'New Zealand', emoji: '🇳🇿' },
  { en: 'Fiji', ipa: '/ˈfiːdʒiː/', vi: 'Fiji', emoji: '🇫🇯' },
  { en: 'Papua New Guinea', ipa: '/ˈpæpuə nuː ˈɡɪni/', vi: 'Papua New Guinea', emoji: '🇵🇬' },
  { en: 'Solomon Islands', ipa: '/ˈsɑːləmən ˈaɪləndz/', vi: 'Quần đảo Solomon', emoji: '🇸🇧' },
  { en: 'Vanuatu', ipa: '/ˌvɑːnuˈɑːtuː/', vi: 'Vanuatu', emoji: '🇻🇺' },
  { en: 'Samoa', ipa: '/səˈmoʊə/', vi: 'Samoa', emoji: '🇼🇸' },
  { en: 'Tonga', ipa: '/ˈtɑːŋɡə/', vi: 'Tonga', emoji: '🇹🇴' },
  { en: 'Kiribati', ipa: '/ˌkɪrɪˈbæti/', vi: 'Kiribati', emoji: '🇰🇮' },
  { en: 'Micronesia', ipa: '/ˌmaɪkroʊˈniːʒə/', vi: 'Micronesia', emoji: '🇫🇲' },
  { en: 'Palau', ipa: '/pəˈlaʊ/', vi: 'Palau', emoji: '🇵🇼' },
  { en: 'Marshall Islands', ipa: '/ˈmɑːrʃl ˈaɪləndz/', vi: 'Quần đảo Marshall', emoji: '🇲🇭' },
  { en: 'Nauru', ipa: '/nɑːˈuːruː/', vi: 'Nauru', emoji: '🇳🇷' },
  { en: 'Tuvalu', ipa: '/tuːˈvɑːluː/', vi: 'Tuvalu', emoji: '🇹🇻' },
];
