// 360 tình huống giao tiếp tiếng Anh cho BA MẸ nói với con trong sinh hoạt hằng ngày.
// 18 chủ đề × 20 câu. Câu ngắn, đúng ngữ pháp, thân thiện với trẻ.

export type Situation = { en: string; vi: string };
export type SituationTopic = {
  slug: string;
  name: string;
  color: string; // màu nhấn (chữ/viền)
  bg: string; // nền nhạt của icon
  icon: string; // key vẽ icon trong client
  situations: Situation[];
};

export const SITUATION_TOPICS: SituationTopic[] = [
  {
    slug: 'buoi-sang',
    name: 'Buổi sáng thức dậy',
    color: '#FF9F45',
    bg: '#FFE5C2',
    icon: 'sun',
    situations: [
      { en: 'Good morning, sweetheart!', vi: 'Chào buổi sáng, cục cưng!' },
      { en: 'Did you sleep well?', vi: 'Con ngủ ngon không?' },
      { en: 'Time to wake up!', vi: 'Đến giờ dậy rồi!' },
      { en: "Let's open the curtains.", vi: 'Mình kéo rèm ra nào.' },
      { en: 'Stretch your arms up high.', vi: 'Vươn tay lên cao nào.' },
      { en: "Let's brush your teeth.", vi: 'Mình đi đánh răng nào.' },
      { en: 'Wash your face, please.', vi: 'Rửa mặt đi con.' },
      { en: "Let's get dressed.", vi: 'Mình thay đồ nào.' },
      { en: 'Comb your hair.', vi: 'Chải tóc đi con.' },
      { en: 'Are you hungry?', vi: 'Con đói chưa?' },
      { en: "Let's have breakfast.", vi: 'Mình ăn sáng thôi.' },
      { en: 'Drink some water.', vi: 'Uống chút nước đi con.' },
      { en: 'Put on your shoes.', vi: 'Đi giày vào con.' },
      { en: "Don't forget your bag.", vi: 'Đừng quên cặp sách nhé.' },
      { en: 'Are you ready for school?', vi: 'Con sẵn sàng đi học chưa?' },
      { en: 'It’s a beautiful day!', vi: 'Hôm nay trời đẹp quá!' },
      { en: 'Give me a morning hug!', vi: 'Ôm mẹ một cái nào!' },
      { en: 'Did you have a nice dream?', vi: 'Đêm qua con mơ đẹp không?' },
      { en: 'Let’s make the bed.', vi: 'Mình gấp chăn gối nào.' },
      { en: 'Have a great day!', vi: 'Chúc con một ngày vui!' },
    ],
  },
  {
    slug: 'gio-an',
    name: 'Giờ ăn',
    color: '#37B3AB',
    bg: '#DCF6F3',
    icon: 'meal',
    situations: [
      { en: 'Are you hungry?', vi: 'Con đói chưa?' },
      { en: "Let's eat!", vi: 'Mình ăn thôi!' },
      { en: 'Wash your hands first.', vi: 'Rửa tay trước nhé.' },
      { en: 'Sit down, please.', vi: 'Ngồi xuống nào con.' },
      { en: 'What would you like to eat?', vi: 'Con muốn ăn gì?' },
      { en: 'Do you want some rice?', vi: 'Con ăn cơm không?' },
      { en: 'Eat your vegetables.', vi: 'Ăn rau đi con.' },
      { en: 'It’s delicious, right?', vi: 'Ngon đúng không?' },
      { en: 'Chew slowly.', vi: 'Nhai từ từ thôi con.' },
      { en: "Don't play with your food.", vi: 'Đừng nghịch đồ ăn nhé.' },
      { en: 'Would you like some more?', vi: 'Con ăn thêm không?' },
      { en: 'Are you full?', vi: 'Con no chưa?' },
      { en: 'Drink your milk.', vi: 'Uống sữa đi con.' },
      { en: 'Use your spoon.', vi: 'Dùng thìa đi con.' },
      { en: 'Try a little bite.', vi: 'Nếm thử một miếng đi con.' },
      { en: 'No sweets before dinner.', vi: 'Không ăn kẹo trước bữa tối nhé.' },
      { en: 'Say thank you.', vi: 'Nói cảm ơn nào.' },
      { en: 'Wipe your mouth.', vi: 'Lau miệng đi con.' },
      { en: "Let's clean up together.", vi: 'Mình cùng dọn dẹp nào.' },
      { en: 'Please finish your food.', vi: 'Ăn hết phần con nhé.' },
    ],
  },
  {
    slug: 'tam-ve-sinh',
    name: 'Tắm & vệ sinh',
    color: '#5AB2E8',
    bg: '#E5F4FF',
    icon: 'bath',
    situations: [
      { en: 'Time for a bath!', vi: 'Đến giờ tắm rồi!' },
      { en: "Let's take off your clothes.", vi: 'Mình cởi đồ ra nào.' },
      { en: 'Is the water warm?', vi: 'Nước ấm chưa con?' },
      { en: 'Wash your body.', vi: 'Kỳ cọ người đi con.' },
      { en: "Don't forget your hair.", vi: 'Đừng quên gội đầu nhé.' },
      { en: 'Close your eyes.', vi: 'Nhắm mắt lại nào.' },
      { en: 'Rinse off the soap.', vi: 'Rửa sạch xà phòng đi con.' },
      { en: "Let's dry you off.", vi: 'Mình lau khô người nào.' },
      { en: 'Put on your pajamas.', vi: 'Mặc đồ ngủ vào con.' },
      { en: 'Brush your teeth.', vi: 'Đánh răng đi con.' },
      { en: 'Wash your hands.', vi: 'Rửa tay nào.' },
      { en: 'Do you need to pee?', vi: 'Con có buồn tè không?' },
      { en: 'Flush the toilet, please.', vi: 'Nhớ xả nước bồn cầu nhé.' },
      { en: 'Blow your nose.', vi: 'Hỉ mũi đi con.' },
      { en: 'Cover your mouth when you cough.', vi: 'Ho thì che miệng nhé.' },
      { en: 'Careful, it’s slippery.', vi: 'Cẩn thận, trơn đấy con.' },
      { en: 'Dry your hands.', vi: 'Lau khô tay đi con.' },
      { en: 'You smell so fresh!', vi: 'Con thơm ghê!' },
      { en: 'Comb your hair now.', vi: 'Giờ chải tóc nào.' },
      { en: 'All clean now!', vi: 'Sạch sẽ rồi nhé!' },
    ],
  },
  {
    slug: 'vui-choi',
    name: 'Vui chơi',
    color: '#FF6B9D',
    bg: '#FFE0EC',
    icon: 'play',
    situations: [
      { en: "Let's play!", vi: 'Mình chơi nào!' },
      { en: 'What do you want to play?', vi: 'Con muốn chơi gì?' },
      { en: 'Be careful!', vi: 'Cẩn thận nhé!' },
      { en: 'It’s your turn.', vi: 'Đến lượt con rồi.' },
      { en: 'Well done!', vi: 'Giỏi lắm!' },
      { en: "Let's share the toys.", vi: 'Mình chia đồ chơi nào.' },
      { en: "Don't run too fast.", vi: 'Đừng chạy nhanh quá con.' },
      { en: "Let's build together.", vi: 'Mình xếp cùng nhau nào.' },
      { en: 'Look at that!', vi: 'Nhìn kìa con!' },
      { en: 'Can I play too?', vi: 'Mẹ chơi cùng nhé?' },
      { en: "Let's draw a picture.", vi: 'Mình vẽ tranh nào.' },
      { en: 'Be gentle with your friends.', vi: 'Nhẹ nhàng với bạn nhé.' },
      { en: "Let's play hide and seek.", vi: 'Mình chơi trốn tìm nào.' },
      { en: 'Catch the ball!', vi: 'Bắt bóng nào!' },
      { en: 'Take turns, please.', vi: 'Chơi lần lượt nhé.' },
      { en: 'You’re doing great!', vi: 'Con làm tốt lắm!' },
      { en: 'That’s so much fun!', vi: 'Vui quá đi!' },
      { en: 'One more time?', vi: 'Chơi thêm lần nữa nhé?' },
      { en: 'Time to clean up the toys.', vi: 'Đến giờ dọn đồ chơi rồi.' },
      { en: "Let's take a little break.", vi: 'Mình nghỉ một chút nào.' },
    ],
  },
  {
    slug: 'ra-ngoai',
    name: 'Ra ngoài',
    color: '#57B85F',
    bg: '#E6F7E9',
    icon: 'walk',
    situations: [
      { en: "Let's go outside.", vi: 'Mình ra ngoài nào.' },
      { en: 'Put on your shoes.', vi: 'Đi giày vào con.' },
      { en: 'Hold my hand.', vi: 'Nắm tay mẹ nào.' },
      { en: 'Wear your hat.', vi: 'Đội mũ vào con.' },
      { en: 'It’s sunny today.', vi: 'Hôm nay trời nắng.' },
      { en: 'Stay close to me.', vi: 'Đi gần mẹ nhé.' },
      { en: 'Watch your step.', vi: 'Xem chừng bước chân nhé.' },
      { en: 'Look both ways.', vi: 'Nhìn cả hai bên đường nhé.' },
      { en: 'Wait for the green light.', vi: 'Chờ đèn xanh nhé.' },
      { en: "Let's cross the street.", vi: 'Mình qua đường nào.' },
      { en: 'Look at the birds!', vi: 'Nhìn mấy chú chim kìa!' },
      { en: "Don't touch that.", vi: 'Đừng chạm vào nhé.' },
      { en: 'Say hello to the neighbor.', vi: 'Chào bác hàng xóm đi con.' },
      { en: "Let's go to the park.", vi: 'Mình ra công viên nào.' },
      { en: 'Are you tired?', vi: 'Con mỏi chân chưa?' },
      { en: 'It might rain.', vi: 'Trời có thể mưa đấy.' },
      { en: 'Bring your umbrella.', vi: 'Mang ô theo nhé.' },
      { en: 'Be polite, please.', vi: 'Ngoan ngoãn nhé con.' },
      { en: 'Did you have fun?', vi: 'Con chơi vui không?' },
      { en: "Let's go home now.", vi: 'Mình về nhà thôi.' },
    ],
  },
  {
    slug: 'hoc-khen-ngoi',
    name: 'Học & khen ngợi',
    color: '#E6B325',
    bg: '#FFF3CC',
    icon: 'star',
    situations: [
      { en: "Let's read a book.", vi: 'Mình đọc sách nào.' },
      { en: 'Great job!', vi: 'Làm tốt lắm!' },
      { en: 'I’m proud of you.', vi: 'Mẹ tự hào về con.' },
      { en: 'You did it!', vi: 'Con làm được rồi!' },
      { en: 'Try again.', vi: 'Thử lại nào con.' },
      { en: 'Keep going!', vi: 'Cố lên nào!' },
      { en: 'That’s correct!', vi: 'Đúng rồi đấy!' },
      { en: "Let's count together.", vi: 'Mình đếm cùng nhau nào.' },
      { en: 'What color is this?', vi: 'Cái này màu gì?' },
      { en: 'You’re so smart!', vi: 'Con thông minh quá!' },
      { en: "Don't give up.", vi: 'Đừng bỏ cuộc nhé.' },
      { en: "Let's learn a new word.", vi: 'Mình học từ mới nào.' },
      { en: 'Can you say it again?', vi: 'Con nói lại được không?' },
      { en: 'Good try!', vi: 'Cố gắng tốt lắm!' },
      { en: 'You’re getting better.', vi: 'Con giỏi lên nhiều rồi.' },
      { en: "Let's practice a little.", vi: 'Mình luyện tập chút nào.' },
      { en: 'Show me what you drew.', vi: 'Cho mẹ xem con vẽ gì nào.' },
      { en: 'Amazing work!', vi: 'Tuyệt vời lắm!' },
      { en: 'I believe in you.', vi: 'Mẹ tin ở con.' },
      { en: 'High five!', vi: 'Đập tay nào!' },
    ],
  },
  {
    slug: 'cam-xuc',
    name: 'Cảm xúc',
    color: '#FF7A59',
    bg: '#FFE7DE',
    icon: 'heart',
    situations: [
      { en: 'Are you happy?', vi: 'Con vui không?' },
      { en: 'Why are you sad?', vi: 'Sao con buồn thế?' },
      { en: 'It’s okay to cry.', vi: 'Khóc cũng không sao đâu.' },
      { en: 'I’m here for you.', vi: 'Có mẹ đây rồi.' },
      { en: "Don't be scared.", vi: 'Đừng sợ nhé con.' },
      { en: 'Are you angry?', vi: 'Con đang giận à?' },
      { en: 'Take a deep breath.', vi: 'Hít thở sâu nào con.' },
      { en: 'Tell me how you feel.', vi: 'Nói cho mẹ nghe con thấy sao.' },
      { en: 'I love you.', vi: 'Mẹ yêu con.' },
      { en: 'You make me happy.', vi: 'Con làm mẹ vui lắm.' },
      { en: 'It’s going to be okay.', vi: 'Rồi sẽ ổn thôi con.' },
      { en: 'Give me a hug.', vi: 'Ôm mẹ một cái nào.' },
      { en: 'Are you feeling better?', vi: 'Con thấy đỡ hơn chưa?' },
      { en: "Don't worry.", vi: 'Đừng lo nhé con.' },
      { en: 'I understand.', vi: 'Mẹ hiểu mà.' },
      { en: 'You are safe with me.', vi: 'Có mẹ, con an toàn mà.' },
      { en: "Let's calm down together.", vi: 'Mình cùng bình tĩnh lại nào.' },
      { en: 'Be kind to others.', vi: 'Hãy tốt bụng với mọi người nhé.' },
      { en: 'Can you say sorry?', vi: 'Con nói xin lỗi được không?' },
      { en: 'I’m so proud of you.', vi: 'Mẹ rất tự hào về con.' },
    ],
  },
  {
    slug: 'gio-di-ngu',
    name: 'Giờ đi ngủ',
    color: '#A06CD5',
    bg: '#E7E0F6',
    icon: 'moon',
    situations: [
      { en: 'Time for bed.', vi: 'Đến giờ đi ngủ rồi.' },
      { en: 'Brush your teeth.', vi: 'Đánh răng đi con.' },
      { en: 'Put on your pajamas.', vi: 'Mặc đồ ngủ vào nào.' },
      { en: 'Are you sleepy?', vi: 'Con buồn ngủ chưa?' },
      { en: "Let's read a bedtime story.", vi: 'Mình đọc truyện trước khi ngủ nào.' },
      { en: 'Lie down, please.', vi: 'Nằm xuống nào con.' },
      { en: 'Hug your teddy bear.', vi: 'Ôm gấu bông đi con.' },
      { en: 'Do you want the light on?', vi: 'Con muốn bật đèn ngủ không?' },
      { en: 'Close your eyes.', vi: 'Nhắm mắt lại con.' },
      { en: "Don't be afraid of the dark.", vi: 'Đừng sợ bóng tối nhé.' },
      { en: "Let's sing a lullaby.", vi: 'Mình hát ru nào.' },
      { en: 'It’s late now.', vi: 'Muộn rồi đấy con.' },
      { en: 'Turn off the light.', vi: 'Tắt đèn nào.' },
      { en: 'Say good night.', vi: 'Chúc ngủ ngon nào.' },
      { en: 'Sweet dreams!', vi: 'Ngủ ngon nhé!' },
      { en: 'I love you so much.', vi: 'Mẹ yêu con nhiều lắm.' },
      { en: 'See you in the morning.', vi: 'Sáng mai gặp lại nhé.' },
      { en: 'Sleep tight.', vi: 'Ngủ thật ngon nhé.' },
      { en: 'Rest well, my dear.', vi: 'Nghỉ ngơi cho khỏe nhé con.' },
      { en: 'Good night!', vi: 'Chúc ngủ ngon!' },
    ],
  },
  {
    slug: 'an-toan',
    name: 'An toàn',
    color: '#E23B3B',
    bg: '#FDE0E0',
    icon: 'shield',
    situations: [
      { en: 'Stop!', vi: 'Dừng lại!' },
      { en: 'Be careful!', vi: 'Cẩn thận nhé!' },
      { en: 'Watch out!', vi: 'Coi chừng!' },
      { en: "Don't touch that.", vi: 'Đừng chạm vào nhé.' },
      { en: 'It’s hot!', vi: 'Nóng đấy con!' },
      { en: 'Careful, it’s sharp.', vi: 'Cẩn thận, sắc đấy.' },
      { en: 'Hold my hand.', vi: 'Nắm tay mẹ nào.' },
      { en: "Don't run near the road.", vi: 'Đừng chạy gần đường nhé.' },
      { en: 'Look before you cross.', vi: 'Nhìn đường trước khi qua nhé.' },
      { en: 'Stay away from the stove.', vi: 'Tránh xa bếp ra con.' },
      { en: 'Keep away from the water.', vi: 'Tránh xa chỗ nước nhé.' },
      { en: "Don't climb up there.", vi: 'Đừng trèo lên đó nhé.' },
      { en: "Don't put that in your mouth.", vi: 'Đừng cho cái đó vào miệng nhé.' },
      { en: 'Buckle your seatbelt.', vi: 'Cài dây an toàn vào con.' },
      { en: "Don't talk to strangers.", vi: 'Đừng nói chuyện với người lạ nhé.' },
      { en: 'Wait for me.', vi: 'Đợi mẹ nhé.' },
      { en: 'Slow down.', vi: 'Chậm lại nào con.' },
      { en: 'Come back here, please.', vi: 'Quay lại đây nào con.' },
      { en: 'Stay close to me.', vi: 'Đi gần mẹ nhé.' },
      { en: 'Tell me if you feel unsafe.', vi: 'Thấy không an toàn thì báo mẹ nhé.' },
    ],
  },
  {
    slug: 'le-phep',
    name: 'Lễ phép',
    color: '#D98324',
    bg: '#FBEAD1',
    icon: 'manners',
    situations: [
      { en: 'Say please.', vi: 'Nói "làm ơn" nào.' },
      { en: 'Say thank you.', vi: 'Nói cảm ơn nào.' },
      { en: 'Say sorry.', vi: 'Nói xin lỗi nào.' },
      { en: 'Say excuse me.', vi: 'Nói "xin lỗi cho con qua" nào.' },
      { en: 'Say hello.', vi: 'Chào hỏi đi con.' },
      { en: 'Say goodbye.', vi: 'Chào tạm biệt nào.' },
      { en: 'Say "you’re welcome".', vi: 'Nói "không có gì" nào.' },
      { en: 'Wait for your turn.', vi: 'Đợi đến lượt con nhé.' },
      { en: 'Share with your friend.', vi: 'Chia sẻ với bạn nhé.' },
      { en: 'Ask nicely.', vi: 'Hỏi lịch sự nào.' },
      { en: "Don't interrupt, please.", vi: 'Đừng ngắt lời nhé.' },
      { en: 'Listen carefully.', vi: 'Lắng nghe kỹ nhé.' },
      { en: 'Look at me when I talk.', vi: 'Nhìn mẹ khi mẹ nói nhé.' },
      { en: 'Use kind words.', vi: 'Dùng lời nói dễ thương nhé.' },
      { en: 'Be gentle.', vi: 'Nhẹ nhàng thôi con.' },
      { en: 'Knock before you enter.', vi: 'Gõ cửa trước khi vào nhé.' },
      { en: 'Help each other.', vi: 'Giúp đỡ nhau nào.' },
      { en: 'Wait patiently.', vi: 'Kiên nhẫn chờ nhé.' },
      { en: 'That’s very polite.', vi: 'Con lễ phép quá.' },
      { en: 'Good manners, well done!', vi: 'Ngoan lắm, giỏi quá!' },
    ],
  },
  {
    slug: 'suc-khoe',
    name: 'Sức khỏe & ốm đau',
    color: '#2E9E8F',
    bg: '#D9F1EC',
    icon: 'health',
    situations: [
      { en: 'Are you feeling okay?', vi: 'Con thấy trong người ổn không?' },
      { en: 'Where does it hurt?', vi: 'Con đau ở đâu?' },
      { en: 'Do you have a fever?', vi: 'Con có sốt không?' },
      { en: 'Does your tummy hurt?', vi: 'Con đau bụng à?' },
      { en: 'Open your mouth, say ah.', vi: 'Há miệng, nói "a" nào.' },
      { en: 'Take your medicine.', vi: 'Uống thuốc đi con.' },
      { en: "Let's see the doctor.", vi: 'Mình đi khám bác sĩ nào.' },
      { en: 'Get some rest.', vi: 'Nghỉ ngơi chút nhé.' },
      { en: 'Drink some water.', vi: 'Uống chút nước đi con.' },
      { en: 'Are you cold?', vi: 'Con có lạnh không?' },
      { en: 'Are you too hot?', vi: 'Con có nóng quá không?' },
      { en: 'Do you feel dizzy?', vi: 'Con có thấy chóng mặt không?' },
      { en: 'Let me check your temperature.', vi: 'Để mẹ đo nhiệt độ nhé.' },
      { en: 'Blow your nose.', vi: 'Hỉ mũi đi con.' },
      { en: 'Cover your mouth when you sneeze.', vi: 'Hắt hơi thì che miệng nhé.' },
      { en: "Don't scratch it.", vi: 'Đừng gãi chỗ đó nhé.' },
      { en: 'Wash the cut gently.', vi: 'Rửa nhẹ vết thương nào.' },
      { en: "Let's put on a band-aid.", vi: 'Mình dán băng cá nhân nào.' },
      { en: 'Tell me if you feel sick.', vi: 'Thấy mệt thì báo mẹ nhé.' },
      { en: 'You’ll feel better soon.', vi: 'Con sẽ khỏe lại sớm thôi.' },
    ],
  },
  {
    slug: 'o-truong',
    name: 'Ở trường',
    color: '#3B7DD8',
    bg: '#DCEAFB',
    icon: 'school',
    situations: [
      { en: 'Have a good day at school.', vi: 'Chúc con một ngày vui ở trường.' },
      { en: 'Listen to your teacher.', vi: 'Nghe lời cô giáo nhé.' },
      { en: 'Be nice to your friends.', vi: 'Ngoan với các bạn nhé.' },
      { en: 'Raise your hand to speak.', vi: 'Giơ tay khi muốn nói nhé.' },
      { en: 'Line up, please.', vi: 'Xếp hàng nào con.' },
      { en: 'Share your toys.', vi: 'Chia đồ chơi cho bạn nhé.' },
      { en: 'Ask the teacher for help.', vi: 'Nhờ cô giúp nhé.' },
      { en: 'Say "may I go to the toilet?"', vi: 'Nói "con xin đi vệ sinh ạ" nhé.' },
      { en: 'Put your things away.', vi: 'Cất đồ gọn gàng nào.' },
      { en: 'Take care of your books.', vi: 'Giữ gìn sách vở nhé.' },
      { en: 'Do your best.', vi: 'Cố gắng hết sức nhé.' },
      { en: "Don't be shy.", vi: 'Đừng ngại nhé con.' },
      { en: 'Eat your snack.', vi: 'Ăn bữa phụ đi con.' },
      { en: 'Play nicely together.', vi: 'Chơi vui vẻ với nhau nhé.' },
      { en: 'Wait for the bell.', vi: 'Chờ chuông reo nhé.' },
      { en: 'Did you make a new friend?', vi: 'Con có bạn mới không?' },
      { en: 'What did you learn today?', vi: 'Hôm nay con học được gì?' },
      { en: 'How was school today?', vi: 'Hôm nay ở trường thế nào?' },
      { en: 'I’ll pick you up later.', vi: 'Lát nữa mẹ đón con nhé.' },
      { en: 'I’m so proud of you.', vi: 'Mẹ tự hào về con lắm.' },
    ],
  },
  {
    slug: 'viec-nha',
    name: 'Việc nhà',
    color: '#8B7BD8',
    bg: '#E7E3F7',
    icon: 'home',
    situations: [
      { en: "Let's clean up.", vi: 'Mình dọn dẹp nào.' },
      { en: 'Put away your toys.', vi: 'Cất đồ chơi đi con.' },
      { en: 'Can you help me?', vi: 'Con giúp mẹ được không?' },
      { en: 'Make your bed.', vi: 'Gấp chăn gối nào.' },
      { en: 'Throw it in the trash.', vi: 'Bỏ vào thùng rác nhé.' },
      { en: "Let's set the table.", vi: 'Mình dọn bàn ăn nào.' },
      { en: 'Water the plants.', vi: 'Tưới cây đi con.' },
      { en: 'Feed the pet.', vi: 'Cho thú cưng ăn nhé.' },
      { en: 'Wipe the table.', vi: 'Lau bàn đi con.' },
      { en: 'Fold your clothes.', vi: 'Gấp quần áo nào.' },
      { en: 'Put your shoes away.', vi: 'Cất giày lên kệ nhé.' },
      { en: 'Turn off the light.', vi: 'Tắt đèn đi con.' },
      { en: 'Close the door, please.', vi: 'Đóng cửa lại nhé.' },
      { en: 'Sweep the floor with me.', vi: 'Quét nhà cùng mẹ nào.' },
      { en: 'Hang up your towel.', vi: 'Treo khăn lên nhé.' },
      { en: "Don't make a mess.", vi: 'Đừng bày bừa nhé.' },
      { en: "Let's do it together.", vi: 'Mình cùng làm nào.' },
      { en: 'Sort the toys by color.', vi: 'Xếp đồ chơi theo màu nào.' },
      { en: 'Great helper!', vi: 'Trợ thủ giỏi quá!' },
      { en: 'Thank you for helping.', vi: 'Cảm ơn con đã giúp.' },
    ],
  },
  {
    slug: 'mua-sam',
    name: 'Đi mua sắm',
    color: '#E06A9C',
    bg: '#FBE0EC',
    icon: 'cart',
    situations: [
      { en: "Let's go shopping.", vi: 'Mình đi mua sắm nào.' },
      { en: 'Hold the cart.', vi: 'Giữ xe đẩy nhé.' },
      { en: 'Stay with me.', vi: 'Đi cùng mẹ nhé.' },
      { en: "Don't touch that.", vi: 'Đừng chạm vào nhé.' },
      { en: 'We need some milk.', vi: 'Mình cần mua sữa.' },
      { en: 'Put it back, please.', vi: 'Để lại chỗ cũ nhé.' },
      { en: 'What do we need?', vi: 'Mình cần mua gì nhỉ?' },
      { en: 'Pick a fruit you like.', vi: 'Chọn một loại quả con thích nào.' },
      { en: 'How much is it?', vi: 'Cái này bao nhiêu tiền?' },
      { en: "Let's pay at the counter.", vi: 'Mình ra quầy trả tiền nào.' },
      { en: 'Say thank you to the cashier.', vi: 'Cảm ơn cô thu ngân nhé.' },
      { en: 'Carry this bag for me.', vi: 'Xách giúp mẹ túi này nhé.' },
      { en: "Don't run in the store.", vi: 'Đừng chạy trong cửa hàng nhé.' },
      { en: 'Just one, okay?', vi: 'Chỉ một cái thôi nhé?' },
      { en: "Let's make a list.", vi: 'Mình lập danh sách nào.' },
      { en: 'Push the cart gently.', vi: 'Đẩy xe nhẹ nhàng nhé.' },
      { en: 'Wait in line.', vi: 'Xếp hàng chờ nhé.' },
      { en: 'That’s too expensive.', vi: 'Cái này đắt quá.' },
      { en: 'We’re done shopping.', vi: 'Mình mua xong rồi.' },
      { en: "Let's go home.", vi: 'Mình về nhà thôi.' },
    ],
  },
  {
    slug: 'thoi-tiet',
    name: 'Thời tiết',
    color: '#3FA9C9',
    bg: '#DAF0F7',
    icon: 'cloud',
    situations: [
      { en: 'It’s sunny today.', vi: 'Hôm nay trời nắng.' },
      { en: 'It’s raining.', vi: 'Trời đang mưa.' },
      { en: 'It’s cloudy.', vi: 'Trời nhiều mây.' },
      { en: 'It’s windy.', vi: 'Trời có gió.' },
      { en: 'It’s cold today.', vi: 'Hôm nay trời lạnh.' },
      { en: 'It’s hot outside.', vi: 'Ngoài trời nóng.' },
      { en: 'Wear a jacket.', vi: 'Mặc áo khoác vào con.' },
      { en: 'Take an umbrella.', vi: 'Mang ô theo nhé.' },
      { en: 'Put on your boots.', vi: 'Đi ủng vào con.' },
      { en: 'Look at the rainbow!', vi: 'Nhìn cầu vồng kìa!' },
      { en: 'The sun is shining.', vi: 'Mặt trời đang chiếu sáng.' },
      { en: 'It might rain later.', vi: 'Lát nữa có thể mưa đấy.' },
      { en: "Let's stay inside.", vi: 'Mình ở trong nhà nhé.' },
      { en: 'The wind is strong.', vi: 'Gió mạnh quá.' },
      { en: 'It’s snowing!', vi: 'Trời đang có tuyết!' },
      { en: 'Wear your warm hat.', vi: 'Đội mũ ấm vào con.' },
      { en: 'The sky is blue.', vi: 'Bầu trời xanh quá.' },
      { en: 'I hear thunder.', vi: 'Mẹ nghe tiếng sấm.' },
      { en: 'Close the window.', vi: 'Đóng cửa sổ lại nhé.' },
      { en: 'What’s the weather like?', vi: 'Thời tiết thế nào nhỉ?' },
    ],
  },
  {
    slug: 'le-hoi',
    name: 'Sinh nhật & lễ hội',
    color: '#E0526E',
    bg: '#FBDEE3',
    icon: 'gift',
    situations: [
      { en: 'Happy birthday!', vi: 'Chúc mừng sinh nhật!' },
      { en: 'Blow out the candles.', vi: 'Thổi nến đi con.' },
      { en: 'Make a wish.', vi: 'Ước một điều nào.' },
      { en: "Let's sing a song.", vi: 'Mình hát một bài nào.' },
      { en: 'Open your present.', vi: 'Mở quà ra nào.' },
      { en: 'Say thank you for the gift.', vi: 'Cảm ơn vì món quà nhé.' },
      { en: "Let's cut the cake.", vi: 'Mình cắt bánh nào.' },
      { en: 'Would you like some cake?', vi: 'Con ăn bánh không?' },
      { en: 'Invite your friends.', vi: 'Mời các bạn nhé.' },
      { en: 'Wear your party hat.', vi: 'Đội mũ sinh nhật vào con.' },
      { en: 'Merry Christmas!', vi: 'Giáng sinh vui vẻ!' },
      { en: 'Happy New Year!', vi: 'Chúc mừng năm mới!' },
      { en: "Let's decorate together.", vi: 'Mình cùng trang trí nào.' },
      { en: 'Give a gift to your friend.', vi: 'Tặng quà cho bạn nhé.' },
      { en: 'Smile for the photo.', vi: 'Cười lên chụp ảnh nào.' },
      { en: 'It’s a special day!', vi: 'Hôm nay là ngày đặc biệt!' },
      { en: "Let's clap for you.", vi: 'Mình vỗ tay nào.' },
      { en: 'How old are you now?', vi: 'Giờ con mấy tuổi rồi?' },
      { en: 'Have fun at the party.', vi: 'Chơi vui ở tiệc nhé.' },
      { en: 'Thank you for coming.', vi: 'Cảm ơn đã đến nhé.' },
    ],
  },
  {
    slug: 'gia-dinh',
    name: 'Gia đình',
    color: '#E68A3D',
    bg: '#FBEBD8',
    icon: 'family',
    situations: [
      { en: 'I love you.', vi: 'Mẹ yêu con.' },
      { en: 'Give grandma a hug.', vi: 'Ôm bà một cái nào.' },
      { en: 'Say hi to grandpa.', vi: 'Chào ông đi con.' },
      { en: 'This is your little brother.', vi: 'Đây là em trai của con.' },
      { en: 'Help your sister.', vi: 'Giúp chị/em con nhé.' },
      { en: "Let's call daddy.", vi: 'Mình gọi cho bố nào.' },
      { en: 'Family time!', vi: 'Giờ của cả nhà!' },
      { en: 'Kiss goodnight.', vi: 'Hôn chúc ngủ ngon nào.' },
      { en: 'We are a happy family.', vi: 'Nhà mình vui thật.' },
      { en: 'Share with your brother.', vi: 'Chia cho em nhé.' },
      { en: 'Be kind to each other.', vi: 'Yêu thương nhau nhé.' },
      { en: 'Grandma loves you.', vi: 'Bà yêu con lắm.' },
      { en: "Let's visit grandpa.", vi: 'Mình về thăm ông nào.' },
      { en: 'Hold the baby gently.', vi: 'Bế em nhẹ nhàng nhé.' },
      { en: 'Wait for your dad.', vi: 'Chờ bố về nhé.' },
      { en: "Let's eat together.", vi: 'Cả nhà cùng ăn nào.' },
      { en: 'Say I love you to mom.', vi: 'Nói yêu mẹ đi con.' },
      { en: 'Take care of each other.', vi: 'Chăm sóc nhau nhé.' },
      { en: 'We miss you.', vi: 'Cả nhà nhớ con.' },
      { en: 'Family hug!', vi: 'Cả nhà ôm nhau nào!' },
    ],
  },
  {
    slug: 'du-lich',
    name: 'Đi chơi xa',
    color: '#2FA37A',
    bg: '#DBF2E8',
    icon: 'car',
    situations: [
      { en: "Let's go on a trip!", vi: 'Mình đi chơi xa nào!' },
      { en: 'Buckle your seatbelt.', vi: 'Cài dây an toàn vào con.' },
      { en: "We're almost there.", vi: 'Sắp tới nơi rồi con.' },
      { en: 'Look out the window.', vi: 'Nhìn ra ngoài cửa sổ nào.' },
      { en: "Don't forget your hat.", vi: 'Đừng quên mũ nhé.' },
      { en: "Let's go to the beach.", vi: 'Mình ra biển nào.' },
      { en: 'Put on sunscreen.', vi: 'Bôi kem chống nắng nhé.' },
      { en: 'Stay near me.', vi: 'Đứng gần mẹ nhé.' },
      { en: "Let's build a sandcastle.", vi: 'Mình xây lâu đài cát nào.' },
      { en: 'Be careful in the water.', vi: 'Cẩn thận dưới nước nhé.' },
      { en: 'Drink water, it’s hot.', vi: 'Uống nước đi, trời nóng.' },
      { en: "Let's take a photo.", vi: 'Mình chụp ảnh nào.' },
      { en: 'Hold my hand here.', vi: 'Nắm tay mẹ ở đây nhé.' },
      { en: 'Are you having fun?', vi: 'Con chơi vui không?' },
      { en: "Let's pack our bags.", vi: 'Mình xếp hành lý nào.' },
      { en: 'Where do you want to go?', vi: 'Con muốn đi đâu?' },
      { en: "Don't wander off.", vi: 'Đừng đi lạc nhé.' },
      { en: "Let's rest for a while.", vi: 'Mình nghỉ một chút nào.' },
      { en: 'What a beautiful view!', vi: 'Cảnh đẹp quá!' },
      { en: 'Time to go home.', vi: 'Đến giờ về rồi.' },
    ],
  },
];

export function situationTopicBySlug(slug: string): SituationTopic | undefined {
  return SITUATION_TOPICS.find((t) => t.slug === slug);
}
