// PHIÊN ÂM IPA cho câu tiếng Anh (tạo tự động từ từ điển CMU qua eng-to-ipa).
// Map theo NGUYÊN VĂN câu tiếng Anh; dùng ở /tinh-huong-tieng-anh.
export const SITUATION_IPA: Record<string, string> = {
  "Good morning, sweetheart!": "gʊd ˈmɔrnɪŋ, sˈwiˌthɑrt!",
  "Did you sleep well?": "dɪd ju slip wɛl?",
  "Time to wake up!": "taɪm tɪ weɪk əp!",
  "Let's open the curtains.": "lɛts ˈoʊpən ðə ˈkərtənz.",
  "Stretch your arms up high.": "strɛʧ jʊr ɑrmz əp haɪ.",
  "Let's brush your teeth.": "lɛts brəʃ jʊr tiθ.",
  "Wash your face, please.": "wɑʃ jʊr feɪs, pliz.",
  "Let's get dressed.": "lɛts gɪt drɛst.",
  "Comb your hair.": "koʊm jʊr hɛr.",
  "Are you hungry?": "ər ju ˈhəŋgri?",
  "Let's have breakfast.": "lɛts hæv ˈbrɛkfəst.",
  "Drink some water.": "drɪŋk səm ˈwɔtər.",
  "Put on your shoes.": "pʊt ɔn jʊr ʃuz.",
  "Don't forget your bag.": "doʊnt fərˈgɛt jʊr bæg.",
  "Are you ready for school?": "ər ju ˈrɛdi fər skul?",
  "It’s a beautiful day!": "ɪts ə ˈbjutəfəl deɪ!",
  "Give me a morning hug!": "gɪv mi ə ˈmɔrnɪŋ həg!",
  "Did you have a nice dream?": "dɪd ju hæv ə nis drim?",
  "Let’s make the bed.": "lɛts meɪk ðə bɛd.",
  "Have a great day!": "hæv ə greɪt deɪ!",
  "Let's eat!": "lɛts it!",
  "Wash your hands first.": "wɑʃ jʊr hænz fərst.",
  "Sit down, please.": "sɪt daʊn, pliz.",
  "What would you like to eat?": "wət wʊd ju laɪk tɪ it?",
  "Do you want some rice?": "du ju wɔnt səm raɪs?",
  "Eat your vegetables.": "it jʊr ˈvɛʤtəbəlz.",
  "It’s delicious, right?": "ɪts dɪˈlɪʃəs, raɪt?",
  "Chew slowly.": "ʧu sˈloʊli.",
  "Don't play with your food.": "doʊnt pleɪ wɪθ jʊr fud.",
  "Would you like some more?": "wʊd ju laɪk səm mɔr?",
  "Are you full?": "ər ju fʊl?",
  "Drink your milk.": "drɪŋk jʊr mɪlk.",
  "Use your spoon.": "juz jʊr spun.",
  "Try a little bite.": "traɪ ə ˈlɪtəl baɪt.",
  "No sweets before dinner.": "noʊ swits ˌbiˈfɔr ˈdɪnər.",
  "Say thank you.": "seɪ θæŋk ju.",
  "Wipe your mouth.": "waɪp jʊr maʊθ.",
  "Let's clean up together.": "lɛts klin əp təˈgɛðər.",
  "Please finish your food.": "pliz ˈfɪnɪʃ jʊr fud.",
  "Time for a bath!": "taɪm fər ə bæθ!",
  "Let's take off your clothes.": "lɛts teɪk ɔf jʊr kloʊðz.",
  "Is the water warm?": "ɪz ðə ˈwɔtər wɔrm?",
  "Wash your body.": "wɑʃ jʊr ˈbɑdi.",
  "Don't forget your hair.": "doʊnt fərˈgɛt jʊr hɛr.",
  "Close your eyes.": "kloʊz jʊr aɪz.",
  "Rinse off the soap.": "rɪns ɔf ðə soʊp.",
  "Let's dry you off.": "lɛts draɪ ju ɔf.",
  "Put on your pajamas.": "pʊt ɔn jʊr pəˈʤɑməz.",
  "Brush your teeth.": "brəʃ jʊr tiθ.",
  "Wash your hands.": "wɑʃ jʊr hænz.",
  "Do you need to pee?": "du ju nid tɪ pi?",
  "Flush the toilet, please.": "fləʃ ðə ˈtɔɪlət, pliz.",
  "Blow your nose.": "bloʊ jʊr noʊz.",
  "Cover your mouth when you cough.": "ˈkəvər jʊr maʊθ wɪn ju kɔf.",
  "Careful, it’s slippery.": "ˈkɛrfəl, ɪts sˈlɪpəri.",
  "Dry your hands.": "draɪ jʊr hænz.",
  "You smell so fresh!": "ju smɛl soʊ frɛʃ!",
  "Comb your hair now.": "koʊm jʊr hɛr naʊ.",
  "All clean now!": "ɔl klin naʊ!",
  "Let's play!": "lɛts pleɪ!",
  "What do you want to play?": "wət du ju wɔnt tɪ pleɪ?",
  "Be careful!": "bi ˈkɛrfəl!",
  "It’s your turn.": "ɪts jʊr tərn.",
  "Well done!": "wɛl dən!",
  "Let's share the toys.": "lɛts ʃɛr ðə tɔɪz.",
  "Don't run too fast.": "doʊnt rən tu fæst.",
  "Let's build together.": "lɛts bɪld təˈgɛðər.",
  "Look at that!": "lʊk æt ðət!",
  "Can I play too?": "kən aɪ pleɪ tu?",
  "Let's draw a picture.": "lɛts drɔ ə ˈpɪkʧər.",
  "Be gentle with your friends.": "bi ˈʤɛnəl wɪθ jʊr frɛndz.",
  "Let's play hide and seek.": "lɛts pleɪ haɪd ənd sik.",
  "Catch the ball!": "kæʧ ðə bɔl!",
  "Take turns, please.": "teɪk tərnz, pliz.",
  "You’re doing great!": "jʊr duɪŋ greɪt!",
  "That’s so much fun!": "ðæts soʊ məʧ fən!",
  "One more time?": "wən mɔr taɪm?",
  "Time to clean up the toys.": "taɪm tɪ klin əp ðə tɔɪz.",
  "Let's take a little break.": "lɛts teɪk ə ˈlɪtəl breɪk.",
  "Let's go outside.": "lɛts goʊ ˈaʊtˈsaɪd.",
  "Hold my hand.": "hoʊld maɪ hænd.",
  "Wear your hat.": "wɛr jʊr hæt.",
  "It’s sunny today.": "ɪts ˈsəni təˈdeɪ.",
  "Stay close to me.": "steɪ kloʊz tɪ mi.",
  "Watch your step.": "wɔʧ jʊr stɛp.",
  "Look both ways.": "lʊk boʊθ weɪz.",
  "Wait for the green light.": "weɪt fər ðə grin laɪt.",
  "Let's cross the street.": "lɛts krɔs ðə strit.",
  "Look at the birds!": "lʊk æt ðə bərdz!",
  "Don't touch that.": "doʊnt təʧ ðət.",
  "Say hello to the neighbor.": "seɪ hɛˈloʊ tɪ ðə ˈneɪbər.",
  "Let's go to the park.": "lɛts goʊ tɪ ðə pɑrk.",
  "Are you tired?": "ər ju taɪərd?",
  "It might rain.": "ɪt maɪt reɪn.",
  "Bring your umbrella.": "brɪŋ jʊr ˈəmˌbrɛlə.",
  "Be polite, please.": "bi pəˈlaɪt, pliz.",
  "Did you have fun?": "dɪd ju hæv fən?",
  "Let's go home now.": "lɛts goʊ hoʊm naʊ.",
  "Let's read a book.": "lɛts rɛd ə bʊk.",
  "Great job!": "greɪt ʤɑb!",
  "I’m proud of you.": "əm praʊd əv ju.",
  "You did it!": "ju dɪd ɪt!",
  "Try again.": "traɪ əˈgɛn.",
  "Keep going!": "kip goʊɪŋ!",
  "That’s correct!": "ðæts kərˈɛkt!",
  "Let's count together.": "lɛts kaʊnt təˈgɛðər.",
  "What color is this?": "wət ˈkələr ɪz ðɪs?",
  "You’re so smart!": "jʊr soʊ smɑrt!",
  "Don't give up.": "doʊnt gɪv əp.",
  "Let's learn a new word.": "lɛts lərn ə nu wərd.",
  "Can you say it again?": "kən ju seɪ ɪt əˈgɛn?",
  "Good try!": "gʊd traɪ!",
  "You’re getting better.": "jʊr ˈgɪtɪŋ ˈbɛtər.",
  "Let's practice a little.": "lɛts ˈpræktɪs ə ˈlɪtəl.",
  "Show me what you drew.": "ʃoʊ mi wət ju dru.",
  "Amazing work!": "əˈmeɪzɪŋ wərk!",
  "I believe in you.": "aɪ bɪˈliv ɪn ju.",
  "High five!": "haɪ faɪv!",
  "Are you happy?": "ər ju ˈhæpi?",
  "Why are you sad?": "waɪ ər ju sæd?",
  "It’s okay to cry.": "ɪts ˌoʊˈkeɪ tɪ kraɪ.",
  "I’m here for you.": "əm hir fər ju.",
  "Don't be scared.": "doʊnt bi skɛrd.",
  "Are you angry?": "ər ju ˈæŋgri?",
  "Take a deep breath.": "teɪk ə dip brɛθ.",
  "Tell me how you feel.": "tɛl mi haʊ ju fil.",
  "I love you.": "aɪ ləv ju.",
  "You make me happy.": "ju meɪk mi ˈhæpi.",
  "It’s going to be okay.": "ɪts goʊɪŋ tɪ bi ˌoʊˈkeɪ.",
  "Give me a hug.": "gɪv mi ə həg.",
  "Are you feeling better?": "ər ju ˈfilɪŋ ˈbɛtər?",
  "Don't worry.": "doʊnt ˈwəri.",
  "I understand.": "aɪ ˌəndərˈstænd.",
  "You are safe with me.": "ju ər seɪf wɪθ mi.",
  "Let's calm down together.": "lɛts kɑm daʊn təˈgɛðər.",
  "Be kind to others.": "bi kaɪnd tɪ ˈəðərz.",
  "Can you say sorry?": "kən ju seɪ ˈsɑri?",
  "I’m so proud of you.": "əm soʊ praʊd əv ju.",
  "Time for bed.": "taɪm fər bɛd.",
  "Are you sleepy?": "ər ju sˈlipi?",
  "Let's read a bedtime story.": "lɛts rɛd ə ˈbɛdˌtaɪm ˈstɔri.",
  "Lie down, please.": "laɪ daʊn, pliz.",
  "Hug your teddy bear.": "həg jʊr ˈtɛdi bɛr.",
  "Do you want the light on?": "du ju wɔnt ðə laɪt ɔn?",
  "Don't be afraid of the dark.": "doʊnt bi əˈfreɪd əv ðə dɑrk.",
  "Let's sing a lullaby.": "lɛts sɪŋ ə ˈlələˌbaɪ.",
  "It’s late now.": "ɪts leɪt naʊ.",
  "Turn off the light.": "tərn ɔf ðə laɪt.",
  "Say good night.": "seɪ gʊd naɪt.",
  "Sweet dreams!": "swit drimz!",
  "I love you so much.": "aɪ ləv ju soʊ məʧ.",
  "See you in the morning.": "si ju ɪn ðə ˈmɔrnɪŋ.",
  "Sleep tight.": "slip taɪt.",
  "Rest well, my dear.": "rɛst wɛl, maɪ dɪr.",
  "Good night!": "gʊd naɪt!",
  "Stop!": "stɑp!",
  "Watch out!": "wɔʧ aʊt!",
  "It’s hot!": "ɪts hɑt!",
  "Careful, it’s sharp.": "ˈkɛrfəl, ɪts ʃɑrp.",
  "Don't run near the road.": "doʊnt rən nɪr ðə roʊd.",
  "Look before you cross.": "lʊk ˌbiˈfɔr ju krɔs.",
  "Stay away from the stove.": "steɪ əˈweɪ frəm ðə stoʊv.",
  "Keep away from the water.": "kip əˈweɪ frəm ðə ˈwɔtər.",
  "Don't climb up there.": "doʊnt klaɪm əp ðɛr.",
  "Don't put that in your mouth.": "doʊnt pʊt ðət ɪn jʊr maʊθ.",
  "Buckle your seatbelt.": "ˈbəkəl jʊr ˈsitˌbɛlt.",
  "Don't talk to strangers.": "doʊnt tɔk tɪ ˈstreɪnʤərz.",
  "Wait for me.": "weɪt fər mi.",
  "Slow down.": "sloʊ daʊn.",
  "Come back here, please.": "kəm bæk hir, pliz.",
  "Tell me if you feel unsafe.": "tɛl mi ɪf ju fil ənˈseɪf.",
  "Say please.": "seɪ pliz.",
  "Say sorry.": "seɪ ˈsɑri.",
  "Say excuse me.": "seɪ ɪkˈskjuz mi.",
  "Say hello.": "seɪ hɛˈloʊ.",
  "Say goodbye.": "seɪ ˌgʊdˈbaɪ.",
  "Say \"you’re welcome\".": "seɪ \"jʊr ˈwɛlkəm\".",
  "Wait for your turn.": "weɪt fər jʊr tərn.",
  "Share with your friend.": "ʃɛr wɪθ jʊr frɛnd.",
  "Ask nicely.": "æsk ˈnaɪsli.",
  "Don't interrupt, please.": "doʊnt ˌɪntərˈəpt, pliz.",
  "Listen carefully.": "ˈlɪsən ˈkɛrfəli.",
  "Look at me when I talk.": "lʊk æt mi wɪn aɪ tɔk.",
  "Use kind words.": "juz kaɪnd wərdz.",
  "Be gentle.": "bi ˈʤɛnəl.",
  "Knock before you enter.": "nɑk ˌbiˈfɔr ju ˈɛnər.",
  "Help each other.": "hɛlp iʧ ˈəðər.",
  "Wait patiently.": "weɪt ˈpeɪʃəntli.",
  "That’s very polite.": "ðæts ˈvɛri pəˈlaɪt.",
  "Good manners, well done!": "gʊd ˈmænərz, wɛl dən!",
  "Are you feeling okay?": "ər ju ˈfilɪŋ ˌoʊˈkeɪ?",
  "Where does it hurt?": "wɛr dɪz ɪt hərt?",
  "Do you have a fever?": "du ju hæv ə ˈfivər?",
  "Does your tummy hurt?": "dɪz jʊr ˈtəmi hərt?",
  "Open your mouth, say ah.": "ˈoʊpən jʊr maʊθ, seɪ ɑ.",
  "Take your medicine.": "teɪk jʊr ˈmɛdəsən.",
  "Let's see the doctor.": "lɛts si ðə ˈdɔktər.",
  "Get some rest.": "gɪt səm rɛst.",
  "Are you cold?": "ər ju koʊld?",
  "Are you too hot?": "ər ju tu hɑt?",
  "Do you feel dizzy?": "du ju fil ˈdɪzi?",
  "Let me check your temperature.": "lɛt mi ʧɛk jʊr ˈtɛmpərəʧər.",
  "Cover your mouth when you sneeze.": "ˈkəvər jʊr maʊθ wɪn ju sniz.",
  "Don't scratch it.": "doʊnt skræʧ ɪt.",
  "Wash the cut gently.": "wɑʃ ðə kət ˈʤɛntli.",
  "Let's put on a band-aid.": "lɛts pʊt ɔn ə bænd-eɪd.",
  "Tell me if you feel sick.": "tɛl mi ɪf ju fil sɪk.",
  "You’ll feel better soon.": "jul fil ˈbɛtər sun.",
  "Have a good day at school.": "hæv ə gʊd deɪ æt skul.",
  "Listen to your teacher.": "ˈlɪsən tɪ jʊr ˈtiʧər.",
  "Be nice to your friends.": "bi nis tɪ jʊr frɛndz.",
  "Raise your hand to speak.": "reɪz jʊr hænd tɪ spik.",
  "Line up, please.": "laɪn əp, pliz.",
  "Share your toys.": "ʃɛr jʊr tɔɪz.",
  "Ask the teacher for help.": "æsk ðə ˈtiʧər fər hɛlp.",
  "Say \"may I go to the toilet?\"": "seɪ \"meɪ aɪ goʊ tɪ ðə ˈtɔɪlət?\"",
  "Put your things away.": "pʊt jʊr θɪŋz əˈweɪ.",
  "Take care of your books.": "teɪk kɛr əv jʊr bʊks.",
  "Do your best.": "du jʊr bɛst.",
  "Don't be shy.": "doʊnt bi ʃaɪ.",
  "Eat your snack.": "it jʊr snæk.",
  "Play nicely together.": "pleɪ ˈnaɪsli təˈgɛðər.",
  "Wait for the bell.": "weɪt fər ðə bɛl.",
  "Did you make a new friend?": "dɪd ju meɪk ə nu frɛnd?",
  "What did you learn today?": "wət dɪd ju lərn təˈdeɪ?",
  "How was school today?": "haʊ wɑz skul təˈdeɪ?",
  "I’ll pick you up later.": "aɪl pɪk ju əp ˈleɪtər.",
  "Let's clean up.": "lɛts klin əp.",
  "Put away your toys.": "pʊt əˈweɪ jʊr tɔɪz.",
  "Can you help me?": "kən ju hɛlp mi?",
  "Make your bed.": "meɪk jʊr bɛd.",
  "Throw it in the trash.": "θroʊ ɪt ɪn ðə træʃ.",
  "Let's set the table.": "lɛts sɛt ðə ˈteɪbəl.",
  "Water the plants.": "ˈwɔtər ðə plænts.",
  "Feed the pet.": "fid ðə pɛt.",
  "Wipe the table.": "waɪp ðə ˈteɪbəl.",
  "Fold your clothes.": "foʊld jʊr kloʊðz.",
  "Put your shoes away.": "pʊt jʊr ʃuz əˈweɪ.",
  "Close the door, please.": "kloʊz ðə dɔr, pliz.",
  "Sweep the floor with me.": "swip ðə flɔr wɪθ mi.",
  "Hang up your towel.": "hæŋ əp jʊr taʊəl.",
  "Don't make a mess.": "doʊnt meɪk ə mɛs.",
  "Let's do it together.": "lɛts du ɪt təˈgɛðər.",
  "Sort the toys by color.": "sɔrt ðə tɔɪz baɪ ˈkələr.",
  "Great helper!": "greɪt ˈhɛlpər!",
  "Thank you for helping.": "θæŋk ju fər ˈhɛlpɪŋ.",
  "Let's go shopping.": "lɛts goʊ ˈʃɑpɪŋ.",
  "Hold the cart.": "hoʊld ðə kɑrt.",
  "Stay with me.": "steɪ wɪθ mi.",
  "We need some milk.": "wi nid səm mɪlk.",
  "Put it back, please.": "pʊt ɪt bæk, pliz.",
  "What do we need?": "wət du wi nid?",
  "Pick a fruit you like.": "pɪk ə frut ju laɪk.",
  "How much is it?": "haʊ məʧ ɪz ɪt?",
  "Let's pay at the counter.": "lɛts peɪ æt ðə ˈkaʊntər.",
  "Say thank you to the cashier.": "seɪ θæŋk ju tɪ ðə kæˈʃɪr.",
  "Carry this bag for me.": "ˈkɛri ðɪs bæg fər mi.",
  "Don't run in the store.": "doʊnt rən ɪn ðə stɔr.",
  "Just one, okay?": "ʤɪst wən, ˌoʊˈkeɪ?",
  "Let's make a list.": "lɛts meɪk ə lɪst.",
  "Push the cart gently.": "pʊʃ ðə kɑrt ˈʤɛntli.",
  "Wait in line.": "weɪt ɪn laɪn.",
  "That’s too expensive.": "ðæts tu ɪkˈspɛnsɪv.",
  "We’re done shopping.": "wɪr dən ˈʃɑpɪŋ.",
  "Let's go home.": "lɛts goʊ hoʊm.",
  "It’s raining.": "ɪts ˈreɪnɪŋ.",
  "It’s cloudy.": "ɪts ˈklaʊdi.",
  "It’s windy.": "ɪts ˈwɪndi.",
  "It’s cold today.": "ɪts koʊld təˈdeɪ.",
  "It’s hot outside.": "ɪts hɑt ˈaʊtˈsaɪd.",
  "Wear a jacket.": "wɛr ə ˈʤækɪt.",
  "Take an umbrella.": "teɪk ən ˈəmˌbrɛlə.",
  "Put on your boots.": "pʊt ɔn jʊr buts.",
  "Look at the rainbow!": "lʊk æt ðə ˈreɪnˌboʊ!",
  "The sun is shining.": "ðə sən ɪz ˈʃaɪnɪŋ.",
  "It might rain later.": "ɪt maɪt reɪn ˈleɪtər.",
  "Let's stay inside.": "lɛts steɪ ˌɪnˈsaɪd.",
  "The wind is strong.": "ðə wɪnd ɪz strɔŋ.",
  "It’s snowing!": "ɪts snoʊɪŋ!",
  "Wear your warm hat.": "wɛr jʊr wɔrm hæt.",
  "The sky is blue.": "ðə skaɪ ɪz blu.",
  "I hear thunder.": "aɪ hir ˈθəndər.",
  "Close the window.": "kloʊz ðə ˈwɪndoʊ.",
  "What’s the weather like?": "wəts ðə ˈwɛðər laɪk?",
  "Happy birthday!": "ˈhæpi ˈbərθˌdeɪ!",
  "Blow out the candles.": "bloʊ aʊt ðə ˈkændəlz.",
  "Make a wish.": "meɪk ə wɪʃ.",
  "Let's sing a song.": "lɛts sɪŋ ə sɔŋ.",
  "Open your present.": "ˈoʊpən jʊr ˈprɛzənt.",
  "Say thank you for the gift.": "seɪ θæŋk ju fər ðə gɪft.",
  "Let's cut the cake.": "lɛts kət ðə keɪk.",
  "Would you like some cake?": "wʊd ju laɪk səm keɪk?",
  "Invite your friends.": "ˌɪnˈvaɪt jʊr frɛndz.",
  "Wear your party hat.": "wɛr jʊr ˈpɑrti hæt.",
  "Merry Christmas!": "ˈmɛri ˈkrɪsməs!",
  "Happy New Year!": "ˈhæpi nu jɪr!",
  "Let's decorate together.": "lɛts ˈdɛkərˌeɪt təˈgɛðər.",
  "Give a gift to your friend.": "gɪv ə gɪft tɪ jʊr frɛnd.",
  "Smile for the photo.": "smaɪl fər ðə ˈfoʊˌtoʊ.",
  "It’s a special day!": "ɪts ə ˈspɛʃəl deɪ!",
  "Let's clap for you.": "lɛts klæp fər ju.",
  "How old are you now?": "haʊ oʊld ər ju naʊ?",
  "Have fun at the party.": "hæv fən æt ðə ˈpɑrti.",
  "Thank you for coming.": "θæŋk ju fər ˈkəmɪŋ.",
  "Give grandma a hug.": "gɪv ˈgrændmɑ ə həg.",
  "Say hi to grandpa.": "seɪ haɪ tɪ ˈgrændˌpɑ.",
  "This is your little brother.": "ðɪs ɪz jʊr ˈlɪtəl ˈbrəðər.",
  "Help your sister.": "hɛlp jʊr ˈsɪstər.",
  "Let's call daddy.": "lɛts kɔl ˈdædi.",
  "Family time!": "ˈfæməli taɪm!",
  "Kiss goodnight.": "kɪs ˈgʊdˌnaɪt.",
  "We are a happy family.": "wi ər ə ˈhæpi ˈfæməli.",
  "Share with your brother.": "ʃɛr wɪθ jʊr ˈbrəðər.",
  "Be kind to each other.": "bi kaɪnd tɪ iʧ ˈəðər.",
  "Grandma loves you.": "ˈgrændmɑ ləvz ju.",
  "Let's visit grandpa.": "lɛts ˈvɪzɪt ˈgrændˌpɑ.",
  "Hold the baby gently.": "hoʊld ðə ˈbeɪbi ˈʤɛntli.",
  "Wait for your dad.": "weɪt fər jʊr dæd.",
  "Let's eat together.": "lɛts it təˈgɛðər.",
  "Say I love you to mom.": "seɪ aɪ ləv ju tɪ mɑm.",
  "Take care of each other.": "teɪk kɛr əv iʧ ˈəðər.",
  "We miss you.": "wi mɪs ju.",
  "Family hug!": "ˈfæməli həg!",
  "Let's go on a trip!": "lɛts goʊ ɔn ə trɪp!",
  "We're almost there.": "wɪr ˈɔlˌmoʊst ðɛr.",
  "Look out the window.": "lʊk aʊt ðə ˈwɪndoʊ.",
  "Don't forget your hat.": "doʊnt fərˈgɛt jʊr hæt.",
  "Let's go to the beach.": "lɛts goʊ tɪ ðə biʧ.",
  "Put on sunscreen.": "pʊt ɔn ˈsənskrin.",
  "Stay near me.": "steɪ nɪr mi.",
  "Let's build a sandcastle.": "lɛts bɪld ə ˈsændˌkæsəl.",
  "Be careful in the water.": "bi ˈkɛrfəl ɪn ðə ˈwɔtər.",
  "Drink water, it’s hot.": "drɪŋk ˈwɔtər, ɪts hɑt.",
  "Let's take a photo.": "lɛts teɪk ə ˈfoʊˌtoʊ.",
  "Hold my hand here.": "hoʊld maɪ hænd hir.",
  "Are you having fun?": "ər ju ˈhævɪŋ fən?",
  "Let's pack our bags.": "lɛts pæk ɑr bægz.",
  "Where do you want to go?": "wɛr du ju wɔnt tɪ goʊ?",
  "Don't wander off.": "doʊnt ˈwɑndər ɔf.",
  "Let's rest for a while.": "lɛts rɛst fər ə waɪl.",
  "What a beautiful view!": "wət ə ˈbjutəfəl vju!",
  "Time to go home.": "taɪm tɪ goʊ hoʊm.",
};
