// Truyện cổ tích Việt Nam cho bé — kể lại ngắn gọn (truyện dân gian, không bản quyền).
// Đọc từng câu / đọc cả truyện bằng giọng Việt (speakSequence). Mỗi câu ≤ ~180 ký tự để đọc trọn.

export type TruyenQuestion = { q: string; options: string[]; correct: number; explain: string };

export type Truyen = {
  slug: string;
  emoji: string;
  title: string;
  cau: string[]; // các câu trong truyện
  baiHoc: string; // bài học rút ra
  cauHoi: TruyenQuestion[]; // câu hỏi đọc hiểu
};

export const TRUYEN_CO_TICH: Truyen[] = [
  {
    slug: 'thanh-giong', emoji: '🐎', title: 'Thánh Gióng',
    cau: [
      'Ngày xưa, ở làng Gióng có hai vợ chồng già hiền lành mà mãi chưa có con.',
      'Một hôm, bà lão ra đồng thấy một vết chân rất to, liền ướm thử. Về nhà bà mang thai và sinh ra một cậu bé.',
      'Lạ thay, cậu bé lên ba vẫn không biết nói, biết cười, cũng chẳng biết đi.',
      'Bấy giờ giặc Ân sang xâm lược nước ta. Nhà vua sai sứ giả đi tìm người tài đánh giặc.',
      'Nghe tiếng sứ giả, cậu bé bỗng cất tiếng nói: "Mẹ mời sứ giả vào đây cho con!"',
      'Cậu bảo sứ giả về tâu vua rèn cho mình ngựa sắt, roi sắt và áo giáp sắt.',
      'Từ đó, cậu bé lớn nhanh như thổi, ăn bao nhiêu cũng không no, áo vừa mặc xong đã chật.',
      'Giặc đến, cậu bé vươn vai thành tráng sĩ, mặc giáp sắt, cưỡi ngựa sắt xông ra trận.',
      'Ngựa sắt phun lửa, tráng sĩ vung roi đánh tan quân giặc. Roi gãy, chàng nhổ tre bên đường quật vào giặc.',
      'Dẹp xong giặc, tráng sĩ cưỡi ngựa lên đỉnh núi Sóc, cởi áo giáp rồi cả người lẫn ngựa bay về trời.',
      'Nhớ ơn, vua phong là Phù Đổng Thiên Vương và lập đền thờ. Dân ta quen gọi là Thánh Gióng.',
    ],
    baiHoc: 'Lòng yêu nước và ý chí có thể làm nên điều phi thường. Ai cũng có thể góp sức bảo vệ quê hương.',
    cauHoi: [
      { q: 'Bà lão mang thai sau khi làm điều gì?', options: ['Ướm chân vào một vết chân to', 'Uống nước suối', 'Ăn quả lạ'], correct: 0, explain: 'Bà ra đồng thấy vết chân to, ướm thử rồi về nhà mang thai.' },
      { q: 'Lên ba tuổi, cậu bé Gióng như thế nào?', options: ['Chưa biết nói, cười, đi', 'Rất nghịch ngợm', 'Học rất giỏi'], correct: 0, explain: 'Cậu bé lên ba vẫn không biết nói, biết cười, cũng chẳng biết đi.' },
      { q: 'Điều gì khiến cậu bé bỗng cất tiếng nói?', options: ['Nghe tiếng sứ giả tìm người tài', 'Nghe mẹ hát', 'Thấy con chim'], correct: 0, explain: 'Nghe sứ giả rao tìm người đánh giặc, cậu bé liền cất tiếng nói.' },
      { q: 'Thánh Gióng lớn lên đánh giặc nào?', options: ['Giặc Ân', 'Giặc Minh', 'Giặc Nguyên'], correct: 0, explain: 'Truyện kể giặc Ân sang xâm lược nước ta.' },
      { q: 'Gióng xin nhà vua rèn cho những gì?', options: ['Ngựa sắt, roi sắt, áo giáp sắt', 'Thuyền và buồm', 'Cung tên và khiên'], correct: 0, explain: 'Cậu bảo sứ giả tâu vua rèn ngựa sắt, roi sắt và áo giáp sắt.' },
      { q: 'Sau khi gặp sứ giả, cậu bé lớn lên ra sao?', options: ['Lớn nhanh như thổi, ăn mấy cũng không no', 'Vẫn nhỏ như cũ', 'Gầy đi'], correct: 0, explain: 'Cậu bé lớn nhanh như thổi, ăn bao nhiêu cũng không no.' },
      { q: 'Con ngựa sắt của Gióng có gì đặc biệt?', options: ['Phun ra lửa', 'Biết bơi', 'Biết nói'], correct: 0, explain: 'Ngựa sắt phun lửa, giúp tráng sĩ xông trận đánh giặc.' },
      { q: 'Khi roi sắt gãy, Gióng dùng gì để đánh giặc?', options: ['Cây tre', 'Thanh gươm', 'Cung tên'], correct: 0, explain: 'Chàng nhổ tre bên đường quật vào giặc.' },
      { q: 'Đánh tan giặc xong, tráng sĩ đi đâu?', options: ['Cưỡi ngựa bay về trời', 'Về nhà với mẹ', 'Ở lại làm quan'], correct: 0, explain: 'Chàng lên đỉnh núi Sóc, cởi áo giáp rồi cả người lẫn ngựa bay về trời.' },
      { q: 'Nhà vua phong cho Gióng danh hiệu gì?', options: ['Phù Đổng Thiên Vương', 'Trạng nguyên', 'Sơn Tinh'], correct: 0, explain: 'Nhớ ơn, vua phong là Phù Đổng Thiên Vương và lập đền thờ.' },
    ],
  },
  {
    slug: 'son-tinh-thuy-tinh', emoji: '⛰️', title: 'Sơn Tinh – Thủy Tinh',
    cau: [
      'Vua Hùng thứ mười tám có một người con gái xinh đẹp tên là Mị Nương.',
      'Vua muốn kén cho con một người chồng thật tài giỏi.',
      'Một hôm, có hai chàng trai cùng đến cầu hôn.',
      'Một người là Sơn Tinh, chúa vùng núi Tản Viên, vẫy tay là núi đồi mọc lên.',
      'Người kia là Thủy Tinh, chúa vùng nước thẳm, hô mưa gọi gió được.',
      'Cả hai đều tài giỏi nên vua ra điều kiện: ai mang lễ vật đến trước sẽ được cưới Mị Nương.',
      'Hôm sau, Sơn Tinh mang lễ vật đến trước và rước Mị Nương về núi.',
      'Thủy Tinh đến sau, không lấy được vợ, nổi giận đuổi theo.',
      'Thủy Tinh hô mưa gió, dâng nước lũ ngập cả ruộng đồng, nhà cửa.',
      'Sơn Tinh không hề nao núng, nước dâng cao bao nhiêu thì núi lại cao lên bấy nhiêu.',
      'Đánh mãi không thắng, Thủy Tinh đành rút quân.',
      'Từ đó, năm nào Thủy Tinh cũng dâng nước đánh Sơn Tinh, gây ra lũ lụt, nhưng lần nào cũng thua.',
    ],
    baiHoc: 'Truyện giải thích hiện tượng lũ lụt hằng năm và ca ngợi tinh thần bền bỉ chống thiên tai của ông cha ta.',
    cauHoi: [
      { q: 'Mị Nương là con gái của ai?', options: ['Vua Hùng thứ mười tám', 'Long Quân', 'Sơn Tinh'], correct: 0, explain: 'Mị Nương là con gái xinh đẹp của Vua Hùng thứ mười tám.' },
      { q: 'Vua Hùng muốn kén cho con một người chồng như thế nào?', options: ['Thật tài giỏi', 'Thật giàu có', 'Thật đông con'], correct: 0, explain: 'Vua muốn kén cho Mị Nương một người chồng thật tài giỏi.' },
      { q: 'Sơn Tinh là chúa vùng nào?', options: ['Vùng núi Tản Viên', 'Vùng biển', 'Vùng trời'], correct: 0, explain: 'Sơn Tinh là chúa vùng núi Tản Viên, vẫy tay là núi đồi mọc lên.' },
      { q: 'Thủy Tinh có tài phép gì?', options: ['Hô mưa gọi gió', 'Dời núi', 'Bay lên trời'], correct: 0, explain: 'Thủy Tinh là chúa vùng nước thẳm, hô mưa gọi gió được.' },
      { q: 'Vua ra điều kiện gì để chọn rể?', options: ['Ai mang lễ vật đến trước', 'Ai khoẻ hơn', 'Ai giàu hơn'], correct: 0, explain: 'Vua hẹn ai mang lễ vật đến trước sẽ được cưới Mị Nương.' },
      { q: 'Ai đã cưới được Mị Nương?', options: ['Sơn Tinh', 'Thủy Tinh', 'Không ai'], correct: 0, explain: 'Sơn Tinh mang lễ vật đến trước nên cưới được Mị Nương.' },
      { q: 'Vì sao Thủy Tinh nổi giận đuổi theo?', options: ['Đến sau, không lấy được vợ', 'Bị chê cười', 'Mất lễ vật'], correct: 0, explain: 'Thủy Tinh đến sau, không lấy được Mị Nương nên nổi giận.' },
      { q: 'Thủy Tinh dâng nước lũ, Sơn Tinh làm gì?', options: ['Dâng núi cao lên chống lại', 'Bỏ chạy', 'Cầu xin'], correct: 0, explain: 'Nước dâng cao bao nhiêu, Sơn Tinh cho núi cao lên bấy nhiêu.' },
      { q: 'Kết cục cuộc chiến ra sao?', options: ['Thủy Tinh thua, đành rút quân', 'Sơn Tinh thua', 'Hai bên hoà'], correct: 0, explain: 'Đánh mãi không thắng, Thủy Tinh đành rút quân.' },
      { q: 'Vì sao hằng năm có lũ lụt (theo truyện)?', options: ['Thủy Tinh dâng nước đánh Sơn Tinh', 'Trời mưa nhiều', 'Sông đầy nước'], correct: 0, explain: 'Năm nào Thủy Tinh cũng dâng nước đánh Sơn Tinh để trả thù.' },
    ],
  },
  {
    slug: 'su-tich-ho-guom', emoji: '🗡️', title: 'Sự tích Hồ Gươm',
    cau: [
      'Thời giặc Minh đô hộ, ở vùng Lam Sơn có nghĩa quân do Lê Lợi đứng đầu nổi dậy chống giặc.',
      'Buổi đầu, nghĩa quân còn yếu, nhiều lần thua trận.',
      'Đức Long Quân quyết định cho nghĩa quân mượn thanh gươm thần để đánh giặc.',
      'Một người dân chài tên Lê Thận ba lần kéo lưới đều được một lưỡi gươm.',
      'Sau này, Lê Lợi tình cờ nhặt được một chuôi gươm nạm ngọc trên cây trong rừng.',
      'Lạ thay, lưỡi gươm của Lê Thận tra vào chuôi gươm ấy thì vừa khít.',
      'Có gươm thần, nghĩa quân đánh đâu thắng đó, cuối cùng đuổi sạch giặc Minh ra khỏi bờ cõi.',
      'Đất nước thanh bình, Lê Lợi lên làm vua.',
      'Một hôm, vua dạo thuyền trên hồ Tả Vọng thì một con rùa vàng nổi lên.',
      'Rùa vàng nói: "Xin bệ hạ trả gươm lại cho Long Quân!"',
      'Vua nâng gươm, rùa vàng đớp lấy rồi lặn xuống nước.',
      'Từ đó, hồ Tả Vọng được đổi tên thành Hồ Gươm (hay Hồ Hoàn Kiếm).',
    ],
    baiHoc: 'Truyện ca ngợi tinh thần đoàn kết đánh giặc cứu nước và giải thích tên gọi Hồ Hoàn Kiếm ở Hà Nội.',
    cauHoi: [
      { q: 'Nghĩa quân Lam Sơn nổi dậy chống giặc nào?', options: ['Giặc Minh', 'Giặc Ân', 'Giặc Nguyên'], correct: 0, explain: 'Thời giặc Minh đô hộ, nghĩa quân Lam Sơn nổi dậy chống lại.' },
      { q: 'Ai lãnh đạo nghĩa quân đánh giặc Minh?', options: ['Lê Lợi', 'Lê Thận', 'Long Quân'], correct: 0, explain: 'Lê Lợi đứng đầu nghĩa quân Lam Sơn.' },
      { q: 'Buổi đầu, nghĩa quân như thế nào?', options: ['Còn yếu, nhiều lần thua trận', 'Rất mạnh', 'Đông vô kể'], correct: 0, explain: 'Buổi đầu nghĩa quân còn yếu, nhiều lần thua trận.' },
      { q: 'Ai quyết định cho nghĩa quân mượn gươm thần?', options: ['Đức Long Quân', 'Vua Hùng', 'Rùa vàng'], correct: 0, explain: 'Đức Long Quân cho nghĩa quân mượn gươm thần để đánh giặc.' },
      { q: 'Người dân chài kéo lưới được phần nào của gươm?', options: ['Lưỡi gươm', 'Chuôi gươm', 'Vỏ gươm'], correct: 0, explain: 'Lê Thận ba lần kéo lưới đều được một lưỡi gươm.' },
      { q: 'Lê Lợi tình cờ nhặt được gì trong rừng?', options: ['Chuôi gươm nạm ngọc', 'Lưỡi gươm', 'Một túi vàng'], correct: 0, explain: 'Lê Lợi nhặt được chuôi gươm nạm ngọc trên cây trong rừng.' },
      { q: 'Khi có gươm thần, nghĩa quân đánh giặc ra sao?', options: ['Đánh đâu thắng đó', 'Vẫn thua', 'Rút lui'], correct: 0, explain: 'Có gươm thần, nghĩa quân đánh đâu thắng đó, đuổi sạch giặc Minh.' },
      { q: 'Sau khi đất nước thanh bình, Lê Lợi làm gì?', options: ['Lên làm vua', 'Về quê', 'Đi tu'], correct: 0, explain: 'Đất nước thanh bình, Lê Lợi lên làm vua.' },
      { q: 'Con vật nào nổi lên đòi lại gươm thần?', options: ['Rùa vàng', 'Cá chép', 'Rồng'], correct: 0, explain: 'Khi vua dạo thuyền, một con rùa vàng nổi lên đòi gươm.' },
      { q: 'Hồ Tả Vọng được đổi tên thành gì?', options: ['Hồ Gươm (Hồ Hoàn Kiếm)', 'Hồ Tây', 'Hồ Ba Bể'], correct: 0, explain: 'Từ đó hồ Tả Vọng đổi tên thành Hồ Gươm hay Hồ Hoàn Kiếm.' },
    ],
  },
  {
    slug: 'cay-tre-tram-dot', emoji: '🎋', title: 'Cây tre trăm đốt',
    cau: [
      'Ngày xưa, có anh nông dân nghèo, khỏe mạnh, hiền lành đi ở cho một lão nhà giàu.',
      'Lão nhà giàu hứa: "Con làm cho ta ba năm, ta sẽ gả con gái cho."',
      'Anh chăm chỉ làm lụng suốt ba năm, mong đến ngày cưới vợ.',
      'Nhưng lão nhà giàu tham lam lại định gả con gái cho một nhà giàu khác.',
      'Lão lừa anh vào rừng tìm cây tre đủ trăm đốt thì mới cho cưới.',
      'Anh tìm mãi trong rừng, chặt bao nhiêu cây cũng không có cây tre nào đủ trăm đốt.',
      'Anh ngồi khóc thì Bụt hiện lên hỏi han và bày cách.',
      'Bụt bảo anh chặt lấy một trăm đốt tre, rồi đọc câu thần chú "Khắc nhập, khắc nhập!"',
      'Anh làm theo, một trăm đốt tre liền dính lại thành cây tre trăm đốt.',
      'Muốn tháo rời để mang về, anh đọc "Khắc xuất, khắc xuất!" thì các đốt tre lại rời ra.',
      'Về đến nơi, thấy lão nhà giàu đang mở tiệc cưới, anh đọc "Khắc nhập" khiến lão dính chặt vào cây tre.',
      'Lão sợ quá phải giữ đúng lời hứa, gả con gái cho anh. Anh đọc "Khắc xuất" thả lão ra.',
    ],
    baiHoc: 'Ở hiền gặp lành, chăm chỉ thật thà sẽ được đền đáp; còn tham lam lừa dối sẽ bị trừng phạt.',
    cauHoi: [
      { q: 'Anh nông dân trong truyện là người như thế nào?', options: ['Nghèo, khoẻ mạnh, hiền lành', 'Giàu có, kiêu ngạo', 'Lười biếng'], correct: 0, explain: 'Anh nông dân nghèo, khoẻ mạnh và hiền lành, đi ở cho lão nhà giàu.' },
      { q: 'Lão nhà giàu hứa gì nếu anh làm cho lão ba năm?', options: ['Gả con gái cho anh', 'Cho một hũ vàng', 'Cho ruộng đất'], correct: 0, explain: 'Lão hứa nếu anh làm ba năm sẽ gả con gái cho anh.' },
      { q: 'Anh nông dân đã làm cho lão nhà giàu mấy năm?', options: ['Ba năm', 'Một năm', 'Mười năm'], correct: 0, explain: 'Anh chăm chỉ làm lụng suốt ba năm để mong cưới vợ.' },
      { q: 'Vì sao lão nhà giàu lừa anh vào rừng?', options: ['Định nuốt lời, gả con cho nhà giàu khác', 'Muốn anh nghỉ ngơi', 'Muốn tặng quà'], correct: 0, explain: 'Lão tham lam định gả con gái cho nhà giàu khác nên tìm cách lừa anh.' },
      { q: 'Lão bắt anh tìm vật gì mới cho cưới?', options: ['Cây tre đủ trăm đốt', 'Cây vàng', 'Con chim quý'], correct: 0, explain: 'Lão lừa anh vào rừng tìm cây tre đủ trăm đốt thì mới cho cưới.' },
      { q: 'Vì sao anh ngồi khóc trong rừng?', options: ['Chặt mãi không có cây tre nào đủ trăm đốt', 'Bị lạc đường', 'Đói bụng'], correct: 0, explain: 'Không có cây tre nào đủ trăm đốt, anh buồn nên ngồi khóc.' },
      { q: 'Ai đã giúp anh nông dân?', options: ['Bụt', 'Nhà vua', 'Rùa vàng'], correct: 0, explain: 'Bụt hiện lên bày cho anh câu thần chú.' },
      { q: 'Câu thần chú để các đốt tre dính lại là gì?', options: ['Khắc nhập, khắc nhập', 'Khắc xuất, khắc xuất', 'Vừng ơi mở ra'], correct: 0, explain: '"Khắc nhập" làm tre dính lại, "khắc xuất" làm tre rời ra.' },
      { q: 'Câu thần chú nào làm các đốt tre rời ra?', options: ['Khắc xuất, khắc xuất', 'Khắc nhập, khắc nhập', 'Úm ba la'], correct: 0, explain: '"Khắc xuất" làm các đốt tre rời ra để anh mang về.' },
      { q: 'Cuối truyện, lão nhà giàu phải làm gì?', options: ['Giữ lời hứa, gả con gái cho anh', 'Đuổi anh đi', 'Chạy trốn'], correct: 0, explain: 'Bị dính vào cây tre, lão sợ quá phải giữ lời, gả con gái cho anh.' },
    ],
  },
  {
    slug: 'su-tich-qua-dua-hau', emoji: '🍉', title: 'Sự tích quả dưa hấu',
    cau: [
      'Ngày xưa, vua Hùng có một người con nuôi tài giỏi tên là Mai An Tiêm.',
      'An Tiêm thường nói của cải làm ra là nhờ đôi bàn tay của mình.',
      'Vua nghe vậy cho là kiêu ngạo, liền đày cả gia đình An Tiêm ra một hòn đảo hoang.',
      'Trên đảo chẳng có gì, nhưng An Tiêm không hề nản chí.',
      'Một hôm, chàng thấy đàn chim ăn một loại hạt rồi nhả xuống, liền nhặt về gieo trồng.',
      'Ít lâu sau, những hạt ấy mọc thành cây, ra những quả to, vỏ xanh, ruột đỏ, ăn rất ngọt và mát.',
      'An Tiêm gọi đó là quả dưa hấu.',
      'Chàng khắc tên mình lên vỏ dưa rồi thả xuống biển cho trôi đi khắp nơi.',
      'Nhờ vậy, thuyền buôn tìm đến đảo đổi lấy dưa, gia đình chàng ngày càng khấm khá.',
      'Vua Hùng biết chuyện, hiểu ra tài năng và ý chí của An Tiêm, bèn cho đón cả nhà về.',
      'Từ đó, giống dưa hấu được trồng khắp nơi trên đất nước ta.',
    ],
    baiHoc: 'Có ý chí, cần cù và tự lực thì dù trong hoàn cảnh khó khăn nhất cũng làm nên thành quả.',
    cauHoi: [
      { q: 'Mai An Tiêm là gì của vua Hùng?', options: ['Con nuôi', 'Đại tướng', 'Người hầu'], correct: 0, explain: 'An Tiêm là người con nuôi tài giỏi của vua Hùng.' },
      { q: 'An Tiêm nói của cải làm ra là nhờ điều gì?', options: ['Đôi bàn tay của mình', 'Ơn vua ban', 'Của trời cho'], correct: 0, explain: 'An Tiêm thường nói của cải làm ra là nhờ đôi bàn tay của chính mình.' },
      { q: 'Vì sao vua Hùng đày An Tiêm ra đảo hoang?', options: ['Cho rằng chàng kiêu ngạo', 'Vì chàng lười biếng', 'Vì chàng trộm cắp'], correct: 0, explain: 'Vua nghe câu nói ấy, cho là kiêu ngạo nên đày cả gia đình chàng ra đảo.' },
      { q: 'Trên đảo hoang, thái độ của An Tiêm ra sao?', options: ['Không hề nản chí', 'Khóc lóc suốt ngày', 'Bỏ cuộc'], correct: 0, explain: 'Đảo chẳng có gì nhưng An Tiêm không hề nản chí.' },
      { q: 'An Tiêm có được hạt dưa từ đâu?', options: ['Hạt do đàn chim ăn rồi nhả xuống', 'Mua ở chợ', 'Vua ban tặng'], correct: 0, explain: 'Chàng thấy đàn chim ăn hạt rồi nhả xuống, liền nhặt về gieo trồng.' },
      { q: 'Mai An Tiêm trồng được quả gì trên đảo?', options: ['Dưa hấu', 'Dưa lê', 'Bí đỏ'], correct: 0, explain: 'Chàng gieo hạt chim nhả và trồng được quả dưa hấu.' },
      { q: 'Quả dưa hấu có đặc điểm gì?', options: ['Vỏ xanh, ruột đỏ, ngọt mát', 'Vỏ vàng, ruột trắng', 'Vỏ đỏ, ruột xanh'], correct: 0, explain: 'Quả to, vỏ xanh, ruột đỏ, ăn rất ngọt và mát.' },
      { q: 'An Tiêm làm gì để mọi người biết đến quả dưa?', options: ['Khắc tên lên vỏ dưa thả trôi biển', 'Đem bán ở chợ', 'Tặng nhà vua'], correct: 0, explain: 'Chàng khắc tên rồi thả dưa xuống biển cho trôi đi khắp nơi.' },
      { q: 'Nhờ đâu gia đình An Tiêm ngày càng khấm khá?', options: ['Thuyền buôn tìm đến đổi lấy dưa', 'Nhặt được vàng', 'Vua cấp lương'], correct: 0, explain: 'Thuyền buôn tìm đến đảo đổi lấy dưa, gia đình chàng ngày càng khấm khá.' },
      { q: 'Cuối truyện, vua Hùng làm gì?', options: ['Hiểu ra và đón cả nhà An Tiêm về', 'Đày thêm lần nữa', 'Quên An Tiêm'], correct: 0, explain: 'Vua hiểu ra tài năng và ý chí của An Tiêm, bèn cho đón cả nhà về.' },
    ],
  },
  {
    slug: 'cay-khe', emoji: '🐦', title: 'Cây khế (Ăn khế trả vàng)',
    cau: [
      'Ngày xưa có hai anh em, cha mẹ mất sớm để lại một ít ruộng vườn.',
      'Người anh tham lam chiếm hết gia tài, chỉ chia cho em một cây khế và một túp lều nhỏ.',
      'Người em hiền lành, ngày ngày chăm sóc cây khế, cây ra quả trĩu cành.',
      'Một hôm, có con chim lạ bay đến ăn khế.',
      'Người em than: "Chim ơi, cây khế là tất cả của nhà tôi!"',
      'Chim liền nói: "Ăn một quả, trả cục vàng, may túi ba gang, mang đi mà đựng."',
      'Người em may một chiếc túi ba gang. Chim chở anh ra đảo có rất nhiều vàng bạc.',
      'Anh chỉ lấy vừa đủ túi ba gang rồi trở về, từ đó sống sung túc.',
      'Người anh tham lam nghe chuyện, đòi đổi hết gia tài lấy cây khế.',
      'Khi chim đến, người anh may một chiếc túi thật to, tới mười hai gang.',
      'Ra đảo, anh ta tham lam nhét vàng đầy túi, còn giắt khắp người.',
      'Túi quá nặng, chim đuối sức, người anh tham lam rơi xuống biển.',
    ],
    baiHoc: 'Hiền lành, biết đủ thì được hưởng phúc; tham lam quá độ sẽ chuốc lấy tai họa.',
    cauHoi: [
      { q: 'Sau khi cha mẹ mất, người anh chia cho em những gì?', options: ['Một cây khế và túp lều nhỏ', 'Một nửa gia tài', 'Một con trâu'], correct: 0, explain: 'Người anh tham lam chiếm hết, chỉ chia cho em cây khế và túp lều nhỏ.' },
      { q: 'Người em trong truyện là người thế nào?', options: ['Hiền lành, chăm chỉ', 'Tham lam', 'Lười biếng'], correct: 0, explain: 'Người em hiền lành, ngày ngày chăm sóc cây khế.' },
      { q: 'Con vật nào bay đến ăn khế?', options: ['Một con chim lạ', 'Con sóc', 'Con dơi'], correct: 0, explain: 'Một hôm có con chim lạ bay đến ăn khế của người em.' },
      { q: 'Con chim hứa trả gì khi ăn khế?', options: ['Cục vàng', 'Hạt ngọc', 'Quả táo'], correct: 0, explain: 'Chim nói "Ăn một quả, trả cục vàng, may túi ba gang".' },
      { q: 'Chim dặn người em may chiếc túi mấy gang?', options: ['Ba gang', 'Sáu gang', 'Một gang'], correct: 0, explain: 'Chim dặn "may túi ba gang, mang đi mà đựng".' },
      { q: 'Chim chở người em đến đâu?', options: ['Ra đảo có nhiều vàng bạc', 'Về kinh thành', 'Lên núi'], correct: 0, explain: 'Chim chở người em ra một hòn đảo có rất nhiều vàng bạc.' },
      { q: 'Người em lấy bao nhiêu vàng?', options: ['Chỉ vừa đủ túi ba gang', 'Lấy thật nhiều', 'Không lấy gì'], correct: 0, explain: 'Người em chỉ lấy vừa đủ túi ba gang rồi trở về, sống sung túc.' },
      { q: 'Người anh tham lam đã may chiếc túi mấy gang?', options: ['Mười hai gang', 'Ba gang', 'Năm gang'], correct: 0, explain: 'Người anh tham lam may một chiếc túi thật to, tới mười hai gang.' },
      { q: 'Vì sao người anh tham lam gặp nạn?', options: ['Lấy quá nhiều vàng, túi quá nặng', 'Đi lạc đường', 'Chim bỏ rơi'], correct: 0, explain: 'Anh ta tham lam nhét vàng quá nặng nên rơi xuống biển.' },
      { q: 'Bài học của truyện Cây khế là gì?', options: ['Hiền lành biết đủ được phúc, tham lam gặp hoạ', 'Phải giàu mới sướng', 'Đừng trồng khế'], correct: 0, explain: 'Hiền lành, biết đủ thì hưởng phúc; tham lam quá độ sẽ chuốc tai hoạ.' },
    ],
  },
  {
    slug: 'tam-cam', emoji: '👗', title: 'Tấm Cám',
    cau: [
      'Ngày xưa có cô Tấm mồ côi, ở với dì ghẻ và em cùng cha khác mẹ tên Cám. Tấm chăm chỉ, hiền lành, còn Cám thì lười biếng.',
      'Một hôm dì sai hai chị em ra đồng bắt tép, hứa thưởng yếm đỏ. Tấm bắt đầy giỏ, còn Cám mải chơi nên lừa trút hết tép của Tấm.',
      'Tấm ngồi khóc. Bụt hiện lên, bảo trong giỏ vẫn còn một con cá bống, đem về nuôi ở giếng.',
      'Mẹ con Cám lén bắt cá bống ăn thịt. Tấm khóc, Bụt bảo tìm xương cá bỏ vào bốn chiếc lọ chôn dưới chân giường.',
      'Nhà vua mở hội. Dì ghẻ trộn thóc lẫn gạo, bắt Tấm nhặt xong mới cho đi. Bụt gọi đàn chim sẻ xuống nhặt giúp.',
      'Tấm đào bốn chiếc lọ lên, được bộ quần áo đẹp cùng đôi hài xinh. Trên đường đi hội, Tấm đánh rơi một chiếc hài xuống nước.',
      'Voi của vua nhặt được chiếc hài. Vua truyền ai ướm vừa sẽ làm hoàng hậu. Chỉ Tấm đi vừa, nên nàng được đón vào cung.',
      'Mẹ con Cám ghen ghét, tìm cách hại Tấm. Nhưng Tấm nhiều lần hoá thân: thành chim vàng anh, cây xoan đào, khung cửi, rồi thành một quả thị thơm.',
      'Một bà lão bán nước đem quả thị về nhà. Hằng ngày, Tấm bước ra từ quả thị giúp bà dọn dẹp, nấu nướng.',
      'Vua đi ngang, ghé hàng nước, nhận ra Tấm nhờ miếng trầu têm cánh phượng quen thuộc, liền đón nàng về cung. Mẹ con Cám xấu hổ bỏ đi.',
    ],
    baiHoc: 'Ở hiền gặp lành, người gian ác rồi sẽ chịu quả báo.',
    cauHoi: [
      { q: 'Tấm sống cùng những ai?', options: ['Dì ghẻ và em Cám', 'Ông bà', 'Một mình'], correct: 0, explain: 'Tấm mồ côi, ở với dì ghẻ và em cùng cha khác mẹ tên Cám.' },
      { q: 'Dì sai hai chị em ra đồng bắt gì, hứa thưởng yếm đỏ?', options: ['Bắt tép', 'Hái hoa', 'Nhổ cỏ'], correct: 0, explain: 'Dì sai bắt tép, hứa thưởng yếm đỏ cho ai bắt được nhiều.' },
      { q: 'Cám đã làm gì với giỏ tép của Tấm?', options: ['Lừa trút hết tép của Tấm', 'Giúp Tấm bắt', 'Cho Tấm thêm'], correct: 0, explain: 'Cám mải chơi rồi lừa trút hết tép trong giỏ của Tấm.' },
      { q: 'Ai hiện lên giúp Tấm mỗi khi cô khóc?', options: ['Bụt', 'Tiên cá', 'Thần đèn'], correct: 0, explain: 'Bụt luôn hiện lên an ủi và giúp đỡ Tấm.' },
      { q: 'Bụt bảo Tấm đem con gì về nuôi ở giếng?', options: ['Cá bống', 'Con rùa', 'Con cua'], correct: 0, explain: 'Bụt bảo trong giỏ còn con cá bống, đem về nuôi ở giếng.' },
      { q: 'Khi vua mở hội, dì bắt Tấm làm gì mới cho đi?', options: ['Nhặt thóc lẫn gạo cho xong', 'Nấu cơm', 'Gánh nước'], correct: 0, explain: 'Dì trộn thóc lẫn gạo, bắt Tấm nhặt xong mới cho đi hội.' },
      { q: 'Ai đã giúp Tấm nhặt thóc?', options: ['Đàn chim sẻ', 'Đàn kiến', 'Đàn gà'], correct: 0, explain: 'Bụt gọi đàn chim sẻ xuống nhặt thóc giúp Tấm.' },
      { q: 'Tấm đánh rơi vật gì trên đường đi hội?', options: ['Một chiếc hài', 'Chiếc khăn', 'Cái nón'], correct: 0, explain: 'Trên đường đi hội, Tấm đánh rơi một chiếc hài xuống nước.' },
      { q: 'Trước khi thành quả thị, Tấm từng hoá thân thành gì?', options: ['Chim vàng anh', 'Con cá', 'Bông hoa sen'], correct: 0, explain: 'Tấm hoá thân thành chim vàng anh, cây xoan đào, khung cửi rồi quả thị.' },
      { q: 'Nhờ vật gì vua nhận ra Tấm ở hàng nước?', options: ['Miếng trầu têm cánh phượng', 'Chiếc nón', 'Cây đàn'], correct: 0, explain: 'Vua nhận ra Tấm nhờ miếng trầu têm cánh phượng khéo léo quen thuộc.' },
    ],
  },
  {
    slug: 'thach-sanh', emoji: '🪕', title: 'Thạch Sanh',
    cau: [
      'Thạch Sanh mồ côi, sống nghèo dưới gốc đa, ngày ngày lên rừng đốn củi. Chàng khoẻ mạnh, thật thà và tốt bụng.',
      'Lý Thông bán rượu thấy Thạch Sanh khoẻ mạnh, liền giả vờ kết nghĩa anh em để lợi dụng chàng.',
      'Vùng ấy có con chằn tinh hung dữ, mỗi năm bắt dân nộp một mạng người. Đến lượt mình, Lý Thông lừa Thạch Sanh đi nộp thay.',
      'Thạch Sanh dũng cảm chém chết chằn tinh. Lý Thông cướp công, đem đầu chằn tinh dâng vua để lĩnh thưởng.',
      'Công chúa bị một con đại bàng khổng lồ quắp đi. Thạch Sanh bắn trúng đại bàng rồi lần theo vết máu tìm ra hang.',
      'Thạch Sanh xuống hang cứu được công chúa. Nhưng Lý Thông lại cướp công và lấp cửa hang hòng hại chàng.',
      'Ở dưới hang, Thạch Sanh cứu con vua Thuỷ Tề và được tặng một cây đàn thần.',
      'Bị vu oan bỏ vào ngục, Thạch Sanh ngồi gảy đàn. Tiếng đàn giãi bày nỗi oan, công chúa nghe thấy liền khỏi bệnh và nói ra sự thật.',
      'Nỗi oan được sáng tỏ, Lý Thông bị trừng phạt. Thạch Sanh được vua gả công chúa cho.',
      'Quân mười tám nước kéo sang gây sự. Thạch Sanh đem niêu cơm thần ra đãi, ăn hết lại đầy khiến họ khâm phục mà rút quân.',
    ],
    baiHoc: 'Thật thà, dũng cảm sẽ được đền đáp; gian dối, tham lam sẽ bị trừng trị.',
    cauHoi: [
      { q: 'Thạch Sanh mồ côi sống ở đâu và làm nghề gì?', options: ['Dưới gốc đa, ngày ngày đốn củi', 'Trong cung vua', 'Ngoài biển đánh cá'], correct: 0, explain: 'Thạch Sanh nghèo, sống dưới gốc đa, ngày ngày lên rừng đốn củi.' },
      { q: 'Lý Thông giả vờ làm gì với Thạch Sanh?', options: ['Kết nghĩa anh em để lợi dụng', 'Nhận làm cha', 'Tặng nhà cửa'], correct: 0, explain: 'Lý Thông giả vờ kết nghĩa anh em để lợi dụng sức khoẻ của chàng.' },
      { q: 'Con quái vật hung dữ bắt dân nộp mạng mỗi năm là gì?', options: ['Chằn tinh', 'Đại bàng', 'Cá kình'], correct: 0, explain: 'Chằn tinh hung dữ, mỗi năm bắt dân nộp một mạng người.' },
      { q: 'Lý Thông đã lừa Thạch Sanh đi làm gì?', options: ['Đi nộp mạng thay hắn', 'Đi buôn', 'Đi học'], correct: 0, explain: 'Đến lượt mình phải nộp mạng, Lý Thông lừa Thạch Sanh đi thay.' },
      { q: 'Ai cướp công giết chằn tinh của Thạch Sanh?', options: ['Lý Thông', 'Nhà vua', 'Công chúa'], correct: 0, explain: 'Lý Thông cướp công, đem đầu chằn tinh dâng vua để lĩnh thưởng.' },
      { q: 'Công chúa bị con vật nào quắp đi?', options: ['Đại bàng khổng lồ', 'Chằn tinh', 'Rồng'], correct: 0, explain: 'Một con đại bàng khổng lồ quắp công chúa bay đi.' },
      { q: 'Thạch Sanh được tặng vật gì khi ở dưới hang?', options: ['Cây đàn thần', 'Thanh gươm', 'Áo giáp'], correct: 0, explain: 'Chàng cứu con vua Thuỷ Tề và được tặng cây đàn thần.' },
      { q: 'Nhờ đâu công chúa khỏi bệnh và nói ra sự thật?', options: ['Nghe tiếng đàn thần của Thạch Sanh', 'Uống thuốc', 'Được vua khuyên'], correct: 0, explain: 'Tiếng đàn giãi bày nỗi oan, công chúa nghe thấy liền khỏi bệnh câm.' },
      { q: 'Niêu cơm thần của Thạch Sanh có gì kỳ lạ?', options: ['Ăn hết lại đầy', 'Biết hát', 'Bay được'], correct: 0, explain: 'Niêu cơm ăn hết lại đầy, đãi cả quân mười tám nước không vơi.' },
      { q: 'Thạch Sanh dùng gì khiến quân mười tám nước khâm phục mà rút lui?', options: ['Niêu cơm thần ăn mãi không hết', 'Gươm báu', 'Voi chiến'], correct: 0, explain: 'Chàng đem niêu cơm thần ra đãi, ăn hết lại đầy, khiến họ khâm phục rút quân.' },
    ],
  },
  {
    slug: 'so-dua', emoji: '🥥', title: 'Sọ Dừa',
    cau: [
      'Hai vợ chồng nghèo hiếm muộn. Một hôm bà uống nước mưa trong chiếc sọ dừa rồi mang thai, sinh ra một đứa bé tròn như quả dừa, đặt tên là Sọ Dừa.',
      'Sọ Dừa lớn lên xin đi chăn bò cho nhà phú ông. Cậu chăn bò rất giỏi, con nào cũng béo tốt.',
      'Ba cô con gái phú ông thay nhau đưa cơm cho Sọ Dừa. Chỉ có cô út hiền lành, đối xử tử tế với cậu.',
      'Một lần, cô út bắt gặp Sọ Dừa hoá thành chàng trai khôi ngô ngồi thổi sáo trên đồi. Cô đem lòng yêu mến.',
      'Sọ Dừa nhờ mẹ đến hỏi cưới cô út. Phú ông thách nhiều lễ vật, Sọ Dừa lo đủ cả nên cưới được cô.',
      'Ngày cưới, Sọ Dừa hiện nguyên hình một chàng trai tuấn tú, khiến hai cô chị vừa tiếc vừa ghen tị.',
      'Sọ Dừa chăm học, thi đỗ trạng nguyên rồi được vua cử đi sứ. Trước khi đi, chàng dặn vợ luôn mang theo một con dao, hòn đá lửa và hai quả trứng gà.',
      'Hai cô chị lừa cô út ra biển rồi đẩy xuống nước hòng cướp chồng em. Cô út bị một con cá lớn nuốt vào bụng.',
      'Nhờ con dao, cô rạch bụng cá thoát ra một hòn đảo, dùng đá lửa nướng cá ăn, hai quả trứng nở thành đôi gà làm bạn.',
      'Thuyền quan trạng đi ngang, con gà cất tiếng gáy gọi. Vợ chồng gặp lại nhau mừng mừng tủi tủi. Hai cô chị xấu hổ bỏ đi biệt xứ.',
    ],
    baiHoc: 'Đừng đánh giá con người qua vẻ bề ngoài; hiền lành, tốt bụng sẽ gặp điều may.',
    cauHoi: [
      { q: 'Khi mới sinh ra, Sọ Dừa có hình dạng thế nào?', options: ['Tròn như quả dừa, không tay chân', 'Cao lớn khoẻ mạnh', 'Bé xíu như ngón tay'], correct: 0, explain: 'Cậu bé sinh ra tròn như quả dừa, không tay chân, nên gọi là Sọ Dừa.' },
      { q: 'Sọ Dừa xin đi làm việc gì cho nhà phú ông?', options: ['Chăn bò', 'Cày ruộng', 'Gánh nước'], correct: 0, explain: 'Sọ Dừa xin đi chăn bò và chăn rất giỏi, con nào cũng béo tốt.' },
      { q: 'Ai đối xử tử tế với Sọ Dừa?', options: ['Cô út', 'Cô cả', 'Phú ông'], correct: 0, explain: 'Chỉ cô út hiền lành, tử tế với Sọ Dừa nên được hưởng hạnh phúc.' },
      { q: 'Cô út bắt gặp Sọ Dừa hoá thành ai trên đồi?', options: ['Một chàng trai khôi ngô thổi sáo', 'Một ông lão', 'Một con chim'], correct: 0, explain: 'Cô út thấy Sọ Dừa hoá thành chàng trai khôi ngô ngồi thổi sáo.' },
      { q: 'Ngày cưới, Sọ Dừa hiện nguyên hình thế nào?', options: ['Một chàng trai tuấn tú', 'Vẫn tròn như dừa', 'Một ông lão'], correct: 0, explain: 'Ngày cưới, Sọ Dừa hiện nguyên hình một chàng trai tuấn tú.' },
      { q: 'Sọ Dừa chăm học và thi đỗ danh hiệu gì?', options: ['Trạng nguyên', 'Tú tài', 'Cử nhân'], correct: 0, explain: 'Sọ Dừa chăm học, thi đỗ trạng nguyên rồi được vua cử đi sứ.' },
      { q: 'Trước khi đi sứ, chàng dặn vợ mang theo những gì?', options: ['Dao, đá lửa và hai quả trứng gà', 'Vàng bạc', 'Chỉ mang quần áo'], correct: 0, explain: 'Chàng dặn vợ luôn mang theo con dao, hòn đá lửa và hai quả trứng gà.' },
      { q: 'Hai cô chị đã làm gì để cướp chồng của em?', options: ['Đẩy cô út xuống biển', 'Đốt nhà', 'Bỏ thuốc'], correct: 0, explain: 'Hai cô chị lừa cô út ra biển rồi đẩy xuống nước.' },
      { q: 'Vật gì giúp cô út thoát khỏi bụng cá?', options: ['Con dao', 'Cây gậy', 'Chiếc nón'], correct: 0, explain: 'Nhờ con dao chồng dặn mang theo, cô rạch bụng cá thoát ra.' },
      { q: 'Nhờ đâu vợ chồng gặp lại được nhau?', options: ['Con gà cất tiếng gáy khi thuyền quan trạng đi qua', 'Cô út bơi về', 'Người dân báo tin'], correct: 0, explain: 'Thuyền quan trạng đi ngang, con gà nở từ trứng cất tiếng gáy gọi.' },
    ],
  },
  {
    slug: 'su-tich-trau-cau', emoji: '🌿', title: 'Sự tích trầu cau',
    cau: [
      'Ngày xưa có hai anh em nhà họ Cao tên Tân và Lang, giống nhau như đúc và rất thương yêu nhau.',
      'Người anh là Tân lấy vợ. Vì hai anh em quá giống nhau, có lần người vợ nhận nhầm em là chồng.',
      'Từ đó người anh đối xử với em có phần lạnh nhạt. Người em buồn tủi, lặng lẽ bỏ nhà ra đi.',
      'Đi mãi tới bờ suối, người em kiệt sức, ngồi khóc rồi hoá thành một tảng đá vôi.',
      'Người anh ân hận đi tìm em. Đến bên tảng đá, anh gục xuống và hoá thành một cây cau mọc thẳng.',
      'Người vợ đi tìm chồng, đến nơi cũng ôm cây cau mà chết, hoá thành dây trầu quấn quanh thân cau.',
      'Vua Hùng đi ngang, nghe kể chuyện, bèn lấy lá trầu, quả cau và chút vôi từ đá ăn thử.',
      'Ba thứ hoà lại có màu đỏ thắm, vị cay nồng ấm áp. Từ đó dân ta có tục ăn trầu trong cưới hỏi, lễ Tết.',
    ],
    baiHoc: 'Tình anh em, vợ chồng thắm thiết, thuỷ chung. Miếng trầu là đầu câu chuyện của người Việt.',
    cauHoi: [
      { q: 'Hai anh em nhà họ Cao có tên là gì?', options: ['Tân và Lang', 'Sơn và Thuỷ', 'An và Bình'], correct: 0, explain: 'Hai anh em nhà họ Cao tên là Tân và Lang.' },
      { q: 'Hai anh em có đặc điểm gì nổi bật?', options: ['Giống nhau như đúc, rất thương nhau', 'Ghét nhau', 'Khác nhau hoàn toàn'], correct: 0, explain: 'Hai anh em giống nhau như đúc và rất thương yêu nhau.' },
      { q: 'Vì sao anh Tân dần lạnh nhạt với em?', options: ['Vì vợ có lần nhận nhầm em là chồng', 'Vì em lười', 'Vì tranh nhau của cải'], correct: 0, explain: 'Do hai anh em quá giống nhau, người vợ nhận nhầm em là chồng.' },
      { q: 'Người em đã làm gì khi buồn tủi?', options: ['Lặng lẽ bỏ nhà ra đi', 'Cãi nhau với anh', 'Ở lì trong nhà'], correct: 0, explain: 'Người em buồn tủi, lặng lẽ bỏ nhà ra đi.' },
      { q: 'Người em trong truyện hoá thành gì?', options: ['Tảng đá vôi', 'Cây cau', 'Dây trầu'], correct: 0, explain: 'Người em hoá thành tảng đá vôi; anh hoá cây cau; vợ hoá dây trầu.' },
      { q: 'Người anh (Tân) đi tìm em rồi hoá thành gì?', options: ['Cây cau mọc thẳng', 'Tảng đá', 'Dòng suối'], correct: 0, explain: 'Người anh gục chết bên tảng đá và hoá thành cây cau mọc thẳng.' },
      { q: 'Người vợ đi tìm chồng rồi hoá thành gì?', options: ['Dây trầu quấn quanh cây cau', 'Bông hoa', 'Con chim'], correct: 0, explain: 'Người vợ hoá thành dây trầu quấn quanh thân cau.' },
      { q: 'Ai đã cho lấy trầu, cau, vôi ăn thử?', options: ['Vua Hùng', 'Ông Bụt', 'Người dân chài'], correct: 0, explain: 'Vua Hùng đi ngang nghe chuyện, cho lấy trầu, cau và vôi ăn thử.' },
      { q: 'Ba thứ trầu, cau, vôi hoà lại có màu gì?', options: ['Đỏ thắm', 'Xanh lá', 'Vàng tươi'], correct: 0, explain: 'Trầu, cau và vôi hoà lại cho màu đỏ thắm, vị cay nồng.' },
      { q: 'Từ câu chuyện này, dân ta có tục lệ gì?', options: ['Tục ăn trầu trong cưới hỏi, lễ Tết', 'Tục thả đèn', 'Tục đua thuyền'], correct: 0, explain: 'Từ đó dân ta có tục ăn trầu trong cưới hỏi, lễ Tết.' },
    ],
  },
  {
    slug: 'ba-co-gai', emoji: '🐿️', title: 'Ba cô gái',
    cau: [
      'Một bà mẹ nghèo sinh được ba cô con gái. Bà hết lòng yêu thương, nuôi các con khôn lớn rồi gả đi xa.',
      'Một hôm bà ốm nặng, nhớ con, liền nhờ Sóc con mang thư đi gọi các con về thăm.',
      'Sóc đến nhà cô cả. Cô đang cọ chậu, viện cớ bận chưa về ngay. Sóc bảo cô sẽ hoá thành rùa — quả nhiên cô biến thành con rùa bò quanh chậu.',
      'Sóc đến nhà cô hai. Cô đang xe chỉ, cũng nói bận. Sóc bảo cô hoá thành nhện — cô liền thành con nhện suốt đời giăng tơ.',
      'Sóc đến nhà cô út. Vừa nghe tin mẹ ốm, cô út tất tả về ngay, không chút chần chừ.',
      'Cô út chăm sóc mẹ tận tình, mẹ dần khỏi bệnh. Cô sống hạnh phúc và được mọi người yêu quý.',
    ],
    baiHoc: 'Hãy hiếu thảo, yêu thương cha mẹ. Con cái hiếu thảo sẽ được yêu quý và gặp phúc.',
    cauHoi: [
      { q: 'Bà mẹ trong truyện có mấy cô con gái?', options: ['Ba cô', 'Hai cô', 'Bốn cô'], correct: 0, explain: 'Bà mẹ nghèo sinh được ba cô con gái.' },
      { q: 'Bà mẹ ốm đã nhờ con vật nào mang thư gọi các con?', options: ['Sóc con', 'Chim sẻ', 'Mèo con'], correct: 0, explain: 'Bà nhờ Sóc con mang thư đi gọi các con về thăm.' },
      { q: 'Cô cả đang làm gì khi Sóc đến báo tin?', options: ['Cọ chậu', 'Nấu cơm', 'Ngủ'], correct: 0, explain: 'Cô cả đang cọ chậu, viện cớ bận nên chưa về ngay.' },
      { q: 'Cô cả mải cọ chậu, không về nên hoá thành con gì?', options: ['Con rùa', 'Con nhện', 'Con chim'], correct: 0, explain: 'Cô cả hoá thành con rùa bò quanh chậu.' },
      { q: 'Cô hai đang làm gì khi Sóc đến?', options: ['Xe chỉ', 'Giặt đồ', 'Đi chợ'], correct: 0, explain: 'Cô hai đang xe chỉ, cũng viện cớ bận.' },
      { q: 'Cô hai không về nên hoá thành con gì?', options: ['Con nhện', 'Con rùa', 'Con bướm'], correct: 0, explain: 'Cô hai hoá thành con nhện, suốt đời giăng tơ.' },
      { q: 'Ai về thăm mẹ ngay khi nghe tin mẹ ốm?', options: ['Cô út', 'Cô cả', 'Cô hai'], correct: 0, explain: 'Chỉ cô út về ngay, nên được yêu quý và hạnh phúc.' },
      { q: 'Bài học của truyện Ba cô gái là gì?', options: ['Hãy hiếu thảo, yêu thương cha mẹ', 'Phải làm việc nhanh', 'Đừng nuôi thú'], correct: 0, explain: 'Con cái hiếu thảo với cha mẹ sẽ được yêu quý và gặp phúc.' },
    ],
  },
  {
    slug: 'rua-va-tho', emoji: '🐢', title: 'Rùa và Thỏ',
    cau: [
      'Thỏ chạy rất nhanh nên hay chê Rùa chậm chạp. Bực mình, Rùa thách Thỏ chạy thi.',
      'Thỏ cười lớn, nhận lời ngay vì tin chắc mình sẽ thắng dễ dàng.',
      'Cuộc thi bắt đầu. Thỏ vọt lên trước, chẳng mấy chốc đã bỏ Rùa lại thật xa.',
      'Thấy Rùa còn ở tít phía sau, Thỏ chủ quan nằm nghỉ dưới gốc cây rồi ngủ quên lúc nào không hay.',
      'Rùa vẫn chậm rãi, kiên trì bò từng bước một, không hề nghỉ ngơi.',
      'Rùa lặng lẽ vượt qua chỗ Thỏ đang ngủ và tiến dần đến đích.',
      'Thỏ giật mình tỉnh dậy, ba chân bốn cẳng chạy tới nhưng đã muộn — Rùa đã về đích trước rồi.',
    ],
    baiHoc: 'Kiên trì, bền bỉ sẽ đi tới đích; chủ quan, kiêu ngạo dễ chuốc thất bại.',
    cauHoi: [
      { q: 'Lúc đầu, Thỏ có thái độ thế nào với Rùa?', options: ['Chê Rùa chậm chạp', 'Khen Rùa giỏi', 'Sợ Rùa'], correct: 0, explain: 'Thỏ chạy nhanh nên hay chê Rùa chậm chạp.' },
      { q: 'Ai là người thách chạy thi?', options: ['Rùa', 'Thỏ', 'Bác Gấu'], correct: 0, explain: 'Bực mình vì bị chê, Rùa thách Thỏ chạy thi.' },
      { q: 'Vào cuộc thi, ai chạy lên trước?', options: ['Thỏ', 'Rùa', 'Cả hai cùng lúc'], correct: 0, explain: 'Thỏ vọt lên trước, chẳng mấy chốc đã bỏ Rùa lại xa.' },
      { q: 'Thấy Rùa còn ở xa, Thỏ đã làm gì?', options: ['Nằm nghỉ dưới gốc cây rồi ngủ quên', 'Chạy tiếp thật nhanh', 'Quay lại chờ Rùa'], correct: 0, explain: 'Thỏ chủ quan nằm nghỉ dưới gốc cây rồi ngủ quên.' },
      { q: 'Rùa đã đi như thế nào trong cuộc thi?', options: ['Chậm rãi, kiên trì, không nghỉ', 'Chạy thật nhanh', 'Vừa đi vừa chơi'], correct: 0, explain: 'Rùa chậm rãi, kiên trì bò từng bước, không hề nghỉ ngơi.' },
      { q: 'Ai đã về đích trước?', options: ['Rùa', 'Thỏ', 'Không ai về đích'], correct: 0, explain: 'Rùa lặng lẽ vượt qua chỗ Thỏ ngủ và về đích trước.' },
      { q: 'Vì sao Thỏ thua cuộc?', options: ['Chủ quan, ngủ quên', 'Bị lạc đường', 'Chạy chậm'], correct: 0, explain: 'Thỏ chủ quan nằm ngủ quên nên bị Rùa vượt qua.' },
      { q: 'Rùa thắng cuộc nhờ điều gì?', options: ['Kiên trì, bền bỉ', 'Chạy nhanh', 'Nhờ Thỏ nhường'], correct: 0, explain: 'Rùa chậm mà kiên trì, không nghỉ nên về đích trước.' },
    ],
  },
  {
    slug: 'co-be-quang-khan-do', emoji: '🧣', title: 'Cô bé quàng khăn đỏ',
    cau: [
      'Có một cô bé lúc nào cũng quàng chiếc khăn màu đỏ, nên mọi người gọi là Cô bé quàng khăn đỏ.',
      'Một hôm, mẹ nhờ cô mang bánh sang biếu bà ngoại đang ốm, dặn đi thẳng đường, đừng la cà.',
      'Đi qua khu rừng, cô gặp một con Sói. Sói hỏi cô đi đâu, cô bé thật thà kể hết mọi chuyện.',
      'Sói chạy tắt đến nhà bà trước, nuốt chửng bà rồi trùm khăn giả làm bà nằm trên giường.',
      'Cô bé đến nơi, thấy "bà" tai to, mắt to, miệng to thì lấy làm lạ. Sói liền chồm dậy nuốt luôn cô bé.',
      'May thay, một bác thợ săn đi ngang, nghe tiếng ngáy khác lạ nên ghé vào và phát hiện con Sói.',
      'Bác rạch bụng Sói, cứu được cả bà và cô bé vẫn bình an vô sự.',
      'Từ đó, cô bé luôn nhớ lời mẹ dặn, không còn la cà hay tin lời người lạ nữa.',
    ],
    baiHoc: 'Phải nghe lời cha mẹ, cảnh giác với người lạ và không kể chuyện riêng cho người lạ.',
    cauHoi: [
      { q: 'Vì sao cô bé được gọi là Cô bé quàng khăn đỏ?', options: ['Vì luôn quàng chiếc khăn màu đỏ', 'Vì thích màu đỏ', 'Vì hay đỏ mặt'], correct: 0, explain: 'Cô bé lúc nào cũng quàng chiếc khăn màu đỏ nên có tên như vậy.' },
      { q: 'Mẹ nhờ cô bé mang gì sang biếu bà ngoại?', options: ['Bánh', 'Hoa', 'Tiền'], correct: 0, explain: 'Mẹ nhờ cô mang bánh sang biếu bà ngoại đang ốm.' },
      { q: 'Mẹ đã dặn cô bé điều gì?', options: ['Đi thẳng đường, đừng la cà', 'Chạy thật nhanh', 'Hái hoa dọc đường'], correct: 0, explain: 'Mẹ dặn cô đi thẳng đường, đừng la cà.' },
      { q: 'Cô bé gặp con vật nào trong rừng?', options: ['Con Sói', 'Con Gấu', 'Con Cáo'], correct: 0, explain: 'Đi qua khu rừng, cô gặp một con Sói.' },
      { q: 'Khi Sói hỏi, cô bé đã làm gì?', options: ['Thật thà kể hết mọi chuyện', 'Bỏ chạy', 'Im lặng'], correct: 0, explain: 'Cô bé thật thà kể hết cho Sói nghe, nên Sói biết đường đến nhà bà.' },
      { q: 'Sói đã làm gì với bà ngoại?', options: ['Nuốt chửng bà', 'Trò chuyện với bà', 'Tặng quà cho bà'], correct: 0, explain: 'Sói chạy tắt đến nhà bà trước và nuốt chửng bà.' },
      { q: 'Sói đã làm gì để lừa cô bé?', options: ['Giả làm bà ngoại', 'Tặng quà', 'Chỉ đường'], correct: 0, explain: 'Sói nuốt bà rồi giả làm bà nằm trên giường để lừa cô bé.' },
      { q: 'Ai đã cứu bà và cô bé?', options: ['Bác thợ săn', 'Người mẹ', 'Chú chó'], correct: 0, explain: 'Bác thợ săn nghe tiếng ngáy lạ, vào rạch bụng Sói cứu hai bà cháu.' },
      { q: 'Sau chuyện đó, cô bé rút ra điều gì?', options: ['Nghe lời mẹ, không la cà, cảnh giác người lạ', 'Không đi thăm bà nữa', 'Sợ đi rừng'], correct: 0, explain: 'Cô bé nhớ lời mẹ, không còn la cà hay tin lời người lạ nữa.' },
    ],
  },
  {
    slug: 'ba-chu-heo-con', emoji: '🐷', title: 'Ba chú heo con',
    cau: [
      'Có ba chú heo con rời nhà mẹ ra ở riêng, mỗi chú tự dựng cho mình một ngôi nhà.',
      'Chú heo thứ nhất lười biếng, dựng vội một ngôi nhà bằng rơm cho nhanh.',
      'Chú heo thứ hai làm nhà bằng gỗ, cũng khá qua loa, cốt cho xong.',
      'Chú heo thứ ba chăm chỉ, kiên nhẫn xây một ngôi nhà bằng gạch thật chắc chắn.',
      'Một con Sói đói bụng tìm đến. Nó hít một hơi thổi phù, ngôi nhà rơm bay tung.',
      'Sói thổi tiếp, ngôi nhà gỗ cũng đổ. Hai chú heo hoảng sợ chạy sang nhà gạch của chú em út.',
      'Sói thổi mãi mà ngôi nhà gạch vẫn đứng vững. Tức mình, nó trèo lên định chui qua ống khói.',
      'Ba chú heo đã đặt sẵn một nồi nước sôi dưới bếp. Sói rơi trúng, bỏng rát, kêu la rồi chạy mất.',
    ],
    baiHoc: 'Chăm chỉ, làm việc cẩn thận và chắc chắn thì mọi thứ mới bền vững, an toàn.',
    cauHoi: [
      { q: 'Ba chú heo con rời nhà mẹ để làm gì?', options: ['Tự xây nhà ra ở riêng', 'Đi học', 'Đi chơi xa'], correct: 0, explain: 'Ba chú heo con rời nhà mẹ, mỗi chú tự dựng một ngôi nhà để ở.' },
      { q: 'Chú heo thứ nhất (lười) làm nhà bằng gì?', options: ['Rơm', 'Gạch', 'Đá'], correct: 0, explain: 'Chú heo thứ nhất lười nên dựng vội ngôi nhà bằng rơm.' },
      { q: 'Chú heo thứ hai làm nhà bằng gì?', options: ['Gỗ', 'Gạch', 'Rơm'], correct: 0, explain: 'Chú heo thứ hai làm nhà bằng gỗ, cũng khá qua loa.' },
      { q: 'Chú heo thứ ba (chăm chỉ) làm nhà bằng gì?', options: ['Gạch', 'Rơm', 'Lá cây'], correct: 0, explain: 'Chú heo thứ ba chăm chỉ xây một ngôi nhà bằng gạch thật chắc chắn.' },
      { q: 'Con vật nào tìm đến phá nhà các chú heo?', options: ['Con Sói', 'Con Cáo', 'Con Hổ'], correct: 0, explain: 'Một con Sói đói bụng tìm đến phá nhà các chú heo.' },
      { q: 'Sói làm cách nào để phá nhà rơm và nhà gỗ?', options: ['Thổi phù cho bay đổ', 'Đốt cháy', 'Đạp đổ'], correct: 0, explain: 'Sói hít hơi thổi phù, nhà rơm bay tung, rồi nhà gỗ cũng đổ.' },
      { q: 'Ngôi nhà của chú heo nào không bị Sói thổi đổ?', options: ['Nhà gạch', 'Nhà rơm', 'Nhà gỗ'], correct: 0, explain: 'Chỉ ngôi nhà gạch xây chắc chắn mới đứng vững trước Sói.' },
      { q: 'Khi không thổi đổ được nhà gạch, Sói định làm gì?', options: ['Trèo lên chui qua ống khói', 'Bỏ đi', 'Gõ cửa xin vào'], correct: 0, explain: 'Tức mình, Sói trèo lên định chui qua ống khói vào nhà.' },
      { q: 'Điều gì khiến Sói bỏng rát phải chạy mất?', options: ['Rơi trúng nồi nước sôi dưới bếp', 'Bị chó cắn', 'Trượt chân'], correct: 0, explain: 'Ba chú heo đặt sẵn nồi nước sôi, Sói rơi trúng nên bỏng rát chạy mất.' },
      { q: 'Vì sao nhà gạch an toàn?', options: ['Xây chắc chắn, cẩn thận', 'Vì to hơn', 'Vì có màu đẹp'], correct: 0, explain: 'Chú heo út chăm chỉ xây nhà gạch cẩn thận nên rất chắc chắn.' },
    ],
  },
  {
    slug: 'vit-con-xau-xi', emoji: '🦢', title: 'Chú vịt con xấu xí',
    cau: [
      'Trong ổ trứng của vịt mẹ có một quả trứng to nở muộn nhất.',
      'Chú vịt con chui ra to lớn, lông xám, trông khác hẳn các anh chị nên bị chê là xấu xí.',
      'Các con vật trong sân đều trêu chọc, xua đuổi chú. Buồn tủi, chú lặng lẽ bỏ đi lang thang.',
      'Chú sống qua một mùa đông giá lạnh, cô đơn và tủi thân giữa gió tuyết.',
      'Mùa xuân ấm áp trở về, chú bơi trên mặt hồ và cúi soi mình xuống làn nước trong.',
      'Kỳ lạ thay, chú nhận ra mình đã thành một con thiên nga trắng muốt, xinh đẹp.',
      'Đàn thiên nga vui vẻ đón chú làm bạn. Ai ngắm nhìn cũng phải tấm tắc khen.',
    ],
    baiHoc: 'Đừng đánh giá ai qua vẻ ngoài; hãy tin vào bản thân, vì ai cũng có vẻ đẹp riêng.',
    cauHoi: [
      { q: 'Quả trứng mà vịt con chui ra có gì đặc biệt?', options: ['To và nở muộn nhất', 'Bé nhất', 'Màu vàng'], correct: 0, explain: 'Trong ổ trứng, có một quả trứng to nở muộn nhất, chính là chú.' },
      { q: 'Vì sao vịt con bị chê là xấu xí?', options: ['To lớn, lông xám, khác hẳn anh chị', 'Vì lười biếng', 'Vì hay khóc'], correct: 0, explain: 'Chú chui ra to lớn, lông xám, trông khác hẳn nên bị chê xấu xí.' },
      { q: 'Vịt con bị các con vật đối xử thế nào?', options: ['Bị chê xấu, trêu chọc', 'Được yêu quý', 'Được tặng quà'], correct: 0, explain: 'Vì trông khác lạ, chú bị chê xấu xí và trêu chọc.' },
      { q: 'Bị trêu chọc, vịt con đã làm gì?', options: ['Buồn bã bỏ đi lang thang', 'Ở lại đánh nhau', 'Trốn trong ổ'], correct: 0, explain: 'Buồn tủi, chú lặng lẽ bỏ đi lang thang một mình.' },
      { q: 'Vịt con sống một mình qua mùa nào giá lạnh?', options: ['Mùa đông', 'Mùa hè', 'Mùa thu'], correct: 0, explain: 'Chú sống qua một mùa đông giá lạnh, cô đơn giữa gió tuyết.' },
      { q: 'Vịt con nhận ra mình đã đổi khác vào lúc nào?', options: ['Mùa xuân, khi soi mình xuống nước', 'Ngay khi sinh ra', 'Vào ban đêm'], correct: 0, explain: 'Mùa xuân, chú bơi trên hồ, soi mình xuống nước và nhận ra sự thay đổi.' },
      { q: 'Lớn lên, chú vịt con hoá thành con gì?', options: ['Thiên nga', 'Đại bàng', 'Chim công'], correct: 0, explain: 'Chú vốn là thiên nga, lớn lên hoá thành thiên nga trắng xinh đẹp.' },
      { q: 'Kết truyện, đàn thiên nga đối xử với chú ra sao?', options: ['Vui vẻ đón chú làm bạn', 'Xua đuổi chú', 'Không để ý'], correct: 0, explain: 'Đàn thiên nga vui vẻ đón chú làm bạn, ai nhìn cũng khen.' },
    ],
  },
  {
    slug: 'co-be-lo-lem', emoji: '👠', title: 'Cô bé Lọ Lem',
    cau: [
      'Lọ Lem là cô gái hiền lành, mồ côi mẹ, sống cùng dì ghẻ và hai cô con riêng của dì.',
      'Dì ghẻ bắt Lọ Lem làm lụng vất vả suốt ngày, quần áo lấm lem nên mọi người gọi cô là Lọ Lem.',
      'Hoàng tử mở hội kén vợ. Dì ghẻ và hai cô chị xúng xính đi dự, bắt Lọ Lem ở nhà làm việc.',
      'Lọ Lem tủi thân ngồi khóc. Bỗng một bà tiên hiện ra, biến quả bí thành cỗ xe, biến áo rách thành váy đẹp và một đôi giày thuỷ tinh.',
      'Bà tiên dặn cô phải về trước khi chuông điểm mười hai giờ đêm, vì khi đó phép màu sẽ tan biến.',
      'Ở dạ hội, hoàng tử chỉ khiêu vũ cùng Lọ Lem xinh đẹp. Đúng nửa đêm, cô vội chạy về, đánh rơi một chiếc giày thuỷ tinh.',
      'Hoàng tử cầm chiếc giày đi khắp nơi tìm người đi vừa. Hai cô chị ướm thử nhưng đều không vừa.',
      'Đến lượt Lọ Lem, chiếc giày vừa in như đo. Hoàng tử đón cô về, hai người sống bên nhau hạnh phúc.',
    ],
    baiHoc: 'Hiền lành, tốt bụng sẽ gặp điều tốt đẹp; hãy luôn giữ tấm lòng nhân hậu.',
    cauHoi: [
      { q: 'Lọ Lem sống cùng những ai?', options: ['Dì ghẻ và hai cô con riêng của dì', 'Ông bà ngoại', 'Một mình'], correct: 0, explain: 'Lọ Lem mồ côi mẹ, sống cùng dì ghẻ và hai cô con riêng của dì.' },
      { q: 'Vì sao cô gái được gọi là Lọ Lem?', options: ['Vì làm lụng vất vả, quần áo lấm lem', 'Vì thích tên đó', 'Vì hay khóc'], correct: 0, explain: 'Cô phải làm lụng suốt ngày, quần áo lấm lem nên gọi là Lọ Lem.' },
      { q: 'Hoàng tử mở hội để làm gì?', options: ['Kén vợ', 'Mừng sinh nhật', 'Thi hát'], correct: 0, explain: 'Hoàng tử mở dạ hội để kén vợ.' },
      { q: 'Ai đã giúp Lọ Lem đi dự dạ hội?', options: ['Bà tiên', 'Dì ghẻ', 'Hoàng tử'], correct: 0, explain: 'Bà tiên hiện ra, hoá phép cho Lọ Lem xe, váy đẹp và giày thuỷ tinh.' },
      { q: 'Bà tiên đã biến quả bí thành gì?', options: ['Một cỗ xe', 'Một ngôi nhà', 'Một con ngựa'], correct: 0, explain: 'Bà tiên biến quả bí thành cỗ xe đưa Lọ Lem đi dự hội.' },
      { q: 'Bà tiên dặn Lọ Lem phải về trước lúc nào?', options: ['Mười hai giờ đêm', 'Lúc trời sáng', 'Lúc hoàng hôn'], correct: 0, explain: 'Bà dặn phải về trước khi chuông điểm mười hai giờ đêm, vì phép màu sẽ tan.' },
      { q: 'Ở dạ hội, hoàng tử khiêu vũ cùng ai?', options: ['Lọ Lem', 'Hai cô chị', 'Dì ghẻ'], correct: 0, explain: 'Hoàng tử chỉ khiêu vũ cùng Lọ Lem xinh đẹp.' },
      { q: 'Lọ Lem đánh rơi vật gì khi vội chạy về?', options: ['Chiếc giày thuỷ tinh', 'Chiếc khăn', 'Cái vương miện'], correct: 0, explain: 'Đúng nửa đêm cô vội về và đánh rơi một chiếc giày thuỷ tinh.' },
      { q: 'Hoàng tử cầm chiếc giày đi khắp nơi để làm gì?', options: ['Tìm người đi vừa chiếc giày', 'Đem bán', 'Tặng người khác'], correct: 0, explain: 'Hoàng tử đi tìm người đi vừa chiếc giày để cưới làm vợ.' },
      { q: 'Cuối truyện, ai đi vừa chiếc giày thuỷ tinh?', options: ['Lọ Lem', 'Cô chị cả', 'Cô chị hai'], correct: 0, explain: 'Chiếc giày vừa in với chân Lọ Lem, hoàng tử đón cô về sống hạnh phúc.' },
    ],
  },
];

export const totalTruyen = () => TRUYEN_CO_TICH.length;
