// Từ vựng tiếng Anh cho bé, chia theo chủ đề.
//
// Mỗi chủ đề là một trang SEO riêng (/tu-vung-tieng-anh/{slug}) + là nguyên liệu cho
// chế độ flashcard/nghe phát âm. Dữ liệu tĩnh (không cần DB, không gọi API) nên trang
// render tĩnh, nhanh, luôn có nội dung. Phát âm dùng Web Speech API của trình duyệt
// (miễn phí, tức thì) — xem VocabTopicClient.
//
// Nguyên tắc dữ liệu:
//   • en: từ tiếng Anh viết thường (trừ danh từ riêng), phổ thông với trẻ tiểu học.
//   • ipa: phiên âm quốc tế (giọng Mỹ), đặt trong / /.
//   • vi: nghĩa tiếng Việt ngắn gọn.
//   • emoji: hình minh hoạ tức thì (không tốn asset); để '' nếu không có emoji hợp.
//   • example/exampleVi: câu ví dụ ĐƠN GIẢN cho bé (tuỳ chọn).

import { ANIMALS } from './animals-data';
import { COUNTRIES } from './countries-data';

export type VocabWord = {
  en: string;
  ipa: string;
  vi: string;
  emoji: string;
  example?: string;
  exampleVi?: string;
};

export type VocabTopic = {
  slug: string;
  emoji: string;
  /** H1 + breadcrumb, vd "Động vật". */
  heading: string;
  /** <title>, giữ dưới ~60 ký tự kể cả brand. */
  title: string;
  description: string;
  /** Đoạn mở đầu riêng từng chủ đề (không tái sử dụng). */
  intro: string;
  words: VocabWord[];
};

export const VOCAB_TOPICS: VocabTopic[] = [
  {
    slug: 'dong-vat',
    emoji: '🐶',
    heading: 'Động vật',
    title: 'Từ vựng tiếng Anh chủ đề động vật cho bé',
    description:
      'Học từ vựng tiếng Anh về con vật cho bé: dog, cat, lion, elephant… kèm phiên âm, nghĩa tiếng Việt, hình minh hoạ và phát âm chuẩn. Học miễn phí.',
    intro:
      'Con vật là chủ đề bé yêu thích nhất khi bắt đầu học tiếng Anh. Dưới đây là các từ vựng động vật quen thuộc kèm phiên âm và cách phát âm để bé vừa nhìn hình, vừa nghe, vừa đọc theo.',
    words: ANIMALS,
  },
  {
    slug: 'mau-sac',
    emoji: '🎨',
    heading: 'Màu sắc',
    title: 'Từ vựng tiếng Anh chủ đề màu sắc cho bé',
    description:
      'Học màu sắc tiếng Anh cho bé: red, blue, yellow, green… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn. Bé học màu qua hình minh hoạ.',
    intro:
      'Màu sắc giúp bé mô tả thế giới xung quanh. Hãy cùng bé gọi tên từng màu bằng tiếng Anh, nghe phát âm và tìm đồ vật cùng màu trong nhà để nhớ lâu hơn.',
    words: [
      { en: 'red', ipa: '/red/', vi: 'màu đỏ', emoji: '🔴', example: 'The apple is red.', exampleVi: 'Quả táo màu đỏ.' },
      { en: 'blue', ipa: '/bluː/', vi: 'màu xanh dương', emoji: '🔵', example: 'The sky is blue.', exampleVi: 'Bầu trời màu xanh.' },
      { en: 'yellow', ipa: '/ˈjeloʊ/', vi: 'màu vàng', emoji: '🟡', example: 'The sun is yellow.', exampleVi: 'Mặt trời màu vàng.' },
      { en: 'green', ipa: '/ɡriːn/', vi: 'màu xanh lá', emoji: '🟢', example: 'The leaf is green.', exampleVi: 'Chiếc lá màu xanh.' },
      { en: 'orange', ipa: '/ˈɔːrɪndʒ/', vi: 'màu cam', emoji: '🟠' },
      { en: 'purple', ipa: '/ˈpɜːrpl/', vi: 'màu tím', emoji: '🟣' },
      { en: 'pink', ipa: '/pɪŋk/', vi: 'màu hồng', emoji: '🌸' },
      { en: 'brown', ipa: '/braʊn/', vi: 'màu nâu', emoji: '🟤' },
      { en: 'black', ipa: '/blæk/', vi: 'màu đen', emoji: '⚫', example: 'The cat is black.', exampleVi: 'Con mèo màu đen.' },
      { en: 'white', ipa: '/waɪt/', vi: 'màu trắng', emoji: '⚪', example: 'Milk is white.', exampleVi: 'Sữa màu trắng.' },
      { en: 'gray', ipa: '/ɡreɪ/', vi: 'màu xám', emoji: '🩶' },
      { en: 'gold', ipa: '/ɡoʊld/', vi: 'màu vàng kim', emoji: '🟨' },
      { en: 'silver', ipa: '/ˈsɪlvər/', vi: 'màu bạc', emoji: '⚙️' },
      { en: 'colorful', ipa: '/ˈkʌlərfl/', vi: 'nhiều màu sắc', emoji: '🌈' },
      { en: 'light blue', ipa: '/laɪt bluː/', vi: 'xanh nhạt', emoji: '🩵' },
      { en: 'dark blue', ipa: '/dɑːrk bluː/', vi: 'xanh đậm', emoji: '🔵' },
      { en: 'navy', ipa: '/ˈneɪvi/', vi: 'xanh navy', emoji: '🔵' },
      { en: 'turquoise', ipa: '/ˈtɜːrkɔɪz/', vi: 'xanh ngọc', emoji: '🩵' },
      { en: 'beige', ipa: '/beɪʒ/', vi: 'màu be', emoji: '🟤' },
      { en: 'violet', ipa: '/ˈvaɪələt/', vi: 'màu tím violet', emoji: '🟣' },
    ],
  },
  {
    slug: 'con-so',
    emoji: '🔢',
    heading: 'Con số',
    title: 'Từ vựng tiếng Anh chủ đề con số cho bé',
    description:
      'Học đếm số tiếng Anh cho bé từ one đến hundred: phiên âm, nghĩa và phát âm chuẩn. Bé vừa học tiếng Anh vừa tập đếm.',
    intro:
      'Đếm số là kỹ năng nền tảng. Bé hãy nghe và đọc theo từ one đến ten trước, rồi mở rộng tới twenty và các số tròn chục. Vừa đọc vừa đếm ngón tay để nhớ nhanh hơn nhé.',
    words: [
      { en: 'one', ipa: '/wʌn/', vi: 'số một (1)', emoji: '1️⃣' },
      { en: 'two', ipa: '/tuː/', vi: 'số hai (2)', emoji: '2️⃣' },
      { en: 'three', ipa: '/θriː/', vi: 'số ba (3)', emoji: '3️⃣' },
      { en: 'four', ipa: '/fɔːr/', vi: 'số bốn (4)', emoji: '4️⃣' },
      { en: 'five', ipa: '/faɪv/', vi: 'số năm (5)', emoji: '5️⃣' },
      { en: 'six', ipa: '/sɪks/', vi: 'số sáu (6)', emoji: '6️⃣' },
      { en: 'seven', ipa: '/ˈsevn/', vi: 'số bảy (7)', emoji: '7️⃣' },
      { en: 'eight', ipa: '/eɪt/', vi: 'số tám (8)', emoji: '8️⃣' },
      { en: 'nine', ipa: '/naɪn/', vi: 'số chín (9)', emoji: '9️⃣' },
      { en: 'ten', ipa: '/ten/', vi: 'số mười (10)', emoji: '🔟' },
      { en: 'eleven', ipa: '/ɪˈlevn/', vi: 'số mười một (11)', emoji: '🔢' },
      { en: 'twelve', ipa: '/twelv/', vi: 'số mười hai (12)', emoji: '🔢' },
      { en: 'thirteen', ipa: '/ˌθɜːrˈtiːn/', vi: 'số mười ba (13)', emoji: '🔢' },
      { en: 'fourteen', ipa: '/ˌfɔːrˈtiːn/', vi: 'số mười bốn (14)', emoji: '🔢' },
      { en: 'fifteen', ipa: '/ˌfɪfˈtiːn/', vi: 'số mười lăm (15)', emoji: '🔢' },
      { en: 'sixteen', ipa: '/ˌsɪksˈtiːn/', vi: 'số mười sáu (16)', emoji: '🔢' },
      { en: 'seventeen', ipa: '/ˌsevnˈtiːn/', vi: 'số mười bảy (17)', emoji: '🔢' },
      { en: 'eighteen', ipa: '/ˌeɪˈtiːn/', vi: 'số mười tám (18)', emoji: '🔢' },
      { en: 'nineteen', ipa: '/ˌnaɪnˈtiːn/', vi: 'số mười chín (19)', emoji: '🔢' },
      { en: 'twenty', ipa: '/ˈtwenti/', vi: 'số hai mươi (20)', emoji: '🔢' },
      { en: 'thirty', ipa: '/ˈθɜːrti/', vi: 'số ba mươi (30)', emoji: '🔢' },
      { en: 'forty', ipa: '/ˈfɔːrti/', vi: 'số bốn mươi (40)', emoji: '🔢' },
      { en: 'fifty', ipa: '/ˈfɪfti/', vi: 'số năm mươi (50)', emoji: '🔢' },
      { en: 'hundred', ipa: '/ˈhʌndrəd/', vi: 'một trăm (100)', emoji: '💯' },
    ],
  },
  {
    slug: 'gia-dinh',
    emoji: '👨‍👩‍👧‍👦',
    heading: 'Gia đình',
    title: 'Từ vựng tiếng Anh chủ đề gia đình cho bé',
    description:
      'Học từ vựng gia đình tiếng Anh cho bé: father, mother, brother, sister… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Gia đình là những người thân yêu nhất của bé. Cùng học cách gọi bố, mẹ, ông, bà, anh, chị bằng tiếng Anh và giới thiệu về gia đình mình nhé.',
    words: [
      { en: 'father', ipa: '/ˈfɑːðər/', vi: 'bố, cha', emoji: '👨', example: 'This is my father.', exampleVi: 'Đây là bố của con.' },
      { en: 'mother', ipa: '/ˈmʌðər/', vi: 'mẹ', emoji: '👩', example: 'I love my mother.', exampleVi: 'Con yêu mẹ.' },
      { en: 'parents', ipa: '/ˈperənts/', vi: 'bố mẹ', emoji: '👫' },
      { en: 'brother', ipa: '/ˈbrʌðər/', vi: 'anh, em trai', emoji: '👦' },
      { en: 'sister', ipa: '/ˈsɪstər/', vi: 'chị, em gái', emoji: '👧' },
      { en: 'baby', ipa: '/ˈbeɪbi/', vi: 'em bé', emoji: '👶' },
      { en: 'grandfather', ipa: '/ˈɡrænfɑːðər/', vi: 'ông', emoji: '👴' },
      { en: 'grandmother', ipa: '/ˈɡrænmʌðər/', vi: 'bà', emoji: '👵' },
      { en: 'grandparents', ipa: '/ˈɡrænperənts/', vi: 'ông bà', emoji: '👴👵' },
      { en: 'uncle', ipa: '/ˈʌŋkl/', vi: 'chú, bác, cậu', emoji: '👨' },
      { en: 'aunt', ipa: '/ænt/', vi: 'cô, dì, bác gái', emoji: '👩' },
      { en: 'cousin', ipa: '/ˈkʌzn/', vi: 'anh chị em họ', emoji: '🧒' },
      { en: 'family', ipa: '/ˈfæməli/', vi: 'gia đình', emoji: '👨‍👩‍👧‍👦', example: 'I have a happy family.', exampleVi: 'Con có một gia đình hạnh phúc.' },
      { en: 'son', ipa: '/sʌn/', vi: 'con trai', emoji: '👦' },
      { en: 'daughter', ipa: '/ˈdɔːtər/', vi: 'con gái', emoji: '👧' },
      { en: 'twins', ipa: '/twɪnz/', vi: 'cặp sinh đôi', emoji: '👯' },
      { en: 'husband', ipa: '/ˈhʌzbənd/', vi: 'người chồng', emoji: '🤵' },
      { en: 'wife', ipa: '/waɪf/', vi: 'người vợ', emoji: '👰' },
      { en: 'nephew', ipa: '/ˈnefjuː/', vi: 'cháu trai', emoji: '👦' },
      { en: 'niece', ipa: '/niːs/', vi: 'cháu gái', emoji: '👧' },
      { en: 'grandchild', ipa: '/ˈɡræntʃaɪld/', vi: 'cháu', emoji: '🧒' },
      { en: 'relatives', ipa: '/ˈrelətɪvz/', vi: 'họ hàng', emoji: '👨‍👩‍👧‍👦' },
    ],
  },
  {
    slug: 'trai-cay',
    emoji: '🍎',
    heading: 'Trái cây',
    title: 'Từ vựng tiếng Anh chủ đề trái cây cho bé',
    description:
      'Học tên trái cây bằng tiếng Anh cho bé: apple, banana, orange, mango… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Trái cây vừa ngon vừa tốt cho sức khoẻ. Cùng bé gọi tên các loại quả quen thuộc bằng tiếng Anh và kể xem bé thích ăn quả nào nhất nhé.',
    words: [
      { en: 'apple', ipa: '/ˈæpl/', vi: 'quả táo', emoji: '🍎', example: 'I eat an apple.', exampleVi: 'Con ăn một quả táo.' },
      { en: 'banana', ipa: '/bəˈnænə/', vi: 'quả chuối', emoji: '🍌' },
      { en: 'orange', ipa: '/ˈɔːrɪndʒ/', vi: 'quả cam', emoji: '🍊' },
      { en: 'grape', ipa: '/ɡreɪp/', vi: 'quả nho', emoji: '🍇' },
      { en: 'watermelon', ipa: '/ˈwɔːtərmelən/', vi: 'quả dưa hấu', emoji: '🍉' },
      { en: 'mango', ipa: '/ˈmæŋɡoʊ/', vi: 'quả xoài', emoji: '🥭' },
      { en: 'strawberry', ipa: '/ˈstrɔːberi/', vi: 'quả dâu tây', emoji: '🍓' },
      { en: 'pineapple', ipa: '/ˈpaɪnæpl/', vi: 'quả dứa', emoji: '🍍' },
      { en: 'lemon', ipa: '/ˈlemən/', vi: 'quả chanh', emoji: '🍋' },
      { en: 'peach', ipa: '/piːtʃ/', vi: 'quả đào', emoji: '🍑' },
      { en: 'cherry', ipa: '/ˈtʃeri/', vi: 'quả anh đào', emoji: '🍒' },
      { en: 'coconut', ipa: '/ˈkoʊkənʌt/', vi: 'quả dừa', emoji: '🥥' },
      { en: 'pear', ipa: '/per/', vi: 'quả lê', emoji: '🍐' },
      { en: 'kiwi', ipa: '/ˈkiːwiː/', vi: 'quả kiwi', emoji: '🥝' },
      { en: 'papaya', ipa: '/pəˈpaɪə/', vi: 'quả đu đủ', emoji: '🥭' },
      { en: 'plum', ipa: '/plʌm/', vi: 'quả mận', emoji: '🍇' },
      { en: 'guava', ipa: '/ˈɡwɑːvə/', vi: 'quả ổi', emoji: '🍈' },
      { en: 'longan', ipa: '/ˈlɒŋɡən/', vi: 'quả nhãn', emoji: '🟤' },
      { en: 'avocado', ipa: '/ˌævəˈkɑːdoʊ/', vi: 'quả bơ', emoji: '🥑' },
      { en: 'blueberry', ipa: '/ˈbluːberi/', vi: 'quả việt quất', emoji: '🫐' },
      { en: 'lime', ipa: '/laɪm/', vi: 'quả chanh xanh', emoji: '🟢' },
      { en: 'melon', ipa: '/ˈmelən/', vi: 'quả dưa lưới', emoji: '🍈' },
      { en: 'apricot', ipa: '/ˈæprɪkɑːt/', vi: 'quả mơ', emoji: '🟠' },
      { en: 'pomegranate', ipa: '/ˈpɑːmɪɡrænɪt/', vi: 'quả lựu', emoji: '🔴' },
      { en: 'dragon fruit', ipa: '/ˈdræɡən fruːt/', vi: 'quả thanh long', emoji: '🐉' },
      { en: 'jackfruit', ipa: '/ˈdʒækfruːt/', vi: 'quả mít', emoji: '🟡' },
      { en: 'rambutan', ipa: '/ræmˈbuːtn/', vi: 'quả chôm chôm', emoji: '🔴' },
      { en: 'star fruit', ipa: '/stɑːr fruːt/', vi: 'quả khế', emoji: '⭐' },
      { en: 'persimmon', ipa: '/pərˈsɪmən/', vi: 'quả hồng', emoji: '🟠' },
      { en: 'tangerine', ipa: '/ˌtændʒəˈriːn/', vi: 'quả quýt', emoji: '🍊' },
    ],
  },
  {
    slug: 'rau-cu',
    emoji: '🥕',
    heading: 'Rau củ',
    title: 'Từ vựng tiếng Anh chủ đề rau củ cho bé',
    description:
      'Học tên rau củ bằng tiếng Anh cho bé: carrot, tomato, potato, onion… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Ăn nhiều rau củ giúp bé cao lớn và khoẻ mạnh. Cùng học tên các loại rau củ quen thuộc bằng tiếng Anh và tìm chúng trong bữa cơm nhà mình nhé.',
    words: [
      { en: 'carrot', ipa: '/ˈkærət/', vi: 'củ cà rốt', emoji: '🥕' },
      { en: 'tomato', ipa: '/təˈmeɪtoʊ/', vi: 'quả cà chua', emoji: '🍅' },
      { en: 'potato', ipa: '/pəˈteɪtoʊ/', vi: 'củ khoai tây', emoji: '🥔' },
      { en: 'onion', ipa: '/ˈʌnjən/', vi: 'củ hành', emoji: '🧅' },
      { en: 'corn', ipa: '/kɔːrn/', vi: 'bắp ngô', emoji: '🌽' },
      { en: 'cucumber', ipa: '/ˈkjuːkʌmbər/', vi: 'quả dưa chuột', emoji: '🥒' },
      { en: 'broccoli', ipa: '/ˈbrɑːkəli/', vi: 'bông cải xanh', emoji: '🥦' },
      { en: 'mushroom', ipa: '/ˈmʌʃruːm/', vi: 'cây nấm', emoji: '🍄' },
      { en: 'pumpkin', ipa: '/ˈpʌmpkɪn/', vi: 'quả bí đỏ', emoji: '🎃' },
      { en: 'pepper', ipa: '/ˈpepər/', vi: 'quả ớt chuông', emoji: '🫑' },
      { en: 'cabbage', ipa: '/ˈkæbɪdʒ/', vi: 'bắp cải', emoji: '🥬' },
      { en: 'lettuce', ipa: '/ˈletɪs/', vi: 'rau xà lách', emoji: '🥬' },
      { en: 'garlic', ipa: '/ˈɡɑːrlɪk/', vi: 'củ tỏi', emoji: '🧄' },
      { en: 'ginger', ipa: '/ˈdʒɪndʒər/', vi: 'củ gừng', emoji: '🫚' },
      { en: 'eggplant', ipa: '/ˈeɡplænt/', vi: 'quả cà tím', emoji: '🍆' },
      { en: 'bean', ipa: '/biːn/', vi: 'hạt đậu', emoji: '🫘' },
      { en: 'pea', ipa: '/piː/', vi: 'hạt đậu Hà Lan', emoji: '🟢' },
      { en: 'chili', ipa: '/ˈtʃɪli/', vi: 'quả ớt', emoji: '🌶️' },
      { en: 'spinach', ipa: '/ˈspɪnɪtʃ/', vi: 'rau bina', emoji: '🥬' },
      { en: 'celery', ipa: '/ˈseləri/', vi: 'cần tây', emoji: '🥬' },
      { en: 'sweet potato', ipa: '/swiːt pəˈteɪtoʊ/', vi: 'khoai lang', emoji: '🍠' },
      { en: 'bean sprout', ipa: '/biːn spraʊt/', vi: 'giá đỗ', emoji: '🌱' },
      { en: 'bitter melon', ipa: '/ˈbɪtər ˈmelən/', vi: 'mướp đắng', emoji: '🥒' },
      { en: 'okra', ipa: '/ˈoʊkrə/', vi: 'đậu bắp', emoji: '🫛' },
      { en: 'asparagus', ipa: '/əˈspærəɡəs/', vi: 'măng tây', emoji: '🥬' },
      { en: 'radish', ipa: '/ˈrædɪʃ/', vi: 'củ cải', emoji: '🥕' },
      { en: 'taro', ipa: '/ˈtɑːroʊ/', vi: 'khoai môn', emoji: '🥔' },
      { en: 'water spinach', ipa: '/ˈwɔːtər ˈspɪnɪtʃ/', vi: 'rau muống', emoji: '🥬' },
    ],
  },
  {
    slug: 'co-the',
    emoji: '🧑',
    heading: 'Bộ phận cơ thể',
    title: 'Từ vựng tiếng Anh chủ đề cơ thể cho bé',
    description:
      'Học bộ phận cơ thể tiếng Anh cho bé: head, eye, nose, hand… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Cùng bé chỉ vào từng bộ phận trên cơ thể và gọi tên bằng tiếng Anh. Vừa học vừa chơi trò "Touch your nose!" để bé nhớ từ thật nhanh.',
    words: [
      { en: 'head', ipa: '/hed/', vi: 'cái đầu', emoji: '🧠' },
      { en: 'hair', ipa: '/her/', vi: 'tóc', emoji: '💇' },
      { en: 'face', ipa: '/feɪs/', vi: 'khuôn mặt', emoji: '😊' },
      { en: 'eye', ipa: '/aɪ/', vi: 'mắt', emoji: '👁️', example: 'I have two eyes.', exampleVi: 'Con có hai mắt.' },
      { en: 'ear', ipa: '/ɪr/', vi: 'tai', emoji: '👂' },
      { en: 'nose', ipa: '/noʊz/', vi: 'mũi', emoji: '👃' },
      { en: 'mouth', ipa: '/maʊθ/', vi: 'miệng', emoji: '👄' },
      { en: 'tooth', ipa: '/tuːθ/', vi: 'răng', emoji: '🦷' },
      { en: 'tongue', ipa: '/tʌŋ/', vi: 'lưỡi', emoji: '👅' },
      { en: 'neck', ipa: '/nek/', vi: 'cổ', emoji: '🧣' },
      { en: 'shoulder', ipa: '/ˈʃoʊldər/', vi: 'vai', emoji: '💪' },
      { en: 'hand', ipa: '/hænd/', vi: 'bàn tay', emoji: '✋' },
      { en: 'finger', ipa: '/ˈfɪŋɡər/', vi: 'ngón tay', emoji: '👆' },
      { en: 'arm', ipa: '/ɑːrm/', vi: 'cánh tay', emoji: '💪' },
      { en: 'leg', ipa: '/leɡ/', vi: 'chân', emoji: '🦵' },
      { en: 'knee', ipa: '/niː/', vi: 'đầu gối', emoji: '🦵' },
      { en: 'foot', ipa: '/fʊt/', vi: 'bàn chân', emoji: '🦶' },
      { en: 'toe', ipa: '/toʊ/', vi: 'ngón chân', emoji: '🦶' },
      { en: 'stomach', ipa: '/ˈstʌmək/', vi: 'bụng', emoji: '🤰' },
      { en: 'back', ipa: '/bæk/', vi: 'lưng', emoji: '🔙' },
      { en: 'forehead', ipa: '/ˈfɔːrhed/', vi: 'trán', emoji: '🧑' },
      { en: 'eyebrow', ipa: '/ˈaɪbraʊ/', vi: 'lông mày', emoji: '🤨' },
      { en: 'cheek', ipa: '/tʃiːk/', vi: 'má', emoji: '😊' },
      { en: 'chin', ipa: '/tʃɪn/', vi: 'cằm', emoji: '🧑' },
      { en: 'lip', ipa: '/lɪp/', vi: 'môi', emoji: '👄' },
      { en: 'chest', ipa: '/tʃest/', vi: 'ngực', emoji: '🫁' },
      { en: 'elbow', ipa: '/ˈelboʊ/', vi: 'khuỷu tay', emoji: '💪' },
      { en: 'wrist', ipa: '/rɪst/', vi: 'cổ tay', emoji: '⌚' },
      { en: 'ankle', ipa: '/ˈæŋkl/', vi: 'mắt cá chân', emoji: '🦶' },
      { en: 'palm', ipa: '/pɑːm/', vi: 'lòng bàn tay', emoji: '✋' },
      { en: 'heart', ipa: '/hɑːrt/', vi: 'tim', emoji: '❤️' },
      { en: 'brain', ipa: '/breɪn/', vi: 'não', emoji: '🧠' },
    ],
  },
  {
    slug: 'do-an',
    emoji: '🍔',
    heading: 'Đồ ăn & thức uống',
    title: 'Từ vựng tiếng Anh chủ đề đồ ăn cho bé',
    description:
      'Học từ vựng đồ ăn thức uống tiếng Anh cho bé: rice, bread, milk, water… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Từ vựng đồ ăn giúp bé gọi món và nói về bữa ăn của mình. Cùng học tên các món quen thuộc bằng tiếng Anh và hỏi bé "What do you like?" nhé.',
    words: [
      { en: 'rice', ipa: '/raɪs/', vi: 'cơm', emoji: '🍚', example: 'I eat rice.', exampleVi: 'Con ăn cơm.' },
      { en: 'bread', ipa: '/bred/', vi: 'bánh mì', emoji: '🍞' },
      { en: 'milk', ipa: '/mɪlk/', vi: 'sữa', emoji: '🥛', example: 'I drink milk.', exampleVi: 'Con uống sữa.' },
      { en: 'water', ipa: '/ˈwɔːtər/', vi: 'nước', emoji: '💧' },
      { en: 'egg', ipa: '/eɡ/', vi: 'quả trứng', emoji: '🥚' },
      { en: 'noodle', ipa: '/ˈnuːdl/', vi: 'mì, bún', emoji: '🍜' },
      { en: 'soup', ipa: '/suːp/', vi: 'súp, canh', emoji: '🍲' },
      { en: 'meat', ipa: '/miːt/', vi: 'thịt', emoji: '🍖' },
      { en: 'chicken', ipa: '/ˈtʃɪkɪn/', vi: 'thịt gà', emoji: '🍗' },
      { en: 'cake', ipa: '/keɪk/', vi: 'bánh ngọt', emoji: '🍰' },
      { en: 'candy', ipa: '/ˈkændi/', vi: 'kẹo', emoji: '🍬' },
      { en: 'ice cream', ipa: '/ˈaɪs kriːm/', vi: 'kem', emoji: '🍦' },
      { en: 'pizza', ipa: '/ˈpiːtsə/', vi: 'bánh pizza', emoji: '🍕' },
      { en: 'hamburger', ipa: '/ˈhæmbɜːrɡər/', vi: 'bánh hamburger', emoji: '🍔' },
      { en: 'sandwich', ipa: '/ˈsænwɪtʃ/', vi: 'bánh mì kẹp', emoji: '🥪' },
      { en: 'cheese', ipa: '/tʃiːz/', vi: 'phô mai', emoji: '🧀' },
      { en: 'juice', ipa: '/dʒuːs/', vi: 'nước ép', emoji: '🧃' },
      { en: 'tea', ipa: '/tiː/', vi: 'trà', emoji: '🍵' },
      { en: 'sugar', ipa: '/ˈʃʊɡər/', vi: 'đường', emoji: '🧂' },
      { en: 'salt', ipa: '/sɔːlt/', vi: 'muối', emoji: '🧂' },
      { en: 'pork', ipa: '/pɔːrk/', vi: 'thịt lợn', emoji: '🥓' },
      { en: 'beef', ipa: '/biːf/', vi: 'thịt bò', emoji: '🥩' },
      { en: 'sausage', ipa: '/ˈsɔːsɪdʒ/', vi: 'xúc xích', emoji: '🌭' },
      { en: 'french fries', ipa: '/frentʃ fraɪz/', vi: 'khoai tây chiên', emoji: '🍟' },
      { en: 'cookie', ipa: '/ˈkʊki/', vi: 'bánh quy', emoji: '🍪' },
      { en: 'donut', ipa: '/ˈdoʊnʌt/', vi: 'bánh vòng', emoji: '🍩' },
      { en: 'pancake', ipa: '/ˈpænkeɪk/', vi: 'bánh kếp', emoji: '🥞' },
      { en: 'popcorn', ipa: '/ˈpɑːpkɔːrn/', vi: 'bỏng ngô', emoji: '🍿' },
      { en: 'salad', ipa: '/ˈsæləd/', vi: 'rau trộn', emoji: '🥗' },
      { en: 'spaghetti', ipa: '/spəˈɡeti/', vi: 'mì Ý', emoji: '🍝' },
      { en: 'sushi', ipa: '/ˈsuːʃi/', vi: 'sushi', emoji: '🍣' },
      { en: 'porridge', ipa: '/ˈpɔːrɪdʒ/', vi: 'cháo', emoji: '🥣' },
    ],
  },
  {
    slug: 'quan-ao',
    emoji: '👕',
    heading: 'Quần áo',
    title: 'Từ vựng tiếng Anh chủ đề quần áo cho bé',
    description:
      'Học từ vựng quần áo tiếng Anh cho bé: shirt, dress, shoes, hat… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Mỗi sáng bé mặc gì tới trường? Cùng học tên các món quần áo bằng tiếng Anh để bé tự kể về trang phục của mình nhé.',
    words: [
      { en: 'shirt', ipa: '/ʃɜːrt/', vi: 'áo sơ mi', emoji: '👔' },
      { en: 't-shirt', ipa: '/ˈtiː ʃɜːrt/', vi: 'áo phông', emoji: '👕' },
      { en: 'dress', ipa: '/dres/', vi: 'váy, đầm', emoji: '👗' },
      { en: 'pants', ipa: '/pænts/', vi: 'quần dài', emoji: '👖' },
      { en: 'shorts', ipa: '/ʃɔːrts/', vi: 'quần đùi', emoji: '🩳' },
      { en: 'skirt', ipa: '/skɜːrt/', vi: 'chân váy', emoji: '👗' },
      { en: 'shoes', ipa: '/ʃuːz/', vi: 'giày', emoji: '👟' },
      { en: 'socks', ipa: '/sɑːks/', vi: 'tất, vớ', emoji: '🧦' },
      { en: 'hat', ipa: '/hæt/', vi: 'mũ', emoji: '👒' },
      { en: 'cap', ipa: '/kæp/', vi: 'mũ lưỡi trai', emoji: '🧢' },
      { en: 'jacket', ipa: '/ˈdʒækɪt/', vi: 'áo khoác', emoji: '🧥' },
      { en: 'coat', ipa: '/koʊt/', vi: 'áo choàng', emoji: '🧥' },
      { en: 'sweater', ipa: '/ˈswetər/', vi: 'áo len', emoji: '🧶' },
      { en: 'boots', ipa: '/buːts/', vi: 'ủng, bốt', emoji: '👢' },
      { en: 'sandals', ipa: '/ˈsændlz/', vi: 'dép quai hậu', emoji: '👡' },
      { en: 'gloves', ipa: '/ɡlʌvz/', vi: 'găng tay', emoji: '🧤' },
      { en: 'scarf', ipa: '/skɑːrf/', vi: 'khăn quàng', emoji: '🧣' },
      { en: 'glasses', ipa: '/ˈɡlæsɪz/', vi: 'kính', emoji: '👓' },
      { en: 'jeans', ipa: '/dʒiːnz/', vi: 'quần bò', emoji: '👖' },
      { en: 'suit', ipa: '/suːt/', vi: 'bộ vest', emoji: '🤵' },
      { en: 'vest', ipa: '/vest/', vi: 'áo gi lê', emoji: '🦺' },
      { en: 'raincoat', ipa: '/ˈreɪnkoʊt/', vi: 'áo mưa', emoji: '🧥' },
      { en: 'swimsuit', ipa: '/ˈswɪmsuːt/', vi: 'đồ bơi', emoji: '🩱' },
      { en: 'pajamas', ipa: '/pəˈdʒɑːməz/', vi: 'đồ ngủ', emoji: '🩳' },
      { en: 'slippers', ipa: '/ˈslɪpərz/', vi: 'dép lê', emoji: '🩴' },
      { en: 'tie', ipa: '/taɪ/', vi: 'cà vạt', emoji: '👔' },
      { en: 'mittens', ipa: '/ˈmɪtnz/', vi: 'găng tay hở ngón', emoji: '🧤' },
      { en: 'uniform', ipa: '/ˈjuːnɪfɔːrm/', vi: 'đồng phục', emoji: '👕' },
    ],
  },
  {
    slug: 'do-dung-hoc-tap',
    emoji: '✏️',
    heading: 'Đồ dùng học tập',
    title: 'Từ vựng tiếng Anh chủ đề đồ dùng học tập',
    description:
      'Học từ vựng đồ dùng học tập tiếng Anh cho bé: book, pen, pencil, ruler… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Trong cặp sách của bé có gì? Cùng học tên các đồ dùng học tập bằng tiếng Anh để bé sắp xếp và gọi tên chúng mỗi ngày tới lớp.',
    words: [
      { en: 'book', ipa: '/bʊk/', vi: 'quyển sách', emoji: '📖', example: 'This is my book.', exampleVi: 'Đây là sách của con.' },
      { en: 'pen', ipa: '/pen/', vi: 'bút mực', emoji: '🖊️' },
      { en: 'pencil', ipa: '/ˈpensl/', vi: 'bút chì', emoji: '✏️' },
      { en: 'ruler', ipa: '/ˈruːlər/', vi: 'thước kẻ', emoji: '📏' },
      { en: 'eraser', ipa: '/ɪˈreɪsər/', vi: 'cục tẩy', emoji: '🧽' },
      { en: 'bag', ipa: '/bæɡ/', vi: 'cặp sách', emoji: '🎒' },
      { en: 'notebook', ipa: '/ˈnoʊtbʊk/', vi: 'quyển vở', emoji: '📓' },
      { en: 'scissors', ipa: '/ˈsɪzərz/', vi: 'cái kéo', emoji: '✂️' },
      { en: 'crayon', ipa: '/ˈkreɪən/', vi: 'bút sáp màu', emoji: '🖍️' },
      { en: 'glue', ipa: '/ɡluː/', vi: 'keo dán', emoji: '🩹' },
      { en: 'desk', ipa: '/desk/', vi: 'bàn học', emoji: '🪑' },
      { en: 'board', ipa: '/bɔːrd/', vi: 'bảng', emoji: '📋' },
      { en: 'chalk', ipa: '/tʃɔːk/', vi: 'phấn', emoji: '🖌️' },
      { en: 'marker', ipa: '/ˈmɑːrkər/', vi: 'bút dạ', emoji: '🖊️' },
      { en: 'sharpener', ipa: '/ˈʃɑːrpənər/', vi: 'gọt bút chì', emoji: '🔪' },
      { en: 'paper', ipa: '/ˈpeɪpər/', vi: 'giấy', emoji: '📄' },
      { en: 'globe', ipa: '/ɡloʊb/', vi: 'quả địa cầu', emoji: '🌐' },
      { en: 'map', ipa: '/mæp/', vi: 'bản đồ', emoji: '🗺️' },
      { en: 'textbook', ipa: '/ˈtekstbʊk/', vi: 'sách giáo khoa', emoji: '📗' },
      { en: 'dictionary', ipa: '/ˈdɪkʃəneri/', vi: 'từ điển', emoji: '📕' },
      { en: 'calculator', ipa: '/ˈkælkjuleɪtər/', vi: 'máy tính bỏ túi', emoji: '🧮' },
      { en: 'backpack', ipa: '/ˈbækpæk/', vi: 'ba lô', emoji: '🎒' },
      { en: 'folder', ipa: '/ˈfoʊldər/', vi: 'bìa kẹp hồ sơ', emoji: '📁' },
      { en: 'stapler', ipa: '/ˈsteɪplər/', vi: 'cái dập ghim', emoji: '📎' },
      { en: 'highlighter', ipa: '/ˈhaɪlaɪtər/', vi: 'bút dạ quang', emoji: '🖍️' },
      { en: 'compass', ipa: '/ˈkʌmpəs/', vi: 'com pa', emoji: '🧭' },
    ],
  },
  {
    slug: 'phuong-tien',
    emoji: '🚗',
    heading: 'Phương tiện giao thông',
    title: 'Từ vựng tiếng Anh chủ đề phương tiện cho bé',
    description:
      'Học từ vựng phương tiện giao thông tiếng Anh cho bé: car, bus, bike, plane… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Bé đi học bằng gì? Cùng học tên các phương tiện giao thông bằng tiếng Anh và bắt chước tiếng còi xe cho vui nhé!',
    words: [
      { en: 'car', ipa: '/kɑːr/', vi: 'ô tô', emoji: '🚗', example: 'The car is red.', exampleVi: 'Chiếc ô tô màu đỏ.' },
      { en: 'bus', ipa: '/bʌs/', vi: 'xe buýt', emoji: '🚌' },
      { en: 'bike', ipa: '/baɪk/', vi: 'xe đạp', emoji: '🚲' },
      { en: 'motorbike', ipa: '/ˈmoʊtərbaɪk/', vi: 'xe máy', emoji: '🏍️' },
      { en: 'train', ipa: '/treɪn/', vi: 'tàu hoả', emoji: '🚆' },
      { en: 'plane', ipa: '/pleɪn/', vi: 'máy bay', emoji: '✈️' },
      { en: 'boat', ipa: '/boʊt/', vi: 'thuyền', emoji: '⛵' },
      { en: 'ship', ipa: '/ʃɪp/', vi: 'tàu thuỷ', emoji: '🚢' },
      { en: 'truck', ipa: '/trʌk/', vi: 'xe tải', emoji: '🚚' },
      { en: 'taxi', ipa: '/ˈtæksi/', vi: 'xe taxi', emoji: '🚕' },
      { en: 'helicopter', ipa: '/ˈhelɪkɑːptər/', vi: 'trực thăng', emoji: '🚁' },
      { en: 'ambulance', ipa: '/ˈæmbjələns/', vi: 'xe cứu thương', emoji: '🚑' },
      { en: 'fire truck', ipa: '/ˈfaɪər trʌk/', vi: 'xe cứu hoả', emoji: '🚒' },
      { en: 'police car', ipa: '/pəˈliːs kɑːr/', vi: 'xe cảnh sát', emoji: '🚓' },
      { en: 'subway', ipa: '/ˈsʌbweɪ/', vi: 'tàu điện ngầm', emoji: '🚇' },
      { en: 'scooter', ipa: '/ˈskuːtər/', vi: 'xe scooter', emoji: '🛴' },
      { en: 'van', ipa: '/væn/', vi: 'xe van', emoji: '🚐' },
      { en: 'jeep', ipa: '/dʒiːp/', vi: 'xe jeep', emoji: '🚙' },
      { en: 'tram', ipa: '/træm/', vi: 'tàu điện', emoji: '🚊' },
      { en: 'ferry', ipa: '/ˈferi/', vi: 'phà', emoji: '⛴️' },
      { en: 'canoe', ipa: '/kəˈnuː/', vi: 'xuồng', emoji: '🛶' },
      { en: 'hot air balloon', ipa: '/hɑːt er bəˈluːn/', vi: 'khinh khí cầu', emoji: '🎈' },
      { en: 'spaceship', ipa: '/ˈspeɪsʃɪp/', vi: 'tàu vũ trụ', emoji: '🚀' },
      { en: 'crane', ipa: '/kreɪn/', vi: 'xe cần cẩu', emoji: '🏗️' },
      { en: 'sled', ipa: '/sled/', vi: 'xe trượt tuyết', emoji: '🛷' },
      { en: 'cable car', ipa: '/ˈkeɪbl kɑːr/', vi: 'cáp treo', emoji: '🚠' },
    ],
  },
  {
    slug: 'thoi-tiet',
    emoji: '☀️',
    heading: 'Thời tiết',
    title: 'Từ vựng tiếng Anh chủ đề thời tiết cho bé',
    description:
      'Học từ vựng thời tiết tiếng Anh cho bé: sunny, rainy, windy, cloudy… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Hôm nay trời thế nào? Cùng học từ vựng thời tiết bằng tiếng Anh và tập trả lời câu hỏi "How is the weather today?" mỗi sáng nhé.',
    words: [
      { en: 'sunny', ipa: '/ˈsʌni/', vi: 'nắng', emoji: '☀️', example: 'It is sunny today.', exampleVi: 'Hôm nay trời nắng.' },
      { en: 'rainy', ipa: '/ˈreɪni/', vi: 'mưa', emoji: '🌧️' },
      { en: 'cloudy', ipa: '/ˈklaʊdi/', vi: 'nhiều mây', emoji: '☁️' },
      { en: 'windy', ipa: '/ˈwɪndi/', vi: 'gió', emoji: '🌬️' },
      { en: 'snowy', ipa: '/ˈsnoʊi/', vi: 'có tuyết', emoji: '❄️' },
      { en: 'stormy', ipa: '/ˈstɔːrmi/', vi: 'bão', emoji: '⛈️' },
      { en: 'foggy', ipa: '/ˈfɔːɡi/', vi: 'sương mù', emoji: '🌫️' },
      { en: 'hot', ipa: '/hɑːt/', vi: 'nóng', emoji: '🥵' },
      { en: 'cold', ipa: '/koʊld/', vi: 'lạnh', emoji: '🥶' },
      { en: 'warm', ipa: '/wɔːrm/', vi: 'ấm áp', emoji: '🌤️' },
      { en: 'cool', ipa: '/kuːl/', vi: 'mát mẻ', emoji: '🍃' },
      { en: 'thunder', ipa: '/ˈθʌndər/', vi: 'sấm', emoji: '🌩️' },
      { en: 'lightning', ipa: '/ˈlaɪtnɪŋ/', vi: 'chớp', emoji: '⚡' },
      { en: 'rainbow', ipa: '/ˈreɪnboʊ/', vi: 'cầu vồng', emoji: '🌈' },
      { en: 'storm', ipa: '/stɔːrm/', vi: 'cơn bão', emoji: '🌪️' },
      { en: 'breeze', ipa: '/briːz/', vi: 'gió nhẹ', emoji: '🍃' },
      { en: 'frost', ipa: '/frɔːst/', vi: 'sương giá', emoji: '❄️' },
      { en: 'hail', ipa: '/heɪl/', vi: 'mưa đá', emoji: '🌨️' },
      { en: 'drizzle', ipa: '/ˈdrɪzl/', vi: 'mưa phùn', emoji: '🌦️' },
      { en: 'ice', ipa: '/aɪs/', vi: 'băng', emoji: '🧊' },
    ],
  },
  {
    slug: 'nghe-nghiep',
    emoji: '👩‍⚕️',
    heading: 'Nghề nghiệp',
    title: 'Từ vựng tiếng Anh chủ đề nghề nghiệp cho bé',
    description:
      'Học từ vựng nghề nghiệp tiếng Anh cho bé: teacher, doctor, farmer, police… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Lớn lên bé muốn làm nghề gì? Cùng học tên các nghề nghiệp bằng tiếng Anh và tập nói "I want to be a…" nhé.',
    words: [
      { en: 'teacher', ipa: '/ˈtiːtʃər/', vi: 'giáo viên', emoji: '👩‍🏫', example: 'My teacher is kind.', exampleVi: 'Cô giáo của con hiền.' },
      { en: 'doctor', ipa: '/ˈdɑːktər/', vi: 'bác sĩ', emoji: '👨‍⚕️' },
      { en: 'nurse', ipa: '/nɜːrs/', vi: 'y tá', emoji: '👩‍⚕️' },
      { en: 'dentist', ipa: '/ˈdentɪst/', vi: 'nha sĩ', emoji: '🦷' },
      { en: 'farmer', ipa: '/ˈfɑːrmər/', vi: 'nông dân', emoji: '👨‍🌾' },
      { en: 'police officer', ipa: '/pəˈliːs ˈɔːfɪsər/', vi: 'cảnh sát', emoji: '👮' },
      { en: 'firefighter', ipa: '/ˈfaɪərfaɪtər/', vi: 'lính cứu hoả', emoji: '👨‍🚒' },
      { en: 'chef', ipa: '/ʃef/', vi: 'đầu bếp', emoji: '👨‍🍳' },
      { en: 'pilot', ipa: '/ˈpaɪlət/', vi: 'phi công', emoji: '👨‍✈️' },
      { en: 'singer', ipa: '/ˈsɪŋər/', vi: 'ca sĩ', emoji: '🎤' },
      { en: 'worker', ipa: '/ˈwɜːrkər/', vi: 'công nhân', emoji: '👷' },
      { en: 'driver', ipa: '/ˈdraɪvər/', vi: 'tài xế', emoji: '🚗' },
      { en: 'artist', ipa: '/ˈɑːrtɪst/', vi: 'hoạ sĩ', emoji: '🎨' },
      { en: 'scientist', ipa: '/ˈsaɪəntɪst/', vi: 'nhà khoa học', emoji: '🔬' },
      { en: 'engineer', ipa: '/ˌendʒɪˈnɪr/', vi: 'kỹ sư', emoji: '👷' },
      { en: 'soldier', ipa: '/ˈsoʊldʒər/', vi: 'bộ đội', emoji: '💂' },
      { en: 'vet', ipa: '/vet/', vi: 'bác sĩ thú y', emoji: '🐾' },
      { en: 'astronaut', ipa: '/ˈæstrənɔːt/', vi: 'phi hành gia', emoji: '👨‍🚀' },
      { en: 'lawyer', ipa: '/ˈlɔːjər/', vi: 'luật sư', emoji: '⚖️' },
      { en: 'waiter', ipa: '/ˈweɪtər/', vi: 'bồi bàn', emoji: '🧑‍🍳' },
      { en: 'cashier', ipa: '/kæˈʃɪr/', vi: 'thu ngân', emoji: '💵' },
      { en: 'barber', ipa: '/ˈbɑːrbər/', vi: 'thợ cắt tóc', emoji: '💈' },
      { en: 'tailor', ipa: '/ˈteɪlər/', vi: 'thợ may', emoji: '🧵' },
      { en: 'plumber', ipa: '/ˈplʌmər/', vi: 'thợ sửa ống nước', emoji: '🔧' },
      { en: 'carpenter', ipa: '/ˈkɑːrpəntər/', vi: 'thợ mộc', emoji: '🪚' },
      { en: 'photographer', ipa: '/fəˈtɑːɡrəfər/', vi: 'nhiếp ảnh gia', emoji: '📷' },
      { en: 'actor', ipa: '/ˈæktər/', vi: 'diễn viên', emoji: '🎭' },
      { en: 'magician', ipa: '/məˈdʒɪʃn/', vi: 'ảo thuật gia', emoji: '🎩' },
      { en: 'sailor', ipa: '/ˈseɪlər/', vi: 'thuỷ thủ', emoji: '⚓' },
      { en: 'mechanic', ipa: '/məˈkænɪk/', vi: 'thợ máy', emoji: '🔧' },
      { en: 'postman', ipa: '/ˈpoʊstmən/', vi: 'người đưa thư', emoji: '📮' },
    ],
  },
  {
    slug: 'hinh-khoi',
    emoji: '🔷',
    heading: 'Hình khối',
    title: 'Từ vựng tiếng Anh chủ đề hình khối cho bé',
    description:
      'Học từ vựng hình khối tiếng Anh cho bé: circle, square, triangle, star… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Xung quanh bé có rất nhiều hình dạng. Cùng học tên các hình bằng tiếng Anh và tìm đồ vật có hình tương ứng trong nhà nhé.',
    words: [
      { en: 'circle', ipa: '/ˈsɜːrkl/', vi: 'hình tròn', emoji: '⭕' },
      { en: 'square', ipa: '/skwer/', vi: 'hình vuông', emoji: '🟦' },
      { en: 'triangle', ipa: '/ˈtraɪæŋɡl/', vi: 'hình tam giác', emoji: '🔺' },
      { en: 'rectangle', ipa: '/ˈrektæŋɡl/', vi: 'hình chữ nhật', emoji: '▬' },
      { en: 'star', ipa: '/stɑːr/', vi: 'hình ngôi sao', emoji: '⭐' },
      { en: 'heart', ipa: '/hɑːrt/', vi: 'hình trái tim', emoji: '❤️' },
      { en: 'diamond', ipa: '/ˈdaɪəmənd/', vi: 'hình thoi', emoji: '🔷' },
      { en: 'oval', ipa: '/ˈoʊvl/', vi: 'hình bầu dục', emoji: '🥚' },
      { en: 'pentagon', ipa: '/ˈpentəɡɑːn/', vi: 'hình ngũ giác', emoji: '⬠' },
      { en: 'hexagon', ipa: '/ˈheksəɡɑːn/', vi: 'hình lục giác', emoji: '⬡' },
      { en: 'cube', ipa: '/kjuːb/', vi: 'hình lập phương', emoji: '🧊' },
      { en: 'cone', ipa: '/koʊn/', vi: 'hình nón', emoji: '🍦' },
      { en: 'cylinder', ipa: '/ˈsɪlɪndər/', vi: 'hình trụ', emoji: '🥫' },
      { en: 'sphere', ipa: '/sfɪr/', vi: 'hình cầu', emoji: '🔴' },
      { en: 'arrow', ipa: '/ˈæroʊ/', vi: 'mũi tên', emoji: '➡️' },
      { en: 'crescent', ipa: '/ˈkresnt/', vi: 'hình trăng lưỡi liềm', emoji: '🌙' },
      { en: 'semicircle', ipa: '/ˈsemisɜːrkl/', vi: 'nửa hình tròn', emoji: '◗' },
      { en: 'cross', ipa: '/krɔːs/', vi: 'hình chữ thập', emoji: '✝️' },
      { en: 'spiral', ipa: '/ˈspaɪrəl/', vi: 'hình xoắn ốc', emoji: '🌀' },
      { en: 'zigzag', ipa: '/ˈzɪɡzæɡ/', vi: 'hình zíc zắc', emoji: '⚡' },
    ],
  },
  {
    slug: 'do-trong-nha',
    emoji: '🏠',
    heading: 'Đồ vật trong nhà',
    title: 'Từ vựng tiếng Anh chủ đề đồ vật trong nhà',
    description:
      'Học từ vựng đồ vật trong nhà tiếng Anh cho bé: table, chair, bed, door… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Đi một vòng quanh nhà cùng bé và gọi tên đồ vật bằng tiếng Anh. Vừa chỉ vừa đọc để bé ghi nhớ tự nhiên nhất.',
    words: [
      { en: 'table', ipa: '/ˈteɪbl/', vi: 'cái bàn', emoji: '🪑' },
      { en: 'chair', ipa: '/tʃer/', vi: 'cái ghế', emoji: '🪑' },
      { en: 'bed', ipa: '/bed/', vi: 'cái giường', emoji: '🛏️' },
      { en: 'sofa', ipa: '/ˈsoʊfə/', vi: 'ghế sô pha', emoji: '🛋️' },
      { en: 'door', ipa: '/dɔːr/', vi: 'cửa ra vào', emoji: '🚪' },
      { en: 'window', ipa: '/ˈwɪndoʊ/', vi: 'cửa sổ', emoji: '🪟' },
      { en: 'clock', ipa: '/klɑːk/', vi: 'đồng hồ', emoji: '🕐' },
      { en: 'lamp', ipa: '/læmp/', vi: 'đèn', emoji: '💡' },
      { en: 'television', ipa: '/ˈtelɪvɪʒn/', vi: 'ti vi', emoji: '📺' },
      { en: 'fan', ipa: '/fæn/', vi: 'quạt', emoji: '🌀' },
      { en: 'fridge', ipa: '/frɪdʒ/', vi: 'tủ lạnh', emoji: '🧊' },
      { en: 'mirror', ipa: '/ˈmɪrər/', vi: 'gương', emoji: '🪞' },
      { en: 'key', ipa: '/kiː/', vi: 'chìa khoá', emoji: '🔑' },
      { en: 'pillow', ipa: '/ˈpɪloʊ/', vi: 'cái gối', emoji: '🛏️' },
      { en: 'towel', ipa: '/ˈtaʊəl/', vi: 'khăn tắm', emoji: '🧻' },
      { en: 'cup', ipa: '/kʌp/', vi: 'cái cốc', emoji: '☕' },
      { en: 'bowl', ipa: '/boʊl/', vi: 'cái bát', emoji: '🥣' },
      { en: 'spoon', ipa: '/spuːn/', vi: 'cái thìa', emoji: '🥄' },
      { en: 'fork', ipa: '/fɔːrk/', vi: 'cái nĩa', emoji: '🍴' },
      { en: 'plate', ipa: '/pleɪt/', vi: 'cái đĩa', emoji: '🍽️' },
      { en: 'carpet', ipa: '/ˈkɑːrpət/', vi: 'tấm thảm', emoji: '🟫' },
      { en: 'curtain', ipa: '/ˈkɜːrtn/', vi: 'rèm cửa', emoji: '🪟' },
      { en: 'blanket', ipa: '/ˈblæŋkɪt/', vi: 'cái chăn', emoji: '🛏️' },
      { en: 'shelf', ipa: '/ʃelf/', vi: 'cái kệ', emoji: '📚' },
      { en: 'drawer', ipa: '/drɔːr/', vi: 'ngăn kéo', emoji: '🗄️' },
      { en: 'wardrobe', ipa: '/ˈwɔːrdroʊb/', vi: 'tủ quần áo', emoji: '🚪' },
      { en: 'vase', ipa: '/veɪs/', vi: 'lọ hoa', emoji: '🏺' },
      { en: 'basket', ipa: '/ˈbæskɪt/', vi: 'cái giỏ', emoji: '🧺' },
      { en: 'broom', ipa: '/bruːm/', vi: 'cái chổi', emoji: '🧹' },
      { en: 'bucket', ipa: '/ˈbʌkɪt/', vi: 'cái xô', emoji: '🪣' },
    ],
  },
  {
    slug: 'dong-vat-bien',
    emoji: '🐬',
    heading: 'Động vật biển',
    title: 'Từ vựng tiếng Anh chủ đề động vật biển',
    description:
      'Học từ vựng động vật biển tiếng Anh cho bé: fish, crab, dolphin, whale… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Dưới biển sâu có rất nhiều bạn thú thú vị. Cùng khám phá và gọi tên các loài động vật biển bằng tiếng Anh nhé.',
    words: [
      { en: 'fish', ipa: '/fɪʃ/', vi: 'con cá', emoji: '🐠' },
      { en: 'crab', ipa: '/kræb/', vi: 'con cua', emoji: '🦀' },
      { en: 'octopus', ipa: '/ˈɑːktəpʊs/', vi: 'bạch tuộc', emoji: '🐙' },
      { en: 'dolphin', ipa: '/ˈdɑːlfɪn/', vi: 'cá heo', emoji: '🐬' },
      { en: 'whale', ipa: '/weɪl/', vi: 'cá voi', emoji: '🐳' },
      { en: 'shark', ipa: '/ʃɑːrk/', vi: 'cá mập', emoji: '🦈' },
      { en: 'turtle', ipa: '/ˈtɜːrtl/', vi: 'con rùa', emoji: '🐢' },
      { en: 'starfish', ipa: '/ˈstɑːrfɪʃ/', vi: 'sao biển', emoji: '⭐' },
      { en: 'shrimp', ipa: '/ʃrɪmp/', vi: 'con tôm', emoji: '🦐' },
      { en: 'lobster', ipa: '/ˈlɑːbstər/', vi: 'tôm hùm', emoji: '🦞' },
      { en: 'seahorse', ipa: '/ˈsiːhɔːrs/', vi: 'cá ngựa', emoji: '🐴' },
      { en: 'jellyfish', ipa: '/ˈdʒelifɪʃ/', vi: 'con sứa', emoji: '🪼' },
      { en: 'seal', ipa: '/siːl/', vi: 'hải cẩu', emoji: '🦭' },
      { en: 'squid', ipa: '/skwɪd/', vi: 'con mực', emoji: '🦑' },
      { en: 'penguin', ipa: '/ˈpeŋɡwɪn/', vi: 'chim cánh cụt', emoji: '🐧' },
      { en: 'coral', ipa: '/ˈkɔːrəl/', vi: 'san hô', emoji: '🪸' },
      { en: 'clam', ipa: '/klæm/', vi: 'con nghêu', emoji: '🦪' },
      { en: 'oyster', ipa: '/ˈɔɪstər/', vi: 'con hàu', emoji: '🦪' },
      { en: 'seaweed', ipa: '/ˈsiːwiːd/', vi: 'rong biển', emoji: '🌿' },
      { en: 'eel', ipa: '/iːl/', vi: 'con lươn', emoji: '🐍' },
      { en: 'stingray', ipa: '/ˈstɪŋreɪ/', vi: 'cá đuối', emoji: '🐟' },
      { en: 'walrus', ipa: '/ˈwɔːlrəs/', vi: 'hải mã', emoji: '🦭' },
      { en: 'otter', ipa: '/ˈɑːtər/', vi: 'rái cá', emoji: '🦦' },
      { en: 'sea lion', ipa: '/siː ˈlaɪən/', vi: 'sư tử biển', emoji: '🦭' },
    ],
  },
  {
    slug: 'con-trung',
    emoji: '🐝',
    heading: 'Côn trùng',
    title: 'Từ vựng tiếng Anh chủ đề côn trùng cho bé',
    description:
      'Học từ vựng côn trùng tiếng Anh cho bé: bee, ant, butterfly, spider… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Trong vườn nhà có nhiều bạn côn trùng nhỏ xíu. Cùng học tên chúng bằng tiếng Anh và quan sát chúng bay, bò thật vui nhé.',
    words: [
      { en: 'bee', ipa: '/biː/', vi: 'con ong', emoji: '🐝' },
      { en: 'ant', ipa: '/ænt/', vi: 'con kiến', emoji: '🐜' },
      { en: 'butterfly', ipa: '/ˈbʌtərflaɪ/', vi: 'con bướm', emoji: '🦋' },
      { en: 'spider', ipa: '/ˈspaɪdər/', vi: 'con nhện', emoji: '🕷️' },
      { en: 'ladybug', ipa: '/ˈleɪdibʌɡ/', vi: 'bọ rùa', emoji: '🐞' },
      { en: 'fly', ipa: '/flaɪ/', vi: 'con ruồi', emoji: '🪰' },
      { en: 'mosquito', ipa: '/məˈskiːtoʊ/', vi: 'con muỗi', emoji: '🦟' },
      { en: 'snail', ipa: '/sneɪl/', vi: 'con ốc sên', emoji: '🐌' },
      { en: 'grasshopper', ipa: '/ˈɡræshɑːpər/', vi: 'châu chấu', emoji: '🦗' },
      { en: 'worm', ipa: '/wɜːrm/', vi: 'con giun', emoji: '🪱' },
      { en: 'dragonfly', ipa: '/ˈdræɡənflaɪ/', vi: 'chuồn chuồn', emoji: '🪰' },
      { en: 'caterpillar', ipa: '/ˈkætərpɪlər/', vi: 'sâu bướm', emoji: '🐛' },
      { en: 'beetle', ipa: '/ˈbiːtl/', vi: 'bọ cánh cứng', emoji: '🪲' },
      { en: 'cricket', ipa: '/ˈkrɪkɪt/', vi: 'con dế', emoji: '🦗' },
      { en: 'firefly', ipa: '/ˈfaɪərflaɪ/', vi: 'đom đóm', emoji: '✨' },
      { en: 'wasp', ipa: '/wɑːsp/', vi: 'ong bắp cày', emoji: '🐝' },
      { en: 'moth', ipa: '/mɔːθ/', vi: 'bướm đêm', emoji: '🦋' },
      { en: 'cockroach', ipa: '/ˈkɑːkroʊtʃ/', vi: 'con gián', emoji: '🪳' },
      { en: 'centipede', ipa: '/ˈsentɪpiːd/', vi: 'con rết', emoji: '🐛' },
      { en: 'scorpion', ipa: '/ˈskɔːrpiən/', vi: 'bọ cạp', emoji: '🦂' },
      { en: 'termite', ipa: '/ˈtɜːrmaɪt/', vi: 'con mối', emoji: '🐜' },
      { en: 'flea', ipa: '/fliː/', vi: 'con bọ chét', emoji: '🦟' },
      { en: 'mantis', ipa: '/ˈmæntɪs/', vi: 'bọ ngựa', emoji: '🦗' },
    ],
  },
  {
    slug: 'the-thao',
    emoji: '⚽',
    heading: 'Thể thao',
    title: 'Từ vựng tiếng Anh chủ đề thể thao cho bé',
    description:
      'Học từ vựng thể thao tiếng Anh cho bé: football, swimming, running, tennis… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Vận động giúp bé khoẻ mạnh và vui vẻ. Cùng học tên các môn thể thao bằng tiếng Anh và kể xem bé thích chơi môn nào nhất nhé.',
    words: [
      { en: 'football', ipa: '/ˈfʊtbɔːl/', vi: 'bóng đá', emoji: '⚽' },
      { en: 'basketball', ipa: '/ˈbæskɪtbɔːl/', vi: 'bóng rổ', emoji: '🏀' },
      { en: 'volleyball', ipa: '/ˈvɑːlibɔːl/', vi: 'bóng chuyền', emoji: '🏐' },
      { en: 'tennis', ipa: '/ˈtenɪs/', vi: 'quần vợt', emoji: '🎾' },
      { en: 'badminton', ipa: '/ˈbædmɪntən/', vi: 'cầu lông', emoji: '🏸' },
      { en: 'swimming', ipa: '/ˈswɪmɪŋ/', vi: 'bơi lội', emoji: '🏊' },
      { en: 'running', ipa: '/ˈrʌnɪŋ/', vi: 'chạy bộ', emoji: '🏃' },
      { en: 'cycling', ipa: '/ˈsaɪklɪŋ/', vi: 'đạp xe', emoji: '🚴' },
      { en: 'dancing', ipa: '/ˈdænsɪŋ/', vi: 'nhảy múa', emoji: '💃' },
      { en: 'skating', ipa: '/ˈskeɪtɪŋ/', vi: 'trượt patin', emoji: '⛸️' },
      { en: 'jumping', ipa: '/ˈdʒʌmpɪŋ/', vi: 'nhảy cao', emoji: '🤸' },
      { en: 'boxing', ipa: '/ˈbɑːksɪŋ/', vi: 'quyền anh', emoji: '🥊' },
      { en: 'karate', ipa: '/kəˈrɑːti/', vi: 'karate', emoji: '🥋' },
      { en: 'golf', ipa: '/ɡɑːlf/', vi: 'gôn', emoji: '⛳' },
      { en: 'skiing', ipa: '/ˈskiːɪŋ/', vi: 'trượt tuyết', emoji: '⛷️' },
      { en: 'yoga', ipa: '/ˈjoʊɡə/', vi: 'yoga', emoji: '🧘' },
      { en: 'table tennis', ipa: '/ˈteɪbl tenɪs/', vi: 'bóng bàn', emoji: '🏓' },
      { en: 'baseball', ipa: '/ˈbeɪsbɔːl/', vi: 'bóng chày', emoji: '⚾' },
      { en: 'hockey', ipa: '/ˈhɑːki/', vi: 'khúc côn cầu', emoji: '🏒' },
      { en: 'rugby', ipa: '/ˈrʌɡbi/', vi: 'bóng bầu dục', emoji: '🏉' },
      { en: 'wrestling', ipa: '/ˈreslɪŋ/', vi: 'đấu vật', emoji: '🤼' },
      { en: 'judo', ipa: '/ˈdʒuːdoʊ/', vi: 'võ judo', emoji: '🥋' },
      { en: 'gymnastics', ipa: '/dʒɪmˈnæstɪks/', vi: 'thể dục dụng cụ', emoji: '🤸' },
      { en: 'archery', ipa: '/ˈɑːrtʃəri/', vi: 'bắn cung', emoji: '🏹' },
      { en: 'surfing', ipa: '/ˈsɜːrfɪŋ/', vi: 'lướt sóng', emoji: '🏄' },
      { en: 'diving', ipa: '/ˈdaɪvɪŋ/', vi: 'lặn', emoji: '🤿' },
      { en: 'climbing', ipa: '/ˈklaɪmɪŋ/', vi: 'leo núi', emoji: '🧗' },
      { en: 'bowling', ipa: '/ˈboʊlɪŋ/', vi: 'bowling', emoji: '🎳' },
    ],
  },
  {
    slug: 'cam-xuc',
    emoji: '😀',
    heading: 'Cảm xúc',
    title: 'Từ vựng tiếng Anh chủ đề cảm xúc cho bé',
    description:
      'Học từ vựng cảm xúc tiếng Anh cho bé: happy, sad, angry, scared… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Học gọi tên cảm xúc giúp bé hiểu bản thân và bạn bè hơn. Cùng học các từ chỉ cảm xúc bằng tiếng Anh và làm mặt biểu cảm cho vui nhé.',
    words: [
      { en: 'happy', ipa: '/ˈhæpi/', vi: 'vui vẻ', emoji: '😀', example: 'I am happy.', exampleVi: 'Con vui.' },
      { en: 'sad', ipa: '/sæd/', vi: 'buồn', emoji: '😢' },
      { en: 'angry', ipa: '/ˈæŋɡri/', vi: 'tức giận', emoji: '😠' },
      { en: 'scared', ipa: '/skerd/', vi: 'sợ hãi', emoji: '😨' },
      { en: 'tired', ipa: '/ˈtaɪərd/', vi: 'mệt mỏi', emoji: '😫' },
      { en: 'sleepy', ipa: '/ˈsliːpi/', vi: 'buồn ngủ', emoji: '😴' },
      { en: 'hungry', ipa: '/ˈhʌŋɡri/', vi: 'đói', emoji: '😋' },
      { en: 'surprised', ipa: '/sərˈpraɪzd/', vi: 'ngạc nhiên', emoji: '😲' },
      { en: 'shy', ipa: '/ʃaɪ/', vi: 'ngại ngùng', emoji: '😳' },
      { en: 'excited', ipa: '/ɪkˈsaɪtɪd/', vi: 'phấn khích', emoji: '🤩' },
      { en: 'bored', ipa: '/bɔːrd/', vi: 'chán', emoji: '🥱' },
      { en: 'proud', ipa: '/praʊd/', vi: 'tự hào', emoji: '😌' },
      { en: 'nervous', ipa: '/ˈnɜːrvəs/', vi: 'lo lắng', emoji: '😰' },
      { en: 'brave', ipa: '/breɪv/', vi: 'dũng cảm', emoji: '💪' },
      { en: 'love', ipa: '/lʌv/', vi: 'yêu thương', emoji: '🥰' },
      { en: 'worried', ipa: '/ˈwɜːrid/', vi: 'lo lắng', emoji: '😟' },
      { en: 'jealous', ipa: '/ˈdʒeləs/', vi: 'ghen tị', emoji: '😒' },
      { en: 'confused', ipa: '/kənˈfjuːzd/', vi: 'bối rối', emoji: '😕' },
      { en: 'calm', ipa: '/kɑːm/', vi: 'bình tĩnh', emoji: '😌' },
      { en: 'lonely', ipa: '/ˈloʊnli/', vi: 'cô đơn', emoji: '😔' },
      { en: 'curious', ipa: '/ˈkjʊriəs/', vi: 'tò mò', emoji: '🤨' },
    ],
  },
  {
    slug: 'thien-nhien',
    emoji: '🌳',
    heading: 'Thiên nhiên',
    title: 'Từ vựng tiếng Anh chủ đề thiên nhiên cho bé',
    description:
      'Học từ vựng thiên nhiên tiếng Anh cho bé: sun, moon, tree, flower… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Thiên nhiên quanh ta thật đẹp. Cùng học tên mặt trời, mặt trăng, cây cối, hoa lá bằng tiếng Anh trong mỗi chuyến đi chơi nhé.',
    words: [
      { en: 'sun', ipa: '/sʌn/', vi: 'mặt trời', emoji: '☀️' },
      { en: 'moon', ipa: '/muːn/', vi: 'mặt trăng', emoji: '🌙' },
      { en: 'star', ipa: '/stɑːr/', vi: 'ngôi sao', emoji: '⭐' },
      { en: 'sky', ipa: '/skaɪ/', vi: 'bầu trời', emoji: '🌌' },
      { en: 'tree', ipa: '/triː/', vi: 'cái cây', emoji: '🌳' },
      { en: 'flower', ipa: '/ˈflaʊər/', vi: 'bông hoa', emoji: '🌸' },
      { en: 'grass', ipa: '/ɡræs/', vi: 'cỏ', emoji: '🌿' },
      { en: 'leaf', ipa: '/liːf/', vi: 'chiếc lá', emoji: '🍃' },
      { en: 'mountain', ipa: '/ˈmaʊntn/', vi: 'ngọn núi', emoji: '⛰️' },
      { en: 'hill', ipa: '/hɪl/', vi: 'ngọn đồi', emoji: '🏞️' },
      { en: 'river', ipa: '/ˈrɪvər/', vi: 'dòng sông', emoji: '🏞️' },
      { en: 'lake', ipa: '/leɪk/', vi: 'hồ nước', emoji: '🏕️' },
      { en: 'sea', ipa: '/siː/', vi: 'biển', emoji: '🌊' },
      { en: 'beach', ipa: '/biːtʃ/', vi: 'bãi biển', emoji: '🏖️' },
      { en: 'forest', ipa: '/ˈfɔːrɪst/', vi: 'rừng', emoji: '🌲' },
      { en: 'island', ipa: '/ˈaɪlənd/', vi: 'hòn đảo', emoji: '🏝️' },
      { en: 'cloud', ipa: '/klaʊd/', vi: 'đám mây', emoji: '☁️' },
      { en: 'rain', ipa: '/reɪn/', vi: 'mưa', emoji: '🌧️' },
      { en: 'stone', ipa: '/stoʊn/', vi: 'hòn đá', emoji: '🪨' },
      { en: 'sand', ipa: '/sænd/', vi: 'cát', emoji: '🏖️' },
      { en: 'valley', ipa: '/ˈvæli/', vi: 'thung lũng', emoji: '🏞️' },
      { en: 'waterfall', ipa: '/ˈwɔːtərfɔːl/', vi: 'thác nước', emoji: '💦' },
      { en: 'cave', ipa: '/keɪv/', vi: 'hang động', emoji: '🕳️' },
      { en: 'desert', ipa: '/ˈdezərt/', vi: 'sa mạc', emoji: '🏜️' },
      { en: 'volcano', ipa: '/vɑːlˈkeɪnoʊ/', vi: 'núi lửa', emoji: '🌋' },
      { en: 'jungle', ipa: '/ˈdʒʌŋɡl/', vi: 'rừng rậm', emoji: '🌴' },
      { en: 'pond', ipa: '/pɑːnd/', vi: 'cái ao', emoji: '🦆' },
      { en: 'rock', ipa: '/rɑːk/', vi: 'tảng đá', emoji: '🪨' },
      { en: 'path', ipa: '/pæθ/', vi: 'lối đi', emoji: '🛤️' },
      { en: 'cliff', ipa: '/klɪf/', vi: 'vách đá', emoji: '⛰️' },
    ],
  },
  {
    slug: 'do-choi',
    emoji: '🧸',
    heading: 'Đồ chơi',
    title: 'Từ vựng tiếng Anh chủ đề đồ chơi cho bé',
    description:
      'Học từ vựng đồ chơi tiếng Anh cho bé: ball, doll, teddy bear, kite… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Đồ chơi là người bạn thân của bé. Cùng học tên các món đồ chơi bằng tiếng Anh và kể xem bé thích chơi món nào nhất nhé.',
    words: [
      { en: 'ball', ipa: '/bɔːl/', vi: 'quả bóng', emoji: '⚽' },
      { en: 'doll', ipa: '/dɑːl/', vi: 'búp bê', emoji: '🪆' },
      { en: 'teddy bear', ipa: '/ˈtedi ber/', vi: 'gấu bông', emoji: '🧸' },
      { en: 'car', ipa: '/kɑːr/', vi: 'xe đồ chơi', emoji: '🚗' },
      { en: 'kite', ipa: '/kaɪt/', vi: 'cái diều', emoji: '🪁' },
      { en: 'balloon', ipa: '/bəˈluːn/', vi: 'bong bóng', emoji: '🎈' },
      { en: 'blocks', ipa: '/blɑːks/', vi: 'khối xếp hình', emoji: '🧱' },
      { en: 'puzzle', ipa: '/ˈpʌzl/', vi: 'trò ghép hình', emoji: '🧩' },
      { en: 'robot', ipa: '/ˈroʊbɑːt/', vi: 'người máy', emoji: '🤖' },
      { en: 'drum', ipa: '/drʌm/', vi: 'cái trống', emoji: '🥁' },
      { en: 'yo-yo', ipa: '/ˈjoʊjoʊ/', vi: 'con quay yo-yo', emoji: '🪀' },
      { en: 'top', ipa: '/tɑːp/', vi: 'con quay', emoji: '🌀' },
      { en: 'marble', ipa: '/ˈmɑːrbl/', vi: 'viên bi', emoji: '🔮' },
      { en: 'water gun', ipa: '/ˈwɔːtər ɡʌn/', vi: 'súng nước', emoji: '🔫' },
      { en: 'bubble', ipa: '/ˈbʌbl/', vi: 'bong bóng xà phòng', emoji: '🫧' },
      { en: 'slime', ipa: '/slaɪm/', vi: 'chất nhờn slime', emoji: '🟢' },
      { en: 'board game', ipa: '/bɔːrd ɡeɪm/', vi: 'trò chơi cờ', emoji: '🎲' },
      { en: 'toy train', ipa: '/tɔɪ treɪn/', vi: 'tàu hoả đồ chơi', emoji: '🚂' },
      { en: 'rocking horse', ipa: '/ˈrɑːkɪŋ hɔːrs/', vi: 'ngựa bập bênh', emoji: '🎠' },
      { en: 'whistle', ipa: '/ˈwɪsl/', vi: 'cái còi', emoji: '🎵' },
      { en: 'sticker', ipa: '/ˈstɪkər/', vi: 'hình dán', emoji: '🏷️' },
      { en: 'dice', ipa: '/daɪs/', vi: 'xúc xắc', emoji: '🎲' },
    ],
  },
  {
    slug: 'ngay-thang',
    emoji: '📅',
    heading: 'Ngày, tháng & thời gian',
    title: 'Từ vựng tiếng Anh: ngày, tháng, thời gian',
    description:
      'Học các ngày trong tuần và tháng trong năm bằng tiếng Anh cho bé: Monday, Sunday, January… kèm phiên âm và phát âm chuẩn.',
    intro:
      'Thứ mấy rồi nhỉ? Cùng học tên các ngày trong tuần và tháng trong năm bằng tiếng Anh để bé biết đọc lịch và trả lời "What day is it today?".',
    words: [
      { en: 'Monday', ipa: '/ˈmʌndeɪ/', vi: 'thứ Hai', emoji: '📅' },
      { en: 'Tuesday', ipa: '/ˈtuːzdeɪ/', vi: 'thứ Ba', emoji: '📅' },
      { en: 'Wednesday', ipa: '/ˈwenzdeɪ/', vi: 'thứ Tư', emoji: '📅' },
      { en: 'Thursday', ipa: '/ˈθɜːrzdeɪ/', vi: 'thứ Năm', emoji: '📅' },
      { en: 'Friday', ipa: '/ˈfraɪdeɪ/', vi: 'thứ Sáu', emoji: '📅' },
      { en: 'Saturday', ipa: '/ˈsætərdeɪ/', vi: 'thứ Bảy', emoji: '📅' },
      { en: 'Sunday', ipa: '/ˈsʌndeɪ/', vi: 'Chủ nhật', emoji: '📅' },
      { en: 'today', ipa: '/təˈdeɪ/', vi: 'hôm nay', emoji: '⭐' },
      { en: 'tomorrow', ipa: '/təˈmɔːroʊ/', vi: 'ngày mai', emoji: '➡️' },
      { en: 'yesterday', ipa: '/ˈjestərdeɪ/', vi: 'hôm qua', emoji: '⬅️' },
      { en: 'morning', ipa: '/ˈmɔːrnɪŋ/', vi: 'buổi sáng', emoji: '🌅' },
      { en: 'afternoon', ipa: '/ˌæftərˈnuːn/', vi: 'buổi chiều', emoji: '🌤️' },
      { en: 'evening', ipa: '/ˈiːvnɪŋ/', vi: 'buổi tối', emoji: '🌆' },
      { en: 'night', ipa: '/naɪt/', vi: 'ban đêm', emoji: '🌙' },
      { en: 'week', ipa: '/wiːk/', vi: 'tuần', emoji: '🗓️' },
      { en: 'month', ipa: '/mʌnθ/', vi: 'tháng', emoji: '📆' },
      { en: 'year', ipa: '/jɪr/', vi: 'năm', emoji: '🎊' },
    ],
  },
  {
    slug: 'hanh-dong',
    emoji: '🏃',
    heading: 'Hành động (động từ)',
    title: 'Từ vựng tiếng Anh chủ đề hành động cho bé',
    description:
      'Học động từ hành động tiếng Anh cho bé: run, jump, eat, sleep… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Vừa học vừa làm động tác giúp bé nhớ động từ nhanh nhất. Bé nghe từ nào thì làm hành động đó — "Jump! Run! Clap!" thật vui nhé.',
    words: [
      { en: 'run', ipa: '/rʌn/', vi: 'chạy', emoji: '🏃', example: 'I can run.', exampleVi: 'Con biết chạy.' },
      { en: 'walk', ipa: '/wɔːk/', vi: 'đi bộ', emoji: '🚶' },
      { en: 'jump', ipa: '/dʒʌmp/', vi: 'nhảy', emoji: '🤾' },
      { en: 'eat', ipa: '/iːt/', vi: 'ăn', emoji: '🍽️' },
      { en: 'drink', ipa: '/drɪŋk/', vi: 'uống', emoji: '🥤' },
      { en: 'sleep', ipa: '/sliːp/', vi: 'ngủ', emoji: '😴' },
      { en: 'read', ipa: '/riːd/', vi: 'đọc', emoji: '📖' },
      { en: 'write', ipa: '/raɪt/', vi: 'viết', emoji: '✍️' },
      { en: 'sing', ipa: '/sɪŋ/', vi: 'hát', emoji: '🎤' },
      { en: 'dance', ipa: '/dæns/', vi: 'nhảy múa', emoji: '💃' },
      { en: 'draw', ipa: '/drɔː/', vi: 'vẽ', emoji: '🎨' },
      { en: 'play', ipa: '/pleɪ/', vi: 'chơi', emoji: '🧸' },
      { en: 'swim', ipa: '/swɪm/', vi: 'bơi', emoji: '🏊' },
      { en: 'sit', ipa: '/sɪt/', vi: 'ngồi', emoji: '🪑' },
      { en: 'stand', ipa: '/stænd/', vi: 'đứng', emoji: '🧍' },
      { en: 'open', ipa: '/ˈoʊpən/', vi: 'mở', emoji: '📂' },
      { en: 'close', ipa: '/kloʊz/', vi: 'đóng', emoji: '📁' },
      { en: 'listen', ipa: '/ˈlɪsn/', vi: 'lắng nghe', emoji: '👂' },
      { en: 'clap', ipa: '/klæp/', vi: 'vỗ tay', emoji: '👏' },
      { en: 'smile', ipa: '/smaɪl/', vi: 'mỉm cười', emoji: '😊' },
      { en: 'cry', ipa: '/kraɪ/', vi: 'khóc', emoji: '😭' },
      { en: 'laugh', ipa: '/læf/', vi: 'cười to', emoji: '😄' },
      { en: 'think', ipa: '/θɪŋk/', vi: 'suy nghĩ', emoji: '🤔' },
      { en: 'help', ipa: '/help/', vi: 'giúp đỡ', emoji: '🤝' },
      { en: 'wait', ipa: '/weɪt/', vi: 'chờ đợi', emoji: '⏳' },
      { en: 'look', ipa: '/lʊk/', vi: 'nhìn', emoji: '👀' },
      { en: 'give', ipa: '/ɡɪv/', vi: 'đưa, tặng', emoji: '🎁' },
      { en: 'take', ipa: '/teɪk/', vi: 'lấy', emoji: '🤲' },
      { en: 'throw', ipa: '/θroʊ/', vi: 'ném', emoji: '🤾' },
      { en: 'catch', ipa: '/kætʃ/', vi: 'bắt', emoji: '🧤' },
      { en: 'push', ipa: '/pʊʃ/', vi: 'đẩy', emoji: '👐' },
      { en: 'pull', ipa: '/pʊl/', vi: 'kéo', emoji: '🪢' },
      { en: 'kick', ipa: '/kɪk/', vi: 'đá', emoji: '⚽' },
      { en: 'fix', ipa: '/fɪks/', vi: 'sửa chữa', emoji: '🔧' },
    ],
  },
  {
    slug: 'chao-hoi',
    emoji: '👋',
    heading: 'Chào hỏi & lịch sự',
    title: 'Từ vựng tiếng Anh chào hỏi, lịch sự cho bé',
    description:
      'Học các câu chào hỏi và từ lịch sự tiếng Anh cho bé: hello, thank you, please, sorry… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Chào hỏi và nói lời lịch sự là bài học đầu tiên khi bé giao tiếp tiếng Anh. Cùng bé tập nói "Hello", "Thank you", "Sorry" mỗi ngày để trở thành em bé ngoan và tự tin nhé.',
    words: [
      { en: 'hello', ipa: '/həˈloʊ/', vi: 'xin chào', emoji: '👋', example: 'Hello, teacher!', exampleVi: 'Chào cô ạ!' },
      { en: 'hi', ipa: '/haɪ/', vi: 'chào', emoji: '🙋' },
      { en: 'goodbye', ipa: '/ˌɡʊdˈbaɪ/', vi: 'tạm biệt', emoji: '👋' },
      { en: 'thank you', ipa: '/ˈθæŋk juː/', vi: 'cảm ơn', emoji: '🙏' },
      { en: 'please', ipa: '/pliːz/', vi: 'làm ơn', emoji: '🙏' },
      { en: 'sorry', ipa: '/ˈsɑːri/', vi: 'xin lỗi', emoji: '😔' },
      { en: 'excuse me', ipa: '/ɪkˈskjuːz miː/', vi: 'xin lỗi (làm phiền)', emoji: '🙋' },
      { en: 'yes', ipa: '/jes/', vi: 'vâng, có', emoji: '✅' },
      { en: 'no', ipa: '/noʊ/', vi: 'không', emoji: '❌' },
      { en: 'welcome', ipa: '/ˈwelkəm/', vi: 'chào mừng', emoji: '🎉' },
      { en: 'good morning', ipa: '/ɡʊd ˈmɔːrnɪŋ/', vi: 'chào buổi sáng', emoji: '🌅' },
      { en: 'good night', ipa: '/ɡʊd naɪt/', vi: 'chúc ngủ ngon', emoji: '🌙' },
      { en: 'good afternoon', ipa: '/ɡʊd ˌæftərˈnuːn/', vi: 'chào buổi chiều', emoji: '🌤️' },
      { en: 'good evening', ipa: '/ɡʊd ˈiːvnɪŋ/', vi: 'chào buổi tối', emoji: '🌆' },
      { en: 'see you', ipa: '/siː juː/', vi: 'hẹn gặp lại', emoji: '👋' },
      { en: 'how are you', ipa: '/haʊ ɑːr juː/', vi: 'bạn khoẻ không', emoji: '🙂' },
      { en: 'fine', ipa: '/faɪn/', vi: 'khoẻ, ổn', emoji: '😊' },
      { en: 'nice to meet you', ipa: '/naɪs tə miːt juː/', vi: 'rất vui được gặp bạn', emoji: '🤝' },
      { en: 'congratulations', ipa: '/kənˌɡrætʃəˈleɪʃnz/', vi: 'chúc mừng', emoji: '🎉' },
      { en: 'happy birthday', ipa: '/ˈhæpi ˈbɜːrθdeɪ/', vi: 'chúc mừng sinh nhật', emoji: '🎂' },
    ],
  },
  {
    slug: 'dia-diem',
    emoji: '🏙️',
    heading: 'Địa điểm',
    title: 'Từ vựng tiếng Anh chủ đề địa điểm cho bé',
    description:
      'Học từ vựng địa điểm tiếng Anh cho bé: school, hospital, park, market… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Quanh khu phố của bé có rất nhiều nơi thú vị. Cùng học tên các địa điểm bằng tiếng Anh để bé biết mình đang ở đâu và sắp đi đâu nhé.',
    words: [
      { en: 'school', ipa: '/skuːl/', vi: 'trường học', emoji: '🏫', example: 'I go to school.', exampleVi: 'Con đi học.' },
      { en: 'hospital', ipa: '/ˈhɑːspɪtl/', vi: 'bệnh viện', emoji: '🏥' },
      { en: 'park', ipa: '/pɑːrk/', vi: 'công viên', emoji: '🏞️' },
      { en: 'market', ipa: '/ˈmɑːrkɪt/', vi: 'chợ', emoji: '🛒' },
      { en: 'supermarket', ipa: '/ˈsuːpərmɑːrkɪt/', vi: 'siêu thị', emoji: '🏬' },
      { en: 'zoo', ipa: '/zuː/', vi: 'sở thú', emoji: '🦁' },
      { en: 'library', ipa: '/ˈlaɪbreri/', vi: 'thư viện', emoji: '📚' },
      { en: 'restaurant', ipa: '/ˈrestrɑːnt/', vi: 'nhà hàng', emoji: '🍽️' },
      { en: 'bank', ipa: '/bæŋk/', vi: 'ngân hàng', emoji: '🏦' },
      { en: 'post office', ipa: '/ˈpoʊst ɔːfɪs/', vi: 'bưu điện', emoji: '📮' },
      { en: 'airport', ipa: '/ˈerpɔːrt/', vi: 'sân bay', emoji: '🛫' },
      { en: 'cinema', ipa: '/ˈsɪnəmə/', vi: 'rạp phim', emoji: '🎬' },
      { en: 'farm', ipa: '/fɑːrm/', vi: 'nông trại', emoji: '🚜' },
      { en: 'home', ipa: '/hoʊm/', vi: 'nhà', emoji: '🏠' },
      { en: 'church', ipa: '/tʃɜːrtʃ/', vi: 'nhà thờ', emoji: '⛪' },
      { en: 'temple', ipa: '/ˈtempl/', vi: 'ngôi chùa, đền', emoji: '🛕' },
      { en: 'museum', ipa: '/mjuˈziːəm/', vi: 'bảo tàng', emoji: '🏛️' },
      { en: 'station', ipa: '/ˈsteɪʃn/', vi: 'nhà ga', emoji: '🚉' },
      { en: 'bus stop', ipa: '/bʌs stɑːp/', vi: 'trạm xe buýt', emoji: '🚏' },
      { en: 'playground', ipa: '/ˈpleɪɡraʊnd/', vi: 'sân chơi', emoji: '🛝' },
      { en: 'swimming pool', ipa: '/ˈswɪmɪŋ puːl/', vi: 'hồ bơi', emoji: '🏊' },
      { en: 'hotel', ipa: '/hoʊˈtel/', vi: 'khách sạn', emoji: '🏨' },
      { en: 'factory', ipa: '/ˈfæktri/', vi: 'nhà máy', emoji: '🏭' },
      { en: 'stadium', ipa: '/ˈsteɪdiəm/', vi: 'sân vận động', emoji: '🏟️' },
      { en: 'bakery', ipa: '/ˈbeɪkəri/', vi: 'tiệm bánh', emoji: '🥐' },
      { en: 'pharmacy', ipa: '/ˈfɑːrməsi/', vi: 'nhà thuốc', emoji: '💊' },
      { en: 'gym', ipa: '/dʒɪm/', vi: 'phòng tập', emoji: '🏋️' },
    ],
  },
  {
    slug: 'phong-trong-nha',
    emoji: '🚪',
    heading: 'Phòng trong nhà',
    title: 'Từ vựng tiếng Anh các phòng trong nhà',
    description:
      'Học từ vựng các phòng trong nhà tiếng Anh cho bé: bedroom, kitchen, bathroom, garden… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Ngôi nhà của bé có những phòng nào? Cùng đi một vòng và gọi tên từng phòng bằng tiếng Anh để bé thuộc thật nhanh nhé.',
    words: [
      { en: 'living room', ipa: '/ˈlɪvɪŋ ruːm/', vi: 'phòng khách', emoji: '🛋️' },
      { en: 'bedroom', ipa: '/ˈbedruːm/', vi: 'phòng ngủ', emoji: '🛏️' },
      { en: 'kitchen', ipa: '/ˈkɪtʃɪn/', vi: 'nhà bếp', emoji: '🍳' },
      { en: 'bathroom', ipa: '/ˈbæθruːm/', vi: 'phòng tắm', emoji: '🛁' },
      { en: 'garden', ipa: '/ˈɡɑːrdn/', vi: 'khu vườn', emoji: '🌷' },
      { en: 'garage', ipa: '/ɡəˈrɑːʒ/', vi: 'nhà để xe', emoji: '🚗' },
      { en: 'stairs', ipa: '/sterz/', vi: 'cầu thang', emoji: '🪜' },
      { en: 'roof', ipa: '/ruːf/', vi: 'mái nhà', emoji: '🏠' },
      { en: 'wall', ipa: '/wɔːl/', vi: 'bức tường', emoji: '🧱' },
      { en: 'floor', ipa: '/flɔːr/', vi: 'sàn nhà', emoji: '🔲' },
      { en: 'gate', ipa: '/ɡeɪt/', vi: 'cổng', emoji: '🚪' },
      { en: 'yard', ipa: '/jɑːrd/', vi: 'sân', emoji: '🌳' },
      { en: 'dining room', ipa: '/ˈdaɪnɪŋ ruːm/', vi: 'phòng ăn', emoji: '🍽️' },
      { en: 'study', ipa: '/ˈstʌdi/', vi: 'phòng học', emoji: '📚' },
      { en: 'attic', ipa: '/ˈætɪk/', vi: 'gác mái', emoji: '🏠' },
      { en: 'basement', ipa: '/ˈbeɪsmənt/', vi: 'tầng hầm', emoji: '🕳️' },
      { en: 'balcony', ipa: '/ˈbælkəni/', vi: 'ban công', emoji: '🪟' },
      { en: 'hallway', ipa: '/ˈhɔːlweɪ/', vi: 'hành lang', emoji: '🚪' },
      { en: 'closet', ipa: '/ˈklɑːzət/', vi: 'tủ tường', emoji: '🚪' },
      { en: 'porch', ipa: '/pɔːrtʃ/', vi: 'hiên nhà', emoji: '🏡' },
    ],
  },
  {
    slug: 'tinh-tu',
    emoji: '📏',
    heading: 'Tính từ miêu tả',
    title: 'Từ vựng tiếng Anh tính từ miêu tả cho bé',
    description:
      'Học tính từ miêu tả tiếng Anh cho bé: big, small, tall, fast… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn. Học qua các cặp trái nghĩa.',
    intro:
      'Tính từ giúp bé miêu tả mọi thứ: to hay nhỏ, nhanh hay chậm, mới hay cũ. Cùng học các tính từ thường gặp bằng tiếng Anh và chỉ vào đồ vật để so sánh nhé.',
    words: [
      { en: 'big', ipa: '/bɪɡ/', vi: 'to, lớn', emoji: '🐘', example: 'The elephant is big.', exampleVi: 'Con voi to.' },
      { en: 'small', ipa: '/smɔːl/', vi: 'nhỏ', emoji: '🐭' },
      { en: 'tall', ipa: '/tɔːl/', vi: 'cao', emoji: '🦒' },
      { en: 'short', ipa: '/ʃɔːrt/', vi: 'thấp, ngắn', emoji: '📏' },
      { en: 'long', ipa: '/lɔːŋ/', vi: 'dài', emoji: '📏' },
      { en: 'fast', ipa: '/fæst/', vi: 'nhanh', emoji: '🏃' },
      { en: 'slow', ipa: '/sloʊ/', vi: 'chậm', emoji: '🐢' },
      { en: 'new', ipa: '/nuː/', vi: 'mới', emoji: '✨' },
      { en: 'old', ipa: '/oʊld/', vi: 'cũ, già', emoji: '👴' },
      { en: 'hot', ipa: '/hɑːt/', vi: 'nóng', emoji: '🔥' },
      { en: 'cold', ipa: '/koʊld/', vi: 'lạnh', emoji: '🧊' },
      { en: 'clean', ipa: '/kliːn/', vi: 'sạch', emoji: '🧼' },
      { en: 'dirty', ipa: '/ˈdɜːrti/', vi: 'bẩn', emoji: '🧹' },
      { en: 'beautiful', ipa: '/ˈbjuːtɪfl/', vi: 'đẹp', emoji: '🌸' },
      { en: 'strong', ipa: '/strɔːŋ/', vi: 'khoẻ, mạnh', emoji: '💪' },
      { en: 'good', ipa: '/ɡʊd/', vi: 'tốt, giỏi', emoji: '👍' },
      { en: 'bad', ipa: '/bæd/', vi: 'xấu, tệ', emoji: '👎' },
      { en: 'young', ipa: '/jʌŋ/', vi: 'trẻ', emoji: '🧒' },
      { en: 'heavy', ipa: '/ˈhevi/', vi: 'nặng', emoji: '🪨' },
      { en: 'light', ipa: '/laɪt/', vi: 'nhẹ', emoji: '🪶' },
      { en: 'wide', ipa: '/waɪd/', vi: 'rộng', emoji: '↔️' },
      { en: 'narrow', ipa: '/ˈnæroʊ/', vi: 'hẹp', emoji: '🚪' },
      { en: 'empty', ipa: '/ˈempti/', vi: 'trống, rỗng', emoji: '📭' },
      { en: 'full', ipa: '/fʊl/', vi: 'đầy', emoji: '📬' },
      { en: 'wet', ipa: '/wet/', vi: 'ướt', emoji: '💧' },
      { en: 'dry', ipa: '/draɪ/', vi: 'khô', emoji: '🌵' },
      { en: 'loud', ipa: '/laʊd/', vi: 'to, ồn', emoji: '🔊' },
      { en: 'quiet', ipa: '/ˈkwaɪət/', vi: 'yên lặng', emoji: '🔇' },
      { en: 'easy', ipa: '/ˈiːzi/', vi: 'dễ', emoji: '😊' },
      { en: 'difficult', ipa: '/ˈdɪfɪkəlt/', vi: 'khó', emoji: '😣' },
      { en: 'dark', ipa: '/dɑːrk/', vi: 'tối', emoji: '🌑' },
      { en: 'bright', ipa: '/braɪt/', vi: 'sáng', emoji: '💡' },
    ],
  },
  {
    slug: 'vi-tri',
    emoji: '📍',
    heading: 'Vị trí (giới từ)',
    title: 'Từ vựng tiếng Anh chỉ vị trí cho bé',
    description:
      'Học từ chỉ vị trí (giới từ) tiếng Anh cho bé: in, on, under, next to… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Con mèo đang ở đâu? Trên bàn hay dưới ghế? Cùng học các từ chỉ vị trí bằng tiếng Anh và chơi trò đặt đồ vật để bé nói đúng vị trí nhé.',
    words: [
      { en: 'in', ipa: '/ɪn/', vi: 'ở trong', emoji: '📥' },
      { en: 'on', ipa: '/ɑːn/', vi: 'ở trên (bề mặt)', emoji: '⬆️' },
      { en: 'under', ipa: '/ˈʌndər/', vi: 'ở dưới', emoji: '⬇️' },
      { en: 'next to', ipa: '/ˈnekst tuː/', vi: 'bên cạnh', emoji: '↔️' },
      { en: 'behind', ipa: '/bɪˈhaɪnd/', vi: 'phía sau', emoji: '🔙' },
      { en: 'in front of', ipa: '/ɪn ˈfrʌnt əv/', vi: 'phía trước', emoji: '🔜' },
      { en: 'between', ipa: '/bɪˈtwiːn/', vi: 'ở giữa', emoji: '↔️' },
      { en: 'near', ipa: '/nɪr/', vi: 'gần', emoji: '📍' },
      { en: 'up', ipa: '/ʌp/', vi: 'lên trên', emoji: '🔼' },
      { en: 'down', ipa: '/daʊn/', vi: 'xuống dưới', emoji: '🔽' },
      { en: 'left', ipa: '/left/', vi: 'bên trái', emoji: '⬅️' },
      { en: 'right', ipa: '/raɪt/', vi: 'bên phải', emoji: '➡️' },
      { en: 'here', ipa: '/hɪr/', vi: 'ở đây', emoji: '📍' },
      { en: 'there', ipa: '/ðer/', vi: 'ở đó', emoji: '📌' },
      { en: 'inside', ipa: '/ɪnˈsaɪd/', vi: 'bên trong', emoji: '📥' },
      { en: 'outside', ipa: '/ˌaʊtˈsaɪd/', vi: 'bên ngoài', emoji: '📤' },
      { en: 'above', ipa: '/əˈbʌv/', vi: 'phía trên', emoji: '⬆️' },
      { en: 'below', ipa: '/bɪˈloʊ/', vi: 'phía dưới', emoji: '⬇️' },
      { en: 'around', ipa: '/əˈraʊnd/', vi: 'xung quanh', emoji: '🔄' },
      { en: 'top', ipa: '/tɑːp/', vi: 'trên cùng', emoji: '🔝' },
      { en: 'bottom', ipa: '/ˈbɑːtəm/', vi: 'dưới cùng', emoji: '⬇️' },
      { en: 'middle', ipa: '/ˈmɪdl/', vi: 'ở giữa', emoji: '🎯' },
      { en: 'far', ipa: '/fɑːr/', vi: 'xa', emoji: '📏' },
    ],
  },
  {
    slug: 'cong-nghe',
    emoji: '💻',
    heading: 'Đồ điện tử',
    title: 'Từ vựng tiếng Anh chủ đề đồ điện tử cho bé',
    description:
      'Học từ vựng đồ điện tử tiếng Anh cho bé: computer, phone, television, camera… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Quanh nhà bé có nhiều đồ điện tử hữu ích. Cùng học tên chúng bằng tiếng Anh và nhớ dùng đồ điện tử đúng giờ, đúng cách nhé.',
    words: [
      { en: 'computer', ipa: '/kəmˈpjuːtər/', vi: 'máy tính', emoji: '💻' },
      { en: 'laptop', ipa: '/ˈlæptɑːp/', vi: 'máy tính xách tay', emoji: '💻' },
      { en: 'phone', ipa: '/foʊn/', vi: 'điện thoại', emoji: '📱' },
      { en: 'television', ipa: '/ˈtelɪvɪʒn/', vi: 'ti vi', emoji: '📺' },
      { en: 'camera', ipa: '/ˈkæmərə/', vi: 'máy ảnh', emoji: '📷' },
      { en: 'radio', ipa: '/ˈreɪdioʊ/', vi: 'đài', emoji: '📻' },
      { en: 'headphones', ipa: '/ˈhedfoʊnz/', vi: 'tai nghe', emoji: '🎧' },
      { en: 'keyboard', ipa: '/ˈkiːbɔːrd/', vi: 'bàn phím', emoji: '⌨️' },
      { en: 'mouse', ipa: '/maʊs/', vi: 'chuột máy tính', emoji: '🖱️' },
      { en: 'robot', ipa: '/ˈroʊbɑːt/', vi: 'người máy', emoji: '🤖' },
      { en: 'battery', ipa: '/ˈbætəri/', vi: 'pin', emoji: '🔋' },
      { en: 'printer', ipa: '/ˈprɪntər/', vi: 'máy in', emoji: '🖨️' },
      { en: 'speaker', ipa: '/ˈspiːkər/', vi: 'loa', emoji: '🔊' },
      { en: 'game console', ipa: '/ɡeɪm ˈkɑːnsoʊl/', vi: 'máy chơi game', emoji: '🎮' },
      { en: 'tablet', ipa: '/ˈtæblət/', vi: 'máy tính bảng', emoji: '📱' },
      { en: 'charger', ipa: '/ˈtʃɑːrdʒər/', vi: 'bộ sạc', emoji: '🔌' },
      { en: 'screen', ipa: '/skriːn/', vi: 'màn hình', emoji: '🖥️' },
      { en: 'monitor', ipa: '/ˈmɑːnɪtər/', vi: 'màn hình máy tính', emoji: '🖥️' },
      { en: 'projector', ipa: '/prəˈdʒektər/', vi: 'máy chiếu', emoji: '📽️' },
      { en: 'drone', ipa: '/droʊn/', vi: 'máy bay không người lái', emoji: '🚁' },
      { en: 'smartwatch', ipa: '/ˈsmɑːrtwɑːtʃ/', vi: 'đồng hồ thông minh', emoji: '⌚' },
      { en: 'webcam', ipa: '/ˈwebkæm/', vi: 'máy quay web', emoji: '📷' },
      { en: 'remote control', ipa: '/rɪˈmoʊt kənˈtroʊl/', vi: 'điều khiển từ xa', emoji: '🎛️' },
      { en: 'power bank', ipa: '/ˈpaʊər bæŋk/', vi: 'sạc dự phòng', emoji: '🔋' },
      { en: 'earbuds', ipa: '/ˈɪrbʌdz/', vi: 'tai nghe nhét tai', emoji: '🎧' },
    ],
  },
  {
    slug: 'nhac-cu',
    emoji: '🎵',
    heading: 'Nhạc cụ',
    title: 'Từ vựng tiếng Anh chủ đề nhạc cụ cho bé',
    description:
      'Học từ vựng nhạc cụ tiếng Anh cho bé: piano, guitar, drum, violin… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Âm nhạc thật vui! Cùng học tên các nhạc cụ bằng tiếng Anh và bắt chước tiếng của chúng — tùng tùng cắc cắc — cho thật rộn ràng nhé.',
    words: [
      { en: 'piano', ipa: '/piˈænoʊ/', vi: 'đàn piano', emoji: '🎹' },
      { en: 'guitar', ipa: '/ɡɪˈtɑːr/', vi: 'đàn ghi ta', emoji: '🎸' },
      { en: 'drum', ipa: '/drʌm/', vi: 'cái trống', emoji: '🥁' },
      { en: 'violin', ipa: '/ˌvaɪəˈlɪn/', vi: 'đàn vĩ cầm', emoji: '🎻' },
      { en: 'flute', ipa: '/fluːt/', vi: 'cái sáo', emoji: '🪈' },
      { en: 'trumpet', ipa: '/ˈtrʌmpɪt/', vi: 'kèn trumpet', emoji: '🎺' },
      { en: 'saxophone', ipa: '/ˈsæksəfoʊn/', vi: 'kèn saxophone', emoji: '🎷' },
      { en: 'harmonica', ipa: '/hɑːrˈmɑːnɪkə/', vi: 'khẩu cầm', emoji: '🎵' },
      { en: 'bell', ipa: '/bel/', vi: 'cái chuông', emoji: '🔔' },
      { en: 'microphone', ipa: '/ˈmaɪkrəfoʊn/', vi: 'micro', emoji: '🎤' },
      { en: 'maracas', ipa: '/məˈrɑːkəs/', vi: 'trống lắc', emoji: '🪇' },
      { en: 'accordion', ipa: '/əˈkɔːrdiən/', vi: 'đàn xếp', emoji: '🪗' },
      { en: 'cello', ipa: '/ˈtʃeloʊ/', vi: 'đàn cello', emoji: '🎻' },
      { en: 'harp', ipa: '/hɑːrp/', vi: 'đàn hạc', emoji: '🎵' },
      { en: 'ukulele', ipa: '/ˌjuːkəˈleɪli/', vi: 'đàn ukulele', emoji: '🎸' },
      { en: 'organ', ipa: '/ˈɔːrɡən/', vi: 'đàn organ', emoji: '🎹' },
      { en: 'tambourine', ipa: '/ˌtæmbəˈriːn/', vi: 'trống lục lạc', emoji: '🪘' },
      { en: 'triangle', ipa: '/ˈtraɪæŋɡl/', vi: 'kẻng tam giác', emoji: '📐' },
      { en: 'cymbals', ipa: '/ˈsɪmblz/', vi: 'chũm choẹ', emoji: '🥁' },
      { en: 'recorder', ipa: '/rɪˈkɔːrdər/', vi: 'sáo recorder', emoji: '🪈' },
    ],
  },
  {
    slug: 'hoa',
    emoji: '🌸',
    heading: 'Các loài hoa',
    title: 'Từ vựng tiếng Anh chủ đề các loài hoa',
    description:
      'Học tên các loài hoa bằng tiếng Anh cho bé: rose, sunflower, lotus, tulip… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Hoa làm cho khu vườn thêm rực rỡ. Cùng bé gọi tên các loài hoa quen thuộc bằng tiếng Anh và tìm chúng khi đi dạo trong công viên nhé.',
    words: [
      { en: 'rose', ipa: '/roʊz/', vi: 'hoa hồng', emoji: '🌹' },
      { en: 'sunflower', ipa: '/ˈsʌnflaʊər/', vi: 'hoa hướng dương', emoji: '🌻' },
      { en: 'lotus', ipa: '/ˈloʊtəs/', vi: 'hoa sen', emoji: '🪷' },
      { en: 'tulip', ipa: '/ˈtuːlɪp/', vi: 'hoa tulip', emoji: '🌷' },
      { en: 'daisy', ipa: '/ˈdeɪzi/', vi: 'hoa cúc', emoji: '🌼' },
      { en: 'lily', ipa: '/ˈlɪli/', vi: 'hoa loa kèn', emoji: '🌸' },
      { en: 'orchid', ipa: '/ˈɔːrkɪd/', vi: 'hoa lan', emoji: '🌺' },
      { en: 'cherry blossom', ipa: '/ˈtʃeri blɑːsəm/', vi: 'hoa anh đào', emoji: '🌸' },
      { en: 'hibiscus', ipa: '/haɪˈbɪskəs/', vi: 'hoa dâm bụt', emoji: '🌺' },
      { en: 'daffodil', ipa: '/ˈdæfədɪl/', vi: 'hoa thuỷ tiên', emoji: '🌼' },
      { en: 'jasmine', ipa: '/ˈdʒæzmɪn/', vi: 'hoa nhài', emoji: '🌼' },
      { en: 'marigold', ipa: '/ˈmerɪɡoʊld/', vi: 'hoa cúc vạn thọ', emoji: '🌼' },
      { en: 'carnation', ipa: '/kɑːrˈneɪʃn/', vi: 'hoa cẩm chướng', emoji: '🌸' },
      { en: 'lavender', ipa: '/ˈlævəndər/', vi: 'hoa oải hương', emoji: '💜' },
      { en: 'chrysanthemum', ipa: '/krɪˈsænθəməm/', vi: 'hoa cúc', emoji: '🌼' },
      { en: 'peony', ipa: '/ˈpiːəni/', vi: 'hoa mẫu đơn', emoji: '🌺' },
      { en: 'dandelion', ipa: '/ˈdændɪlaɪən/', vi: 'hoa bồ công anh', emoji: '🌼' },
      { en: 'iris', ipa: '/ˈaɪrɪs/', vi: 'hoa diên vĩ', emoji: '🌸' },
      { en: 'violet', ipa: '/ˈvaɪələt/', vi: 'hoa violet', emoji: '💜' },
      { en: 'magnolia', ipa: '/mæɡˈnoʊliə/', vi: 'hoa mộc lan', emoji: '🌸' },
      { en: 'morning glory', ipa: '/ˈmɔːrnɪŋ ˈɡlɔːri/', vi: 'hoa bìm bìm', emoji: '🌺' },
      { en: 'water lily', ipa: '/ˈwɔːtər ˈlɪli/', vi: 'hoa súng', emoji: '🪷' },
    ],
  },
  {
    slug: 'vu-tru',
    emoji: '🚀',
    heading: 'Vũ trụ & không gian',
    title: 'Từ vựng tiếng Anh chủ đề vũ trụ cho bé',
    description:
      'Học từ vựng vũ trụ tiếng Anh cho bé: space, planet, rocket, astronaut… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Bầu trời đêm có gì? Cùng bé du hành vào vũ trụ và học tên mặt trời, hành tinh, tên lửa bằng tiếng Anh — biết đâu bé sẽ thành phi hành gia!',
    words: [
      { en: 'space', ipa: '/speɪs/', vi: 'vũ trụ', emoji: '🌌' },
      { en: 'planet', ipa: '/ˈplænɪt/', vi: 'hành tinh', emoji: '🪐' },
      { en: 'earth', ipa: '/ɜːrθ/', vi: 'trái đất', emoji: '🌍' },
      { en: 'sun', ipa: '/sʌn/', vi: 'mặt trời', emoji: '☀️' },
      { en: 'moon', ipa: '/muːn/', vi: 'mặt trăng', emoji: '🌙' },
      { en: 'star', ipa: '/stɑːr/', vi: 'ngôi sao', emoji: '⭐' },
      { en: 'rocket', ipa: '/ˈrɑːkɪt/', vi: 'tên lửa', emoji: '🚀' },
      { en: 'astronaut', ipa: '/ˈæstrənɔːt/', vi: 'phi hành gia', emoji: '👨‍🚀' },
      { en: 'satellite', ipa: '/ˈsætəlaɪt/', vi: 'vệ tinh', emoji: '🛰️' },
      { en: 'comet', ipa: '/ˈkɑːmɪt/', vi: 'sao chổi', emoji: '☄️' },
      { en: 'galaxy', ipa: '/ˈɡæləksi/', vi: 'thiên hà', emoji: '🌌' },
      { en: 'alien', ipa: '/ˈeɪliən/', vi: 'người ngoài hành tinh', emoji: '👽' },
      { en: 'universe', ipa: '/ˈjuːnɪvɜːrs/', vi: 'vũ trụ bao la', emoji: '🌌' },
      { en: 'Mars', ipa: '/mɑːrz/', vi: 'Sao Hoả', emoji: '🔴' },
      { en: 'Jupiter', ipa: '/ˈdʒuːpɪtər/', vi: 'Sao Mộc', emoji: '🪐' },
      { en: 'Saturn', ipa: '/ˈsætərn/', vi: 'Sao Thổ', emoji: '🪐' },
      { en: 'Venus', ipa: '/ˈviːnəs/', vi: 'Sao Kim', emoji: '🟡' },
      { en: 'meteor', ipa: '/ˈmiːtiər/', vi: 'sao băng', emoji: '☄️' },
      { en: 'telescope', ipa: '/ˈtelɪskoʊp/', vi: 'kính thiên văn', emoji: '🔭' },
      { en: 'orbit', ipa: '/ˈɔːrbɪt/', vi: 'quỹ đạo', emoji: '🌀' },
      { en: 'gravity', ipa: '/ˈɡrævəti/', vi: 'trọng lực', emoji: '🍎' },
    ],
  },
  {
    slug: 'le-hoi',
    emoji: '🎉',
    heading: 'Lễ hội & ngày lễ',
    title: 'Từ vựng tiếng Anh chủ đề lễ hội, ngày lễ',
    description:
      'Học từ vựng lễ hội, ngày lễ tiếng Anh cho bé: birthday, Christmas, party, gift… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Ai cũng thích ngày lễ và tiệc tùng! Cùng học tên các ngày lễ và đồ vật ngày hội bằng tiếng Anh để bé chúc mừng bạn bè thật vui nhé.',
    words: [
      { en: 'birthday', ipa: '/ˈbɜːrθdeɪ/', vi: 'sinh nhật', emoji: '🎂', example: 'Happy birthday!', exampleVi: 'Chúc mừng sinh nhật!' },
      { en: 'party', ipa: '/ˈpɑːrti/', vi: 'bữa tiệc', emoji: '🎉' },
      { en: 'gift', ipa: '/ɡɪft/', vi: 'món quà', emoji: '🎁' },
      { en: 'cake', ipa: '/keɪk/', vi: 'bánh kem', emoji: '🎂' },
      { en: 'candle', ipa: '/ˈkændl/', vi: 'cây nến', emoji: '🕯️' },
      { en: 'balloon', ipa: '/bəˈluːn/', vi: 'bóng bay', emoji: '🎈' },
      { en: 'firework', ipa: '/ˈfaɪərwɜːrk/', vi: 'pháo hoa', emoji: '🎆' },
      { en: 'lantern', ipa: '/ˈlæntərn/', vi: 'đèn lồng', emoji: '🏮' },
      { en: 'Christmas', ipa: '/ˈkrɪsməs/', vi: 'lễ Giáng sinh', emoji: '🎄' },
      { en: 'Halloween', ipa: '/ˌhæləˈwiːn/', vi: 'lễ hội Halloween', emoji: '🎃' },
      { en: 'New Year', ipa: '/nuː jɪr/', vi: 'năm mới', emoji: '🎊' },
      { en: 'Tet', ipa: '/tet/', vi: 'Tết Nguyên Đán', emoji: '🧧' },
      { en: 'wedding', ipa: '/ˈwedɪŋ/', vi: 'đám cưới', emoji: '💒' },
      { en: 'festival', ipa: '/ˈfestɪvl/', vi: 'lễ hội', emoji: '🎪' },
      { en: 'parade', ipa: '/pəˈreɪd/', vi: 'cuộc diễu hành', emoji: '🎏' },
      { en: 'Easter', ipa: '/ˈiːstər/', vi: 'lễ Phục sinh', emoji: '🐰' },
      { en: 'Valentine', ipa: '/ˈvæləntaɪn/', vi: 'lễ tình nhân', emoji: '💝' },
      { en: 'Mid-Autumn Festival', ipa: '/mɪd ˈɔːtəm ˈfestɪvl/', vi: 'Tết Trung thu', emoji: '🥮' },
      { en: "Children's Day", ipa: '/ˈtʃɪldrənz deɪ/', vi: 'ngày Quốc tế Thiếu nhi', emoji: '🎈' },
    ],
  },
  {
    slug: 'chim',
    emoji: '🐦',
    heading: 'Các loài chim',
    title: 'Từ vựng tiếng Anh chủ đề các loài chim',
    description:
      'Học tên các loài chim bằng tiếng Anh cho bé: eagle, parrot, peacock, swan… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Trên trời có bao nhiêu loài chim xinh đẹp. Cùng học tên các loài chim bằng tiếng Anh và bắt chước tiếng hót líu lo của chúng nhé.',
    words: [
      { en: 'eagle', ipa: '/ˈiːɡl/', vi: 'đại bàng', emoji: '🦅' },
      { en: 'parrot', ipa: '/ˈpærət/', vi: 'con vẹt', emoji: '🦜' },
      { en: 'peacock', ipa: '/ˈpiːkɑːk/', vi: 'con công', emoji: '🦚' },
      { en: 'sparrow', ipa: '/ˈspæroʊ/', vi: 'chim sẻ', emoji: '🐦' },
      { en: 'swan', ipa: '/swɑːn/', vi: 'thiên nga', emoji: '🦢' },
      { en: 'flamingo', ipa: '/fləˈmɪŋɡoʊ/', vi: 'chim hồng hạc', emoji: '🦩' },
      { en: 'dove', ipa: '/dʌv/', vi: 'chim bồ câu', emoji: '🕊️' },
      { en: 'rooster', ipa: '/ˈruːstər/', vi: 'con gà trống', emoji: '🐓' },
      { en: 'turkey', ipa: '/ˈtɜːrki/', vi: 'gà tây', emoji: '🦃' },
      { en: 'ostrich', ipa: '/ˈɑːstrɪtʃ/', vi: 'đà điểu', emoji: '🦤' },
      { en: 'penguin', ipa: '/ˈpeŋɡwɪn/', vi: 'chim cánh cụt', emoji: '🐧' },
      { en: 'crow', ipa: '/kroʊ/', vi: 'con quạ', emoji: '🐦‍⬛' },
      { en: 'pigeon', ipa: '/ˈpɪdʒɪn/', vi: 'chim bồ câu', emoji: '🕊️' },
      { en: 'seagull', ipa: '/ˈsiːɡʌl/', vi: 'mòng biển', emoji: '🐦' },
      { en: 'woodpecker', ipa: '/ˈwʊdpekər/', vi: 'chim gõ kiến', emoji: '🐦' },
      { en: 'cuckoo', ipa: '/ˈkuːkuː/', vi: 'chim tu hú', emoji: '🐦' },
      { en: 'magpie', ipa: '/ˈmæɡpaɪ/', vi: 'chim ác là', emoji: '🐦' },
      { en: 'hummingbird', ipa: '/ˈhʌmɪŋbɜːrd/', vi: 'chim ruồi', emoji: '🐦' },
      { en: 'quail', ipa: '/kweɪl/', vi: 'chim cút', emoji: '🐦' },
      { en: 'pheasant', ipa: '/ˈfeznt/', vi: 'chim trĩ', emoji: '🐦' },
    ],
  },
  {
    slug: 'thang-trong-nam',
    emoji: '📆',
    heading: '12 tháng trong năm',
    title: 'Từ vựng tiếng Anh 12 tháng trong năm',
    description:
      'Học tên 12 tháng trong năm bằng tiếng Anh cho bé: January, February, March… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Một năm có 12 tháng. Cùng học tên các tháng bằng tiếng Anh để bé biết tháng sinh nhật của mình và đọc lịch thật giỏi nhé.',
    words: [
      { en: 'January', ipa: '/ˈdʒænjueri/', vi: 'tháng Một', emoji: '📆' },
      { en: 'February', ipa: '/ˈfebrueri/', vi: 'tháng Hai', emoji: '📆' },
      { en: 'March', ipa: '/mɑːrtʃ/', vi: 'tháng Ba', emoji: '📆' },
      { en: 'April', ipa: '/ˈeɪprəl/', vi: 'tháng Tư', emoji: '📆' },
      { en: 'May', ipa: '/meɪ/', vi: 'tháng Năm', emoji: '📆' },
      { en: 'June', ipa: '/dʒuːn/', vi: 'tháng Sáu', emoji: '📆' },
      { en: 'July', ipa: '/dʒuˈlaɪ/', vi: 'tháng Bảy', emoji: '📆' },
      { en: 'August', ipa: '/ˈɔːɡəst/', vi: 'tháng Tám', emoji: '📆' },
      { en: 'September', ipa: '/sepˈtembər/', vi: 'tháng Chín', emoji: '📆' },
      { en: 'October', ipa: '/ɑːkˈtoʊbər/', vi: 'tháng Mười', emoji: '📆' },
      { en: 'November', ipa: '/noʊˈvembər/', vi: 'tháng Mười Một', emoji: '📆' },
      { en: 'December', ipa: '/dɪˈsembər/', vi: 'tháng Mười Hai', emoji: '🎄' },
    ],
  },
  {
    slug: 'bon-mua',
    emoji: '🍂',
    heading: 'Bốn mùa',
    title: 'Từ vựng tiếng Anh chủ đề bốn mùa cho bé',
    description:
      'Học tên bốn mùa bằng tiếng Anh cho bé: spring, summer, autumn, winter… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Một năm có bốn mùa, mỗi mùa một vẻ. Cùng học tên các mùa bằng tiếng Anh và kể xem bé thích mùa nào nhất nhé.',
    words: [
      { en: 'spring', ipa: '/sprɪŋ/', vi: 'mùa xuân', emoji: '🌷' },
      { en: 'summer', ipa: '/ˈsʌmər/', vi: 'mùa hè', emoji: '☀️' },
      { en: 'autumn', ipa: '/ˈɔːtəm/', vi: 'mùa thu', emoji: '🍂' },
      { en: 'fall', ipa: '/fɔːl/', vi: 'mùa thu (Mỹ)', emoji: '🍁' },
      { en: 'winter', ipa: '/ˈwɪntər/', vi: 'mùa đông', emoji: '❄️' },
      { en: 'season', ipa: '/ˈsiːzn/', vi: 'mùa', emoji: '🗓️' },
      { en: 'dry season', ipa: '/draɪ ˈsiːzn/', vi: 'mùa khô', emoji: '🌵' },
      { en: 'rainy season', ipa: '/ˈreɪni ˈsiːzn/', vi: 'mùa mưa', emoji: '🌧️' },
    ],
  },
  {
    slug: 'do-uong',
    emoji: '🥤',
    heading: 'Đồ uống',
    title: 'Từ vựng tiếng Anh chủ đề đồ uống cho bé',
    description:
      'Học từ vựng đồ uống tiếng Anh cho bé: water, milk, juice, tea… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Bé thích uống gì nhất? Cùng học tên các loại đồ uống bằng tiếng Anh và nhớ uống đủ nước mỗi ngày để khoẻ mạnh nhé.',
    words: [
      { en: 'water', ipa: '/ˈwɔːtər/', vi: 'nước lọc', emoji: '💧' },
      { en: 'milk', ipa: '/mɪlk/', vi: 'sữa', emoji: '🥛' },
      { en: 'juice', ipa: '/dʒuːs/', vi: 'nước ép', emoji: '🧃' },
      { en: 'tea', ipa: '/tiː/', vi: 'trà', emoji: '🍵' },
      { en: 'coffee', ipa: '/ˈkɔːfi/', vi: 'cà phê', emoji: '☕' },
      { en: 'soda', ipa: '/ˈsoʊdə/', vi: 'nước ngọt có ga', emoji: '🥤' },
      { en: 'lemonade', ipa: '/ˌleməˈneɪd/', vi: 'nước chanh', emoji: '🍋' },
      { en: 'smoothie', ipa: '/ˈsmuːði/', vi: 'sinh tố', emoji: '🥤' },
      { en: 'coconut water', ipa: '/ˈkoʊkənʌt ˈwɔːtər/', vi: 'nước dừa', emoji: '🥥' },
      { en: 'hot chocolate', ipa: '/hɑːt ˈtʃɑːklət/', vi: 'sô cô la nóng', emoji: '☕' },
      { en: 'yogurt', ipa: '/ˈjoʊɡərt/', vi: 'sữa chua', emoji: '🥛' },
      { en: 'milkshake', ipa: '/ˈmɪlkʃeɪk/', vi: 'sữa lắc', emoji: '🥤' },
      { en: 'iced tea', ipa: '/aɪst tiː/', vi: 'trà đá', emoji: '🧋' },
      { en: 'cocoa', ipa: '/ˈkoʊkoʊ/', vi: 'ca cao', emoji: '☕' },
      { en: 'orange juice', ipa: '/ˈɔːrɪndʒ dʒuːs/', vi: 'nước cam', emoji: '🍊' },
      { en: 'apple juice', ipa: '/ˈæpl dʒuːs/', vi: 'nước táo', emoji: '🍎' },
      { en: 'sugarcane juice', ipa: '/ˈʃʊɡərkeɪn dʒuːs/', vi: 'nước mía', emoji: '🥤' },
    ],
  },
  {
    slug: 'phong-bep',
    emoji: '🍳',
    heading: 'Đồ dùng nhà bếp',
    title: 'Từ vựng tiếng Anh đồ dùng nhà bếp cho bé',
    description:
      'Học từ vựng đồ dùng nhà bếp tiếng Anh cho bé: pot, pan, knife, bottle… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Nhà bếp có rất nhiều đồ dùng thú vị. Cùng học tên chúng bằng tiếng Anh và nhớ cẩn thận với dao, bếp nóng nhé!',
    words: [
      { en: 'pot', ipa: '/pɑːt/', vi: 'cái nồi', emoji: '🍲' },
      { en: 'pan', ipa: '/pæn/', vi: 'cái chảo', emoji: '🍳' },
      { en: 'knife', ipa: '/naɪf/', vi: 'con dao', emoji: '🔪' },
      { en: 'bottle', ipa: '/ˈbɑːtl/', vi: 'cái chai', emoji: '🍼' },
      { en: 'jar', ipa: '/dʒɑːr/', vi: 'cái lọ', emoji: '🫙' },
      { en: 'kettle', ipa: '/ˈketl/', vi: 'ấm đun nước', emoji: '🫖' },
      { en: 'oven', ipa: '/ˈʌvn/', vi: 'lò nướng', emoji: '🔥' },
      { en: 'stove', ipa: '/stoʊv/', vi: 'bếp', emoji: '🍳' },
      { en: 'blender', ipa: '/ˈblendər/', vi: 'máy xay', emoji: '🌀' },
      { en: 'tray', ipa: '/treɪ/', vi: 'cái khay', emoji: '🍽️' },
      { en: 'chopsticks', ipa: '/ˈtʃɑːpstɪks/', vi: 'đôi đũa', emoji: '🥢' },
      { en: 'napkin', ipa: '/ˈnæpkɪn/', vi: 'khăn ăn', emoji: '🧻' },
    ],
  },
  {
    slug: 'phong-tam',
    emoji: '🛁',
    heading: 'Đồ trong phòng tắm',
    title: 'Từ vựng tiếng Anh đồ trong phòng tắm cho bé',
    description:
      'Học từ vựng đồ dùng phòng tắm tiếng Anh cho bé: soap, towel, toothbrush, shower… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Giữ vệ sinh sạch sẽ giúp bé luôn khoẻ mạnh. Cùng học tên các đồ dùng trong phòng tắm bằng tiếng Anh và nhớ đánh răng, rửa tay mỗi ngày nhé.',
    words: [
      { en: 'soap', ipa: '/soʊp/', vi: 'xà phòng', emoji: '🧼' },
      { en: 'shampoo', ipa: '/ʃæmˈpuː/', vi: 'dầu gội', emoji: '🧴' },
      { en: 'toothbrush', ipa: '/ˈtuːθbrʌʃ/', vi: 'bàn chải đánh răng', emoji: '🪥' },
      { en: 'toothpaste', ipa: '/ˈtuːθpeɪst/', vi: 'kem đánh răng', emoji: '🧴' },
      { en: 'towel', ipa: '/ˈtaʊəl/', vi: 'khăn tắm', emoji: '🧻' },
      { en: 'comb', ipa: '/koʊm/', vi: 'cái lược', emoji: '💈' },
      { en: 'shower', ipa: '/ˈʃaʊər/', vi: 'vòi hoa sen', emoji: '🚿' },
      { en: 'toilet', ipa: '/ˈtɔɪlət/', vi: 'bồn cầu', emoji: '🚽' },
      { en: 'sink', ipa: '/sɪŋk/', vi: 'bồn rửa', emoji: '🚰' },
      { en: 'tissue', ipa: '/ˈtɪʃuː/', vi: 'khăn giấy', emoji: '🧻' },
      { en: 'bathtub', ipa: '/ˈbæθtʌb/', vi: 'bồn tắm', emoji: '🛁' },
      { en: 'mirror', ipa: '/ˈmɪrər/', vi: 'cái gương', emoji: '🪞' },
    ],
  },
  {
    slug: 'hoat-dong-hang-ngay',
    emoji: '⏰',
    heading: 'Thói quen hằng ngày',
    title: 'Từ vựng tiếng Anh thói quen hằng ngày cho bé',
    description:
      'Học từ vựng thói quen hằng ngày tiếng Anh cho bé: wake up, brush teeth, go to school… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Một ngày của bé bắt đầu và kết thúc thế nào? Cùng học các hoạt động hằng ngày bằng tiếng Anh để bé kể lại lịch sinh hoạt của mình nhé.',
    words: [
      { en: 'wake up', ipa: '/weɪk ʌp/', vi: 'thức dậy', emoji: '⏰' },
      { en: 'brush teeth', ipa: '/brʌʃ tiːθ/', vi: 'đánh răng', emoji: '🪥' },
      { en: 'wash face', ipa: '/wɑːʃ feɪs/', vi: 'rửa mặt', emoji: '🧼' },
      { en: 'get dressed', ipa: '/ɡet drest/', vi: 'mặc quần áo', emoji: '👕' },
      { en: 'eat breakfast', ipa: '/iːt ˈbrekfəst/', vi: 'ăn sáng', emoji: '🍳' },
      { en: 'go to school', ipa: '/ɡoʊ tə skuːl/', vi: 'đi học', emoji: '🏫' },
      { en: 'do homework', ipa: '/duː ˈhoʊmwɜːrk/', vi: 'làm bài tập', emoji: '📝' },
      { en: 'have lunch', ipa: '/hæv lʌntʃ/', vi: 'ăn trưa', emoji: '🍱' },
      { en: 'take a bath', ipa: '/teɪk ə bæθ/', vi: 'tắm', emoji: '🛁' },
      { en: 'have dinner', ipa: '/hæv ˈdɪnər/', vi: 'ăn tối', emoji: '🍽️' },
      { en: 'go to bed', ipa: '/ɡoʊ tə bed/', vi: 'đi ngủ', emoji: '🛏️' },
    ],
  },
  {
    slug: 'so-thich',
    emoji: '🎨',
    heading: 'Sở thích',
    title: 'Từ vựng tiếng Anh chủ đề sở thích cho bé',
    description:
      'Học từ vựng sở thích tiếng Anh cho bé: reading, drawing, singing, cooking… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Bé thích làm gì lúc rảnh? Cùng học tên các sở thích bằng tiếng Anh và tập nói "My hobby is…" để giới thiệu về mình nhé.',
    words: [
      { en: 'reading', ipa: '/ˈriːdɪŋ/', vi: 'đọc sách', emoji: '📖' },
      { en: 'drawing', ipa: '/ˈdrɔːɪŋ/', vi: 'vẽ', emoji: '✏️' },
      { en: 'painting', ipa: '/ˈpeɪntɪŋ/', vi: 'tô màu, vẽ tranh', emoji: '🎨' },
      { en: 'singing', ipa: '/ˈsɪŋɪŋ/', vi: 'ca hát', emoji: '🎤' },
      { en: 'dancing', ipa: '/ˈdænsɪŋ/', vi: 'nhảy múa', emoji: '💃' },
      { en: 'cooking', ipa: '/ˈkʊkɪŋ/', vi: 'nấu ăn', emoji: '🍳' },
      { en: 'gardening', ipa: '/ˈɡɑːrdnɪŋ/', vi: 'làm vườn', emoji: '🌱' },
      { en: 'fishing', ipa: '/ˈfɪʃɪŋ/', vi: 'câu cá', emoji: '🎣' },
      { en: 'cycling', ipa: '/ˈsaɪklɪŋ/', vi: 'đạp xe', emoji: '🚴' },
      { en: 'camping', ipa: '/ˈkæmpɪŋ/', vi: 'cắm trại', emoji: '⛺' },
      { en: 'photography', ipa: '/fəˈtɑːɡrəfi/', vi: 'chụp ảnh', emoji: '📷' },
      { en: 'collecting', ipa: '/kəˈlektɪŋ/', vi: 'sưu tầm', emoji: '🏷️' },
      { en: 'chess', ipa: '/tʃes/', vi: 'chơi cờ vua', emoji: '♟️' },
      { en: 'origami', ipa: '/ˌɔːrɪˈɡɑːmi/', vi: 'xếp giấy', emoji: '🦢' },
      { en: 'baking', ipa: '/ˈbeɪkɪŋ/', vi: 'làm bánh', emoji: '🧁' },
      { en: 'hiking', ipa: '/ˈhaɪkɪŋ/', vi: 'đi bộ đường dài', emoji: '🥾' },
      { en: 'skating', ipa: '/ˈskeɪtɪŋ/', vi: 'trượt patin', emoji: '⛸️' },
      { en: 'karaoke', ipa: '/ˌkæriˈoʊki/', vi: 'hát karaoke', emoji: '🎤' },
      { en: 'magic', ipa: '/ˈmædʒɪk/', vi: 'ảo thuật', emoji: '🎩' },
      { en: 'traveling', ipa: '/ˈtrævlɪŋ/', vi: 'du lịch', emoji: '✈️' },
    ],
  },
  {
    slug: 'nong-trai',
    emoji: '🚜',
    heading: 'Nông trại',
    title: 'Từ vựng tiếng Anh chủ đề nông trại cho bé',
    description:
      'Học từ vựng nông trại tiếng Anh cho bé: farm, tractor, barn, field… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Ở nông trại có bác nông dân, có máy cày và bao điều thú vị. Cùng học tên các thứ ở nông trại bằng tiếng Anh nhé.',
    words: [
      { en: 'farm', ipa: '/fɑːrm/', vi: 'nông trại', emoji: '🚜' },
      { en: 'tractor', ipa: '/ˈtræktər/', vi: 'máy cày', emoji: '🚜' },
      { en: 'barn', ipa: '/bɑːrn/', vi: 'nhà kho', emoji: '🏚️' },
      { en: 'hay', ipa: '/heɪ/', vi: 'cỏ khô', emoji: '🌾' },
      { en: 'fence', ipa: '/fens/', vi: 'hàng rào', emoji: '🚧' },
      { en: 'scarecrow', ipa: '/ˈskerkroʊ/', vi: 'bù nhìn', emoji: '🌾' },
      { en: 'field', ipa: '/fiːld/', vi: 'cánh đồng', emoji: '🌱' },
      { en: 'hen', ipa: '/hen/', vi: 'gà mái', emoji: '🐔' },
      { en: 'rooster', ipa: '/ˈruːstər/', vi: 'gà trống', emoji: '🐓' },
      { en: 'well', ipa: '/wel/', vi: 'cái giếng', emoji: '🕳️' },
      { en: 'farmer', ipa: '/ˈfɑːrmər/', vi: 'nông dân', emoji: '👨‍🌾' },
      { en: 'crops', ipa: '/krɑːps/', vi: 'cây trồng, mùa màng', emoji: '🌾' },
      { en: 'wheat', ipa: '/wiːt/', vi: 'lúa mì', emoji: '🌾' },
      { en: 'silo', ipa: '/ˈsaɪloʊ/', vi: 'kho chứa ngũ cốc', emoji: '🏗️' },
      { en: 'chicken coop', ipa: '/ˈtʃɪkɪn kuːp/', vi: 'chuồng gà', emoji: '🐔' },
      { en: 'plow', ipa: '/plaʊ/', vi: 'cái cày', emoji: '🚜' },
      { en: 'harvest', ipa: '/ˈhɑːrvɪst/', vi: 'thu hoạch', emoji: '🌾' },
      { en: 'orchard', ipa: '/ˈɔːrtʃərd/', vi: 'vườn cây ăn quả', emoji: '🍎' },
    ],
  },
  {
    slug: 'so-thu-tu',
    emoji: '🥇',
    heading: 'Số thứ tự',
    title: 'Từ vựng tiếng Anh số thứ tự cho bé',
    description:
      'Học số thứ tự tiếng Anh cho bé: first, second, third, fourth… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Ai về nhất, ai về nhì? Cùng học các số thứ tự bằng tiếng Anh để bé nói được thứ hạng và ngày tháng nhé.',
    words: [
      { en: 'first', ipa: '/fɜːrst/', vi: 'thứ nhất', emoji: '🥇' },
      { en: 'second', ipa: '/ˈsekənd/', vi: 'thứ hai', emoji: '🥈' },
      { en: 'third', ipa: '/θɜːrd/', vi: 'thứ ba', emoji: '🥉' },
      { en: 'fourth', ipa: '/fɔːrθ/', vi: 'thứ tư', emoji: '4️⃣' },
      { en: 'fifth', ipa: '/fɪfθ/', vi: 'thứ năm', emoji: '5️⃣' },
      { en: 'sixth', ipa: '/sɪksθ/', vi: 'thứ sáu', emoji: '6️⃣' },
      { en: 'seventh', ipa: '/ˈsevnθ/', vi: 'thứ bảy', emoji: '7️⃣' },
      { en: 'eighth', ipa: '/eɪtθ/', vi: 'thứ tám', emoji: '8️⃣' },
      { en: 'ninth', ipa: '/naɪnθ/', vi: 'thứ chín', emoji: '9️⃣' },
      { en: 'tenth', ipa: '/tenθ/', vi: 'thứ mười', emoji: '🔟' },
    ],
  },
  {
    slug: 'dai-tu-tu-hoi',
    emoji: '❓',
    heading: 'Đại từ & từ để hỏi',
    title: 'Từ vựng tiếng Anh đại từ và từ để hỏi',
    description:
      'Học đại từ và từ để hỏi tiếng Anh cho bé: I, you, he, she, what, where… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Đại từ và từ để hỏi là "chìa khoá" để bé đặt câu và giao tiếp. Cùng học I, you, what, where… bằng tiếng Anh nhé.',
    words: [
      { en: 'I', ipa: '/aɪ/', vi: 'tôi, tớ', emoji: '🙋' },
      { en: 'you', ipa: '/juː/', vi: 'bạn', emoji: '👉' },
      { en: 'he', ipa: '/hiː/', vi: 'anh ấy, cậu ấy', emoji: '👦' },
      { en: 'she', ipa: '/ʃiː/', vi: 'cô ấy, chị ấy', emoji: '👧' },
      { en: 'it', ipa: '/ɪt/', vi: 'nó (vật)', emoji: '📦' },
      { en: 'we', ipa: '/wiː/', vi: 'chúng tôi', emoji: '👨‍👩‍👧' },
      { en: 'they', ipa: '/ðeɪ/', vi: 'họ, chúng nó', emoji: '👥' },
      { en: 'what', ipa: '/wɑːt/', vi: 'cái gì', emoji: '❓' },
      { en: 'where', ipa: '/wer/', vi: 'ở đâu', emoji: '📍' },
      { en: 'when', ipa: '/wen/', vi: 'khi nào', emoji: '⏰' },
      { en: 'who', ipa: '/huː/', vi: 'ai', emoji: '🧑' },
      { en: 'why', ipa: '/waɪ/', vi: 'tại sao', emoji: '🤔' },
      { en: 'how', ipa: '/haʊ/', vi: 'như thế nào', emoji: '💭' },
      { en: 'which', ipa: '/wɪtʃ/', vi: 'cái nào', emoji: '🔀' },
    ],
  },
  {
    slug: 'quoc-gia',
    emoji: '🌏',
    heading: 'Quốc gia',
    title: 'Từ vựng tiếng Anh chủ đề quốc gia cho bé',
    description:
      'Học tên các quốc gia bằng tiếng Anh cho bé: Vietnam, America, Japan, China… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Thế giới có rất nhiều quốc gia. Cùng học tên một số nước bằng tiếng Anh và tìm chúng trên bản đồ hay quả địa cầu nhé.',
    words: COUNTRIES,
  },
  {
    slug: 'dung-cu',
    emoji: '🔧',
    heading: 'Dụng cụ',
    title: 'Từ vựng tiếng Anh chủ đề dụng cụ cho bé',
    description:
      'Học từ vựng dụng cụ tiếng Anh cho bé: hammer, saw, screwdriver, ladder… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Bố hay dùng dụng cụ gì khi sửa đồ? Cùng học tên các dụng cụ bằng tiếng Anh và nhớ để dụng cụ tránh xa tầm tay nếu còn nhỏ nhé.',
    words: [
      { en: 'hammer', ipa: '/ˈhæmər/', vi: 'cái búa', emoji: '🔨' },
      { en: 'saw', ipa: '/sɔː/', vi: 'cái cưa', emoji: '🪚' },
      { en: 'screwdriver', ipa: '/ˈskruːdraɪvər/', vi: 'tua vít', emoji: '🪛' },
      { en: 'wrench', ipa: '/rentʃ/', vi: 'cờ lê', emoji: '🔧' },
      { en: 'nail', ipa: '/neɪl/', vi: 'cái đinh', emoji: '📌' },
      { en: 'ladder', ipa: '/ˈlædər/', vi: 'cái thang', emoji: '🪜' },
      { en: 'brush', ipa: '/brʌʃ/', vi: 'cây cọ', emoji: '🖌️' },
      { en: 'drill', ipa: '/drɪl/', vi: 'máy khoan', emoji: '🛠️' },
      { en: 'tape', ipa: '/teɪp/', vi: 'băng dính', emoji: '📏' },
      { en: 'rope', ipa: '/roʊp/', vi: 'sợi dây thừng', emoji: '🪢' },
      { en: 'shovel', ipa: '/ˈʃʌvl/', vi: 'cái xẻng', emoji: '🥄' },
      { en: 'axe', ipa: '/æks/', vi: 'cái rìu', emoji: '🪓' },
      { en: 'screw', ipa: '/skruː/', vi: 'con ốc vít', emoji: '🔩' },
      { en: 'bolt', ipa: '/boʊlt/', vi: 'bu lông', emoji: '🔩' },
      { en: 'pliers', ipa: '/ˈplaɪərz/', vi: 'cái kìm', emoji: '🗜️' },
      { en: 'toolbox', ipa: '/ˈtuːlbɑːks/', vi: 'hộp dụng cụ', emoji: '🧰' },
      { en: 'tape measure', ipa: '/teɪp ˈmeʒər/', vi: 'thước dây', emoji: '📏' },
      { en: 'chisel', ipa: '/ˈtʃɪzl/', vi: 'cái đục', emoji: '🔨' },
    ],
  },
  {
    slug: 'gia-vi',
    emoji: '🧂',
    heading: 'Gia vị',
    title: 'Từ vựng tiếng Anh chủ đề gia vị cho bé',
    description:
      'Học từ vựng gia vị tiếng Anh cho bé: salt, sugar, pepper, honey… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Gia vị làm cho món ăn thêm ngon. Cùng học tên các loại gia vị bằng tiếng Anh và giúp mẹ tìm chúng trong bếp nhé.',
    words: [
      { en: 'salt', ipa: '/sɔːlt/', vi: 'muối', emoji: '🧂' },
      { en: 'sugar', ipa: '/ˈʃʊɡər/', vi: 'đường', emoji: '🍚' },
      { en: 'pepper', ipa: '/ˈpepər/', vi: 'tiêu', emoji: '⚫' },
      { en: 'chili', ipa: '/ˈtʃɪli/', vi: 'ớt', emoji: '🌶️' },
      { en: 'honey', ipa: '/ˈhʌni/', vi: 'mật ong', emoji: '🍯' },
      { en: 'soy sauce', ipa: '/ˈsɔɪ sɔːs/', vi: 'nước tương', emoji: '🍶' },
      { en: 'fish sauce', ipa: '/fɪʃ sɔːs/', vi: 'nước mắm', emoji: '🐟' },
      { en: 'vinegar', ipa: '/ˈvɪnɪɡər/', vi: 'giấm', emoji: '🍾' },
      { en: 'oil', ipa: '/ɔɪl/', vi: 'dầu ăn', emoji: '🫗' },
      { en: 'butter', ipa: '/ˈbʌtər/', vi: 'bơ', emoji: '🧈' },
      { en: 'garlic', ipa: '/ˈɡɑːrlɪk/', vi: 'tỏi', emoji: '🧄' },
      { en: 'ginger', ipa: '/ˈdʒɪndʒər/', vi: 'gừng', emoji: '🫚' },
      { en: 'cinnamon', ipa: '/ˈsɪnəmən/', vi: 'quế', emoji: '🟤' },
      { en: 'curry', ipa: '/ˈkɜːri/', vi: 'cà ri', emoji: '🍛' },
      { en: 'ketchup', ipa: '/ˈketʃəp/', vi: 'tương cà', emoji: '🍅' },
      { en: 'mustard', ipa: '/ˈmʌstərd/', vi: 'mù tạt', emoji: '🟡' },
    ],
  },
  {
    slug: 'phu-kien',
    emoji: '👜',
    heading: 'Phụ kiện & trang sức',
    title: 'Từ vựng tiếng Anh phụ kiện, trang sức cho bé',
    description:
      'Học từ vựng phụ kiện, trang sức tiếng Anh cho bé: ring, necklace, watch, glasses… kèm phiên âm, nghĩa tiếng Việt và phát âm chuẩn.',
    intro:
      'Mẹ hay đeo gì cho đẹp? Cùng học tên các phụ kiện và trang sức bằng tiếng Anh để bé gọi đúng tên nhé.',
    words: [
      { en: 'ring', ipa: '/rɪŋ/', vi: 'chiếc nhẫn', emoji: '💍' },
      { en: 'necklace', ipa: '/ˈnekləs/', vi: 'vòng cổ', emoji: '📿' },
      { en: 'bracelet', ipa: '/ˈbreɪslət/', vi: 'vòng tay', emoji: '🔗' },
      { en: 'earrings', ipa: '/ˈɪrɪŋz/', vi: 'bông tai', emoji: '💎' },
      { en: 'watch', ipa: '/wɑːtʃ/', vi: 'đồng hồ đeo tay', emoji: '⌚' },
      { en: 'crown', ipa: '/kraʊn/', vi: 'vương miện', emoji: '👑' },
      { en: 'glasses', ipa: '/ˈɡlæsɪz/', vi: 'kính', emoji: '👓' },
      { en: 'belt', ipa: '/belt/', vi: 'thắt lưng', emoji: '👖' },
      { en: 'umbrella', ipa: '/ʌmˈbrelə/', vi: 'cái ô', emoji: '☂️' },
      { en: 'wallet', ipa: '/ˈwɑːlət/', vi: 'cái ví', emoji: '👛' },
      { en: 'handbag', ipa: '/ˈhændbæɡ/', vi: 'túi xách', emoji: '👜' },
      { en: 'hairpin', ipa: '/ˈherpɪn/', vi: 'kẹp tóc', emoji: '📎' },
      { en: 'sunglasses', ipa: '/ˈsʌnɡlæsɪz/', vi: 'kính râm', emoji: '🕶️' },
      { en: 'headband', ipa: '/ˈhedbænd/', vi: 'băng đô', emoji: '👸' },
      { en: 'hair tie', ipa: '/her taɪ/', vi: 'dây buộc tóc', emoji: '💇' },
      { en: 'keychain', ipa: '/ˈkiːtʃeɪn/', vi: 'móc chìa khoá', emoji: '🔑' },
      { en: 'badge', ipa: '/bædʒ/', vi: 'huy hiệu', emoji: '📛' },
      { en: 'brooch', ipa: '/broʊtʃ/', vi: 'trâm cài', emoji: '📿' },
    ],
  },
];

const bySlug = new Map(VOCAB_TOPICS.map((t) => [t.slug, t]));

export function findVocabTopic(slug?: string | null): VocabTopic | null {
  return (slug && bySlug.get(slug)) || null;
}

/** Chủ đề đủ chất lượng để index (≥ 8 từ để tránh trang mỏng). */
export function publishableVocabTopics(): VocabTopic[] {
  return VOCAB_TOPICS.filter((t) => t.words.length >= 8);
}

export function totalVocabWords(): number {
  return VOCAB_TOPICS.reduce((sum, t) => sum + t.words.length, 0);
}
