// Kho từ cho "Vòng tròn âm vần" — mỗi âm đầu một vòng tròn 10 từ.
//
// Chỉ liệt kê TỪ + hình + câu gợi ý; các bước đánh vần được sinh tự động bằng
// `danhVan.ts`. Nhờ vậy thêm từ mới chỉ cần một dòng, và cách đánh vần luôn nhất
// quán giữa gần 300 từ.
//
// Nguyên tắc chọn từ:
//  • Vật/việc bé nhìn thấy hằng ngày, có emoji minh hoạ rõ nghĩa.
//  • Ưu tiên tiếng ĐƠN trước, từ hai tiếng để sau (khó hơn).
//  • Âm đầu phải nằm ở TIẾNG ĐẦU của từ, để bé nhìn là thấy âm đang học.

export type TuVong = {
  /** Từ hiển thị, có thể gồm hai tiếng ("phong bì"). */
  tu: string;
  /** Hình mặc định khi chưa có ảnh thật. */
  emoji: string;
  /**
   * Ảnh thật, ghi tay (vd ảnh trên S3). Bỏ trống thì hệ thống tự tìm ảnh cùng tên
   * trong public/hinh-tu/ — xem `lib/hinhTu.ts`. Không có ảnh thì dùng emoji.
   */
  anh?: string;
  /** Câu ngắn giúp bé hình dung nghĩa. */
  cau: string;
};

export type VongAm = {
  /** Chữ viết của âm, dùng làm slug: "ph", "ng"… */
  am: string;
  /** Cách đọc khi đánh vần: "phờ". */
  doc: string;
  /**
   * Nhóm để xếp thứ tự học:
   *  • 'don'/'ghep' — ÂM ĐẦU, từ trong vòng BẮT ĐẦU bằng âm đó (bờ → bò, bàn…).
   *  • 'nguyenam'   — ÂM CHÍNH, từ trong vòng CHỨA nguyên âm đó ở giữa (a → ba, cà…).
   * Nguyên âm không làm âm đầu trong tiếng Việt, nên không thể bắt từ phải mở đầu
   * bằng "ă" hay "â" — gần như không có từ nào như vậy.
   */
  nhom: 'don' | 'ghep' | 'nguyenam';
  mau: string;
  tu: TuVong[];
};

export const VONG_AM: VongAm[] = [
  { am: 'b', doc: 'bờ', nhom: 'don', mau: '#ef4444', tu: [
    { tu: 'bò', emoji: '🐄', cau: 'Con bò gặm cỏ ngoài đồng.' },
    { tu: 'bé', emoji: '👶', cau: 'Em bé đang ngủ ngon.' },
    { tu: 'bàn', emoji: '🪑', cau: 'Bé ngồi học ở bàn.' },
    { tu: 'bút', emoji: '🖊️', cau: 'Bé cầm bút viết bài.' },
    { tu: 'bánh', emoji: '🍰', cau: 'Bánh sinh nhật thơm ngon.' },
    { tu: 'bóng', emoji: '⚽', cau: 'Quả bóng tròn bé sút tung lưới.' },
    { tu: 'biển', emoji: '🏖️', cau: 'Biển xanh sóng vỗ rì rào.' },
    { tu: 'bướm', emoji: '🦋', cau: 'Con bướm bay quanh vườn hoa.' },
    { tu: 'bắp', emoji: '🌽', cau: 'Bắp luộc thơm và ngọt.' },
    { tu: 'bà', emoji: '👵', cau: 'Bà kể chuyện cho bé nghe.' },
  ] },
  { am: 'c', doc: 'cờ', nhom: 'don', mau: '#f97316', tu: [
    { tu: 'cá', emoji: '🐟', cau: 'Con cá bơi trong hồ.' },
    { tu: 'cua', emoji: '🦀', cau: 'Con cua bò ngang trên cát.' },
    { tu: 'cây', emoji: '🌳', cau: 'Cây xanh toả bóng mát.' },
    { tu: 'cửa', emoji: '🚪', cau: 'Bé mở cửa vào nhà.' },
    { tu: 'cơm', emoji: '🍚', cau: 'Cả nhà cùng ăn cơm.' },
    { tu: 'cún', emoji: '🐶', cau: 'Chú cún vẫy đuôi mừng bé.' },
    { tu: 'cầu', emoji: '🌉', cau: 'Cây cầu bắc qua sông.' },
    { tu: 'cỏ', emoji: '🌿', cau: 'Cỏ non xanh mướt.' },
    { tu: 'cam', emoji: '🍊', cau: 'Quả cam mọng nước.' },
    { tu: 'còi', emoji: '📢', cau: 'Còi xe kêu inh ỏi.' },
  ] },
  { am: 'd', doc: 'dờ', nhom: 'don', mau: '#eab308', tu: [
    { tu: 'dê', emoji: '🐐', cau: 'Con dê leo lên đồi.' },
    { tu: 'dừa', emoji: '🥥', cau: 'Cây dừa cao vút bên bờ.' },
    { tu: 'dao', emoji: '🔪', cau: 'Con dao rất sắc, bé đừng chạm.' },
    { tu: 'dép', emoji: '🩴', cau: 'Bé xỏ dép ra sân.' },
    { tu: 'dâu', emoji: '🍓', cau: 'Quả dâu chín đỏ mọng.' },
    { tu: 'dơi', emoji: '🦇', cau: 'Con dơi bay trong đêm.' },
    { tu: 'dây', emoji: '🪢', cau: 'Bé nhảy dây rất giỏi.' },
    { tu: 'dưa', emoji: '🍉', cau: 'Dưa hấu đỏ và ngọt.' },
    { tu: 'dù', emoji: '☂️', cau: 'Trời mưa bé che dù.' },
    { tu: 'dế', emoji: '🦗', cau: 'Con dế gáy ri ri.' },
  ] },
  { am: 'đ', doc: 'đờ', nhom: 'don', mau: '#84cc16', tu: [
    { tu: 'đèn', emoji: '💡', cau: 'Đèn sáng cả căn phòng.' },
    { tu: 'đũa', emoji: '🥢', cau: 'Bé tập cầm đũa.' },
    { tu: 'đá', emoji: '🪨', cau: 'Hòn đá nằm bên đường.' },
    { tu: 'đàn', emoji: '🎹', cau: 'Bé học chơi đàn.' },
    { tu: 'đường', emoji: '🛣️', cau: 'Con đường dẫn về nhà.' },
    { tu: 'đồng hồ', emoji: '⏰', cau: 'Đồng hồ báo thức reo.' },
    { tu: 'đu đủ', emoji: '🥭', cau: 'Quả đu đủ chín vàng.' },
    { tu: 'đôi', emoji: '👟', cau: 'Một đôi giày mới.' },
    { tu: 'đỏ', emoji: '🔴', cau: 'Màu đỏ của quả cà chua.' },
    { tu: 'đám mây', emoji: '☁️', cau: 'Đám mây trắng trôi lững lờ.' },
  ] },
  { am: 'g', doc: 'gờ', nhom: 'don', mau: '#22c55e', tu: [
    { tu: 'gà', emoji: '🐔', cau: 'Con gà gáy ò ó o.' },
    { tu: 'gạo', emoji: '🌾', cau: 'Hạt gạo trắng ngần.' },
    { tu: 'gấu', emoji: '🐻', cau: 'Chú gấu bông của bé.' },
    { tu: 'găng tay', emoji: '🧤', cau: 'Trời lạnh bé đeo găng tay.' },
    { tu: 'gương', emoji: '🪞', cau: 'Bé soi gương chải tóc.' },
    { tu: 'gói', emoji: '📦', cau: 'Một gói quà thật to.' },
    { tu: 'gừng', emoji: '🫚', cau: 'Củ gừng cay và thơm.' },
    { tu: 'gõ', emoji: '🚪', cau: 'Bé gõ cửa trước khi vào.' },
    { tu: 'gấc', emoji: '🍈', cau: 'Quả gấc đỏ au.' },
    { tu: 'gạch', emoji: '🧱', cau: 'Viên gạch xây nhà.' },
  ] },
  { am: 'h', doc: 'hờ', nhom: 'don', mau: '#14b8a6', tu: [
    { tu: 'hoa', emoji: '🌸', cau: 'Bông hoa nở thật đẹp.' },
    { tu: 'hổ', emoji: '🐯', cau: 'Con hổ là chúa sơn lâm.' },
    { tu: 'hộp', emoji: '📦', cau: 'Chiếc hộp đựng đồ chơi.' },
    { tu: 'hồ', emoji: '🏞️', cau: 'Mặt hồ phẳng như gương.' },
    { tu: 'hạt', emoji: '🌱', cau: 'Bé gieo hạt xuống đất.' },
    { tu: 'hát', emoji: '🎤', cau: 'Bé hát cho cả nhà nghe.' },
    { tu: 'hươu', emoji: '🦌', cau: 'Con hươu có cổ dài.' },
    { tu: 'hành', emoji: '🧅', cau: 'Củ hành làm cay mắt.' },
    { tu: 'học', emoji: '📚', cau: 'Bé chăm chỉ học bài.' },
    { tu: 'hến', emoji: '🐚', cau: 'Con hến sống dưới sông.' },
  ] },
  { am: 'k', doc: 'cờ', nhom: 'don', mau: '#06b6d4', tu: [
    { tu: 'kem', emoji: '🍦', cau: 'Que kem mát lạnh.' },
    { tu: 'kéo', emoji: '✂️', cau: 'Bé dùng kéo cắt giấy.' },
    { tu: 'kẹo', emoji: '🍬', cau: 'Viên kẹo ngọt lịm.' },
    { tu: 'kìm', emoji: '🔧', cau: 'Bố dùng kìm sửa xe.' },
    { tu: 'kính', emoji: '👓', cau: 'Ông đeo kính đọc báo.' },
    { tu: 'kiến', emoji: '🐜', cau: 'Đàn kiến tha mồi về tổ.' },
    { tu: 'kể', emoji: '📖', cau: 'Mẹ kể chuyện cổ tích.' },
    { tu: 'kim', emoji: '🪡', cau: 'Cây kim nhỏ và nhọn.' },
    { tu: 'kênh', emoji: '📺', cau: 'Bé xem kênh thiếu nhi.' },
    { tu: 'kê', emoji: '🪑', cau: 'Bé kê ghế lại gần bàn.' },
  ] },
  { am: 'l', doc: 'lờ', nhom: 'don', mau: '#3b82f6', tu: [
    { tu: 'lá', emoji: '🍃', cau: 'Chiếc lá rơi trong gió.' },
    { tu: 'lê', emoji: '🍐', cau: 'Quả lê giòn và ngọt.' },
    { tu: 'lửa', emoji: '🔥', cau: 'Ngọn lửa cháy bập bùng.' },
    { tu: 'lợn', emoji: '🐷', cau: 'Con lợn kêu ủn ỉn.' },
    { tu: 'lược', emoji: '💇', cau: 'Bé chải tóc bằng lược.' },
    { tu: 'lúa', emoji: '🌾', cau: 'Cánh đồng lúa chín vàng.' },
    { tu: 'lạc', emoji: '🥜', cau: 'Hạt lạc rang thơm bùi.' },
    { tu: 'làng', emoji: '🏘️', cau: 'Ngôi làng nhỏ ven sông.' },
    { tu: 'lụa', emoji: '🧣', cau: 'Tấm khăn lụa mềm mại.' },
    { tu: 'lồng', emoji: '🐦', cau: 'Con chim trong lồng hót vang.' },
  ] },
  { am: 'm', doc: 'mờ', nhom: 'don', mau: '#8b5cf6', tu: [
    { tu: 'mèo', emoji: '🐱', cau: 'Con mèo kêu meo meo.' },
    { tu: 'mẹ', emoji: '👩', cau: 'Mẹ nấu cơm cho cả nhà.' },
    { tu: 'mưa', emoji: '🌧️', cau: 'Trời mưa rơi tí tách.' },
    { tu: 'mũ', emoji: '🧢', cau: 'Bé đội mũ khi ra nắng.' },
    { tu: 'măng', emoji: '🎍', cau: 'Búp măng non mọc lên.' },
    { tu: 'mắt', emoji: '👁️', cau: 'Đôi mắt bé sáng long lanh.' },
    { tu: 'mật ong', emoji: '🍯', cau: 'Mật ong vàng óng và ngọt.' },
    { tu: 'muối', emoji: '🧂', cau: 'Hạt muối trắng và mặn.' },
    { tu: 'mận', emoji: '🍑', cau: 'Quả mận chua chua ngọt ngọt.' },
    { tu: 'máy bay', emoji: '✈️', cau: 'Máy bay bay trên bầu trời.' },
  ] },
  { am: 'n', doc: 'nờ', nhom: 'don', mau: '#ec4899', tu: [
    { tu: 'nón', emoji: '👒', cau: 'Chiếc nón lá che nắng.' },
    { tu: 'nai', emoji: '🦌', cau: 'Chú nai vàng ngơ ngác.' },
    { tu: 'nơ', emoji: '🎀', cau: 'Chiếc nơ hồng cài trên tóc.' },
    { tu: 'nước', emoji: '💧', cau: 'Bé uống nước cho mát.' },
    { tu: 'nến', emoji: '🕯️', cau: 'Ngọn nến lung linh.' },
    { tu: 'nồi', emoji: '🍲', cau: 'Nồi canh đang sôi.' },
    { tu: 'nem', emoji: '🥟', cau: 'Món nem rán giòn tan.' },
    { tu: 'núi', emoji: '⛰️', cau: 'Ngọn núi cao chót vót.' },
    { tu: 'nắng', emoji: '☀️', cau: 'Nắng vàng trải khắp sân.' },
    { tu: 'nấm', emoji: '🍄', cau: 'Cây nấm mọc sau mưa.' },
  ] },
  // Âm "p" đứng riêng rất hiếm trong tiếng Việt: hầu hết từ bắt đầu bằng "p" là
  // từ mượn. Vẫn phải dạy vì sách lớp 1 có bài này, nhưng vòng chỉ 8 từ — thà ít
  // mà đúng còn hơn nhét đại từ "ph" vào cho đủ 10 (lỗi đã từng mắc).
  { am: 'p', doc: 'pờ', nhom: 'don', mau: '#78716c', tu: [
    { tu: 'pin', emoji: '🔋', cau: 'Đồng hồ sắp hết pin rồi.' },
    { tu: 'pô', emoji: '🛵', cau: 'Ống pô xe máy rất nóng.' },
    { tu: 'pí po', emoji: '🚑', cau: 'Xe cứu thương kêu pí po.' },
    { tu: 'pa nô', emoji: '🪧', cau: 'Tấm pa nô treo trước cổng trường.' },
    { tu: 'pê đan', emoji: '🚲', cau: 'Bé đạp pê đan cho xe chạy.' },
    { tu: 'pi a nô', emoji: '🎹', cau: 'Chị Mai chơi đàn pi a nô.' },
    { tu: 'pa tê', emoji: '🥪', cau: 'Bánh mì kẹp pa tê thơm béo.' },
    { tu: 'pít tông', emoji: '⚙️', cau: 'Pít tông chạy lên xuống trong máy.' },
  ] },
  { am: 'qu', doc: 'quờ', nhom: 'ghep', mau: '#a855f7', tu: [
    { tu: 'quả', emoji: '🍎', cau: 'Quả táo đỏ trên cây.' },
    { tu: 'quạt', emoji: '🌀', cau: 'Chiếc quạt quay vù vù.' },
    { tu: 'quà', emoji: '🎁', cau: 'Hộp quà buộc nơ xinh.' },
    { tu: 'quần', emoji: '👖', cau: 'Bé mặc quần dài đi học.' },
    { tu: 'quê', emoji: '🏞️', cau: 'Bé về quê thăm bà.' },
    { tu: 'quýt', emoji: '🍊', cau: 'Quả quýt vàng ngọt lịm.' },
    { tu: 'quét', emoji: '🧹', cau: 'Bé quét nhà giúp mẹ.' },
    { tu: 'quyển', emoji: '📕', cau: 'Một quyển sách hay.' },
    { tu: 'quen', emoji: '🤝', cau: 'Bé làm quen bạn mới.' },
    { tu: 'quang', emoji: '🌅', cau: 'Trời quang mây tạnh.' },
  ] },
  { am: 'r', doc: 'rờ', nhom: 'don', mau: '#0ea5e9', tu: [
    { tu: 'rùa', emoji: '🐢', cau: 'Con rùa bò chậm chạp.' },
    { tu: 'rắn', emoji: '🐍', cau: 'Con rắn trườn trong cỏ.' },
    { tu: 'rau', emoji: '🥬', cau: 'Bé ăn nhiều rau xanh.' },
    { tu: 'rổ', emoji: '🧺', cau: 'Cái rổ đựng đầy quả.' },
    { tu: 'rừng', emoji: '🌲', cau: 'Khu rừng rậm rạp.' },
    { tu: 'rễ', emoji: '🌱', cau: 'Rễ cây bám sâu vào đất.' },
    { tu: 'rơm', emoji: '🌾', cau: 'Đống rơm vàng sau mùa gặt.' },
    { tu: 'ru', emoji: '🎵', cau: 'Mẹ ru bé ngủ.' },
    { tu: 'rửa', emoji: '🧼', cau: 'Bé rửa tay trước khi ăn.' },
    { tu: 'ruộng', emoji: '🌾', cau: 'Thửa ruộng xanh mướt.' },
  ] },
  { am: 's', doc: 'sờ', nhom: 'don', mau: '#f59e0b', tu: [
    { tu: 'sao', emoji: '⭐', cau: 'Ngôi sao lấp lánh trên trời.' },
    { tu: 'sách', emoji: '📗', cau: 'Quyển sách nhiều tranh đẹp.' },
    { tu: 'sông', emoji: '🏞️', cau: 'Dòng sông hiền hoà.' },
    { tu: 'sư tử', emoji: '🦁', cau: 'Con sư tử có bờm to.' },
    { tu: 'sữa', emoji: '🥛', cau: 'Bé uống sữa mỗi sáng.' },
    { tu: 'sân', emoji: '🏫', cau: 'Sân trường rộng rãi.' },
    { tu: 'sen', emoji: '🪷', cau: 'Bông sen thơm ngát.' },
    { tu: 'sóc', emoji: '🐿️', cau: 'Con sóc nhảy chuyền cành.' },
    { tu: 'súp', emoji: '🥣', cau: 'Bát súp nóng hổi.' },
    { tu: 'sườn', emoji: '🍖', cau: 'Món sườn nướng thơm phức.' },
  ] },
  { am: 't', doc: 'tờ', nhom: 'don', mau: '#10b981', tu: [
    { tu: 'tôm', emoji: '🦐', cau: 'Con tôm búng tanh tách.' },
    { tu: 'tủ', emoji: '🗄️', cau: 'Chiếc tủ đựng quần áo.' },
    { tu: 'tai', emoji: '👂', cau: 'Bé nghe bằng đôi tai.' },
    { tu: 'táo', emoji: '🍎', cau: 'Quả táo giòn ngọt.' },
    { tu: 'tàu', emoji: '🚢', cau: 'Con tàu ra khơi.' },
    { tu: 'tóc', emoji: '💇', cau: 'Mái tóc bé đen mượt.' },
    { tu: 'tim', emoji: '❤️', cau: 'Trái tim đập thình thịch.' },
    { tu: 'tổ', emoji: '🪺', cau: 'Tổ chim trên cành cây.' },
    { tu: 'tuyết', emoji: '❄️', cau: 'Bông tuyết trắng rơi.' },
    { tu: 'tết', emoji: '🧧', cau: 'Tết đến bé được lì xì.' },
  ] },
  { am: 'v', doc: 'vờ', nhom: 'don', mau: '#6366f1', tu: [
    { tu: 'vịt', emoji: '🦆', cau: 'Con vịt bơi trong ao.' },
    { tu: 'vở', emoji: '📓', cau: 'Quyển vở mới tinh.' },
    { tu: 'voi', emoji: '🐘', cau: 'Con voi có vòi rất dài.' },
    { tu: 'vẽ', emoji: '🎨', cau: 'Bé vẽ tranh gia đình.' },
    { tu: 'vườn', emoji: '🌷', cau: 'Khu vườn đầy hoa.' },
    { tu: 'vòng', emoji: '💍', cau: 'Chiếc vòng tay xinh xắn.' },
    { tu: 've', emoji: '🦗', cau: 'Con ve kêu râm ran mùa hè.' },
    { tu: 'vai', emoji: '🎒', cau: 'Bé đeo cặp trên vai.' },
    { tu: 'vá', emoji: '🧵', cau: 'Bà vá lại chiếc áo.' },
    { tu: 'ván', emoji: '🛹', cau: 'Bé trượt ván rất giỏi.' },
  ] },
  { am: 'x', doc: 'xờ', nhom: 'don', mau: '#d946ef', tu: [
    { tu: 'xe', emoji: '🚗', cau: 'Chiếc xe chạy bon bon.' },
    { tu: 'xoài', emoji: '🥭', cau: 'Quả xoài chín thơm.' },
    { tu: 'xôi', emoji: '🍙', cau: 'Gói xôi nóng buổi sáng.' },
    { tu: 'xanh', emoji: '💚', cau: 'Màu xanh của lá cây.' },
    { tu: 'xích đu', emoji: '🎠', cau: 'Bé chơi xích đu ngoài sân.' },
    { tu: 'xương', emoji: '🦴', cau: 'Chú chó gặm khúc xương.' },
    { tu: 'xúc xích', emoji: '🌭', cau: 'Cây xúc xích thơm ngon.' },
    { tu: 'xẻng', emoji: '🪏', cau: 'Bé xúc cát bằng xẻng.' },
    { tu: 'xà phòng', emoji: '🧼', cau: 'Bé rửa tay bằng xà phòng.' },
    { tu: 'xuồng', emoji: '🛶', cau: 'Chiếc xuồng nhỏ trên sông.' },
  ] },

  // Không có vòng cho chữ "p" đứng riêng: tiếng Việt gần như không có tiếng nào
  // mở đầu bằng "p" (chỉ vài từ mượn như "pin", "pi-a-nô"). Chữ p hầu như luôn
  // đi cùng h thành "ph" — nên nó nằm ở vòng "ph" bên dưới.

  // ── Âm ghép ──
  { am: 'ch', doc: 'chờ', nhom: 'ghep', mau: '#ef4444', tu: [
    { tu: 'chó', emoji: '🐕', cau: 'Con chó trông nhà rất giỏi.' },
    { tu: 'chim', emoji: '🐦', cau: 'Con chim hót líu lo.' },
    { tu: 'chuối', emoji: '🍌', cau: 'Quả chuối vàng ươm.' },
    { tu: 'chăn', emoji: '🛏️', cau: 'Bé đắp chăn cho ấm.' },
    { tu: 'chè', emoji: '🍧', cau: 'Cốc chè mát lạnh.' },
    { tu: 'chân', emoji: '🦵', cau: 'Bé chạy bằng đôi chân.' },
    { tu: 'chổi', emoji: '🧹', cau: 'Cây chổi quét sân.' },
    { tu: 'chuông', emoji: '🔔', cau: 'Tiếng chuông reo vào lớp.' },
    { tu: 'chợ', emoji: '🏪', cau: 'Mẹ đi chợ mua rau.' },
    { tu: 'chì', emoji: '✏️', cau: 'Bút chì để bé tập viết.' },
  ] },
  { am: 'gh', doc: 'gờ', nhom: 'ghep', mau: '#22c55e', tu: [
    { tu: 'ghế', emoji: '🪑', cau: 'Bé ngồi trên ghế.' },
    { tu: 'ghi', emoji: '📝', cau: 'Bé ghi bài vào vở.' },
    { tu: 'ghé', emoji: '🚶', cau: 'Bé ghé thăm nhà bà.' },
    { tu: 'ghẹ', emoji: '🦀', cau: 'Con ghẹ sống ở biển.' },
    { tu: 'ghép', emoji: '🧩', cau: 'Bé ghép hình rất khéo.' },
    { tu: 'ghim', emoji: '📌', cau: 'Cây ghim giữ tờ giấy.' },
    { tu: 'ghen', emoji: '😾', cau: 'Bé không nên ghen với bạn.' },
    { tu: 'ghe', emoji: '🛶', cau: 'Chiếc ghe chở đầy trái cây.' },
    { tu: 'ghẻ', emoji: '🩹', cau: 'Rửa tay sạch để không bị ghẻ.' },
    { tu: 'ghì', emoji: '🤗', cau: 'Mẹ ghì bé vào lòng.' },
  ] },
  { am: 'gi', doc: 'giờ', nhom: 'ghep', mau: '#84cc16', tu: [
    { tu: 'giày', emoji: '👟', cau: 'Đôi giày mới của bé.' },
    { tu: 'giường', emoji: '🛏️', cau: 'Bé ngủ trên giường.' },
    { tu: 'giấy', emoji: '📄', cau: 'Tờ giấy trắng để vẽ.' },
    { tu: 'giỏ', emoji: '🧺', cau: 'Chiếc giỏ đựng hoa quả.' },
    { tu: 'gió', emoji: '🌬️', cau: 'Cơn gió mát thổi qua.' },
    { tu: 'giếng', emoji: '🪣', cau: 'Cái giếng nước trong veo.' },
    { tu: 'giun', emoji: '🪱', cau: 'Con giun làm tơi đất.' },
    { tu: 'giặt', emoji: '🧺', cau: 'Mẹ giặt quần áo.' },
    { tu: 'giòn', emoji: '🍘', cau: 'Bánh giòn tan trong miệng.' },
    { tu: 'giúp', emoji: '🤝', cau: 'Bé giúp mẹ dọn nhà.' },
  ] },
  { am: 'kh', doc: 'khờ', nhom: 'ghep', mau: '#06b6d4', tu: [
    { tu: 'khỉ', emoji: '🐵', cau: 'Con khỉ leo trèo nhanh thoăn thoắt.' },
    { tu: 'khăn', emoji: '🧣', cau: 'Chiếc khăn quàng cổ ấm áp.' },
    { tu: 'khoai', emoji: '🍠', cau: 'Củ khoai nướng thơm bùi.' },
    { tu: 'kho', emoji: '🏬', cau: 'Nhà kho chứa đầy hàng.' },
    { tu: 'khói', emoji: '💨', cau: 'Làn khói bay lên cao.' },
    { tu: 'khế', emoji: '🌟', cau: 'Quả khế năm cánh chua chua.' },
    { tu: 'khóc', emoji: '😢', cau: 'Em bé khóc đòi mẹ.' },
    { tu: 'khoá', emoji: '🔒', cau: 'Ổ khoá giữ cửa an toàn.' },
    { tu: 'không', emoji: '🚫', cau: 'Bé lắc đầu nói không.' },
    { tu: 'khủng long', emoji: '🦖', cau: 'Con khủng long thật to lớn.' },
  ] },
  { am: 'ng', doc: 'ngờ', nhom: 'ghep', mau: '#3b82f6', tu: [
    { tu: 'ngựa', emoji: '🐴', cau: 'Con ngựa phi nước đại.' },
    { tu: 'ngôi sao', emoji: '⭐', cau: 'Ngôi sao sáng nhất trời đêm.' },
    { tu: 'ngô', emoji: '🌽', cau: 'Bắp ngô luộc thơm ngọt.' },
    { tu: 'ngủ', emoji: '😴', cau: 'Bé ngủ ngon giấc.' },
    { tu: 'ngón tay', emoji: '👆', cau: 'Bàn tay có năm ngón tay.' },
    { tu: 'ngoan', emoji: '😊', cau: 'Bé rất ngoan và lễ phép.' },
    { tu: 'ngày', emoji: '🌞', cau: 'Một ngày mới bắt đầu.' },
    { tu: 'ngan', emoji: '🦆', cau: 'Con ngan bơi cùng đàn vịt.' },
    { tu: 'ngọt', emoji: '🍬', cau: 'Viên kẹo ngọt lịm.' },
    { tu: 'ngồi', emoji: '🪑', cau: 'Bé ngồi thẳng lưng khi viết.' },
  ] },
  { am: 'ngh', doc: 'ngờ', nhom: 'ghep', mau: '#6366f1', tu: [
    { tu: 'nghe', emoji: '👂', cau: 'Bé nghe cô giáo giảng bài.' },
    { tu: 'nghỉ', emoji: '🛋️', cau: 'Bé nghỉ ngơi sau giờ học.' },
    { tu: 'nghĩ', emoji: '💭', cau: 'Bé nghĩ ra cách làm hay.' },
    { tu: 'nghé', emoji: '🐃', cau: 'Chú nghé con theo mẹ ra đồng.' },
    { tu: 'nghiêng', emoji: '↗️', cau: 'Cái cây nghiêng theo chiều gió.' },
    { tu: 'nghèo', emoji: '🏚️', cau: 'Bạn nhỏ nhà nghèo mà học giỏi.' },
    { tu: 'nghề', emoji: '🧑‍🌾', cau: 'Bố làm nghề nông.' },
    { tu: 'nghìn', emoji: '🔢', cau: 'Một nghìn đồng.' },
    { tu: 'nghiêm', emoji: '🧍', cau: 'Các bạn đứng nghiêm chào cờ.' },
    { tu: 'nghịch', emoji: '🤸', cau: 'Bé nghịch ngợm nhưng đáng yêu.' },
  ] },
  { am: 'nh', doc: 'nhờ', nhom: 'ghep', mau: '#8b5cf6', tu: [
    { tu: 'nhà', emoji: '🏠', cau: 'Ngôi nhà thân yêu của bé.' },
    { tu: 'nhãn', emoji: '🍈', cau: 'Chùm nhãn ngọt lịm.' },
    { tu: 'nhện', emoji: '🕷️', cau: 'Con nhện giăng tơ.' },
    { tu: 'nhạc', emoji: '🎵', cau: 'Bé nghe nhạc thiếu nhi.' },
    { tu: 'nhảy', emoji: '🤾', cau: 'Bé nhảy dây rất giỏi.' },
    { tu: 'nhỏ', emoji: '🐜', cau: 'Con kiến thật nhỏ bé.' },
    { tu: 'nhớ', emoji: '💗', cau: 'Bé nhớ bà ở quê.' },
    { tu: 'nhóm', emoji: '👨‍👩‍👧', cau: 'Cả nhóm cùng làm bài.' },
    { tu: 'nhanh', emoji: '⚡', cau: 'Bé chạy rất nhanh.' },
    { tu: 'nhuộm', emoji: '🎨', cau: 'Nắng nhuộm vàng cánh đồng.' },
  ] },
  { am: 'ph', doc: 'phờ', nhom: 'ghep', mau: '#ec4899', tu: [
    { tu: 'phở', emoji: '🍜', cau: 'Bát phở nóng thơm lừng.' },
    { tu: 'phao', emoji: '🛟', cau: 'Bé mang phao khi tập bơi.' },
    { tu: 'pháo', emoji: '🎆', cau: 'Pháo hoa sáng rực bầu trời.' },
    { tu: 'phố', emoji: '🏙️', cau: 'Con phố đông người qua lại.' },
    { tu: 'phà', emoji: '⛴️', cau: 'Chiếc phà chở khách qua sông.' },
    { tu: 'phấn', emoji: '🖍️', cau: 'Cô giáo viết bảng bằng phấn.' },
    { tu: 'phim', emoji: '🎬', cau: 'Bé xem phim hoạt hình.' },
    { tu: 'phòng', emoji: '🛏️', cau: 'Căn phòng gọn gàng.' },
    { tu: 'phong bì', emoji: '✉️', cau: 'Lá thư trong phong bì.' },
    { tu: 'phượng', emoji: '🌺', cau: 'Hoa phượng đỏ rực sân trường.' },
  ] },
  { am: 'th', doc: 'thờ', nhom: 'ghep', mau: '#f59e0b', tu: [
    { tu: 'thỏ', emoji: '🐰', cau: 'Con thỏ có đôi tai dài.' },
    { tu: 'thuyền', emoji: '⛵', cau: 'Chiếc thuyền lướt trên sóng.' },
    { tu: 'thìa', emoji: '🥄', cau: 'Bé xúc cơm bằng thìa.' },
    { tu: 'thước', emoji: '📏', cau: 'Cây thước kẻ đường thẳng.' },
    { tu: 'thang', emoji: '🪜', cau: 'Cái thang bắc lên cao.' },
    { tu: 'thư', emoji: '💌', cau: 'Bé viết thư cho bà.' },
    { tu: 'thầy', emoji: '👨‍🏫', cau: 'Thầy giáo giảng bài rất hay.' },
    { tu: 'thóc', emoji: '🌾', cau: 'Hạt thóc vàng phơi đầy sân.' },
    { tu: 'thơm', emoji: '🌼', cau: 'Bông hoa thơm ngát.' },
    { tu: 'thác', emoji: '🏞️', cau: 'Dòng thác đổ trắng xoá.' },
  ] },
  { am: 'tr', doc: 'trờ', nhom: 'ghep', mau: '#14b8a6', tu: [
    { tu: 'trâu', emoji: '🐃', cau: 'Con trâu cày ruộng.' },
    { tu: 'trăng', emoji: '🌙', cau: 'Ông trăng tròn vành vạnh.' },
    { tu: 'trứng', emoji: '🥚', cau: 'Quả trứng gà tròn xinh.' },
    { tu: 'tre', emoji: '🎋', cau: 'Luỹ tre xanh đầu làng.' },
    { tu: 'trường', emoji: '🏫', cau: 'Bé đến trường mỗi sáng.' },
    { tu: 'trời', emoji: '🌤️', cau: 'Bầu trời trong xanh.' },
    { tu: 'tranh', emoji: '🖼️', cau: 'Bức tranh treo trên tường.' },
    { tu: 'trống', emoji: '🥁', cau: 'Tiếng trống trường vang lên.' },
    { tu: 'trà', emoji: '🍵', cau: 'Ông uống trà buổi sáng.' },
    { tu: 'trắng', emoji: '🤍', cau: 'Màu trắng của mây.' },
  ] },

  // ─────────────────────────────────────────────────────────────────────────
  // NGUYÊN ÂM — vòng "âm chính".
  // Ở đây từ CHỨA nguyên âm chứ không mở đầu bằng nó: tiếng Việt gần như không có
  // từ nào bắt đầu bằng "ă" hay "â", mà đó lại đúng là cách bé gặp chúng khi ghép
  // vần (b-a-ba, ch-ăn-chăn). Ép cho đủ 10 từ mở đầu bằng nguyên âm là bịa dữ liệu.
  // ─────────────────────────────────────────────────────────────────────────
  { am: 'a', doc: 'a', nhom: 'nguyenam', mau: '#e11d48', tu: [
    { tu: 'ba', emoji: '👨', cau: 'Ba dắt bé đi học.' },
    { tu: 'na', emoji: '🍈', cau: 'Quả na chín thơm lừng.' },
    { tu: 'cà', emoji: '🍆', cau: 'Quả cà tím trong vườn.' },
    { tu: 'sao', emoji: '⭐', cau: 'Ngôi sao sáng trên trời.' },
    { tu: 'tai', emoji: '👂', cau: 'Bé nghe bằng tai.' },
    { tu: 'chanh', emoji: '🍋', cau: 'Quả chanh chua lắm.' },
    { tu: 'canh', emoji: '🍲', cau: 'Bát canh nóng hổi.' },
    { tu: 'áo', emoji: '👕', cau: 'Chiếc áo mới của bé.' },
    { tu: 'ao', emoji: '🦆', cau: 'Đàn vịt bơi trong ao.' },
    { tu: 'cát', emoji: '🏖️', cau: 'Bé xây lâu đài cát.' },
  ] },
  { am: 'ă', doc: 'á', nhom: 'nguyenam', mau: '#f43f5e', tu: [
    { tu: 'ăn', emoji: '🍚', cau: 'Bé ăn cơm ngon lành.' },
    { tu: 'trăng', emoji: '🌙', cau: 'Ông trăng tròn vành vạnh.' },
    { tu: 'khăn', emoji: '🧣', cau: 'Chiếc khăn quàng cổ.' },
    { tu: 'chăn', emoji: '🛏️', cau: 'Bé đắp chăn cho ấm.' },
    { tu: 'tắm', emoji: '🛁', cau: 'Bé đi tắm cho sạch.' },
    { tu: 'nắng', emoji: '☀️', cau: 'Trời nắng chang chang.' },
    { tu: 'răng', emoji: '🦷', cau: 'Bé đánh răng mỗi sáng.' },
    { tu: 'sắn', emoji: '🍠', cau: 'Củ sắn luộc bùi bùi.' },
    { tu: 'thằn lằn', emoji: '🦎', cau: 'Con thằn lằn bò trên tường.' },
    { tu: 'cằm', emoji: '🧒', cau: 'Bé chống cằm suy nghĩ.' },
  ] },
  { am: 'â', doc: 'ớ', nhom: 'nguyenam', mau: '#fb7185', tu: [
    { tu: 'ấm', emoji: '🫖', cau: 'Cái ấm đun nước sôi.' },
    { tu: 'mây', emoji: '☁️', cau: 'Đám mây trắng bay ngang trời.' },
    { tu: 'chân', emoji: '🦶', cau: 'Bé rửa chân trước khi ngủ.' },
    { tu: 'tất', emoji: '🧦', cau: 'Đôi tất giữ chân ấm.' },
    { tu: 'gậy', emoji: '🦯', cau: 'Ông chống gậy đi bộ.' },
    { tu: 'trâu', emoji: '🐃', cau: 'Con trâu cày ruộng.' },
    { tu: 'sấu', emoji: '🐊', cau: 'Con cá sấu há miệng.' },
    { tu: 'nấm', emoji: '🍄', cau: 'Cây nấm mọc sau mưa.' },
    { tu: 'bầu', emoji: '🥒', cau: 'Quả bầu treo trên giàn.' },
    { tu: 'cầu vồng', emoji: '🌈', cau: 'Cầu vồng bảy sắc sau cơn mưa.' },
  ] },
  { am: 'e', doc: 'e', nhom: 'nguyenam', mau: '#d946ef', tu: [
    { tu: 'em', emoji: '👧', cau: 'Em của bé đang cười.' },
    { tu: 'xe', emoji: '🚗', cau: 'Chiếc xe chạy trên đường.' },
    { tu: 'que', emoji: '🥢', cau: 'Que tre nhỏ trên tay bé.' },
    { tu: 'kèn', emoji: '🎺', cau: 'Bé thổi kèn tò te.' },
    { tu: 'sen', emoji: '🪷', cau: 'Bông sen nở giữa hồ.' },
    { tu: 'vẹt', emoji: '🦜', cau: 'Con vẹt biết nói theo người.' },
    { tu: 'leo', emoji: '🧗', cau: 'Bé leo cầu thang thật giỏi.' },
    { tu: 'chén', emoji: '🥣', cau: 'Cái chén đựng cơm.' },
    { tu: 'nghé', emoji: '🐄', cau: 'Chú nghé con theo mẹ ra đồng.' },
    { tu: 'tre', emoji: '🎋', cau: 'Bụi tre xanh đầu làng.' },
  ] },
  { am: 'ê', doc: 'ê', nhom: 'nguyenam', mau: '#a855f7', tu: [
    { tu: 'ếch', emoji: '🐸', cau: 'Con ếch kêu ộp ộp.' },
    { tu: 'đêm', emoji: '🌙', cau: 'Ban đêm trời tối om.' },
    { tu: 'bê', emoji: '🐄', cau: 'Chú bê con uống sữa.' },
    { tu: 'nệm', emoji: '🛏️', cau: 'Bé nằm trên nệm êm.' },
    { tu: 'tên', emoji: '🏷️', cau: 'Bé viết tên mình lên vở.' },
    { tu: 'mềm', emoji: '🧸', cau: 'Con gấu bông mềm mại.' },
    { tu: 'thềm', emoji: '🏠', cau: 'Bé ngồi chơi ở thềm nhà.' },
    { tu: 'bến', emoji: '⛴️', cau: 'Bến sông có nhiều thuyền.' },
    { tu: 'ghế', emoji: '🪑', cau: 'Bé ngồi lên ghế.' },
    { tu: 'sếu', emoji: '🕊️', cau: 'Con chim sếu bay cao.' },
  ] },
  { am: 'i', doc: 'i', nhom: 'nguyenam', mau: '#8b5cf6', tu: [
    { tu: 'đi', emoji: '🚶', cau: 'Bé đi bộ tới trường.' },
    { tu: 'chì', emoji: '✏️', cau: 'Bút chì để bé vẽ.' },
    { tu: 'bi', emoji: '🔵', cau: 'Viên bi tròn lăn trên sàn.' },
    { tu: 'mì', emoji: '🍜', cau: 'Tô mì nóng hổi.' },
    { tu: 'chim', emoji: '🐦', cau: 'Con chim hót trên cành.' },
    { tu: 'tim', emoji: '❤️', cau: 'Trái tim đập thình thịch.' },
    { tu: 'đình', emoji: '⛩️', cau: 'Mái đình cong cong.' },
    { tu: 'vịt', emoji: '🦆', cau: 'Con vịt bơi dưới ao.' },
    { tu: 'lịch', emoji: '📅', cau: 'Tờ lịch treo trên tường.' },
    { tu: 'phim', emoji: '🎬', cau: 'Bé xem phim hoạt hình.' },
  ] },
  { am: 'o', doc: 'o', nhom: 'nguyenam', mau: '#6366f1', tu: [
    { tu: 'ong', emoji: '🐝', cau: 'Con ong hút mật hoa.' },
    { tu: 'cò', emoji: '🕊️', cau: 'Con cò trắng bay lả bay la.' },
    { tu: 'nho', emoji: '🍇', cau: 'Chùm nho tím mọng nước.' },
    { tu: 'vòi', emoji: '🚿', cau: 'Vòi nước chảy róc rách.' },
    { tu: 'tóc', emoji: '💇', cau: 'Mái tóc bé đen nhánh.' },
    { tu: 'chó', emoji: '🐕', cau: 'Con chó trông nhà.' },
    { tu: 'vòng', emoji: '💍', cau: 'Chiếc vòng đeo tay xinh xắn.' },
    { tu: 'sói', emoji: '🐺', cau: 'Con sói tru trong rừng.' },
    { tu: 'thỏ', emoji: '🐰', cau: 'Con thỏ ăn cà rốt.' },
    { tu: 'ngón', emoji: '☝️', cau: 'Bé đếm ngón tay.' },
  ] },
  { am: 'ô', doc: 'ô', nhom: 'nguyenam', mau: '#3b82f6', tu: [
    { tu: 'ô', emoji: '☂️', cau: 'Trời mưa bé che ô.' },
    { tu: 'ốc', emoji: '🐌', cau: 'Con ốc bò chậm chạp.' },
    { tu: 'ổ', emoji: '🥚', cau: 'Ổ trứng gà trong chuồng.' },
    { tu: 'cột', emoji: '🪵', cau: 'Cây cột chống mái nhà.' },
    { tu: 'ông', emoji: '👴', cau: 'Ông kể chuyện ngày xưa.' },
    { tu: 'tôm', emoji: '🦐', cau: 'Con tôm càng đỏ au.' },
    { tu: 'cốm', emoji: '🍡', cau: 'Gói cốm xanh thơm mùi lúa.' },
    { tu: 'sông', emoji: '🏞️', cau: 'Dòng sông chảy hiền hoà.' },
    { tu: 'trống', emoji: '🥁', cau: 'Bé gõ trống tùng tùng.' },
    { tu: 'chổi', emoji: '🧹', cau: 'Bé cầm chổi quét nhà.' },
  ] },
  { am: 'ơ', doc: 'ơ', nhom: 'nguyenam', mau: '#0ea5e9', tu: [
    { tu: 'ớt', emoji: '🌶️', cau: 'Quả ớt đỏ rất cay.' },
    { tu: 'bơ', emoji: '🥑', cau: 'Quả bơ béo ngậy.' },
    { tu: 'mơ', emoji: '🍑', cau: 'Quả mơ chua chua.' },
    { tu: 'vở', emoji: '📓', cau: 'Bé viết vào quyển vở.' },
    { tu: 'cờ', emoji: '🚩', cau: 'Lá cờ bay trong gió.' },
    { tu: 'trời', emoji: '🌤️', cau: 'Bầu trời xanh cao vời vợi.' },
    { tu: 'bơi', emoji: '🏊', cau: 'Bé tập bơi ở bể.' },
    { tu: 'lớp', emoji: '🏫', cau: 'Lớp học có nhiều bạn.' },
    { tu: 'sợi', emoji: '🧶', cau: 'Sợi len cuộn tròn.' },
    { tu: 'chợ', emoji: '🧺', cau: 'Mẹ đi chợ mua rau.' },
  ] },
  { am: 'u', doc: 'u', nhom: 'nguyenam', mau: '#06b6d4', tu: [
    { tu: 'tủ', emoji: '🗄️', cau: 'Cái tủ đựng quần áo.' },
    { tu: 'vua', emoji: '👑', cau: 'Ông vua đội mũ miện.' },
    { tu: 'chú', emoji: '🧑', cau: 'Chú của bé rất vui tính.' },
    { tu: 'chuối', emoji: '🍌', cau: 'Quả chuối chín vàng.' },
    { tu: 'thùng', emoji: '🛢️', cau: 'Cái thùng đựng nước.' },
    { tu: 'múa', emoji: '💃', cau: 'Bé múa theo tiếng nhạc.' },
    { tu: 'túi', emoji: '👜', cau: 'Chiếc túi xách của mẹ.' },
    { tu: 'nụ', emoji: '🌷', cau: 'Nụ hoa sắp nở.' },
    { tu: 'búp bê', emoji: '🪆', cau: 'Bé bế búp bê.' },
    { tu: 'vui', emoji: '😊', cau: 'Bé cười thật vui.' },
  ] },
  { am: 'ư', doc: 'ư', nhom: 'nguyenam', mau: '#14b8a6', tu: [
    { tu: 'thư', emoji: '✉️', cau: 'Lá thư gửi cho bà.' },
    { tu: 'sữa', emoji: '🥛', cau: 'Ly sữa trắng thơm.' },
    { tu: 'rừng', emoji: '🌲', cau: 'Khu rừng có nhiều cây to.' },
    { tu: 'vườn', emoji: '🌺', cau: 'Vườn hoa nhà bé.' },
    { tu: 'trứng', emoji: '🥚', cau: 'Quả trứng gà tròn.' },
    { tu: 'bưởi', emoji: '🍊', cau: 'Quả bưởi to và mọng.' },
    { tu: 'lươn', emoji: '🐍', cau: 'Con lươn trơn tuột.' },
    { tu: 'mứt', emoji: '🍬', cau: 'Hộp mứt ngày Tết.' },
    { tu: 'nướng', emoji: '🍢', cau: 'Món thịt nướng thơm lừng.' },
    { tu: 'tưới', emoji: '🚿', cau: 'Bé tưới cây mỗi sáng.' },
  ] },
  // "y" làm nguyên âm: đứng một mình (y tá, yến) hoặc trong vần yê/uy.
  { am: 'y', doc: 'i dài', nhom: 'nguyenam', mau: '#10b981', tu: [
    { tu: 'y tá', emoji: '👩‍⚕️', cau: 'Cô y tá chăm sóc bé.' },
    { tu: 'yến', emoji: '🐦', cau: 'Chim yến làm tổ trên vách đá.' },
    { tu: 'yêu', emoji: '❤️', cau: 'Bé yêu ông bà.' },
    { tu: 'yên', emoji: '🚲', cau: 'Bé ngồi lên yên xe đạp.' },
    { tu: 'yếm', emoji: '👶', cau: 'Bé đeo yếm khi ăn.' },
    { tu: 'ý', emoji: '💭', cau: 'Bé nêu ý kiến của mình.' },
    { tu: 'yếu', emoji: '🤒', cau: 'Bạn ấy ốm nên người yếu.' },
    { tu: 'quyển', emoji: '📕', cau: 'Quyển sách mới tinh.' },
    { tu: 'chuyện', emoji: '📖', cau: 'Bà kể chuyện cho bé nghe.' },
    { tu: 'tuyết', emoji: '❄️', cau: 'Bông tuyết trắng rơi.' },
  ] },
];

/** Tìm một vòng theo mã âm. */
export const timVong = (am: string) => VONG_AM.find((v) => v.am === am);
