export type SentenceItem = {
  id: number;
  text: string;
  category?: string;
};

export const sentences: SentenceItem[] = [
  // Fruits & Food
  { id: 1, text: "Mai ăn na.", category: "food" },
  { id: 2, text: "Bé ăn cam." },
  { id: 3, text: "Ăn dâu tây." },
  { id: 4, text: "Bé uống sữa." },
  { id: 5, text: "Mẹ nấu cơm." },
  { id: 6, text: "Ăn bánh mì." },
  { id: 7, text: "Bà nấu xúp." },
  { id: 8, text: "Bé thích táo." },
  { id: 9, text: "Ăn nho xanh." },
  { id: 10, text: "Uống nước ngọt." },

  // Daily Activities
  { id: 11, text: "Bé đi học.", category: "activity" },
  { id: 12, text: "Bé đi ngủ." },
  { id: 13, text: "Mẹ dạy bé." },
  { id: 14, text: "Bé chơi bóng." },
  { id: 15, text: "Chạy rất nhanh." },
  { id: 16, text: "Nhảy cao cao." },
  { id: 17, text: "Bé hát hay." },
  { id: 18, text: "Vẽ hình đẹp." },
  { id: 19, text: "Đọc sách hay." },
  { id: 20, text: "Viết bài tập." },

  // Family
  { id: 21, text: "Bà cho bé na.", category: "family" },
  { id: 22, text: "Mẹ bế bé." },
  { id: 23, text: "Bố yêu bé." },
  { id: 24, text: "Em bé đáng yêu." },
  { id: 25, text: "Anh yêu em." },
  { id: 26, text: "Chị chơi với bé." },
  { id: 27, text: "Cả nhà vui vẻ." },
  { id: 28, text: "Bà ngoại rất tốt." },
  { id: 29, text: "Ông ngoại kể chuyện." },
  { id: 30, text: "Cảm ơn bố mẹ." },

  // Animals
  { id: 31, text: "Cá bơi.", category: "animal" },
  { id: 32, text: "Bé có ô." },
  { id: 33, text: "Chó sủa gâu gâu." },
  { id: 34, text: "Mèo mèo meo meo." },
  { id: 35, text: "Chim hót líu lo." },
  { id: 36, text: "Bò kêu cục cục." },
  { id: 37, text: "Voi có vòi dài." },
  { id: 38, text: "Khỉ nhảy lên cây." },
  { id: 39, text: "Ngựa chạy rất mạnh." },
  { id: 40, text: "Lợn thích lăn bùn." },
  { id: 41, text: "Thỏ chạy nhanh." },
  { id: 42, text: "Chuột sợ mèo." },
  { id: 43, text: "Gà gáy sáng sớm." },
  { id: 44, text: "Vịt bơi trên nước." },
  { id: 45, text: "Nai có sừng đẹp." },

  // Nature & Weather
  { id: 46, text: "Trời nắng đẹp.", category: "nature" },
  { id: 47, text: "Mưa nước mưa." },
  { id: 48, text: "Cây xanh tốt." },
  { id: 49, text: "Hoa hồng đỏ." },
  { id: 50, text: "Hoa sen trắng." },
  { id: 51, text: "Mây trắng bồng bồng." },
  { id: 52, text: "Gió thổi mát." },
  { id: 53, text: "Sóng biển xanh." },
  { id: 54, text: "Cồn cát vàng." },
  { id: 55, text: "Núi cao chạm trời." },
  { id: 56, text: "Sông chảy xiết xiết." },
  { id: 57, text: "Thác nước đẹp." },
  { id: 58, text: "Bụi tre xanh mát." },
  { id: 59, text: "Vườn hoa rực rỡ." },
  { id: 60, text: "Rừng cây rậm rạp." },

  // School & Learning
  { id: 61, text: "Đi học sớm sớm.", category: "school" },
  { id: 62, text: "Thầy dạy rất giỏi." },
  { id: 63, text: "Cô giáo tốt bụng." },
  { id: 64, text: "Lớp học sạch sẽ." },
  { id: 65, text: "Bạn tốt bụng lắm." },
  { id: 66, text: "Chơi cùng bạn." },
  { id: 67, text: "Giáo dục rất hay." },
  { id: 68, text: "Sách giáo khoa hay." },
  { id: 69, text: "Bút chì màu đẹp." },
  { id: 70, text: "Tập vở rất gọn." },
  { id: 71, text: "Tính toán lắm lí." },
  { id: 72, text: "Học bài rất tốt." },
  { id: 73, text: "Nghịch ngợm lắm." },
  { id: 74, text: "Chăm chỉ mỗi ngày." },
  { id: 75, text: "Cẩn thận làm bài." },

  // Emotions & Actions
  { id: 76, text: "Bé cười tươi tươi.", category: "emotion" },
  { id: 77, text: "Vui vẻ mỗi ngày." },
  { id: 78, text: "Buồn lắm rồi." },
  { id: 79, text: "Thích chơi trò chơi." },
  { id: 80, text: "Sợ những điều tối." },
  { id: 81, text: "Yêu bố yêu mẹ." },
  { id: 82, text: "Tức tưởi lắm." },
  { id: 83, text: "Hạnh phúc mỗi ngày." },
  { id: 84, text: "Khỏe mạnh rất tốt." },
  { id: 85, text: "Thôi đừng khóc nữa." },

  // Objects & Toys
  { id: 86, text: "Có búp bê đẹp.", category: "toy" },
  { id: 87, text: "Xe đua chạy nhanh." },
  { id: 88, text: "Bóng đúp đúp đúp." },
  { id: 89, text: "Nước đờn xanh xanh." },
  { id: 90, text: "Xúc xích rất vui." },
  { id: 91, text: "Gấu bông ôm chặt." },
  { id: 92, text: "Lego xây nhà cao." },
  { id: 93, text: "Búp bê xinh xinh." },
  { id: 94, text: "Xe máy không gõ." },
  { id: 95, text: "Đôi giày đẹp tuyệt." },
  { id: 96, text: "Mũ nón yêu yêu." },
  { id: 97, text: "Túi ba lô đầy." },
  { id: 98, text: "Đồng hồ đeo tay." },
  { id: 99, text: "Đèn pin sáng sáng." },
  { id: 100, text: "Kéo cắt rất sắc." },
  { id: 101, text: "Bông gòn mềm mại." },
  { id: 102, text: "Khăn quàng đẹp." },
];
