export type NumberQuantityCategory =
  | 'fruits'
  | 'animals'
  | 'shapes'
  | 'toys'
  | 'school';

export type NumberQuantityLevel = 'easy' | 'medium' | 'hard';

export type NumberQuantityQuestion = {
  id: string;
  prompt: string;
  hint: string;
  level: NumberQuantityLevel;
  category: NumberQuantityCategory;
  correctNumber: number;
  quantityEmoji: string;
  quantityLabel: string;
  options: number[];
};

export const numberQuantityCategories = [
  { key: 'fruits', label: 'Trái cây', icon: '🍎', total: 6 },
  { key: 'animals', label: 'Con vật', icon: '🐻', total: 6 },
  { key: 'shapes', label: 'Hình khối', icon: '🔺', total: 6 },
  { key: 'toys', label: 'Đồ chơi', icon: '🧸', total: 6 },
  { key: 'school', label: 'Đồ dùng học tập', icon: '✏️', total: 6 },
] as const;

export const numberQuantityData: Record<
  NumberQuantityCategory,
  {
    label: string;
    icon: string;
    questions: NumberQuantityQuestion[];
  }
> = {
  fruits: {
    label: 'Trái cây',
    icon: '🍎',
    questions: [
      {
        id: 'fruits-1',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số quả táo',
        level: 'easy',
        category: 'fruits',
        correctNumber: 1,
        quantityEmoji: '🍎',
        quantityLabel: '1 quả táo',
        options: [1, 2, 3, 4],
      },
      {
        id: 'fruits-2',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số quả chuối',
        level: 'easy',
        category: 'fruits',
        correctNumber: 2,
        quantityEmoji: '🍌🍌',
        quantityLabel: '2 quả chuối',
        options: [1, 2, 3, 4],
      },
      {
        id: 'fruits-3',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số quả cam',
        level: 'medium',
        category: 'fruits',
        correctNumber: 3,
        quantityEmoji: '🍊🍊🍊',
        quantityLabel: '3 quả cam',
        options: [2, 3, 4, 5],
      },
      {
        id: 'fruits-4',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số quả dâu',
        level: 'medium',
        category: 'fruits',
        correctNumber: 4,
        quantityEmoji: '🍓🍓🍓🍓',
        quantityLabel: '4 quả dâu',
        options: [3, 4, 5, 6],
      },
      {
        id: 'fruits-5',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số quả nho',
        level: 'hard',
        category: 'fruits',
        correctNumber: 5,
        quantityEmoji: '🍇🍇🍇🍇🍇',
        quantityLabel: '5 chùm nho',
        options: [4, 5, 6, 7],
      },
      {
        id: 'fruits-6',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số quả chanh',
        level: 'hard',
        category: 'fruits',
        correctNumber: 6,
        quantityEmoji: '🍋🍋🍋🍋🍋🍋',
        quantityLabel: '6 quả chanh',
        options: [5, 6, 7, 8],
      },
    ],
  },

  animals: {
    label: 'Con vật',
    icon: '🐻',
    questions: [
      {
        id: 'animals-1',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số con mèo',
        level: 'easy',
        category: 'animals',
        correctNumber: 1,
        quantityEmoji: '🐱',
        quantityLabel: '1 con mèo',
        options: [1, 2, 3, 4],
      },
      {
        id: 'animals-2',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số con chó',
        level: 'easy',
        category: 'animals',
        correctNumber: 2,
        quantityEmoji: '🐶🐶',
        quantityLabel: '2 con chó',
        options: [1, 2, 3, 4],
      },
      {
        id: 'animals-3',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số con cá',
        level: 'medium',
        category: 'animals',
        correctNumber: 3,
        quantityEmoji: '🐟🐟🐟',
        quantityLabel: '3 con cá',
        options: [2, 3, 4, 5],
      },
      {
        id: 'animals-4',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số con thỏ',
        level: 'medium',
        category: 'animals',
        correctNumber: 4,
        quantityEmoji: '🐰🐰🐰🐰',
        quantityLabel: '4 con thỏ',
        options: [3, 4, 5, 6],
      },
      {
        id: 'animals-5',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số con gà',
        level: 'hard',
        category: 'animals',
        correctNumber: 5,
        quantityEmoji: '🐔🐔🐔🐔🐔',
        quantityLabel: '5 con gà',
        options: [4, 5, 6, 7],
      },
      {
        id: 'animals-6',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số con vịt',
        level: 'hard',
        category: 'animals',
        correctNumber: 6,
        quantityEmoji: '🦆🦆🦆🦆🦆🦆',
        quantityLabel: '6 con vịt',
        options: [5, 6, 7, 8],
      },
    ],
  },

  shapes: {
    label: 'Hình khối',
    icon: '🔺',
    questions: [
      {
        id: 'shapes-1',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số hình tròn',
        level: 'easy',
        category: 'shapes',
        correctNumber: 1,
        quantityEmoji: '⚪',
        quantityLabel: '1 hình tròn',
        options: [1, 2, 3, 4],
      },
      {
        id: 'shapes-2',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số hình vuông',
        level: 'easy',
        category: 'shapes',
        correctNumber: 2,
        quantityEmoji: '🟦🟦',
        quantityLabel: '2 hình vuông',
        options: [1, 2, 3, 4],
      },
      {
        id: 'shapes-3',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số hình tam giác',
        level: 'medium',
        category: 'shapes',
        correctNumber: 3,
        quantityEmoji: '🔺🔺🔺',
        quantityLabel: '3 hình tam giác',
        options: [2, 3, 4, 5],
      },
      {
        id: 'shapes-4',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số hình ngôi sao',
        level: 'medium',
        category: 'shapes',
        correctNumber: 4,
        quantityEmoji: '⭐️⭐️⭐️⭐️',
        quantityLabel: '4 ngôi sao',
        options: [3, 4, 5, 6],
      },
      {
        id: 'shapes-5',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số hình thoi',
        level: 'hard',
        category: 'shapes',
        correctNumber: 5,
        quantityEmoji: '🔷🔷🔷🔷🔷',
        quantityLabel: '5 hình thoi',
        options: [4, 5, 6, 7],
      },
      {
        id: 'shapes-6',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số trái tim',
        level: 'hard',
        category: 'shapes',
        correctNumber: 6,
        quantityEmoji: '❤️❤️❤️❤️❤️❤️',
        quantityLabel: '6 trái tim',
        options: [5, 6, 7, 8],
      },
    ],
  },

  toys: {
    label: 'Đồ chơi',
    icon: '🧸',
    questions: [
      {
        id: 'toys-1',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số gấu bông',
        level: 'easy',
        category: 'toys',
        correctNumber: 1,
        quantityEmoji: '🧸',
        quantityLabel: '1 gấu bông',
        options: [1, 2, 3, 4],
      },
      {
        id: 'toys-2',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số quả bóng',
        level: 'easy',
        category: 'toys',
        correctNumber: 2,
        quantityEmoji: '⚽⚽',
        quantityLabel: '2 quả bóng',
        options: [1, 2, 3, 4],
      },
      {
        id: 'toys-3',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số con quay',
        level: 'medium',
        category: 'toys',
        correctNumber: 3,
        quantityEmoji: '🪀🪀🪀',
        quantityLabel: '3 con quay',
        options: [2, 3, 4, 5],
      },
      {
        id: 'toys-4',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số xe đồ chơi',
        level: 'medium',
        category: 'toys',
        correctNumber: 4,
        quantityEmoji: '🚗🚗🚗🚗',
        quantityLabel: '4 xe đồ chơi',
        options: [3, 4, 5, 6],
      },
      {
        id: 'toys-5',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số khối xếp hình',
        level: 'hard',
        category: 'toys',
        correctNumber: 5,
        quantityEmoji: '🧱🧱🧱🧱🧱',
        quantityLabel: '5 khối xếp hình',
        options: [4, 5, 6, 7],
      },
      {
        id: 'toys-6',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số búp bê',
        level: 'hard',
        category: 'toys',
        correctNumber: 6,
        quantityEmoji: '🪆🪆🪆🪆🪆🪆',
        quantityLabel: '6 búp bê',
        options: [5, 6, 7, 8],
      },
    ],
  },

  school: {
    label: 'Đồ dùng học tập',
    icon: '✏️',
    questions: [
      {
        id: 'school-1',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số bút chì',
        level: 'easy',
        category: 'school',
        correctNumber: 1,
        quantityEmoji: '✏️',
        quantityLabel: '1 bút chì',
        options: [1, 2, 3, 4],
      },
      {
        id: 'school-2',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số quyển sách',
        level: 'easy',
        category: 'school',
        correctNumber: 2,
        quantityEmoji: '📘📘',
        quantityLabel: '2 quyển sách',
        options: [1, 2, 3, 4],
      },
      {
        id: 'school-3',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số cục tẩy',
        level: 'medium',
        category: 'school',
        correctNumber: 3,
        quantityEmoji: '🩶🩶🩶',
        quantityLabel: '3 cục tẩy',
        options: [2, 3, 4, 5],
      },
      {
        id: 'school-4',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số thước kẻ',
        level: 'medium',
        category: 'school',
        correctNumber: 4,
        quantityEmoji: '📏📏📏📏',
        quantityLabel: '4 thước kẻ',
        options: [3, 4, 5, 6],
      },
      {
        id: 'school-5',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số cây bút màu',
        level: 'hard',
        category: 'school',
        correctNumber: 5,
        quantityEmoji: '🖍️🖍️🖍️🖍️🖍️',
        quantityLabel: '5 bút màu',
        options: [4, 5, 6, 7],
      },
      {
        id: 'school-6',
        prompt: 'Hãy chọn số đúng với số lượng hình',
        hint: 'Đếm số cặp sách',
        level: 'hard',
        category: 'school',
        correctNumber: 6,
        quantityEmoji: '🎒🎒🎒🎒🎒🎒',
        quantityLabel: '6 cặp sách',
        options: [5, 6, 7, 8],
      },
    ],
  },
};
