// Dữ liệu chuyên đề "Toán tư duy" lớp 1–5.
// CẤU TRÚC CHUẨN — câu hỏi thêm sau: chỉ cần đổ mảng vào `questions` của từng lớp,
// theo ĐÚNG format quiz đang dùng (question / options / correct_index / explanation +
// bản _speech cho TTS). Khi có câu hỏi, trang tự render + phát Quiz schema (hasPart).

export type TuDuyQuestion = {
  id: string;
  subject?: string;
  lesson?: string;
  question: string;
  question_speech?: string;
  options: string[];
  correct_index: number;
  countdown?: string[];
  explanation?: string;
  explanation_speech?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
};

export type TuDuyGrade = {
  grade: number;
  /** Mô tả unique cho SEO (2–3 câu). */
  intro: string;
  /** Các dạng bài toán tư duy của lớp — nội dung unique, hiển thị + dùng làm keyword. */
  topics: string[];
  faq: { q: string; a: string }[];
  /** Ngân hàng câu hỏi — ĐỔ VÀO SAU. */
  questions: TuDuyQuestion[];
};

export const GRADES = [1, 2, 3, 4, 5] as const;

export const TOAN_TU_DUY: Record<number, TuDuyGrade> = {
  1: {
    grade: 1,
    intro:
      'Toán tư duy lớp 1 giúp bé 6–7 tuổi làm quen với suy luận qua các bài đếm, so sánh, tìm quy luật và phân loại đơn giản. Bé học cách quan sát, phán đoán và giải thích lựa chọn của mình thay vì chỉ tính toán máy móc.',
    topics: [
      'Đếm và so sánh số lượng',
      'Tìm quy luật hình và màu sắc',
      'Ghép hình, xếp khối',
      'Phân loại theo đặc điểm',
      'Logic đơn giản (đúng – sai)',
      'Định hướng không gian: trái – phải, trên – dưới',
    ],
    faq: [
      { q: 'Toán tư duy lớp 1 học những gì?', a: 'Bé lớp 1 học đếm và so sánh, tìm quy luật hình – màu, ghép hình, phân loại và logic đơn giản — rèn khả năng quan sát và suy luận từ sớm.' },
      { q: 'Toán tư duy lớp 1 có khó không?', a: 'Không. Các bài được thiết kế nhẹ nhàng, nhiều hình ảnh trực quan, phù hợp bé 6–7 tuổi mới vào lớp 1, giúp bé thấy toán học thú vị.' },
      { q: 'Học toán tư duy sớm có lợi ích gì?', a: 'Giúp bé phát triển tư duy logic, khả năng quan sát và phán đoán, tạo nền tảng học toán vững vàng và tự tin hơn ở các lớp trên.' },
    ],
    questions: [
      {
        id: 'thu-thach-iq-lop-1-01',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trên cây có 3 con chim, bay đến thêm 2 con nữa.\nHỏi trên cây có tất cả mấy con chim?',
        question_speech: 'Trên cây có ba con chim, bay đến thêm hai con nữa. Hỏi trên cây có tất cả mấy con chim?',
        options: ['5 con', '4 con', '6 con', '3 con'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Có 3 con chim, thêm 2 con nữa: 3 + 2 = 5. Vậy trên cây có 5 con chim.',
        explanation_speech: 'Ba con chim thêm hai con nữa là năm con. Vậy trên cây có năm con chim.',
      },
      {
        id: 'thu-thach-iq-lop-1-02',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số liền sau của số 9 là số nào?',
        question_speech: 'Số liền sau của số chín là số nào?',
        options: ['8', '9', '10', '11'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Đếm tiếp sau 9 ta được 10. Vậy số liền sau của 9 là 10.',
        explanation_speech: 'Đếm tiếp sau chín ta được mười. Vậy số liền sau của chín là mười.',
      },
      {
        id: 'thu-thach-iq-lop-1-03',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trong các số 2, 4, 6, 7 số nào lớn nhất?',
        question_speech: 'Trong các số hai, bốn, sáu, bảy số nào lớn nhất?',
        options: ['2', '4', '6', '7'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'So sánh 2, 4, 6, 7 thì 7 là số lớn nhất.',
        explanation_speech: 'So sánh hai, bốn, sáu, bảy thì bảy là số lớn nhất.',
      },
      {
        id: 'thu-thach-iq-lop-1-04',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Điền số còn thiếu vào dãy: 1, 2, 3, ?, 5',
        question_speech: 'Điền số còn thiếu vào dãy: một, hai, ba, dấu hỏi, năm.',
        options: ['3', '4', '5', '6'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy số đếm tăng dần từng 1 đơn vị: 1, 2, 3, 4, 5. Số còn thiếu là 4.',
        explanation_speech: 'Dãy số tăng dần từng một đơn vị: một, hai, ba, bốn, năm. Số còn thiếu là bốn.',
      },
      {
        id: 'thu-thach-iq-lop-1-05',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 5 cái bánh, bé ăn 2 cái.\nHỏi còn lại mấy cái bánh?',
        question_speech: 'Có năm cái bánh, bé ăn hai cái. Hỏi còn lại mấy cái bánh?',
        options: ['1', '2', '3', '4'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Còn lại bằng 5 trừ 2: 5 − 2 = 3. Vậy còn 3 cái bánh.',
        explanation_speech: 'Năm trừ hai bằng ba. Vậy còn ba cái bánh.',
      },
      {
        id: 'thu-thach-iq-lop-1-06',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một con gà có 2 chân.\nHỏi 3 con gà có bao nhiêu chân?',
        question_speech: 'Một con gà có hai chân. Hỏi ba con gà có bao nhiêu chân?',
        options: ['6', '5', '8', '4'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi con 2 chân, 3 con là 2 + 2 + 2 = 6 chân.',
        explanation_speech: 'Mỗi con hai chân, ba con là hai cộng hai cộng hai bằng sáu chân.',
      },
      {
        id: 'thu-thach-iq-lop-1-07',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Lan cao hơn Mai. Mai cao hơn Hoa.\nHỏi ai thấp nhất?',
        question_speech: 'Lan cao hơn Mai. Mai cao hơn Hoa. Hỏi ai thấp nhất?',
        options: ['Lan', 'Mai', 'Hoa', 'Không rõ'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Lan cao hơn Mai, Mai cao hơn Hoa nên Hoa thấp nhất.',
        explanation_speech: 'Lan cao hơn Mai, Mai cao hơn Hoa, nên Hoa là người thấp nhất.',
      },
      {
        id: 'thu-thach-iq-lop-1-08',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Dãy màu lặp lại: đỏ, xanh, đỏ, xanh, đỏ, …\nHỏi màu tiếp theo là màu gì?',
        question_speech: 'Dãy màu lặp lại: đỏ, xanh, đỏ, xanh, đỏ. Hỏi màu tiếp theo là màu gì?',
        options: ['Đỏ', 'Xanh', 'Vàng', 'Tím'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Quy luật là đỏ rồi xanh xen kẽ. Sau màu đỏ sẽ đến màu xanh.',
        explanation_speech: 'Quy luật là đỏ rồi xanh xen kẽ nhau. Sau màu đỏ sẽ đến màu xanh.',
      },
      {
        id: 'thu-thach-iq-lop-1-09',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Điền số còn thiếu vào dãy: 2, 4, 6, ?, 10',
        question_speech: 'Điền số còn thiếu vào dãy: hai, bốn, sáu, dấu hỏi, mười.',
        options: ['5', '6', '7', '8'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy số tăng dần từng 2 đơn vị: 2, 4, 6, 8, 10. Số còn thiếu là 8.',
        explanation_speech: 'Dãy số tăng dần từng hai đơn vị: hai, bốn, sáu, tám, mười. Số còn thiếu là tám.',
      },
      {
        id: 'thu-thach-iq-lop-1-10',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bé có 4 viên bi xanh và 3 viên bi đỏ.\nBé cho bạn 2 viên.\nHỏi bé còn lại mấy viên bi?',
        question_speech: 'Bé có bốn viên bi xanh và ba viên bi đỏ. Bé cho bạn hai viên. Hỏi bé còn lại mấy viên bi?',
        options: ['4', '5', '6', '7'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Bé có tất cả 4 + 3 = 7 viên. Cho bạn 2 viên còn 7 − 2 = 5 viên.',
        explanation_speech: 'Bé có tất cả bốn cộng ba bằng bảy viên. Cho bạn hai viên, còn bảy trừ hai bằng năm viên.',
      },
    ],
  },
  2: {
    grade: 2,
    intro:
      'Toán tư duy lớp 2 mở rộng suy luận với dãy số theo quy luật, phép cộng – trừ có lời văn, đếm hình và các bài logic. Bé tập phân tích đề bài, tìm mối liên hệ và trình bày cách giải rõ ràng.',
    topics: [
      'Dãy số theo quy luật',
      'Phép cộng, trừ có suy luận',
      'Đếm hình (tam giác, hình vuông)',
      'Bài toán logic đơn giản',
      'Tìm số còn thiếu',
      'Suy luận về tuổi, nhiều hơn – ít hơn',
    ],
    faq: [
      { q: 'Toán tư duy lớp 2 gồm những dạng nào?', a: 'Gồm dãy số quy luật, cộng trừ có suy luận, đếm hình, tìm số còn thiếu và các bài logic về tuổi, nhiều hơn – ít hơn.' },
      { q: 'Làm sao giúp bé lớp 2 học toán tư duy hiệu quả?', a: 'Cho bé đọc kỹ đề, vẽ hình hoặc liệt kê trường hợp, và giải thích tại sao chọn đáp án đó — hiểu bản chất thay vì học vẹt.' },
      { q: 'Toán tư duy khác gì toán trên lớp?', a: 'Toán tư duy nhấn vào suy luận và cách nghĩ, thường có nhiều cách tiếp cận, giúp bé linh hoạt hơn so với việc chỉ áp dụng công thức.' },
    ],
    questions: [
      {
        id: 'thu-thach-iq-lop-2-01',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Lan có 15 cái kẹo, cho bạn 6 cái. Lan còn lại mấy cái?',
        options: ['9 cái', '8 cái', '11 cái', '21 cái'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '15 − 6 = 9. Lan còn 9 cái kẹo.',
      },
      {
        id: 'thu-thach-iq-lop-2-02',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 4 rổ, mỗi rổ 5 quả cam. Tất cả có bao nhiêu quả cam?',
        options: ['9 quả', '20 quả', '15 quả', '25 quả'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '4 × 5 = 20 quả cam.',
      },
      {
        id: 'thu-thach-iq-lop-2-03',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số liền trước của số 30 là số nào?',
        options: ['31', '20', '29', '28'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Liền trước 30 là 30 − 1 = 29.',
      },
      {
        id: 'thu-thach-iq-lop-2-04',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Điền số còn thiếu vào dãy: 2, 4, 6, ?, 10',
        options: ['7', '9', '12', '8'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy tăng đều 2 đơn vị: 6 + 2 = 8.',
      },
      {
        id: 'thu-thach-iq-lop-2-05',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'An cao 105cm, Bình thấp hơn An 8cm. Bình cao bao nhiêu?',
        options: ['97cm', '113cm', '98cm', '107cm'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '105 − 8 = 97cm.',
      },
      {
        id: 'thu-thach-iq-lop-2-06',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một tuần lễ có mấy ngày?',
        options: ['5 ngày', '7 ngày', '10 ngày', '30 ngày'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một tuần có 7 ngày.',
      },
      {
        id: 'thu-thach-iq-lop-2-07',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hình nào có 4 cạnh bằng nhau?',
        options: ['Hình tam giác', 'Hình tròn', 'Hình vuông', 'Hình chữ nhật'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Hình vuông có 4 cạnh bằng nhau.',
      },
      {
        id: 'thu-thach-iq-lop-2-08',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '24 + 18 = ?',
        options: ['32', '44', '40', '42'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '24 + 18 = 42.',
      },
      {
        id: 'thu-thach-iq-lop-2-09',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Mẹ mua 3 chục quả trứng. Có tất cả bao nhiêu quả?',
        options: ['30 quả', '13 quả', '3 quả', '33 quả'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '3 chục = 3 × 10 = 30 quả.',
      },
      {
        id: 'thu-thach-iq-lop-2-10',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Nam có 12 viên bi, nhiều hơn Hoa 5 viên. Hoa có mấy viên?',
        options: ['17 viên', '7 viên', '6 viên', '8 viên'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '12 − 5 = 7 viên.',
      },
      {
        id: 'thu-thach-iq-lop-2-11',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số lớn nhất trong các số 45, 54, 40, 44 là số nào?',
        options: ['45', '44', '54', '40'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '54 là số lớn nhất.',
      },
      {
        id: 'thu-thach-iq-lop-2-12',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '5 × 3 = ?',
        options: ['8', '10', '35', '15'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '5 × 3 = 15.',
      },
    ],
  },
  3: {
    grade: 3,
    intro:
      'Toán tư duy lớp 3 đưa bé đến các bài toán nhân – chia có suy luận, trồng cây, dãy số và logic loại trừ. Bé rèn khả năng lập luận theo nhiều bước và kiểm tra lại kết quả.',
    topics: [
      'Phép nhân, chia có suy luận',
      'Bài toán trồng cây, khoảng cách',
      'Dãy số và quy luật',
      'Suy luận logic (phương pháp loại trừ)',
      'Đếm hình và hình học',
      'Bài toán về thời gian, lịch',
    ],
    faq: [
      { q: 'Toán tư duy lớp 3 học gì?', a: 'Bé học nhân chia có suy luận, bài toán trồng cây, dãy số, suy luận loại trừ, đếm hình và bài toán thời gian – lịch.' },
      { q: 'Bài toán trồng cây là gì?', a: 'Là dạng toán tính số cây (hoặc cọc, đèn…) trồng trên đoạn đường theo khoảng cách — kinh điển trong toán tư duy lớp 3, rèn cách suy luận về khoảng và số điểm.' },
      { q: 'Bé cần chuẩn bị gì để học tốt?', a: 'Nắm chắc bảng cửu chương và phép nhân chia cơ bản, sau đó luyện đọc – phân tích đề để chọn cách giải phù hợp.' },
    ],
    questions: [
      {
        id: 'thu-thach-iq-lop-3-01',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 6 hộp, mỗi hộp 8 chiếc bút. Tất cả có bao nhiêu chiếc bút?',
        options: ['48 bút', '14 bút', '54 bút', '40 bút'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '6 × 8 = 48 bút.',
      },
      {
        id: 'thu-thach-iq-lop-3-02',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '42 : 6 = ?',
        options: ['6', '7', '8', '9'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '42 : 6 = 7.',
      },
      {
        id: 'thu-thach-iq-lop-3-03',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hình chữ nhật dài 5cm, rộng 3cm. Chu vi hình đó là?',
        options: ['8cm', '15cm', '16cm', '13cm'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Chu vi = (5 + 3) × 2 = 16cm.',
      },
      {
        id: 'thu-thach-iq-lop-3-04',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Điền số còn thiếu: 5, 10, 15, ?, 25',
        options: ['18', '22', '21', '20'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy tăng đều 5: 15 + 5 = 20.',
      },
      {
        id: 'thu-thach-iq-lop-3-05',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Lan có 36 bông hoa, chia đều vào 4 bình. Mỗi bình mấy bông?',
        options: ['9 bông', '8 bông', '6 bông', '12 bông'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '36 : 4 = 9 bông.',
      },
      {
        id: 'thu-thach-iq-lop-3-06',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Gấp 7 lên 4 lần được số nào?',
        options: ['11', '28', '21', '24'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '7 × 4 = 28.',
      },
      {
        id: 'thu-thach-iq-lop-3-07',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một ngày có bao nhiêu giờ?',
        options: ['12 giờ', '60 giờ', '24 giờ', '7 giờ'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một ngày có 24 giờ.',
      },
      {
        id: 'thu-thach-iq-lop-3-08',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '125 + 78 = ?',
        options: ['193', '213', '198', '203'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '125 + 78 = 203.',
      },
      {
        id: 'thu-thach-iq-lop-3-09',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 5 chiếc ô tô, mỗi xe có 4 bánh. Tất cả có mấy bánh xe?',
        options: ['20 bánh', '9 bánh', '16 bánh', '24 bánh'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '5 × 4 = 20 bánh.',
      },
      {
        id: 'thu-thach-iq-lop-3-10',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số nào sau đây chia hết cho 5?',
        options: ['12', '20', '33', '47'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '20 : 5 = 4 nên 20 chia hết cho 5.',
      },
      {
        id: 'thu-thach-iq-lop-3-11',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tìm x, biết: x × 3 = 27',
        options: ['8', '24', '9', '30'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'x = 27 : 3 = 9.',
      },
      {
        id: 'thu-thach-iq-lop-3-12',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Mai có 48 quyển vở, cho đi 1/4 số vở. Mai cho đi mấy quyển?',
        options: ['4 quyển', '24 quyển', '16 quyển', '12 quyển'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '48 : 4 = 12 quyển.',
      },
    ],
  },
  4: {
    grade: 4,
    intro:
      'Toán tư duy lớp 4 tập trung vào các bài toán tổng – hiệu, tổng – tỉ, dãy số cách đều và suy luận logic nâng cao. Bé học cách đặt bài toán về dạng quen thuộc và giải bằng sơ đồ, lập luận.',
    topics: [
      'Tìm hai số khi biết tổng và hiệu',
      'Tìm hai số khi biết tổng và tỉ',
      'Dãy số cách đều',
      'Suy luận logic nâng cao',
      'Chu vi, diện tích theo tư duy',
      'Bài toán tính ngược',
    ],
    faq: [
      { q: 'Toán tư duy lớp 4 gồm dạng bài nào?', a: 'Gồm tổng – hiệu, tổng – tỉ, dãy số cách đều, suy luận logic nâng cao, chu vi – diện tích tư duy và bài toán tính ngược.' },
      { q: 'Vẽ sơ đồ đoạn thẳng có giúp ích không?', a: 'Rất hữu ích. Sơ đồ đoạn thẳng giúp bé nhìn rõ mối quan hệ tổng – hiệu – tỉ và tìm ra lời giải nhanh, chính xác.' },
      { q: 'Học toán tư duy lớp 4 để làm gì?', a: 'Giúp bé làm chủ các dạng toán điển hình, chuẩn bị cho kiểm tra, thi học sinh giỏi và tạo nền tảng cho toán lớp 5.' },
    ],
    questions: [
      {
        id: 'thu-thach-iq-lop-4-01',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '25 × 4 = ?',
        options: ['100', '29', '90', '125'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '25 × 4 = 100.',
      },
      {
        id: 'thu-thach-iq-lop-4-02',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '144 : 12 = ?',
        options: ['11', '12', '14', '24'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '144 : 12 = 12.',
      },
      {
        id: 'thu-thach-iq-lop-4-03',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trung bình cộng của 6 và 10 là bao nhiêu?',
        options: ['16', '7', '8', '9'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '(6 + 10) : 2 = 8.',
      },
      {
        id: 'thu-thach-iq-lop-4-04',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một hình vuông có cạnh 6cm. Diện tích hình vuông đó là?',
        options: ['24 cm²', '12 cm²', '30 cm²', '36 cm²'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Diện tích = 6 × 6 = 36 cm².',
      },
      {
        id: 'thu-thach-iq-lop-4-05',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một nửa (1/2) của 40 là bao nhiêu?',
        options: ['20', '80', '10', '4'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '40 : 2 = 20.',
      },
      {
        id: 'thu-thach-iq-lop-4-06',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 3 thùng, mỗi thùng 24 chai nước. Tất cả có bao nhiêu chai?',
        options: ['27 chai', '72 chai', '48 chai', '64 chai'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '3 × 24 = 72 chai.',
      },
      {
        id: 'thu-thach-iq-lop-4-07',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số lẻ liền sau số 47 là số nào?',
        options: ['48', '45', '49', '51'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Số lẻ liền sau 47 là 49.',
      },
      {
        id: 'thu-thach-iq-lop-4-08',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một giờ có bao nhiêu phút?',
        options: ['100 phút', '30 phút', '24 phút', '60 phút'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một giờ có 60 phút.',
      },
      {
        id: 'thu-thach-iq-lop-4-09',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Mua 5 quyển vở, mỗi quyển 8 000 đồng. Hết tất cả bao nhiêu tiền?',
        options: ['40 000đ', '13 000đ', '45 000đ', '35 000đ'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '5 × 8 000 = 40 000đ.',
      },
      {
        id: 'thu-thach-iq-lop-4-10',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tìm x, biết: x : 6 = 8',
        options: ['14', '48', '42', '54'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'x = 8 × 6 = 48.',
      },
      {
        id: 'thu-thach-iq-lop-4-11',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Ba phần tư (3/4) của 12 là bao nhiêu?',
        options: ['8', '6', '9', '12'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '12 : 4 × 3 = 9.',
      },
      {
        id: 'thu-thach-iq-lop-4-12',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một đội có 32 bạn, xếp đều thành 4 hàng. Mỗi hàng có mấy bạn?',
        options: ['7 bạn', '6 bạn', '9 bạn', '8 bạn'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '32 : 4 = 8 bạn.',
      },
    ],
  },
  5: {
    grade: 5,
    intro:
      'Toán tư duy lớp 5 nâng cao với toán chuyển động, tỉ số phần trăm, phân số và hình học nâng cao. Bé rèn tư duy phân tích, tổng hợp và giải các bài toán nhiều bước — hành trang vững cho bậc THCS.',
    topics: [
      'Toán chuyển động (vận tốc, quãng đường, thời gian)',
      'Tỉ số phần trăm theo tư duy',
      'Phân số và bài toán tỉ lệ',
      'Suy luận logic nâng cao',
      'Hình học nâng cao (diện tích, thể tích)',
      'Bài toán cổ, bài toán dân gian',
    ],
    faq: [
      { q: 'Toán tư duy lớp 5 học những gì?', a: 'Bé học toán chuyển động, tỉ số phần trăm, phân số – tỉ lệ, suy luận nâng cao, hình học nâng cao và các bài toán cổ.' },
      { q: 'Toán tư duy lớp 5 có giúp thi vào lớp 6 không?', a: 'Có. Nhiều dạng bài tư duy lớp 5 xuất hiện trong đề khảo sát và thi vào lớp 6 chất lượng cao, nên luyện tập sớm rất có lợi.' },
      { q: 'Làm sao để bé giải nhanh bài nhiều bước?', a: 'Tập tóm tắt đề, chia bài toán thành các bước nhỏ, và luôn kiểm tra lại kết quả bằng cách thử hoặc ước lượng.' },
    ],
    questions: [
      {
        id: 'thu-thach-iq-lop-5-01',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '2,5 + 1,5 = ?',
        options: ['4', '3', '4,5', '3,5'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '2,5 + 1,5 = 4.',
      },
      {
        id: 'thu-thach-iq-lop-5-02',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '1/2 + 1/4 bằng bao nhiêu?',
        options: ['2/6', '3/4', '1/2', '1'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '1/2 = 2/4; 2/4 + 1/4 = 3/4.',
      },
      {
        id: 'thu-thach-iq-lop-5-03',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '10% của 200 là bao nhiêu?',
        options: ['10', '100', '20', '2'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '200 : 10 = 20.',
      },
      {
        id: 'thu-thach-iq-lop-5-04',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hình chữ nhật dài 8cm, rộng 5cm. Diện tích là bao nhiêu?',
        options: ['13 cm²', '26 cm²', '45 cm²', '40 cm²'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Diện tích = 8 × 5 = 40 cm².',
      },
      {
        id: 'thu-thach-iq-lop-5-05',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một ô tô đi 60km trong 2 giờ. Vận tốc của ô tô là?',
        options: ['30 km/giờ', '120 km/giờ', '62 km/giờ', '15 km/giờ'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Vận tốc = 60 : 2 = 30 km/giờ.',
      },
      {
        id: 'thu-thach-iq-lop-5-06',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '3,6 × 10 = ?',
        options: ['3,6', '36', '360', '30,6'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '3,6 × 10 = 36.',
      },
      {
        id: 'thu-thach-iq-lop-5-07',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trung bình cộng của 4, 6 và 8 là bao nhiêu?',
        options: ['18', '9', '6', '7'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '(4 + 6 + 8) : 3 = 6.',
      },
      {
        id: 'thu-thach-iq-lop-5-08',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '1 giờ 30 phút bằng bao nhiêu phút?',
        options: ['130 phút', '60 phút', '75 phút', '90 phút'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '1 giờ = 60 phút; 60 + 30 = 90 phút.',
      },
      {
        id: 'thu-thach-iq-lop-5-09',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số thập phân 0,5 bằng phân số nào?',
        options: ['1/2', '1/5', '1/4', '5/1'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '0,5 = 5/10 = 1/2.',
      },
      {
        id: 'thu-thach-iq-lop-5-10',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một mảnh vườn hình vuông cạnh 10m. Chu vi mảnh vườn là?',
        options: ['100m', '40m', '20m', '14m'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Chu vi = 10 × 4 = 40m.',
      },
      {
        id: 'thu-thach-iq-lop-5-11',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '25% của 80 là bao nhiêu?',
        options: ['25', '40', '20', '16'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '80 : 4 = 20.',
      },
      {
        id: 'thu-thach-iq-lop-5-12',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '144 : 12 + 6 = ?',
        options: ['12', '24', '66', '18'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tính chia trước: 144 : 12 = 12; 12 + 6 = 18.',
      },
    ],
  },
};

export function getTuDuyGrade(grade: number): TuDuyGrade | null {
  return TOAN_TU_DUY[grade] ?? null;
}
