// Dữ liệu chuyên đề "Toán tư duy" lớp 1–5.
// CẤU TRÚC CHUẨN — câu hỏi thêm sau: chỉ cần đổ mảng vào `questions` của từng lớp,
// theo ĐÚNG format quiz đang dùng (question / options / correct_index / explanation +
// bản _speech cho TTS). Khi có câu hỏi, trang tự render + phát Quiz schema (hasPart).

export type TuDuyQuestion = {
  id: string;
  subject?: string;
  lesson?: string;
  question: string;
  question_speech?: string;
  options: string[];
  correct_index: number;
  countdown?: string[];
  explanation?: string;
  explanation_speech?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
};

export type TuDuyGrade = {
  grade: number;
  /** Mô tả unique cho SEO (2–3 câu). */
  intro: string;
  /** Các dạng bài toán tư duy của lớp — nội dung unique, hiển thị + dùng làm keyword. */
  topics: string[];
  faq: { q: string; a: string }[];
  /** Ngân hàng câu hỏi — ĐỔ VÀO SAU. */
  questions: TuDuyQuestion[];
};

export const GRADES = [1, 2, 3, 4, 5] as const;

export const TOAN_TU_DUY: Record<number, TuDuyGrade> = {
  1: {
    grade: 1,
    intro:
      'Toán tư duy lớp 1 giúp bé 6–7 tuổi làm quen với suy luận qua các bài đếm, so sánh, tìm quy luật và phân loại đơn giản. Bé học cách quan sát, phán đoán và giải thích lựa chọn của mình thay vì chỉ tính toán máy móc.',
    topics: [
      'Đếm và so sánh số lượng',
      'Tìm quy luật hình và màu sắc',
      'Ghép hình, xếp khối',
      'Phân loại theo đặc điểm',
      'Logic đơn giản (đúng – sai)',
      'Định hướng không gian: trái – phải, trên – dưới',
    ],
    faq: [
      { q: 'Toán tư duy lớp 1 học những gì?', a: 'Bé lớp 1 học đếm và so sánh, tìm quy luật hình – màu, ghép hình, phân loại và logic đơn giản — rèn khả năng quan sát và suy luận từ sớm.' },
      { q: 'Toán tư duy lớp 1 có khó không?', a: 'Không. Các bài được thiết kế nhẹ nhàng, nhiều hình ảnh trực quan, phù hợp bé 6–7 tuổi mới vào lớp 1, giúp bé thấy toán học thú vị.' },
      { q: 'Học toán tư duy sớm có lợi ích gì?', a: 'Giúp bé phát triển tư duy logic, khả năng quan sát và phán đoán, tạo nền tảng học toán vững vàng và tự tin hơn ở các lớp trên.' },
    ],
    questions: [
      {
        id: 'thu-thach-iq-lop-1-01',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trên cây có 3 con chim, bay đến thêm 2 con nữa.\nHỏi trên cây có tất cả mấy con chim?',
        question_speech: 'Trên cây có ba con chim, bay đến thêm hai con nữa. Hỏi trên cây có tất cả mấy con chim?',
        options: ['5 con', '4 con', '6 con', '3 con'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Có 3 con chim, thêm 2 con nữa: 3 + 2 = 5. Vậy trên cây có 5 con chim.',
        explanation_speech: 'Ba con chim thêm hai con nữa là năm con. Vậy trên cây có năm con chim.',
      },
      {
        id: 'thu-thach-iq-lop-1-02',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số liền sau của số 9 là số nào?',
        question_speech: 'Số liền sau của số chín là số nào?',
        options: ['8', '9', '10', '11'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Đếm tiếp sau 9 ta được 10. Vậy số liền sau của 9 là 10.',
        explanation_speech: 'Đếm tiếp sau chín ta được mười. Vậy số liền sau của chín là mười.',
      },
      {
        id: 'thu-thach-iq-lop-1-03',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trong các số 2, 4, 6, 7 số nào lớn nhất?',
        question_speech: 'Trong các số hai, bốn, sáu, bảy số nào lớn nhất?',
        options: ['2', '4', '6', '7'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'So sánh 2, 4, 6, 7 thì 7 là số lớn nhất.',
        explanation_speech: 'So sánh hai, bốn, sáu, bảy thì bảy là số lớn nhất.',
      },
      {
        id: 'thu-thach-iq-lop-1-04',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Điền số còn thiếu vào dãy: 1, 2, 3, ?, 5',
        question_speech: 'Điền số còn thiếu vào dãy: một, hai, ba, dấu hỏi, năm.',
        options: ['3', '4', '5', '6'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy số đếm tăng dần từng 1 đơn vị: 1, 2, 3, 4, 5. Số còn thiếu là 4.',
        explanation_speech: 'Dãy số tăng dần từng một đơn vị: một, hai, ba, bốn, năm. Số còn thiếu là bốn.',
      },
      {
        id: 'thu-thach-iq-lop-1-05',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 5 cái bánh, bé ăn 2 cái.\nHỏi còn lại mấy cái bánh?',
        question_speech: 'Có năm cái bánh, bé ăn hai cái. Hỏi còn lại mấy cái bánh?',
        options: ['1', '2', '3', '4'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Còn lại bằng 5 trừ 2: 5 − 2 = 3. Vậy còn 3 cái bánh.',
        explanation_speech: 'Năm trừ hai bằng ba. Vậy còn ba cái bánh.',
      },
      {
        id: 'thu-thach-iq-lop-1-06',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một con gà có 2 chân.\nHỏi 3 con gà có bao nhiêu chân?',
        question_speech: 'Một con gà có hai chân. Hỏi ba con gà có bao nhiêu chân?',
        options: ['6', '5', '8', '4'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi con 2 chân, 3 con là 2 + 2 + 2 = 6 chân.',
        explanation_speech: 'Mỗi con hai chân, ba con là hai cộng hai cộng hai bằng sáu chân.',
      },
      {
        id: 'thu-thach-iq-lop-1-07',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Lan cao hơn Mai. Mai cao hơn Hoa.\nHỏi ai thấp nhất?',
        question_speech: 'Lan cao hơn Mai. Mai cao hơn Hoa. Hỏi ai thấp nhất?',
        options: ['Lan', 'Mai', 'Hoa', 'Không rõ'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Lan cao hơn Mai, Mai cao hơn Hoa nên Hoa thấp nhất.',
        explanation_speech: 'Lan cao hơn Mai, Mai cao hơn Hoa, nên Hoa là người thấp nhất.',
      },
      {
        id: 'thu-thach-iq-lop-1-08',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Dãy màu lặp lại: đỏ, xanh, đỏ, xanh, đỏ, …\nHỏi màu tiếp theo là màu gì?',
        question_speech: 'Dãy màu lặp lại: đỏ, xanh, đỏ, xanh, đỏ. Hỏi màu tiếp theo là màu gì?',
        options: ['Đỏ', 'Xanh', 'Vàng', 'Tím'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Quy luật là đỏ rồi xanh xen kẽ. Sau màu đỏ sẽ đến màu xanh.',
        explanation_speech: 'Quy luật là đỏ rồi xanh xen kẽ nhau. Sau màu đỏ sẽ đến màu xanh.',
      },
      {
        id: 'thu-thach-iq-lop-1-09',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Điền số còn thiếu vào dãy: 2, 4, 6, ?, 10',
        question_speech: 'Điền số còn thiếu vào dãy: hai, bốn, sáu, dấu hỏi, mười.',
        options: ['5', '6', '7', '8'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy số tăng dần từng 2 đơn vị: 2, 4, 6, 8, 10. Số còn thiếu là 8.',
        explanation_speech: 'Dãy số tăng dần từng hai đơn vị: hai, bốn, sáu, tám, mười. Số còn thiếu là tám.',
      },
      {
        id: 'thu-thach-iq-lop-1-10',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bé có 4 viên bi xanh và 3 viên bi đỏ.\nBé cho bạn 2 viên.\nHỏi bé còn lại mấy viên bi?',
        question_speech: 'Bé có bốn viên bi xanh và ba viên bi đỏ. Bé cho bạn hai viên. Hỏi bé còn lại mấy viên bi?',
        options: ['4', '5', '6', '7'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Bé có tất cả 4 + 3 = 7 viên. Cho bạn 2 viên còn 7 − 2 = 5 viên.',
        explanation_speech: 'Bé có tất cả bốn cộng ba bằng bảy viên. Cho bạn hai viên, còn bảy trừ hai bằng năm viên.',
      },
      {
        id: 'thu-thach-iq-lop-1-11',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bé có 4 cái kẹo, bé cho bạn 1 cái.\nHỏi bé còn mấy cái kẹo?',
        question_speech: 'Bé có bốn cái kẹo, bé cho bạn một cái. Hỏi bé còn mấy cái kẹo?',
        options: ['3 cái', '5 cái', '2 cái', '4 cái'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Có 4 cái, cho đi 1 cái: 4 − 1 = 3. Vậy bé còn 3 cái kẹo.',
        explanation_speech: 'Bốn cái bớt một cái còn ba cái.',
      },
      {
        id: 'thu-thach-iq-lop-1-12',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Dãy hình: 🔴 🔵 🔴 🔵 🔴 ...\nHình tiếp theo là hình gì?',
        question_speech: 'Dãy hình đỏ, xanh, đỏ, xanh, đỏ. Hình tiếp theo là hình gì?',
        options: ['Xanh', 'Đỏ', 'Vàng', 'Không có'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy lặp lại đỏ rồi xanh. Sau hình đỏ thứ ba sẽ tới hình xanh.',
        explanation_speech: 'Dãy cứ đỏ rồi xanh nên hình tiếp theo là hình xanh.',
      },
      {
        id: 'thu-thach-iq-lop-1-13',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số nào bé hơn: 7 hay 5?',
        question_speech: 'Số nào bé hơn, bảy hay năm?',
        options: ['5', '7', 'Bằng nhau', 'Không biết'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Đếm từ 1: số 5 đứng trước số 7 nên 5 bé hơn 7.',
        explanation_speech: 'Năm đứng trước bảy nên năm bé hơn.',
      },
      {
        id: 'thu-thach-iq-lop-1-14',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bé xếp hàng, trước bé có 2 bạn, sau bé có 1 bạn.\nHỏi hàng có tất cả mấy bạn?',
        question_speech: 'Bé xếp hàng, trước bé có hai bạn, sau bé có một bạn. Hỏi hàng có tất cả mấy bạn?',
        options: ['4 bạn', '3 bạn', '5 bạn', '2 bạn'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Đếm cả bé: 2 bạn trước + chính bé + 1 bạn sau = 4 bạn. Nhớ đếm cả mình là chỗ dễ quên nhất.',
        explanation_speech: 'Hai bạn trước, cộng chính bé, cộng một bạn sau là bốn bạn.',
      },
      {
        id: 'thu-thach-iq-lop-1-15',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số liền trước của số 6 là số nào?',
        question_speech: 'Số liền trước của số sáu là số nào?',
        options: ['5', '7', '4', '6'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Đếm lùi từ 6 ta được 5. Vậy số liền trước của 6 là 5.',
        explanation_speech: 'Đếm lùi từ 6 ta được 5. Vậy số liền trước của 6 là 5.',
      },
      {
        id: 'thu-thach-iq-lop-1-16',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 3 con mèo, mỗi con có mấy cái tai?\nTất cả có mấy cái tai?',
        question_speech: 'Có ba con mèo, mỗi con có hai cái tai. Tất cả có mấy cái tai?',
        options: ['6 cái', '3 cái', '5 cái', '4 cái'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi con 2 tai, 3 con là 2 + 2 + 2 = 6 cái tai.',
        explanation_speech: 'Hai cộng hai cộng hai bằng sáu.',
      },
      {
        id: 'thu-thach-iq-lop-1-17',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bạn nào cao nhất?\nAn cao hơn Bình. Bình cao hơn Cường.',
        question_speech: 'An cao hơn Bình. Bình cao hơn Cường. Bạn nào cao nhất?',
        options: ['An', 'Bình', 'Cường', 'Bằng nhau'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'An cao hơn Bình, mà Bình lại cao hơn Cường, nên An cao nhất.',
        explanation_speech: 'An cao hơn Bình, Bình cao hơn Cường, vậy An cao nhất.',
      },
      {
        id: 'thu-thach-iq-lop-1-18',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trong rổ có 2 quả táo và 3 quả cam.\nHỏi trong rổ có mấy quả?',
        question_speech: 'Trong rổ có hai quả táo và ba quả cam. Hỏi trong rổ có mấy quả?',
        options: ['5 quả', '6 quả', '4 quả', '3 quả'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Táo và cam đều là quả: 2 + 3 = 5 quả.',
        explanation_speech: 'Hai cộng ba bằng năm quả.',
      },
      {
        id: 'thu-thach-iq-lop-1-19',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hình nào KHÁC nhóm: 🍎 🍌 🍇 🚗 ?',
        question_speech: 'Hình nào khác nhóm: quả táo, quả chuối, chùm nho, cái ô tô?',
        options: ['Ô tô', 'Táo', 'Chuối', 'Nho'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Táo, chuối, nho đều là trái cây; ô tô là xe nên khác nhóm.',
        explanation_speech: 'Ba thứ kia là trái cây, ô tô là xe nên khác nhóm.',
      },
      {
        id: 'thu-thach-iq-lop-1-20',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bé đứng quay mặt ra cửa. Tay phải bé chỉ về phía tủ.\nTủ ở bên nào của bé?',
        question_speech: 'Bé đứng quay mặt ra cửa. Tay phải bé chỉ về phía tủ. Tủ ở bên nào của bé?',
        options: ['Bên phải', 'Bên trái', 'Phía trước', 'Phía sau'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tay phải chỉ về phía nào thì phía đó là bên phải của bé.',
        explanation_speech: 'Tay phải chỉ tới đâu thì đó là bên phải.',
      },
      {
        id: 'thu-thach-iq-lop-1-21',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số nào điền vào chỗ trống: 2, 4, 6, ___, 10',
        question_speech: 'Điền số còn thiếu: hai, bốn, sáu, chấm chấm, mười.',
        options: ['8', '7', '9', '5'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy tăng dần 2 đơn vị: 2, 4, 6, 8, 10.',
        explanation_speech: 'Mỗi số hơn số trước hai đơn vị nên chỗ trống là tám.',
      },
      {
        id: 'thu-thach-iq-lop-1-22',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Mẹ cho bé 2 cái bánh, bà cho thêm 3 cái.\nBé ăn hết 1 cái. Bé còn mấy cái?',
        question_speech: 'Mẹ cho bé hai cái bánh, bà cho thêm ba cái. Bé ăn hết một cái. Bé còn mấy cái?',
        options: ['4 cái', '5 cái', '6 cái', '3 cái'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Bé có 2 + 3 = 5 cái, ăn hết 1 cái nên còn 5 − 1 = 4 cái.',
        explanation_speech: 'Hai cộng ba bằng năm, bớt một còn bốn.',
      },
      {
        id: 'thu-thach-iq-lop-1-23',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có mấy hình tam giác trong hình vẽ: 🔺🔺🔻🔺 ?',
        question_speech: 'Có mấy hình tam giác trong dãy: tam giác, tam giác, tam giác ngược, tam giác?',
        options: ['4', '3', '2', '5'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tam giác quay xuôi hay quay ngược đều là tam giác, đếm được 4 hình.',
        explanation_speech: 'Quay ngược vẫn là tam giác nên có bốn hình.',
      },
      {
        id: 'thu-thach-iq-lop-1-24',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bé có 10 ngón tay. Bé giấu đi 3 ngón.\nCòn mấy ngón?',
        question_speech: 'Bé có mười ngón tay, bé giấu đi ba ngón. Còn mấy ngón?',
        options: ['7 ngón', '6 ngón', '8 ngón', '5 ngón'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '10 − 3 = 7. Bé còn 7 ngón tay.',
        explanation_speech: '10 trừ 3 bằng 7. Bé còn 7 ngón tay.',
      },
      {
        id: 'thu-thach-iq-lop-1-25',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hôm nay là thứ Ba. Ngày mai là thứ mấy?',
        question_speech: 'Hôm nay là thứ Ba, ngày mai là thứ mấy?',
        options: ['Thứ Tư', 'Thứ Hai', 'Thứ Năm', 'Chủ nhật'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Các thứ đi lần lượt: thứ Hai, thứ Ba, thứ Tư... Sau thứ Ba là thứ Tư.',
        explanation_speech: 'Các thứ đi lần lượt: thứ Hai, thứ Ba, thứ Tư... Sau thứ Ba là thứ Tư.',
      },
      {
        id: 'thu-thach-iq-lop-1-26',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Cái nào nặng hơn: 1 quả bóng bay hay 1 quyển sách?',
        question_speech: 'Cái nào nặng hơn, một quả bóng bay hay một quyển sách?',
        options: ['Quyển sách', 'Quả bóng bay', 'Bằng nhau', 'Không biết'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Bóng bay chứa khí nên rất nhẹ, quyển sách nặng hơn.',
        explanation_speech: 'Bóng bay rất nhẹ, quyển sách nặng hơn.',
      },
      {
        id: 'thu-thach-iq-lop-1-27',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bé xếp 3 khối vuông chồng lên nhau, rồi lấy bớt 1 khối.\nCòn mấy khối?',
        question_speech: 'Bé xếp ba khối vuông chồng lên nhau rồi lấy bớt một khối. Còn mấy khối?',
        options: ['2 khối', '3 khối', '1 khối', '4 khối'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '3 − 1 = 2. Còn 2 khối.',
        explanation_speech: '3 trừ 1 bằng 2. Còn 2 khối.',
      },
      {
        id: 'thu-thach-iq-lop-1-28',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trong hộp có 5 bút chì màu đỏ và 0 bút màu xanh.\nLấy đại 1 bút, bút đó màu gì?',
        question_speech: 'Trong hộp có năm bút màu đỏ và không có bút xanh. Lấy đại một bút, bút đó màu gì?',
        options: ['Đỏ', 'Xanh', 'Vàng', 'Không biết'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Hộp chỉ có bút đỏ nên lấy cây nào cũng là màu đỏ.',
        explanation_speech: 'Hộp chỉ có bút đỏ nên chắc chắn lấy được bút đỏ.',
      },
      {
        id: 'thu-thach-iq-lop-1-29',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số 8 gồm 5 và mấy?',
        question_speech: 'Số tám gồm năm và mấy?',
        options: ['3', '2', '4', '5'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '5 + 3 = 8 nên số 8 gồm 5 và 3.',
        explanation_speech: '5 cộng 3 bằng 8 nên số 8 gồm 5 và 3.',
      },
      {
        id: 'thu-thach-iq-lop-1-30',
        subject: 'THỬ THÁCH IQ|LỚP 1 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bé có 2 tay, mỗi tay cầm 2 bông hoa.\nBé cầm mấy bông hoa?',
        question_speech: 'Bé có hai tay, mỗi tay cầm hai bông hoa. Bé cầm mấy bông hoa?',
        options: ['4 bông', '2 bông', '3 bông', '6 bông'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi tay 2 bông, hai tay là 2 + 2 = 4 bông.',
        explanation_speech: 'Hai cộng hai bằng bốn bông.',
      },
    ],
  },
  2: {
    grade: 2,
    intro:
      'Toán tư duy lớp 2 mở rộng suy luận với dãy số theo quy luật, phép cộng – trừ có lời văn, đếm hình và các bài logic. Bé tập phân tích đề bài, tìm mối liên hệ và trình bày cách giải rõ ràng.',
    topics: [
      'Dãy số theo quy luật',
      'Phép cộng, trừ có suy luận',
      'Đếm hình (tam giác, hình vuông)',
      'Bài toán logic đơn giản',
      'Tìm số còn thiếu',
      'Suy luận về tuổi, nhiều hơn – ít hơn',
    ],
    faq: [
      { q: 'Toán tư duy lớp 2 gồm những dạng nào?', a: 'Gồm dãy số quy luật, cộng trừ có suy luận, đếm hình, tìm số còn thiếu và các bài logic về tuổi, nhiều hơn – ít hơn.' },
      { q: 'Làm sao giúp bé lớp 2 học toán tư duy hiệu quả?', a: 'Cho bé đọc kỹ đề, vẽ hình hoặc liệt kê trường hợp, và giải thích tại sao chọn đáp án đó — hiểu bản chất thay vì học vẹt.' },
      { q: 'Toán tư duy khác gì toán trên lớp?', a: 'Toán tư duy nhấn vào suy luận và cách nghĩ, thường có nhiều cách tiếp cận, giúp bé linh hoạt hơn so với việc chỉ áp dụng công thức.' },
    ],
    questions: [
      {
        id: 'thu-thach-iq-lop-2-01',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Lan có 15 cái kẹo, cho bạn 6 cái. Lan còn lại mấy cái?',
        question_speech: 'Lan có 15 cái kẹo, cho bạn 6 cái. Lan còn lại mấy cái?',
        options: ['9 cái', '8 cái', '11 cái', '21 cái'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '15 − 6 = 9. Lan còn 9 cái kẹo.',
        explanation_speech: '15 trừ 6 bằng 9. Lan còn 9 cái kẹo.',
      },
      {
        id: 'thu-thach-iq-lop-2-02',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 4 rổ, mỗi rổ 5 quả cam. Tất cả có bao nhiêu quả cam?',
        question_speech: 'Có 4 rổ, mỗi rổ 5 quả cam. Tất cả có bao nhiêu quả cam?',
        options: ['9 quả', '20 quả', '15 quả', '25 quả'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi rổ 5 quả, có 4 rổ nên lấy 5 × 4 = 20 quả. Nhiều nhóm bằng nhau thì dùng phép nhân cho nhanh.',
        explanation_speech: 'Mỗi rổ 5 quả, có 4 rổ nên lấy 5 nhân 4 bằng 20 quả. Nhiều nhóm bằng nhau thì dùng phép nhân cho nhanh.',
      },
      {
        id: 'thu-thach-iq-lop-2-03',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số liền trước của số 30 là số nào?',
        question_speech: 'Số liền trước của số 30 là số nào?',
        options: ['31', '20', '29', '28'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Liền trước 30 là 30 − 1 = 29.',
        explanation_speech: 'Liền trước 30 là 30 trừ 1 bằng 29.',
      },
      {
        id: 'thu-thach-iq-lop-2-04',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Điền số còn thiếu vào dãy: 2, 4, 6, ?, 10',
        question_speech: 'Điền số còn thiếu vào dãy: 2, 4, 6, ?, 10',
        options: ['7', '9', '12', '8'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy tăng đều 2 đơn vị: 6 + 2 = 8.',
        explanation_speech: 'Dãy tăng đều 2 đơn vị: 6 cộng 2 bằng 8.',
      },
      {
        id: 'thu-thach-iq-lop-2-05',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'An cao 105cm, Bình thấp hơn An 8cm. Bình cao bao nhiêu?',
        question_speech: 'An cao 105cm, Bình thấp hơn An 8cm. Bình cao bao nhiêu?',
        options: ['97cm', '113cm', '98cm', '107cm'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Thấp hơn nghĩa là bớt đi: 105 − 8 = 97cm. Bình cao 97cm.',
        explanation_speech: 'Thấp hơn nghĩa là bớt đi: 105 trừ 8 bằng 97cm. Bình cao 97cm.',
      },
      {
        id: 'thu-thach-iq-lop-2-06',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một tuần lễ có mấy ngày?',
        question_speech: 'Một tuần lễ có mấy ngày?',
        options: ['5 ngày', '7 ngày', '10 ngày', '30 ngày'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một tuần lễ có 7 ngày, từ thứ Hai đến Chủ nhật.',
        explanation_speech: 'Một tuần lễ có 7 ngày, từ thứ Hai đến Chủ nhật.',
      },
      {
        id: 'thu-thach-iq-lop-2-07',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hình nào có 4 cạnh bằng nhau?',
        question_speech: 'Hình nào có 4 cạnh bằng nhau?',
        options: ['Hình tam giác', 'Hình tròn', 'Hình vuông', 'Hình chữ nhật'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Hình vuông có 4 cạnh bằng nhau.',
        explanation_speech: 'Hình vuông có 4 cạnh bằng nhau.',
      },
      {
        id: 'thu-thach-iq-lop-2-08',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '24 + 18 = ?',
        question_speech: '24 cộng 18 bằng bao nhiêu',
        options: ['32', '44', '40', '42'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Cộng hàng đơn vị trước: 4 + 8 = 12, viết 2 nhớ 1. Hàng chục: 2 + 1 + 1 = 4. Kết quả 42.',
        explanation_speech: 'Cộng hàng đơn vị trước: 4 cộng 8 bằng 12, viết 2 nhớ 1. Hàng chục: 2 cộng 1 + 1 bằng 4. Kết quả 42.',
      },
      {
        id: 'thu-thach-iq-lop-2-09',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Mẹ mua 3 chục quả trứng. Có tất cả bao nhiêu quả?',
        question_speech: 'Mẹ mua 3 chục quả trứng. Có tất cả bao nhiêu quả?',
        options: ['30 quả', '13 quả', '3 quả', '33 quả'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '3 chục = 3 × 10 = 30 quả.',
        explanation_speech: '3 chục = 3 nhân 10 bằng 30 quả.',
      },
      {
        id: 'thu-thach-iq-lop-2-10',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Nam có 12 viên bi, nhiều hơn Hoa 5 viên. Hoa có mấy viên?',
        question_speech: 'Nam có 12 viên bi, nhiều hơn Hoa 5 viên. Hoa có mấy viên?',
        options: ['17 viên', '7 viên', '6 viên', '8 viên'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Nam NHIỀU HƠN Hoa 5 viên, nên Hoa ít hơn: 12 − 5 = 7 viên. Đọc kỹ ai nhiều hơn ai.',
        explanation_speech: 'Nam NHIỀU HƠN Hoa 5 viên, nên Hoa ít hơn: 12 trừ 5 bằng 7 viên. Đọc kỹ ai nhiều hơn ai.',
      },
      {
        id: 'thu-thach-iq-lop-2-11',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số lớn nhất trong các số 45, 54, 40, 44 là số nào?',
        question_speech: 'Số lớn nhất trong các số 45, 54, 40, 44 là số nào?',
        options: ['45', '44', '54', '40'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'So hàng chục trước: 54 và 45 đều có 5 và 4, nhưng 54 có 5 chục còn 45 chỉ 4 chục. Vậy 54 lớn nhất.',
        explanation_speech: 'So hàng chục trước: 54 và 45 đều có 5 và 4, nhưng 54 có 5 chục còn 45 chỉ 4 chục. Vậy 54 lớn nhất.',
      },
      {
        id: 'thu-thach-iq-lop-2-12',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '5 × 3 = ?',
        question_speech: '5 nhân 3 bằng bao nhiêu',
        options: ['8', '10', '35', '15'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '5 × 3 nghĩa là 5 + 5 + 5 = 15.',
        explanation_speech: '5 nhân 3 nghĩa là 5 cộng 5 + 5 bằng 15.',
      },
      {
        id: 'thu-thach-iq-lop-2-13',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Dãy số: 3, 6, 9, ___, 15.\nSố còn thiếu là số nào?',
        question_speech: 'Dãy số ba, sáu, chín, chấm chấm, mười lăm. Số còn thiếu là số nào?',
        options: ['12', '10', '13', '11'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy tăng đều: mỗi số hơn số trước 3 đơn vị (3, 6, 9, 12, 15). Muốn tìm số còn thiếu thì lấy số đứng trước cộng 3.',
        explanation_speech: 'Mỗi số hơn số trước ba đơn vị nên số còn thiếu là mười hai.',
      },
      {
        id: 'thu-thach-iq-lop-2-14',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Lan có 15 viên bi, Lan cho Nam 4 viên rồi được mẹ cho thêm 6 viên.\nLan có mấy viên?',
        question_speech: 'Lan có mười lăm viên bi, cho Nam bốn viên rồi được mẹ cho thêm sáu viên. Lan có mấy viên?',
        options: ['17 viên', '15 viên', '19 viên', '13 viên'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '15 − 4 = 11, rồi 11 + 6 = 17 viên.',
        explanation_speech: 'Mười lăm bớt bốn còn mười một, thêm sáu thành mười bảy.',
      },
      {
        id: 'thu-thach-iq-lop-2-15',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một hình vuông lớn được chia thành 4 hình vuông nhỏ bằng nhau.\nCó tất cả mấy hình vuông?',
        question_speech: 'Một hình vuông lớn chia thành bốn hình vuông nhỏ bằng nhau. Có tất cả mấy hình vuông?',
        options: ['5', '4', '6', '8'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Đếm 4 hình nhỏ, cộng thêm chính hình lớn bên ngoài: 4 + 1 = 5 hình vuông.',
        explanation_speech: 'Bốn hình nhỏ cộng hình lớn bên ngoài là năm hình.',
      },
      {
        id: 'thu-thach-iq-lop-2-16',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Anh 8 tuổi, em kém anh 3 tuổi.\nEm mấy tuổi?',
        question_speech: 'Anh tám tuổi, em kém anh ba tuổi. Em mấy tuổi?',
        options: ['5 tuổi', '11 tuổi', '6 tuổi', '4 tuổi'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Kém nghĩa là ít hơn: 8 − 3 = 5 tuổi.',
        explanation_speech: 'Tám bớt ba bằng năm tuổi.',
      },
      {
        id: 'thu-thach-iq-lop-2-17',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số nào cộng với 7 thì được 12?',
        question_speech: 'Số nào cộng với bảy thì được mười hai?',
        options: ['5', '6', '4', '19'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tìm số hạng chưa biết: 12 − 7 = 5. Thử lại 5 + 7 = 12.',
        explanation_speech: 'Mười hai trừ bảy bằng năm.',
      },
      {
        id: 'thu-thach-iq-lop-2-18',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 3 bạn, mỗi bạn bắt tay tất cả các bạn còn lại một lần.\nCó mấy cái bắt tay?',
        question_speech: 'Có ba bạn, mỗi bạn bắt tay các bạn còn lại một lần. Có mấy cái bắt tay?',
        options: ['3', '6', '2', '4'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Các cặp là: bạn 1 với 2, bạn 1 với 3, bạn 2 với 3 — tất cả 3 cái bắt tay. Đếm theo CẶP chứ không nhân, vì hai người chung một cái bắt tay.',
        explanation_speech: 'Có ba cặp nên có ba cái bắt tay.',
      },
      {
        id: 'thu-thach-iq-lop-2-19',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Mẹ mua 2 chục quả trứng.\nMẹ mua bao nhiêu quả?',
        question_speech: 'Mẹ mua hai chục quả trứng. Mẹ mua bao nhiêu quả?',
        options: ['20 quả', '12 quả', '2 quả', '10 quả'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một chục là 10 quả nên 2 chục là 20 quả.',
        explanation_speech: 'Một chục là mười, hai chục là hai mươi.',
      },
      {
        id: 'thu-thach-iq-lop-2-20',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Dãy hình: 1 ngôi sao, 2 ngôi sao, 3 ngôi sao, ...\nNhóm thứ 5 có mấy ngôi sao?',
        question_speech: 'Nhóm một có một ngôi sao, nhóm hai có hai, nhóm ba có ba. Nhóm thứ năm có mấy ngôi sao?',
        options: ['5', '4', '6', '10'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Nhóm thứ mấy thì có bấy nhiêu ngôi sao, nên nhóm thứ 5 có 5 ngôi sao.',
        explanation_speech: 'Nhóm thứ năm có năm ngôi sao.',
      },
      {
        id: 'thu-thach-iq-lop-2-21',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bình nhiều hơn An 5 quyển vở. An có 8 quyển.\nHai bạn có tất cả mấy quyển?',
        question_speech: 'Bình nhiều hơn An năm quyển vở, An có tám quyển. Hai bạn có tất cả mấy quyển?',
        options: ['21 quyển', '13 quyển', '16 quyển', '18 quyển'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Bình có 8 + 5 = 13 quyển. Cả hai có 8 + 13 = 21 quyển. Bài hỏi CẢ HAI nên phải cộng thêm phần của An.',
        explanation_speech: 'Bình có mười ba quyển, cộng tám của An là hai mươi mốt quyển.',
      },
      {
        id: 'thu-thach-iq-lop-2-22',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trong 4 số 12, 7, 20, 15, số nào lớn nhất?',
        question_speech: 'Trong bốn số mười hai, bảy, hai mươi, mười lăm, số nào lớn nhất?',
        options: ['20', '15', '12', '7'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'So hàng chục trước: 20 có 2 chục, các số kia chỉ 1 chục hoặc ít hơn. Vậy 20 lớn nhất.',
        explanation_speech: 'Hai mươi có hai chục nên lớn nhất.',
      },
      {
        id: 'thu-thach-iq-lop-2-23',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một tuần có 7 ngày. Hai tuần có mấy ngày?',
        question_speech: 'Một tuần có bảy ngày. Hai tuần có mấy ngày?',
        options: ['14 ngày', '12 ngày', '15 ngày', '9 ngày'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi tuần 7 ngày, hai tuần là 7 + 7 = 14 ngày. Cũng có thể tính 7 × 2 = 14.',
        explanation_speech: 'Bảy cộng bảy bằng mười bốn ngày.',
      },
      {
        id: 'thu-thach-iq-lop-2-24',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bé đếm: 5, 10, 15, 20, ___.\nSố tiếp theo là?',
        question_speech: 'Bé đếm năm, mười, mười lăm, hai mươi. Số tiếp theo là?',
        options: ['25', '21', '30', '24'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy đếm thêm 5 mỗi bước: sau 20 là 25.',
        explanation_speech: 'Thêm năm nữa là hai mươi lăm.',
      },
      {
        id: 'thu-thach-iq-lop-2-25',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hộp A có 9 cái bánh, hộp B ít hơn hộp A 2 cái.\nHộp B có mấy cái?',
        question_speech: 'Hộp A có chín cái bánh, hộp B ít hơn hộp A hai cái. Hộp B có mấy cái?',
        options: ['7 cái', '11 cái', '6 cái', '8 cái'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Ít hơn là bớt đi: 9 − 2 = 7 cái.',
        explanation_speech: 'Ít hơn là bớt đi: 9 trừ 2 bằng 7 cái.',
      },
      {
        id: 'thu-thach-iq-lop-2-26',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 6 con vịt đang bơi, 2 con lên bờ rồi 3 con khác xuống nước.\nDưới nước có mấy con?',
        question_speech: 'Có sáu con vịt đang bơi, hai con lên bờ rồi ba con khác xuống nước. Dưới nước có mấy con?',
        options: ['7 con', '5 con', '9 con', '4 con'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '6 − 2 = 4, rồi 4 + 3 = 7 con đang ở dưới nước.',
        explanation_speech: 'Sáu bớt hai còn bốn, thêm ba thành bảy.',
      },
      {
        id: 'thu-thach-iq-lop-2-27',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Nếu hôm nay là thứ Sáu thì 3 ngày nữa là thứ mấy?',
        question_speech: 'Nếu hôm nay là thứ Sáu thì ba ngày nữa là thứ mấy?',
        options: ['Thứ Hai', 'Chủ nhật', 'Thứ Ba', 'Thứ Bảy'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Đếm tiếp: thứ Bảy (1), Chủ nhật (2), thứ Hai (3). Vậy 3 ngày nữa là thứ Hai.',
        explanation_speech: 'Thứ Bảy, Chủ nhật rồi thứ Hai.',
      },
      {
        id: 'thu-thach-iq-lop-2-28',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số lớn nhất có hai chữ số là số nào?',
        question_speech: 'Số lớn nhất có hai chữ số là số nào?',
        options: ['99', '98', '100', '90'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Hai chữ số lớn nhất đều là 9, ghép lại được 99. Số 100 có ba chữ số nên không tính.',
        explanation_speech: 'Số lớn nhất có hai chữ số là chín mươi chín.',
      },
      {
        id: 'thu-thach-iq-lop-2-29',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Cô giáo chia 12 cái kẹo đều cho 2 bạn.\nMỗi bạn được mấy cái?',
        question_speech: 'Cô giáo chia mười hai cái kẹo đều cho hai bạn. Mỗi bạn được mấy cái?',
        options: ['6 cái', '5 cái', '4 cái', '10 cái'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Chia đều cho 2 là chia đôi: 12 : 2 = 6 cái.',
        explanation_speech: 'Mười hai chia đôi được sáu cái.',
      },
      {
        id: 'thu-thach-iq-lop-2-30',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bé cắt một sợi dây thành 2 đoạn thì có 1 nhát cắt.\nCắt thành 4 đoạn thì cần mấy nhát?',
        question_speech: 'Cắt sợi dây thành hai đoạn cần một nhát. Cắt thành bốn đoạn cần mấy nhát?',
        options: ['3 nhát', '4 nhát', '2 nhát', '5 nhát'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Số nhát cắt luôn ít hơn số đoạn 1: muốn 4 đoạn thì cắt 3 nhát.',
        explanation_speech: 'Bốn đoạn thì cắt ba nhát.',
      },
      {
        id: 'thu-thach-iq-lop-2-31',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trong lớp có 20 bạn, 9 bạn là nam.\nCó mấy bạn nữ?',
        question_speech: 'Lớp có hai mươi bạn, chín bạn là nam. Có mấy bạn nữ?',
        options: ['11 bạn', '9 bạn', '12 bạn', '10 bạn'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Lấy tổng số bạn trừ số bạn nam: 20 − 9 = 11 bạn nữ.',
        explanation_speech: 'Hai mươi bớt chín còn mười một.',
      },
      {
        id: 'thu-thach-iq-lop-2-32',
        subject: 'THỬ THÁCH IQ|LỚP 2 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một cái bàn có 4 chân. Ba cái bàn có mấy chân?',
        question_speech: 'Một cái bàn có bốn chân. Ba cái bàn có mấy chân?',
        options: ['12 chân', '7 chân', '8 chân', '16 chân'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi bàn 4 chân, ba bàn là 4 + 4 + 4 = 12 chân, hay 4 × 3 = 12 chân.',
        explanation_speech: 'Bốn cộng bốn cộng bốn bằng mười hai.',
      },
    ],
  },
  3: {
    grade: 3,
    intro:
      'Toán tư duy lớp 3 đưa bé đến các bài toán nhân – chia có suy luận, trồng cây, dãy số và logic loại trừ. Bé rèn khả năng lập luận theo nhiều bước và kiểm tra lại kết quả.',
    topics: [
      'Phép nhân, chia có suy luận',
      'Bài toán trồng cây, khoảng cách',
      'Dãy số và quy luật',
      'Suy luận logic (phương pháp loại trừ)',
      'Đếm hình và hình học',
      'Bài toán về thời gian, lịch',
    ],
    faq: [
      { q: 'Toán tư duy lớp 3 học gì?', a: 'Bé học nhân chia có suy luận, bài toán trồng cây, dãy số, suy luận loại trừ, đếm hình và bài toán thời gian – lịch.' },
      { q: 'Bài toán trồng cây là gì?', a: 'Là dạng toán tính số cây (hoặc cọc, đèn…) trồng trên đoạn đường theo khoảng cách — kinh điển trong toán tư duy lớp 3, rèn cách suy luận về khoảng và số điểm.' },
      { q: 'Bé cần chuẩn bị gì để học tốt?', a: 'Nắm chắc bảng cửu chương và phép nhân chia cơ bản, sau đó luyện đọc – phân tích đề để chọn cách giải phù hợp.' },
    ],
    questions: [
      {
        id: 'thu-thach-iq-lop-3-01',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 6 hộp, mỗi hộp 8 chiếc bút. Tất cả có bao nhiêu chiếc bút?',
        question_speech: 'Có 6 hộp, mỗi hộp 8 chiếc bút. Tất cả có bao nhiêu chiếc bút?',
        options: ['48 bút', '14 bút', '54 bút', '40 bút'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi hộp 8 chiếc, có 6 hộp nên 8 × 6 = 48 chiếc bút.',
        explanation_speech: 'Mỗi hộp 8 chiếc, có 6 hộp nên 8 nhân 6 bằng 48 chiếc bút.',
      },
      {
        id: 'thu-thach-iq-lop-3-02',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '42 : 6 = ?',
        question_speech: '42 chia 6 bằng bao nhiêu',
        options: ['6', '7', '8', '9'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Hỏi 42 gồm mấy nhóm 6: vì 6 × 7 = 42 nên 42 : 6 = 7.',
        explanation_speech: 'Hỏi 42 gồm mấy nhóm 6: vì 6 nhân 7 bằng 42 nên 42 chia 6 bằng 7.',
      },
      {
        id: 'thu-thach-iq-lop-3-03',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hình chữ nhật dài 5cm, rộng 3cm. Chu vi hình đó là?',
        question_speech: 'Hình chữ nhật dài 5cm, rộng 3cm. Chu vi hình đó là?',
        options: ['8cm', '15cm', '16cm', '13cm'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Chu vi = (5 + 3) × 2 = 16cm.',
        explanation_speech: 'Chu vi = (5 cộng 3) × 2 bằng 16cm.',
      },
      {
        id: 'thu-thach-iq-lop-3-04',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Điền số còn thiếu: 5, 10, 15, ?, 25',
        question_speech: 'Điền số còn thiếu: 5, 10, 15, ?, 25',
        options: ['18', '22', '21', '20'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Dãy tăng đều 5: 15 + 5 = 20.',
        explanation_speech: 'Dãy tăng đều 5 chia 15 cộng 5 bằng 20.',
      },
      {
        id: 'thu-thach-iq-lop-3-05',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Lan có 36 bông hoa, chia đều vào 4 bình. Mỗi bình mấy bông?',
        question_speech: 'Lan có 36 bông hoa, chia đều vào 4 bình. Mỗi bình mấy bông?',
        options: ['9 bông', '8 bông', '6 bông', '12 bông'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Chia đều thì lấy tổng chia cho số bình: 36 : 4 = 9 bông mỗi bình.',
        explanation_speech: 'Chia đều thì lấy tổng chia cho số bình: 36 chia 4 bằng 9 bông mỗi bình.',
      },
      {
        id: 'thu-thach-iq-lop-3-06',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Gấp 7 lên 4 lần được số nào?',
        question_speech: 'Gấp 7 lên 4 lần được số nào?',
        options: ['11', '28', '21', '24'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Gấp lên mấy lần thì nhân với số đó: 7 × 4 = 28.',
        explanation_speech: 'Gấp lên mấy lần thì nhân với số đó: 7 nhân 4 bằng 28.',
      },
      {
        id: 'thu-thach-iq-lop-3-07',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một ngày có bao nhiêu giờ?',
        question_speech: 'Một ngày có bao nhiêu giờ?',
        options: ['12 giờ', '60 giờ', '24 giờ', '7 giờ'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một ngày đêm có 24 giờ, tính từ 0 giờ đến 24 giờ.',
        explanation_speech: 'Một ngày đêm có 24 giờ, tính từ 0 giờ đến 24 giờ.',
      },
      {
        id: 'thu-thach-iq-lop-3-08',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '125 + 78 = ?',
        question_speech: '125 cộng 78 bằng bao nhiêu',
        options: ['193', '213', '198', '203'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Hàng đơn vị 5 + 8 = 13, viết 3 nhớ 1. Hàng chục 2 + 7 + 1 = 10, viết 0 nhớ 1. Hàng trăm 1 + 1 = 2. Được 203.',
        explanation_speech: 'Hàng đơn vị 5 cộng 8 bằng 13, viết 3 nhớ 1. Hàng chục 2 cộng 7 + 1 bằng 10, viết 0 nhớ 1. Hàng trăm 1 cộng 1 bằng 2. Được 203.',
      },
      {
        id: 'thu-thach-iq-lop-3-09',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 5 chiếc ô tô, mỗi xe có 4 bánh. Tất cả có mấy bánh xe?',
        question_speech: 'Có 5 chiếc ô tô, mỗi xe có 4 bánh. Tất cả có mấy bánh xe?',
        options: ['20 bánh', '9 bánh', '16 bánh', '24 bánh'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi ô tô 4 bánh, có 5 xe nên 4 × 5 = 20 bánh xe.',
        explanation_speech: 'Mỗi ô tô 4 bánh, có 5 xe nên 4 nhân 5 bằng 20 bánh xe.',
      },
      {
        id: 'thu-thach-iq-lop-3-10',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số nào sau đây chia hết cho 5?',
        question_speech: 'Số nào sau đây chia hết cho 5?',
        options: ['12', '20', '33', '47'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '20 : 5 = 4 nên 20 chia hết cho 5.',
        explanation_speech: '20 chia 5 bằng 4 nên 20 chia hết cho 5.',
      },
      {
        id: 'thu-thach-iq-lop-3-11',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tìm x, biết: x × 3 = 27',
        question_speech: 'Tìm x, biết x nhân 3 bằng 27',
        options: ['8', '24', '9', '30'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Muốn tìm thừa số chưa biết thì lấy tích chia cho thừa số kia: x = 27 : 3 = 9. Thử lại 9 × 3 = 27.',
        explanation_speech: 'Muốn tìm thừa số chưa biết thì lấy tích chia cho thừa số kia: x = 27 chia 3 bằng 9. Thử lại 9 nhân 3 bằng 27.',
      },
      {
        id: 'thu-thach-iq-lop-3-12',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Mai có 48 quyển vở, cho đi 1/4 số vở. Mai cho đi mấy quyển?',
        question_speech: 'Mai có 48 quyển vở, cho đi 1/4 số vở. Mai cho đi mấy quyển?',
        options: ['4 quyển', '24 quyển', '16 quyển', '12 quyển'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một phần tư số vở là 48 : 4 = 12 quyển. Mai cho đi 12 quyển.',
        explanation_speech: 'Một phần tư số vở là 48 chia 4 bằng 12 quyển. Mai cho đi 12 quyển.',
      },
      {
        id: 'thu-thach-iq-lop-3-13',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trồng cây dọc con đường dài 20m, cứ 4m trồng một cây, trồng cả hai đầu.\nCần mấy cây?',
        question_speech: 'Trồng cây dọc con đường dài hai mươi mét, cứ bốn mét trồng một cây, trồng cả hai đầu. Cần mấy cây?',
        options: ['6 cây', '5 cây', '4 cây', '7 cây'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Số khoảng cách là 20 : 4 = 5. Trồng cả hai đầu thì số cây nhiều hơn số khoảng 1: 5 + 1 = 6 cây.',
        explanation_speech: 'Năm khoảng thì có sáu cây vì trồng cả hai đầu.',
      },
      {
        id: 'thu-thach-iq-lop-3-14',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một tá bút chì có 12 cái. Cô mua 3 tá.\nCô có bao nhiêu cái bút?',
        question_speech: 'Một tá bút chì có mười hai cái, cô mua ba tá. Cô có bao nhiêu cái bút?',
        options: ['36 cái', '15 cái', '24 cái', '30 cái'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một tá là 12 cái, ba tá là 12 × 3 = 36 cái bút.',
        explanation_speech: 'Mười hai nhân ba bằng ba mươi sáu.',
      },
      {
        id: 'thu-thach-iq-lop-3-15',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Dãy số: 2, 6, 18, ___.\nSố tiếp theo là số nào?',
        question_speech: 'Dãy số hai, sáu, mười tám. Số tiếp theo là số nào?',
        options: ['54', '24', '36', '72'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi số gấp 3 lần số trước: 2 × 3 = 6, 6 × 3 = 18, 18 × 3 = 54.',
        explanation_speech: 'Mỗi số gấp ba lần số trước nên tiếp theo là năm mươi tư.',
      },
      {
        id: 'thu-thach-iq-lop-3-16',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 24 quả cam xếp đều vào 6 đĩa.\nMỗi đĩa mấy quả?',
        question_speech: 'Có hai mươi tư quả cam xếp đều vào sáu đĩa. Mỗi đĩa mấy quả?',
        options: ['4 quả', '5 quả', '6 quả', '3 quả'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Xếp đều thì lấy tổng chia cho số đĩa: 24 : 6 = 4 quả mỗi đĩa.',
        explanation_speech: 'Hai mươi tư chia sáu bằng bốn.',
      },
      {
        id: 'thu-thach-iq-lop-3-17',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Ba bạn An, Bình, Cường có ba màu áo đỏ, vàng, xanh.\nAn không mặc đỏ, Bình mặc vàng. An mặc màu gì?',
        question_speech: 'An không mặc đỏ, Bình mặc vàng. An mặc màu gì?',
        options: ['Xanh', 'Đỏ', 'Vàng', 'Không biết'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Bình đã mặc vàng nên An chỉ còn đỏ hoặc xanh; An không mặc đỏ nên An mặc xanh. Đây là cách loại trừ.',
        explanation_speech: 'Bình mặc vàng, An không mặc đỏ nên An mặc xanh.',
      },
      {
        id: 'thu-thach-iq-lop-3-18',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một hình chữ nhật có chiều dài 8cm, chiều rộng 3cm.\nChu vi bằng bao nhiêu?',
        question_speech: 'Hình chữ nhật dài tám xăng-ti-mét, rộng ba xăng-ti-mét. Chu vi bằng bao nhiêu?',
        options: ['22cm', '11cm', '24cm', '16cm'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Chu vi = (dài + rộng) × 2 = (8 + 3) × 2 = 22cm.',
        explanation_speech: 'Tám cộng ba bằng mười một, nhân hai bằng hai mươi hai.',
      },
      {
        id: 'thu-thach-iq-lop-3-19',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Bây giờ là 9 giờ. Sau 3 giờ 30 phút nữa là mấy giờ?',
        question_speech: 'Bây giờ là chín giờ. Sau ba giờ ba mươi phút nữa là mấy giờ?',
        options: ['12 giờ 30 phút', '11 giờ 30 phút', '12 giờ', '1 giờ 30 phút'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '9 giờ + 3 giờ = 12 giờ, thêm 30 phút thành 12 giờ 30 phút.',
        explanation_speech: 'Chín giờ thêm ba giờ rưỡi là mười hai giờ ba mươi.',
      },
      {
        id: 'thu-thach-iq-lop-3-20',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một cửa hàng có 5 hộp bánh, mỗi hộp 8 cái. Bán hết 12 cái.\nCòn mấy cái?',
        question_speech: 'Cửa hàng có năm hộp bánh, mỗi hộp tám cái, bán hết mười hai cái. Còn mấy cái?',
        options: ['28 cái', '32 cái', '40 cái', '20 cái'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tổng: 5 × 8 = 40 cái. Còn lại: 40 − 12 = 28 cái.',
        explanation_speech: 'Năm nhân tám bằng bốn mươi, bớt mười hai còn hai mươi tám.',
      },
      {
        id: 'thu-thach-iq-lop-3-21',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tháng 2 năm thường có 28 ngày. Tháng đó có mấy tuần lẻ mấy ngày?',
        question_speech: 'Tháng hai có hai mươi tám ngày thì có mấy tuần?',
        options: ['4 tuần chẵn', '3 tuần lẻ 7 ngày', '5 tuần', '4 tuần lẻ 2 ngày'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '28 : 7 = 4 nên đúng 4 tuần, không lẻ ngày nào.',
        explanation_speech: 'Hai mươi tám chia bảy bằng bốn nên đúng bốn tuần.',
      },
      {
        id: 'thu-thach-iq-lop-3-22',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số nào chia hết cho cả 2 và 5?',
        question_speech: 'Số nào chia hết cho cả hai và năm?',
        options: ['30', '25', '12', '9'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Chia hết cho 2 thì tận cùng chẵn, chia hết cho 5 thì tận cùng 0 hoặc 5. Chỉ số tận cùng bằng 0 thoả cả hai: 30.',
        explanation_speech: 'Số tận cùng bằng không chia hết cho cả hai và năm.',
      },
      {
        id: 'thu-thach-iq-lop-3-23',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trong hình có 4 hình tam giác nhỏ ghép thành 1 tam giác lớn.\nTổng cộng có mấy tam giác?',
        question_speech: 'Bốn tam giác nhỏ ghép thành một tam giác lớn. Tổng cộng có mấy tam giác?',
        options: ['5', '4', '6', '8'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '4 tam giác nhỏ cộng 1 tam giác lớn bên ngoài là 5. Nhớ đếm cả hình lớn.',
        explanation_speech: 'Bốn hình nhỏ cộng một hình lớn là năm.',
      },
      {
        id: 'thu-thach-iq-lop-3-24',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một con gà có 2 chân, một con chó có 4 chân.\n3 con gà và 2 con chó có mấy chân?',
        question_speech: 'Ba con gà và hai con chó có mấy chân?',
        options: ['14 chân', '10 chân', '12 chân', '16 chân'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Gà: 3 × 2 = 6 chân. Chó: 2 × 4 = 8 chân. Tổng 6 + 8 = 14 chân.',
        explanation_speech: 'Sáu cộng tám bằng mười bốn chân.',
      },
      {
        id: 'thu-thach-iq-lop-3-25',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Nam đi từ nhà đến trường mất 15 phút. Nam vào lớp lúc 7 giờ.\nNam phải ra khỏi nhà lúc mấy giờ?',
        question_speech: 'Nam đi mất mười lăm phút, vào lớp lúc bảy giờ. Nam phải ra khỏi nhà lúc mấy giờ?',
        options: ['6 giờ 45 phút', '7 giờ 15 phút', '6 giờ 15 phút', '6 giờ 30 phút'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tính ngược: 7 giờ − 15 phút = 6 giờ 45 phút.',
        explanation_speech: 'Bảy giờ lùi mười lăm phút là sáu giờ bốn mươi lăm.',
      },
      {
        id: 'thu-thach-iq-lop-3-26',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tìm số bị chia, biết số chia là 6, thương là 5, không dư.',
        question_speech: 'Số chia là sáu, thương là năm, không dư. Số bị chia là bao nhiêu?',
        options: ['30', '11', '1', '36'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Số bị chia = thương × số chia = 5 × 6 = 30.',
        explanation_speech: 'Năm nhân sáu bằng ba mươi.',
      },
      {
        id: 'thu-thach-iq-lop-3-27',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Lớp 3A có 30 bạn, một phần ba số bạn là nam.\nCó mấy bạn nam?',
        question_speech: 'Lớp có ba mươi bạn, một phần ba là nam. Có mấy bạn nam?',
        options: ['10 bạn', '15 bạn', '3 bạn', '20 bạn'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một phần ba của 30 là 30 : 3 = 10 bạn.',
        explanation_speech: 'Ba mươi chia ba bằng mười.',
      },
      {
        id: 'thu-thach-iq-lop-3-28',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 3 cái áo và 2 cái quần.\nCó mấy cách chọn một bộ gồm 1 áo và 1 quần?',
        question_speech: 'Có ba áo và hai quần, có mấy cách chọn một bộ gồm một áo và một quần?',
        options: ['6 cách', '5 cách', '3 cách', '2 cách'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi áo ghép được với 2 quần: 3 × 2 = 6 cách.',
        explanation_speech: 'Ba nhân hai bằng sáu cách.',
      },
      {
        id: 'thu-thach-iq-lop-3-29',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một sợi dây dài 36m cắt thành các đoạn 9m.\nĐược mấy đoạn?',
        question_speech: 'Sợi dây dài ba mươi sáu mét cắt thành các đoạn chín mét, được mấy đoạn?',
        options: ['4 đoạn', '5 đoạn', '3 đoạn', '6 đoạn'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Lấy độ dài cả sợi chia cho độ dài mỗi đoạn: 36 : 9 = 4 đoạn.',
        explanation_speech: 'Ba mươi sáu chia chín bằng bốn.',
      },
      {
        id: 'thu-thach-iq-lop-3-30',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số nào lớn hơn: 7 × 8 hay 9 × 6?',
        question_speech: 'Số nào lớn hơn, bảy nhân tám hay chín nhân sáu?',
        options: ['7 × 8', '9 × 6', 'Bằng nhau', 'Không so được'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '7 × 8 = 56, 9 × 6 = 54. Vậy 7 × 8 lớn hơn.',
        explanation_speech: 'Năm mươi sáu lớn hơn năm mươi tư.',
      },
      {
        id: 'thu-thach-iq-lop-3-31',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Mai có số kẹo gấp 4 lần Hoa. Hoa có 7 cái.\nCả hai có mấy cái?',
        question_speech: 'Mai có số kẹo gấp bốn lần Hoa, Hoa có bảy cái. Cả hai có mấy cái?',
        options: ['35 cái', '28 cái', '11 cái', '21 cái'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mai có 7 × 4 = 28 cái. Cả hai có 28 + 7 = 35 cái. Câu hỏi là CẢ HAI nên đừng quên phần của Hoa.',
        explanation_speech: 'Hai mươi tám cộng bảy bằng ba mươi lăm.',
      },
      {
        id: 'thu-thach-iq-lop-3-32',
        subject: 'THỬ THÁCH IQ|LỚP 3 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trong một phép chia có dư, số dư là 3.\nSố chia nhỏ nhất có thể là bao nhiêu?',
        question_speech: 'Trong phép chia có dư, số dư là ba. Số chia nhỏ nhất có thể là bao nhiêu?',
        options: ['4', '3', '2', '5'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Số dư luôn NHỎ HƠN số chia, nên số chia phải lớn hơn 3, nhỏ nhất là 4.',
        explanation_speech: 'Số dư nhỏ hơn số chia nên số chia nhỏ nhất là bốn.',
      },
    ],
  },
  4: {
    grade: 4,
    intro:
      'Toán tư duy lớp 4 tập trung vào các bài toán tổng – hiệu, tổng – tỉ, dãy số cách đều và suy luận logic nâng cao. Bé học cách đặt bài toán về dạng quen thuộc và giải bằng sơ đồ, lập luận.',
    topics: [
      'Tìm hai số khi biết tổng và hiệu',
      'Tìm hai số khi biết tổng và tỉ',
      'Dãy số cách đều',
      'Suy luận logic nâng cao',
      'Chu vi, diện tích theo tư duy',
      'Bài toán tính ngược',
    ],
    faq: [
      { q: 'Toán tư duy lớp 4 gồm dạng bài nào?', a: 'Gồm tổng – hiệu, tổng – tỉ, dãy số cách đều, suy luận logic nâng cao, chu vi – diện tích tư duy và bài toán tính ngược.' },
      { q: 'Vẽ sơ đồ đoạn thẳng có giúp ích không?', a: 'Rất hữu ích. Sơ đồ đoạn thẳng giúp bé nhìn rõ mối quan hệ tổng – hiệu – tỉ và tìm ra lời giải nhanh, chính xác.' },
      { q: 'Học toán tư duy lớp 4 để làm gì?', a: 'Giúp bé làm chủ các dạng toán điển hình, chuẩn bị cho kiểm tra, thi học sinh giỏi và tạo nền tảng cho toán lớp 5.' },
    ],
    questions: [
      {
        id: 'thu-thach-iq-lop-4-01',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '25 × 4 = ?',
        question_speech: '25 nhân 4 bằng bao nhiêu',
        options: ['100', '29', '90', '125'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '25 × 4 = 100 — nên thuộc lòng cặp này vì gặp rất nhiều khi tính nhanh.',
        explanation_speech: '25 nhân 4 bằng 100.',
      },
      {
        id: 'thu-thach-iq-lop-4-02',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '144 : 12 = ?',
        question_speech: '144 chia 12 bằng bao nhiêu',
        options: ['11', '12', '14', '24'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Vì 12 × 12 = 144 nên 144 : 12 = 12.',
        explanation_speech: 'Vì 12 nhân 12 bằng 144 nên 144 chia 12 bằng 12.',
      },
      {
        id: 'thu-thach-iq-lop-4-03',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trung bình cộng của 6 và 10 là bao nhiêu?',
        question_speech: 'Trung bình cộng của 6 và 10 là bao nhiêu?',
        options: ['16', '7', '8', '9'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Trung bình cộng là lấy tổng chia cho số các số hạng: (6 + 10) : 2 = 8.',
        explanation_speech: 'Trung bình cộng là lấy tổng chia cho số các số hạng: (6 cộng 10) : 2 bằng 8.',
      },
      {
        id: 'thu-thach-iq-lop-4-04',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một hình vuông có cạnh 6cm. Diện tích hình vuông đó là?',
        question_speech: 'Một hình vuông có cạnh 6cm. Diện tích hình vuông đó là?',
        options: ['24 cm²', '12 cm²', '30 cm²', '36 cm²'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Diện tích = 6 × 6 = 36 cm².',
        explanation_speech: 'Diện tích = 6 nhân 6 bằng 36 cm².',
      },
      {
        id: 'thu-thach-iq-lop-4-05',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một nửa (1/2) của 40 là bao nhiêu?',
        question_speech: 'Một nửa (1/2) của 40 là bao nhiêu?',
        options: ['20', '80', '10', '4'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một nửa là chia đôi: 40 : 2 = 20.',
        explanation_speech: 'Một nửa là chia đôi: 40 chia 2 bằng 20.',
      },
      {
        id: 'thu-thach-iq-lop-4-06',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 3 thùng, mỗi thùng 24 chai nước. Tất cả có bao nhiêu chai?',
        question_speech: 'Có 3 thùng, mỗi thùng 24 chai nước. Tất cả có bao nhiêu chai?',
        options: ['27 chai', '72 chai', '48 chai', '64 chai'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi thùng 24 chai, có 3 thùng nên 24 × 3 = 72 chai.',
        explanation_speech: 'Mỗi thùng 24 chai, có 3 thùng nên 24 nhân 3 bằng 72 chai.',
      },
      {
        id: 'thu-thach-iq-lop-4-07',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số lẻ liền sau số 47 là số nào?',
        question_speech: 'Số lẻ liền sau số 47 là số nào?',
        options: ['48', '45', '49', '51'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Số lẻ liền sau 47 là 49.',
        explanation_speech: 'Số lẻ liền sau 47 là 49.',
      },
      {
        id: 'thu-thach-iq-lop-4-08',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một giờ có bao nhiêu phút?',
        question_speech: 'Một giờ có bao nhiêu phút?',
        options: ['100 phút', '30 phút', '24 phút', '60 phút'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Một giờ có 60 phút, một phút có 60 giây.',
        explanation_speech: 'Một giờ có 60 phút.',
      },
      {
        id: 'thu-thach-iq-lop-4-09',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Mua 5 quyển vở, mỗi quyển 8 000 đồng. Hết tất cả bao nhiêu tiền?',
        question_speech: 'Mua 5 quyển vở, mỗi quyển 8 000 đồng. Hết tất cả bao nhiêu tiền?',
        options: ['40 000đ', '13 000đ', '45 000đ', '35 000đ'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '5 × 8 000 = 40 000đ.',
        explanation_speech: '5 nhân 8 000 bằng 40 000đ.',
      },
      {
        id: 'thu-thach-iq-lop-4-10',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tìm x, biết: x : 6 = 8',
        question_speech: 'Tìm x, biết: x : 6 bằng 8',
        options: ['14', '48', '42', '54'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Muốn tìm số bị chia thì lấy thương nhân số chia: x = 8 × 6 = 48. Thử lại 48 : 6 = 8.',
        explanation_speech: 'Muốn tìm số bị chia thì lấy thương nhân số chia: x = 8 nhân 6 bằng 48. Thử lại 48 chia 6 bằng 8.',
      },
      {
        id: 'thu-thach-iq-lop-4-11',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Ba phần tư (3/4) của 12 là bao nhiêu?',
        question_speech: 'Ba phần tư (3/4) của 12 là bao nhiêu?',
        options: ['8', '6', '9', '12'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tìm một phần tư trước: 12 : 4 = 3, rồi lấy 3 phần: 3 × 3 = 9.',
        explanation_speech: 'Tìm một phần tư trước: 12 chia 4 bằng 3, rồi lấy 3 phần: 3 nhân 3 bằng 9.',
      },
      {
        id: 'thu-thach-iq-lop-4-12',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một đội có 32 bạn, xếp đều thành 4 hàng. Mỗi hàng có mấy bạn?',
        question_speech: 'Một đội có 32 bạn, xếp đều thành 4 hàng. Mỗi hàng có mấy bạn?',
        options: ['7 bạn', '6 bạn', '9 bạn', '8 bạn'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Xếp đều thành 4 hàng thì mỗi hàng có 32 : 4 = 8 bạn.',
        explanation_speech: 'Xếp đều thành 4 hàng thì mỗi hàng có 32 chia 4 bằng 8 bạn.',
      },
      {
        id: 'thu-thach-iq-lop-4-13',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hai số có tổng 48, hiệu 12.\nSố bé là số nào?',
        question_speech: 'Hai số có tổng bốn mươi tám, hiệu mười hai. Số bé là số nào?',
        options: ['18', '30', '24', '20'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Số bé = (tổng − hiệu) : 2 = (48 − 12) : 2 = 18. Thử lại: 18 + 30 = 48, 30 − 18 = 12.',
        explanation_speech: 'Bốn mươi tám trừ mười hai bằng ba mươi sáu, chia đôi được mười tám.',
      },
      {
        id: 'thu-thach-iq-lop-4-14',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tổng hai số là 60, số lớn gấp 3 lần số bé.\nSố bé là bao nhiêu?',
        question_speech: 'Tổng hai số là sáu mươi, số lớn gấp ba lần số bé. Số bé là bao nhiêu?',
        options: ['15', '20', '12', '45'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Coi số bé là 1 phần thì số lớn 3 phần, tổng 4 phần. Số bé = 60 : 4 = 15.',
        explanation_speech: 'Sáu mươi chia bốn phần bằng mười lăm.',
      },
      {
        id: 'thu-thach-iq-lop-4-15',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Dãy số cách đều: 5, 11, 17, 23, ...\nSố thứ 10 là số nào?',
        question_speech: 'Dãy số năm, mười một, mười bảy, hai mươi ba. Số thứ mười là số nào?',
        options: ['59', '53', '65', '60'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Khoảng cách 6. Số thứ 10 = 5 + 6 × 9 = 5 + 54 = 59. Nhân với 9 chứ không phải 10 vì số đầu đã tính rồi.',
        explanation_speech: 'Năm cộng sáu nhân chín bằng năm mươi chín.',
      },
      {
        id: 'thu-thach-iq-lop-4-16',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một mảnh vườn hình vuông cạnh 15m.\nDiện tích là bao nhiêu?',
        question_speech: 'Mảnh vườn hình vuông cạnh mười lăm mét, diện tích bao nhiêu?',
        options: ['225 m²', '60 m²', '150 m²', '30 m²'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Diện tích hình vuông = cạnh × cạnh = 15 × 15 = 225 m².',
        explanation_speech: 'Mười lăm nhân mười lăm bằng hai trăm hai mươi lăm.',
      },
      {
        id: 'thu-thach-iq-lop-4-17',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tôi nghĩ ra một số, nhân với 4 rồi trừ 7 thì được 29.\nSố đó là số nào?',
        question_speech: 'Nghĩ một số, nhân bốn rồi trừ bảy được hai mươi chín. Số đó là số nào?',
        options: ['9', '8', '10', '6'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Làm ngược lại: 29 + 7 = 36, rồi 36 : 4 = 9. Thử lại: 9 × 4 − 7 = 29.',
        explanation_speech: 'Hai mươi chín cộng bảy bằng ba mươi sáu, chia bốn được chín.',
      },
      {
        id: 'thu-thach-iq-lop-4-18',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trung bình cộng của 3 số là 20. Hai số đầu là 15 và 22.\nSố thứ ba là bao nhiêu?',
        question_speech: 'Trung bình cộng ba số là hai mươi, hai số đầu là mười lăm và hai mươi hai. Số thứ ba là bao nhiêu?',
        options: ['23', '20', '25', '18'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tổng ba số = 20 × 3 = 60. Số thứ ba = 60 − 15 − 22 = 23.',
        explanation_speech: 'Sáu mươi trừ mười lăm trừ hai mươi hai bằng hai mươi ba.',
      },
      {
        id: 'thu-thach-iq-lop-4-19',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một đàn có cả gà và chó, đếm được 10 cái đầu và 28 cái chân.\nCó mấy con chó?',
        question_speech: 'Đàn có gà và chó, mười cái đầu và hai mươi tám cái chân. Có mấy con chó?',
        options: ['4 con', '6 con', '5 con', '8 con'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Giả sử cả 10 con đều là gà thì có 20 chân, thiếu 8 chân. Mỗi con chó hơn gà 2 chân, nên có 8 : 2 = 4 con chó.',
        explanation_speech: 'Thiếu tám chân, mỗi con chó hơn hai chân nên có bốn con chó.',
      },
      {
        id: 'thu-thach-iq-lop-4-20',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số nào vừa chia hết cho 3 vừa chia hết cho 5?',
        question_speech: 'Số nào vừa chia hết cho ba vừa chia hết cho năm?',
        options: ['45', '35', '27', '50'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '45 : 3 = 15 và 45 : 5 = 9 nên 45 chia hết cho cả hai.',
        explanation_speech: 'Bốn mươi lăm chia hết cho cả ba và năm.',
      },
      {
        id: 'thu-thach-iq-lop-4-21',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một cửa hàng bán 3 ngày được 120 kg gạo, ngày sau bán hơn ngày trước 10 kg.\nNgày đầu bán bao nhiêu?',
        question_speech: 'Ba ngày bán một trăm hai mươi ki-lô-gam, ngày sau hơn ngày trước mười ki-lô. Ngày đầu bán bao nhiêu?',
        options: ['30 kg', '40 kg', '35 kg', '25 kg'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Ngày giữa chính là trung bình: 120 : 3 = 40 kg. Ngày đầu ít hơn 10 kg nên bằng 30 kg.',
        explanation_speech: 'Ngày giữa bốn mươi ki-lô, ngày đầu ít hơn mười nên ba mươi.',
      },
      {
        id: 'thu-thach-iq-lop-4-22',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hình chữ nhật có chu vi 36cm, chiều dài hơn chiều rộng 4cm.\nChiều rộng bằng bao nhiêu?',
        question_speech: 'Chu vi ba mươi sáu, dài hơn rộng bốn. Chiều rộng bằng bao nhiêu?',
        options: ['7cm', '11cm', '8cm', '9cm'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Nửa chu vi = 36 : 2 = 18 = dài + rộng. Rộng = (18 − 4) : 2 = 7cm.',
        explanation_speech: 'Nửa chu vi mười tám, trừ bốn còn mười bốn, chia đôi được bảy.',
      },
      {
        id: 'thu-thach-iq-lop-4-23',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '4 người thợ làm xong một việc trong 6 ngày.\n8 người thợ làm xong việc đó trong mấy ngày?',
        question_speech: 'Bốn thợ làm xong trong sáu ngày, tám thợ làm xong trong mấy ngày?',
        options: ['3 ngày', '12 ngày', '4 ngày', '2 ngày'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Số người gấp đôi thì thời gian giảm một nửa: 6 : 2 = 3 ngày.',
        explanation_speech: 'Gấp đôi người thì mất một nửa thời gian, còn ba ngày.',
      },
      {
        id: 'thu-thach-iq-lop-4-24',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số 2026 có chữ số hàng trăm là chữ số nào?',
        question_speech: 'Số hai nghìn không trăm hai mươi sáu có chữ số hàng trăm là chữ số nào?',
        options: ['0', '2', '6', '20'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '2026 gồm 2 nghìn, 0 trăm, 2 chục, 6 đơn vị. Hàng trăm là 0.',
        explanation_speech: 'Chữ số hàng trăm là không.',
      },
      {
        id: 'thu-thach-iq-lop-4-25',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một năm nhuận có 366 ngày.\nNăm đó có mấy tuần lẻ mấy ngày?',
        question_speech: 'Năm nhuận có ba trăm sáu mươi sáu ngày, có mấy tuần lẻ mấy ngày?',
        options: ['52 tuần lẻ 2 ngày', '52 tuần lẻ 1 ngày', '51 tuần lẻ 5 ngày', '53 tuần chẵn'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '366 : 7 = 52 dư 2, nên 52 tuần lẻ 2 ngày.',
        explanation_speech: 'Ba trăm sáu mươi sáu chia bảy bằng năm mươi hai dư hai.',
      },
      {
        id: 'thu-thach-iq-lop-4-26',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tuổi bố hiện nay gấp 4 lần tuổi con. Bố hơn con 27 tuổi.\nCon mấy tuổi?',
        question_speech: 'Tuổi bố gấp bốn lần tuổi con, bố hơn con hai mươi bảy tuổi. Con mấy tuổi?',
        options: ['9 tuổi', '36 tuổi', '7 tuổi', '12 tuổi'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Bố 4 phần, con 1 phần, hiệu 3 phần bằng 27 tuổi. Một phần là 27 : 3 = 9. Con 9 tuổi.',
        explanation_speech: 'Hiệu ba phần là hai mươi bảy nên một phần là chín tuổi.',
      },
      {
        id: 'thu-thach-iq-lop-4-27',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một ô tô đi 180km hết 3 giờ.\nMỗi giờ ô tô đi được bao nhiêu ki-lô-mét?',
        question_speech: 'Ô tô đi một trăm tám mươi ki-lô-mét hết ba giờ. Mỗi giờ đi được bao nhiêu?',
        options: ['60 km', '54 km', '90 km', '45 km'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '180 : 3 = 60 km mỗi giờ.',
        explanation_speech: 'Một trăm tám mươi chia ba bằng sáu mươi.',
      },
      {
        id: 'thu-thach-iq-lop-4-28',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Có 5 điểm trên đường tròn, nối từng cặp điểm.\nVẽ được mấy đoạn thẳng?',
        question_speech: 'Có năm điểm trên đường tròn, nối từng cặp. Vẽ được mấy đoạn thẳng?',
        options: ['10 đoạn', '5 đoạn', '20 đoạn', '15 đoạn'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi điểm nối với 4 điểm còn lại là 5 × 4 = 20, nhưng mỗi đoạn bị đếm hai lần nên chia đôi: 20 : 2 = 10 đoạn.',
        explanation_speech: 'Hai mươi chia hai bằng mười đoạn.',
      },
      {
        id: 'thu-thach-iq-lop-4-29',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Phân số nào lớn nhất: 2/3, 3/4, 5/6?',
        question_speech: 'Phân số nào lớn nhất, hai phần ba, ba phần tư hay năm phần sáu?',
        options: ['5/6', '3/4', '2/3', 'Bằng nhau'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Quy đồng mẫu 12: 2/3 = 8/12, 3/4 = 9/12, 5/6 = 10/12. Vậy 5/6 lớn nhất.',
        explanation_speech: 'Quy về mẫu mười hai thì năm phần sáu bằng mười phần mười hai, lớn nhất.',
      },
      {
        id: 'thu-thach-iq-lop-4-30',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một lớp có 32 bạn, số bạn nữ bằng 3/5 số bạn nam.\nLớp có mấy bạn nữ?',
        question_speech: 'Lớp có ba mươi hai bạn, số nữ bằng ba phần năm số nam. Lớp có mấy bạn nữ?',
        options: ['12 bạn', '20 bạn', '15 bạn', '18 bạn'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Nữ 3 phần, nam 5 phần, tổng 8 phần = 32 bạn. Một phần là 4 bạn, nữ có 3 × 4 = 12 bạn.',
        explanation_speech: 'Tổng tám phần là ba mươi hai nên một phần bốn bạn, nữ mười hai bạn.',
      },
      {
        id: 'thu-thach-iq-lop-4-31',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tính nhanh: 25 × 4 × 7',
        question_speech: 'Tính nhanh hai mươi lăm nhân bốn nhân bảy.',
        options: ['700', '175', '280', '350'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Nhóm 25 × 4 = 100 trước cho gọn, rồi 100 × 7 = 700.',
        explanation_speech: 'Hai mươi lăm nhân bốn bằng một trăm, nhân bảy bằng bảy trăm.',
      },
      {
        id: 'thu-thach-iq-lop-4-32',
        subject: 'THỬ THÁCH IQ|LỚP 4 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một hình vuông có diện tích 49 cm².\nChu vi bằng bao nhiêu?',
        question_speech: 'Hình vuông có diện tích bốn mươi chín xăng-ti-mét vuông. Chu vi bằng bao nhiêu?',
        options: ['28cm', '14cm', '49cm', '21cm'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Cạnh × cạnh = 49 nên cạnh = 7cm. Chu vi = 7 × 4 = 28cm.',
        explanation_speech: 'Cạnh bảy, chu vi bằng bảy nhân bốn là hai mươi tám.',
      },
    ],
  },
  5: {
    grade: 5,
    intro:
      'Toán tư duy lớp 5 nâng cao với toán chuyển động, tỉ số phần trăm, phân số và hình học nâng cao. Bé rèn tư duy phân tích, tổng hợp và giải các bài toán nhiều bước — hành trang vững cho bậc THCS.',
    topics: [
      'Toán chuyển động (vận tốc, quãng đường, thời gian)',
      'Tỉ số phần trăm theo tư duy',
      'Phân số và bài toán tỉ lệ',
      'Suy luận logic nâng cao',
      'Hình học nâng cao (diện tích, thể tích)',
      'Bài toán cổ, bài toán dân gian',
    ],
    faq: [
      { q: 'Toán tư duy lớp 5 học những gì?', a: 'Bé học toán chuyển động, tỉ số phần trăm, phân số – tỉ lệ, suy luận nâng cao, hình học nâng cao và các bài toán cổ.' },
      { q: 'Toán tư duy lớp 5 có giúp thi vào lớp 6 không?', a: 'Có. Nhiều dạng bài tư duy lớp 5 xuất hiện trong đề khảo sát và thi vào lớp 6 chất lượng cao, nên luyện tập sớm rất có lợi.' },
      { q: 'Làm sao để bé giải nhanh bài nhiều bước?', a: 'Tập tóm tắt đề, chia bài toán thành các bước nhỏ, và luôn kiểm tra lại kết quả bằng cách thử hoặc ước lượng.' },
    ],
    questions: [
      {
        id: 'thu-thach-iq-lop-5-01',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '2,5 + 1,5 = ?',
        question_speech: '2,5 cộng 1,5 bằng bao nhiêu',
        options: ['4', '3', '4,5', '3,5'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Cộng phần thập phân trước: 0,5 + 0,5 = 1, rồi 2 + 1 + 1 = 4. Kết quả là 4.',
        explanation_speech: 'Cộng phần thập phân trước: 0,5 cộng 0,5 bằng 1, rồi 2 cộng 1 + 1 bằng 4. Kết quả là 4.',
      },
      {
        id: 'thu-thach-iq-lop-5-02',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '1/2 + 1/4 bằng bao nhiêu?',
        question_speech: '1/2 cộng 1/4 bằng bao nhiêu?',
        options: ['2/6', '3/4', '1/2', '1'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '1/2 = 2/4; 2/4 + 1/4 = 3/4.',
        explanation_speech: '1/2 bằng 2/4; 2/4 cộng 1/4 bằng 3/4.',
      },
      {
        id: 'thu-thach-iq-lop-5-03',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '10% của 200 là bao nhiêu?',
        question_speech: '10% của 200 là bao nhiêu?',
        options: ['10', '100', '20', '2'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '10% nghĩa là mười phần trăm, tức chia cho 10: 200 : 10 = 20.',
        explanation_speech: '10% nghĩa là mười phần trăm, tức chia cho 10 chia 200 chia 10 bằng 20.',
      },
      {
        id: 'thu-thach-iq-lop-5-04',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hình chữ nhật dài 8cm, rộng 5cm. Diện tích là bao nhiêu?',
        question_speech: 'Hình chữ nhật dài 8cm, rộng 5cm. Diện tích là bao nhiêu?',
        options: ['13 cm²', '26 cm²', '45 cm²', '40 cm²'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Diện tích = 8 × 5 = 40 cm².',
        explanation_speech: 'Diện tích = 8 nhân 5 bằng 40 cm².',
      },
      {
        id: 'thu-thach-iq-lop-5-05',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một ô tô đi 60km trong 2 giờ. Vận tốc của ô tô là?',
        question_speech: 'Một ô tô đi 60km trong 2 giờ. Vận tốc của ô tô là?',
        options: ['30 km/giờ', '120 km/giờ', '62 km/giờ', '15 km/giờ'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Vận tốc = 60 : 2 = 30 km/giờ.',
        explanation_speech: 'Vận tốc = 60 chia 2 bằng 30 km/giờ.',
      },
      {
        id: 'thu-thach-iq-lop-5-06',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '3,6 × 10 = ?',
        question_speech: '3,6 nhân 10 bằng bao nhiêu',
        options: ['3,6', '36', '360', '30,6'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Nhân với 10 thì dời dấu phẩy sang phải một chữ số: 3,6 thành 36.',
        explanation_speech: 'Nhân với 10 thì dời dấu phẩy sang phải một chữ số: 3,6 thành 36.',
      },
      {
        id: 'thu-thach-iq-lop-5-07',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trung bình cộng của 4, 6 và 8 là bao nhiêu?',
        question_speech: 'Trung bình cộng của 4, 6 và 8 là bao nhiêu?',
        options: ['18', '9', '6', '7'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '(4 + 6 + 8) : 3 = 6.',
        explanation_speech: '(4 cộng 6 + 8) : 3 bằng 6.',
      },
      {
        id: 'thu-thach-iq-lop-5-08',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '1 giờ 30 phút bằng bao nhiêu phút?',
        question_speech: '1 giờ 30 phút bằng bao nhiêu phút?',
        options: ['130 phút', '60 phút', '75 phút', '90 phút'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '1 giờ = 60 phút; 60 + 30 = 90 phút.',
        explanation_speech: '1 giờ = 60 phút; 60 cộng 30 bằng 90 phút.',
      },
      {
        id: 'thu-thach-iq-lop-5-09',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số thập phân 0,5 bằng phân số nào?',
        question_speech: 'Số thập phân 0,5 bằng phân số nào?',
        options: ['1/2', '1/5', '1/4', '5/1'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '0,5 đọc là năm phần mười, rút gọn chia cả hai cho 5 được 1/2.',
        explanation_speech: '0,5 đọc là năm phần mười, rút gọn chia cả hai cho 5 được 1/2.',
      },
      {
        id: 'thu-thach-iq-lop-5-10',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một mảnh vườn hình vuông cạnh 10m. Chu vi mảnh vườn là?',
        question_speech: 'Một mảnh vườn hình vuông cạnh 10m. Chu vi mảnh vườn là?',
        options: ['100m', '40m', '20m', '14m'],
        correct_index: 1,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Chu vi = 10 × 4 = 40m.',
        explanation_speech: 'Chu vi = 10 nhân 4 bằng 40m.',
      },
      {
        id: 'thu-thach-iq-lop-5-11',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '25% của 80 là bao nhiêu?',
        question_speech: '25% của 80 là bao nhiêu?',
        options: ['25', '40', '20', '16'],
        correct_index: 2,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '25% là một phần tư, nên lấy 80 : 4 = 20.',
        explanation_speech: '25% là một phần tư, nên lấy 80 chia 4 bằng 20.',
      },
      {
        id: 'thu-thach-iq-lop-5-12',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: '144 : 12 + 6 = ?',
        question_speech: '144 chia 12 cộng 6 bằng bao nhiêu',
        options: ['12', '24', '66', '18'],
        correct_index: 3,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tính chia trước: 144 : 12 = 12; 12 + 6 = 18.',
        explanation_speech: 'Tính chia trước: 144 chia 12 bằng 12; 12 cộng 6 bằng 18.',
      },
      {
        id: 'thu-thach-iq-lop-5-13',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một ô tô đi với vận tốc 45 km/giờ trong 2 giờ 30 phút.\nQuãng đường dài bao nhiêu?',
        question_speech: 'Ô tô đi bốn mươi lăm ki-lô-mét giờ trong hai giờ ba mươi phút. Quãng đường dài bao nhiêu?',
        options: ['112,5 km', '90 km', '135 km', '100 km'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Đổi 2 giờ 30 phút = 2,5 giờ. Quãng đường = 45 × 2,5 = 112,5 km.',
        explanation_speech: 'Bốn mươi lăm nhân hai phẩy năm bằng một trăm mười hai phẩy năm.',
      },
      {
        id: 'thu-thach-iq-lop-5-14',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Giá một món hàng là 200.000 đồng, giảm 15%.\nGiá sau khi giảm là bao nhiêu?',
        question_speech: 'Giá hai trăm nghìn đồng giảm mười lăm phần trăm. Giá sau khi giảm là bao nhiêu?',
        options: ['170.000 đồng', '185.000 đồng', '30.000 đồng', '150.000 đồng'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Giảm 15% tức còn 85%: 200.000 × 85 : 100 = 170.000 đồng.',
        explanation_speech: 'Còn tám mươi lăm phần trăm là một trăm bảy mươi nghìn đồng.',
      },
      {
        id: 'thu-thach-iq-lop-5-15',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hai người đi ngược chiều cách nhau 60km, vận tốc 12 km/giờ và 18 km/giờ.\nSau mấy giờ họ gặp nhau?',
        question_speech: 'Hai người đi ngược chiều cách nhau sáu mươi ki-lô-mét, vận tốc mười hai và mười tám. Sau mấy giờ gặp nhau?',
        options: ['2 giờ', '3 giờ', '4 giờ', '5 giờ'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi giờ hai người lại gần nhau 12 + 18 = 30 km. Thời gian gặp = 60 : 30 = 2 giờ.',
        explanation_speech: 'Mỗi giờ gần nhau ba mươi ki-lô-mét nên gặp sau hai giờ.',
      },
      {
        id: 'thu-thach-iq-lop-5-16',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một bể hình hộp chữ nhật dài 2m, rộng 1,5m, cao 1m.\nThể tích bể là bao nhiêu?',
        question_speech: 'Bể dài hai mét, rộng một phẩy năm mét, cao một mét. Thể tích bao nhiêu?',
        options: ['3 m³', '4,5 m³', '2 m³', '6 m³'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Thể tích = dài × rộng × cao = 2 × 1,5 × 1 = 3 m³.',
        explanation_speech: 'Hai nhân một phẩy năm nhân một bằng ba mét khối.',
      },
      {
        id: 'thu-thach-iq-lop-5-17',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Lớp có 40 bạn, trong đó 45% là nữ.\nCó bao nhiêu bạn nữ?',
        question_speech: 'Lớp bốn mươi bạn, bốn mươi lăm phần trăm là nữ. Có bao nhiêu bạn nữ?',
        options: ['18 bạn', '22 bạn', '20 bạn', '16 bạn'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '40 × 45 : 100 = 18 bạn nữ.',
        explanation_speech: 'Bốn mươi nhân bốn mươi lăm chia một trăm bằng mười tám.',
      },
      {
        id: 'thu-thach-iq-lop-5-18',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tổng hai số là 90, tỉ số của chúng là 2/3.\nSố lớn là số nào?',
        question_speech: 'Tổng hai số là chín mươi, tỉ số hai phần ba. Số lớn là số nào?',
        options: ['54', '36', '60', '45'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Số bé 2 phần, số lớn 3 phần, tổng 5 phần = 90. Một phần 18, số lớn = 3 × 18 = 54.',
        explanation_speech: 'Một phần mười tám, số lớn ba phần là năm mươi tư.',
      },
      {
        id: 'thu-thach-iq-lop-5-19',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số thập phân 0,25 bằng phân số nào?',
        question_speech: 'Số thập phân không phẩy hai mươi lăm bằng phân số nào?',
        options: ['1/4', '1/2', '2/5', '1/25'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '0,25 = 25/100, rút gọn chia cả hai cho 25 được 1/4.',
        explanation_speech: 'Hai mươi lăm phần trăm rút gọn thành một phần tư.',
      },
      {
        id: 'thu-thach-iq-lop-5-20',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một người bán hàng lãi 20% so với giá vốn. Giá vốn 500.000 đồng.\nGiá bán là bao nhiêu?',
        question_speech: 'Lãi hai mươi phần trăm so với giá vốn năm trăm nghìn. Giá bán là bao nhiêu?',
        options: ['600.000 đồng', '520.000 đồng', '400.000 đồng', '100.000 đồng'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Lãi = 500.000 × 20 : 100 = 100.000. Giá bán = 500.000 + 100.000 = 600.000 đồng.',
        explanation_speech: 'Lãi một trăm nghìn nên giá bán sáu trăm nghìn.',
      },
      {
        id: 'thu-thach-iq-lop-5-21',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một vòi chảy đầy bể trong 4 giờ, vòi kia trong 6 giờ.\nHai vòi cùng chảy thì mấy giờ đầy bể?',
        question_speech: 'Vòi một đầy bể trong bốn giờ, vòi hai trong sáu giờ. Cùng chảy thì mấy giờ đầy?',
        options: ['2,4 giờ', '5 giờ', '2 giờ', '10 giờ'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Mỗi giờ vòi 1 chảy 1/4 bể, vòi 2 chảy 1/6 bể, cộng lại 5/12 bể. Thời gian = 1 : 5/12 = 12/5 = 2,4 giờ.',
        explanation_speech: 'Mỗi giờ hai vòi chảy năm phần mười hai bể nên đầy sau hai phẩy bốn giờ.',
      },
      {
        id: 'thu-thach-iq-lop-5-22',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Diện tích hình tam giác có đáy 12cm, chiều cao 5cm là bao nhiêu?',
        question_speech: 'Tam giác có đáy mười hai, chiều cao năm. Diện tích bao nhiêu?',
        options: ['30 cm²', '60 cm²', '17 cm²', '34 cm²'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Diện tích tam giác = đáy × cao : 2 = 12 × 5 : 2 = 30 cm².',
        explanation_speech: 'Mười hai nhân năm chia hai bằng ba mươi.',
      },
      {
        id: 'thu-thach-iq-lop-5-23',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một hình tròn có bán kính 4cm.\nDiện tích bằng bao nhiêu (lấy π = 3,14)?',
        question_speech: 'Hình tròn bán kính bốn xăng-ti-mét, diện tích bằng bao nhiêu, lấy pi bằng ba phẩy mười bốn?',
        options: ['50,24 cm²', '25,12 cm²', '12,56 cm²', '100,48 cm²'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Diện tích = r × r × π = 4 × 4 × 3,14 = 50,24 cm².',
        explanation_speech: 'Bốn nhân bốn nhân ba phẩy mười bốn bằng năm mươi phẩy hai tư.',
      },
      {
        id: 'thu-thach-iq-lop-5-24',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Trâu đứng ăn 5, trâu nằm ăn 3, lụ khụ trâu già 3 con một bó.\nCó 100 con trâu ăn 100 bó cỏ, hỏi có mấy trâu già? (biết có 4 trâu đứng, 18 trâu nằm)',
        question_speech: 'Có một trăm con trâu ăn một trăm bó cỏ, bốn trâu đứng, mười tám trâu nằm. Có mấy trâu già?',
        options: ['78 con', '70 con', '80 con', '72 con'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tổng 100 con: trâu già = 100 − 4 − 18 = 78 con. Kiểm lại cỏ: 4×5 + 18×3 + 78:3 = 20 + 54 + 26 = 100 bó.',
        explanation_speech: 'Một trăm trừ bốn trừ mười tám bằng bảy mươi tám con.',
      },
      {
        id: 'thu-thach-iq-lop-5-25',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tỉ số phần trăm của 18 và 45 là bao nhiêu?',
        question_speech: 'Tỉ số phần trăm của mười tám và bốn mươi lăm là bao nhiêu?',
        options: ['40%', '25%', '45%', '50%'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: '18 : 45 = 0,4 = 40%.',
        explanation_speech: 'Mười tám chia bốn mươi lăm bằng không phẩy bốn, tức bốn mươi phần trăm.',
      },
      {
        id: 'thu-thach-iq-lop-5-26',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một mảnh đất hình thang có đáy lớn 20m, đáy bé 12m, chiều cao 8m.\nDiện tích là bao nhiêu?',
        question_speech: 'Hình thang đáy lớn hai mươi, đáy bé mười hai, cao tám. Diện tích bao nhiêu?',
        options: ['128 m²', '256 m²', '160 m²', '96 m²'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Diện tích hình thang = (đáy lớn + đáy bé) × cao : 2 = (20 + 12) × 8 : 2 = 128 m².',
        explanation_speech: 'Ba mươi hai nhân tám chia hai bằng một trăm hai mươi tám.',
      },
      {
        id: 'thu-thach-iq-lop-5-27',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Số trung bình cộng của 5 số là 12. Thêm số thứ sáu thì trung bình cộng thành 13.\nSố thứ sáu là bao nhiêu?',
        question_speech: 'Trung bình cộng năm số là mười hai, thêm số thứ sáu thì trung bình thành mười ba. Số thứ sáu là bao nhiêu?',
        options: ['18', '13', '15', '20'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Tổng 5 số = 60, tổng 6 số = 13 × 6 = 78. Số thứ sáu = 78 − 60 = 18.',
        explanation_speech: 'Bảy mươi tám trừ sáu mươi bằng mười tám.',
      },
      {
        id: 'thu-thach-iq-lop-5-28',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một xe máy đi 40km hết 50 phút.\nVận tốc là bao nhiêu km/giờ?',
        question_speech: 'Xe máy đi bốn mươi ki-lô-mét hết năm mươi phút. Vận tốc bao nhiêu ki-lô-mét giờ?',
        options: ['48 km/giờ', '50 km/giờ', '45 km/giờ', '32 km/giờ'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Đổi 50 phút = 50/60 giờ = 5/6 giờ. Vận tốc = 40 : 5/6 = 48 km/giờ.',
        explanation_speech: 'Bốn mươi chia năm phần sáu bằng bốn mươi tám.',
      },
      {
        id: 'thu-thach-iq-lop-5-29',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Rút gọn phân số 36/48 được phân số nào?',
        question_speech: 'Rút gọn phân số ba mươi sáu phần bốn mươi tám.',
        options: ['3/4', '6/8', '9/12', '2/3'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Chia cả tử và mẫu cho 12: 36 : 12 = 3, 48 : 12 = 4, được 3/4 là tối giản.',
        explanation_speech: 'Chia cả hai cho mười hai được ba phần tư.',
      },
      {
        id: 'thu-thach-iq-lop-5-30',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Một đội trồng 250 cây, đã trồng được 60%.\nCòn phải trồng bao nhiêu cây?',
        question_speech: 'Đội trồng hai trăm năm mươi cây, đã trồng sáu mươi phần trăm. Còn phải trồng bao nhiêu?',
        options: ['100 cây', '150 cây', '190 cây', '90 cây'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Còn lại 40%: 250 × 40 : 100 = 100 cây.',
        explanation_speech: 'Còn bốn mươi phần trăm là một trăm cây.',
      },
      {
        id: 'thu-thach-iq-lop-5-31',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Hai số có hiệu 36, số lớn gấp 4 lần số bé.\nSố bé là bao nhiêu?',
        question_speech: 'Hai số có hiệu ba mươi sáu, số lớn gấp bốn lần số bé. Số bé là bao nhiêu?',
        options: ['12', '9', '48', '6'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Số bé 1 phần, số lớn 4 phần, hiệu 3 phần = 36. Một phần = 12, vậy số bé là 12.',
        explanation_speech: 'Hiệu ba phần là ba mươi sáu nên một phần mười hai.',
      },
      {
        id: 'thu-thach-iq-lop-5-32',
        subject: 'THỬ THÁCH IQ|LỚP 5 - Toán tư duy',
        lesson: 'Toán tư duy',
        question: 'Tính nhanh: 0,25 × 8 × 4',
        question_speech: 'Tính nhanh không phẩy hai mươi lăm nhân tám nhân bốn.',
        options: ['8', '6', '16', '2'],
        correct_index: 0,
        countdown: ['5', '4', '3', '2', '1'],
        explanation: 'Nhóm 0,25 × 4 = 1 trước, rồi 1 × 8 = 8.',
        explanation_speech: 'Không phẩy hai mươi lăm nhân bốn bằng một, nhân tám bằng tám.',
      },
    ],
  },
};

export function getTuDuyGrade(grade: number): TuDuyGrade | null {
  return TOAN_TU_DUY[grade] ?? null;
}
