export type OppositeCategory = 'size' | 'temperature' | 'position' | 'speed' | 'emotion';
export type OppositeLevel = 'easy' | 'medium' | 'hard';

export type OppositeQuestion = {
  id: string;
  prompt: string;
  leftText: string;
  leftEmoji: string;
  correct: string;
  options: string[];
  level: OppositeLevel;
  category: OppositeCategory;
};

export const oppositeCategories = [
  { key: 'size', label: 'Kích thước', icon: '📏', total: 6 },
  { key: 'temperature', label: 'Nhiệt độ', icon: '🌡️', total: 6 },
  { key: 'position', label: 'Vị trí', icon: '📍', total: 6 },
  { key: 'speed', label: 'Tốc độ', icon: '⚡', total: 6 },
  { key: 'emotion', label: 'Cảm xúc', icon: '😊', total: 6 },
] as const;

export const oppositeData: Record<
  OppositeCategory,
  {
    label: string;
    icon: string;
    questions: OppositeQuestion[];
  }
> = {
  size: {
    label: 'Kích thước',
    icon: '📏',
    questions: [
      {
        id: 'size-1',
        prompt: 'Hãy chọn từ trái nghĩa với “to”',
        leftText: 'To',
        leftEmoji: '🐘',
        correct: 'Nhỏ',
        options: ['Nhỏ', 'Cao', 'Nóng', 'Nhanh'],
        level: 'easy',
        category: 'size',
      },
      {
        id: 'size-2',
        prompt: 'Hãy chọn từ trái nghĩa với “dài”',
        leftText: 'Dài',
        leftEmoji: '🪢',
        correct: 'Ngắn',
        options: ['Ngắn', 'Rộng', 'Chậm', 'Xa'],
        level: 'easy',
        category: 'size',
      },
      {
        id: 'size-3',
        prompt: 'Hãy chọn từ trái nghĩa với “cao”',
        leftText: 'Cao',
        leftEmoji: '🏢',
        correct: 'Thấp',
        options: ['Thấp', 'To', 'Nặng', 'Lạnh'],
        level: 'medium',
        category: 'size',
      },
      {
        id: 'size-4',
        prompt: 'Hãy chọn từ trái nghĩa với “rộng”',
        leftText: 'Rộng',
        leftEmoji: '🛣️',
        correct: 'Hẹp',
        options: ['Hẹp', 'Dài', 'Xa', 'Vui'],
        level: 'medium',
        category: 'size',
      },
      {
        id: 'size-5',
        prompt: 'Hãy chọn từ trái nghĩa với “nặng”',
        leftText: 'Nặng',
        leftEmoji: '🏋️',
        correct: 'Nhẹ',
        options: ['Nhẹ', 'To', 'Ngắn', 'Tối'],
        level: 'hard',
        category: 'size',
      },
      {
        id: 'size-6',
        prompt: 'Hãy chọn từ trái nghĩa với “dày”',
        leftText: 'Dày',
        leftEmoji: '📚',
        correct: 'Mỏng',
        options: ['Mỏng', 'Rộng', 'Cao', 'Nhanh'],
        level: 'hard',
        category: 'size',
      },
    ],
  },
  temperature: {
    label: 'Nhiệt độ',
    icon: '🌡️',
    questions: [
      {
        id: 'temp-1',
        prompt: 'Hãy chọn từ trái nghĩa với “nóng”',
        leftText: 'Nóng',
        leftEmoji: '☀️',
        correct: 'Lạnh',
        options: ['Lạnh', 'Xa', 'Cao', 'Chậm'],
        level: 'easy',
        category: 'temperature',
      },
      {
        id: 'temp-2',
        prompt: 'Hãy chọn từ trái nghĩa với “ấm”',
        leftText: 'Ấm',
        leftEmoji: '🧣',
        correct: 'Mát',
        options: ['Mát', 'To', 'Hẹp', 'Buồn'],
        level: 'medium',
        category: 'temperature',
      },
      {
        id: 'temp-3',
        prompt: 'Hãy chọn từ trái nghĩa với “khô”',
        leftText: 'Khô',
        leftEmoji: '🏜️',
        correct: 'Ướt',
        options: ['Ướt', 'Lạnh', 'Sáng', 'Cao'],
        level: 'medium',
        category: 'temperature',
      },
      {
        id: 'temp-4',
        prompt: 'Hãy chọn từ trái nghĩa với “sáng”',
        leftText: 'Sáng',
        leftEmoji: '💡',
        correct: 'Tối',
        options: ['Tối', 'Lạnh', 'Ngắn', 'Nhẹ'],
        level: 'hard',
        category: 'temperature',
      },
      {
        id: 'temp-5',
        prompt: 'Hãy chọn từ trái nghĩa với “đông”',
        leftText: 'Đông',
        leftEmoji: '❄️',
        correct: 'Hè',
        options: ['Hè', 'Mưa', 'Lạnh', 'Khô'],
        level: 'hard',
        category: 'temperature',
      },
      {
        id: 'temp-6',
        prompt: 'Hãy chọn từ trái nghĩa với “mưa”',
        leftText: 'Mưa',
        leftEmoji: '🌧️',
        correct: 'Nắng',
        options: ['Nắng', 'Tối', 'Ngắn', 'Nhỏ'],
        level: 'easy',
        category: 'temperature',
      },
    ],
  },
  position: {
    label: 'Vị trí',
    icon: '📍',
    questions: [
      {
        id: 'pos-1',
        prompt: 'Hãy chọn từ trái nghĩa với “trên”',
        leftText: 'Trên',
        leftEmoji: '⬆️',
        correct: 'Dưới',
        options: ['Dưới', 'Ngoài', 'Xa', 'Sau'],
        level: 'easy',
        category: 'position',
      },
      {
        id: 'pos-2',
        prompt: 'Hãy chọn từ trái nghĩa với “trong”',
        leftText: 'Trong',
        leftEmoji: '📦',
        correct: 'Ngoài',
        options: ['Ngoài', 'Trên', 'Xa', 'Nhanh'],
        level: 'easy',
        category: 'position',
      },
      {
        id: 'pos-3',
        prompt: 'Hãy chọn từ trái nghĩa với “trước”',
        leftText: 'Trước',
        leftEmoji: '🚶',
        correct: 'Sau',
        options: ['Sau', 'Dưới', 'Nhỏ', 'Rộng'],
        level: 'medium',
        category: 'position',
      },
      {
        id: 'pos-4',
        prompt: 'Hãy chọn từ trái nghĩa với “gần”',
        leftText: 'Gần',
        leftEmoji: '🤝',
        correct: 'Xa',
        options: ['Xa', 'Trong', 'Dài', 'Buồn'],
        level: 'medium',
        category: 'position',
      },
      {
        id: 'pos-5',
        prompt: 'Hãy chọn từ trái nghĩa với “bên trái”',
        leftText: 'Trái',
        leftEmoji: '⬅️',
        correct: 'Bên phải',
        options: ['Bên phải', 'Ở dưới', 'Ở sau', 'Ở xa'],
        level: 'hard',
        category: 'position',
      },
      {
        id: 'pos-6',
        prompt: 'Hãy chọn từ trái nghĩa với “đầu”',
        leftText: 'Đầu',
        leftEmoji: '🚂',
        correct: 'Cuối',
        options: ['Cuối', 'Ngoài', 'Nhỏ', 'Ướt'],
        level: 'hard',
        category: 'position',
      },
    ],
  },
  speed: {
    label: 'Tốc độ',
    icon: '⚡',
    questions: [
      {
        id: 'speed-1',
        prompt: 'Hãy chọn từ trái nghĩa với “nhanh”',
        leftText: 'Nhanh',
        leftEmoji: '🏃',
        correct: 'Chậm',
        options: ['Chậm', 'Nhỏ', 'Thấp', 'Tối'],
        level: 'easy',
        category: 'speed',
      },
      {
        id: 'speed-2',
        prompt: 'Hãy chọn từ trái nghĩa với “thức”',
        leftText: 'Thức',
        leftEmoji: '👀',
        correct: 'Ngủ',
        options: ['Ngủ', 'Ngồi', 'Buồn', 'Mỏng'],
        level: 'easy',
        category: 'speed',
      },
      {
        id: 'speed-3',
        prompt: 'Hãy chọn từ trái nghĩa với “đứng”',
        leftText: 'Đứng',
        leftEmoji: '🧍',
        correct: 'Ngồi',
        options: ['Ngồi', 'Nằm', 'Đi', 'Chạy'],
        level: 'medium',
        category: 'speed',
      },
      {
        id: 'speed-4',
        prompt: 'Hãy chọn từ trái nghĩa với “mở”',
        leftText: 'Mở',
        leftEmoji: '🚪',
        correct: 'Đóng',
        options: ['Đóng', 'Thấp', 'Hẹp', 'Chậm'],
        level: 'medium',
        category: 'speed',
      },
      {
        id: 'speed-5',
        prompt: 'Hãy chọn từ trái nghĩa với “đến”',
        leftText: 'Đến',
        leftEmoji: '🛬',
        correct: 'Đi',
        options: ['Đi', 'Ngủ', 'Chậm', 'Tối'],
        level: 'hard',
        category: 'speed',
      },
      {
        id: 'speed-6',
        prompt: 'Hãy chọn từ trái nghĩa với “lên”',
        leftText: 'Lên',
        leftEmoji: '🪜',
        correct: 'Xuống',
        options: ['Xuống', 'Ra', 'Vào', 'Mở'],
        level: 'hard',
        category: 'speed',
      },
    ],
  },
  emotion: {
    label: 'Cảm xúc',
    icon: '😊',
    questions: [
      {
        id: 'emo-1',
        prompt: 'Hãy chọn từ trái nghĩa với “vui”',
        leftText: 'Vui',
        leftEmoji: '😄',
        correct: 'Buồn',
        options: ['Buồn', 'Giận', 'Lạnh', 'Nhỏ'],
        level: 'easy',
        category: 'emotion',
      },
      {
        id: 'emo-2',
        prompt: 'Hãy chọn từ trái nghĩa với “cười”',
        leftText: 'Cười',
        leftEmoji: '😂',
        correct: 'Khóc',
        options: ['Khóc', 'Ngủ', 'Chạy', 'Mở'],
        level: 'easy',
        category: 'emotion',
      },
      {
        id: 'emo-3',
        prompt: 'Hãy chọn từ trái nghĩa với “yêu”',
        leftText: 'Yêu',
        leftEmoji: '💖',
        correct: 'Ghét',
        options: ['Ghét', 'Buồn', 'Lạnh', 'Xa'],
        level: 'medium',
        category: 'emotion',
      },
      {
        id: 'emo-4',
        prompt: 'Hãy chọn từ trái nghĩa với “can đảm”',
        leftText: 'Can đảm',
        leftEmoji: '🦁',
        correct: 'Sợ hãi',
        options: ['Sợ hãi', 'Buồn ngủ', 'Giận dữ', 'Yếu'],
        level: 'hard',
        category: 'emotion',
      },
      {
        id: 'emo-5',
        prompt: 'Hãy chọn từ trái nghĩa với “bình tĩnh”',
        leftText: 'Bình tĩnh',
        leftEmoji: '🧘',
        correct: 'Lo lắng',
        options: ['Lo lắng', 'Buồn', 'Mệt', 'Chậm'],
        level: 'hard',
        category: 'emotion',
      },
      {
        id: 'emo-6',
        prompt: 'Hãy chọn từ trái nghĩa với “mạnh”',
        leftText: 'Mạnh',
        leftEmoji: '💪',
        correct: 'Yếu',
        options: ['Yếu', 'Nhẹ', 'Nhỏ', 'Tối'],
        level: 'medium',
        category: 'emotion',
      },
    ],
  },
};