export type HalfMatchCategory =
  | 'fruits'
  | 'animals'
  | 'objects'
  | 'faces'
  | 'mixed';

export type HalfMatchLevel = 'easy' | 'medium' | 'hard';

export type HalfMatchQuestion = {
  id: string;
  prompt: string;
  hint: string;
  level: HalfMatchLevel;
  category: HalfMatchCategory;
  leftHalf: string;
  correct: string;
  fullLabel: string;
  options: string[];
};

export const halfMatchCategories = [
  { key: 'fruits', label: 'Trái cây', icon: '🍎', total: 6 },
  { key: 'animals', label: 'Con vật', icon: '🐻', total: 6 },
  { key: 'objects', label: 'Đồ vật', icon: '🧸', total: 6 },
  { key: 'faces', label: 'Biểu cảm', icon: '😊', total: 6 },
  { key: 'mixed', label: 'Tổng hợp', icon: '✨', total: 6 },
] as const;

export const halfMatchData: Record<
  HalfMatchCategory,
  {
    label: string;
    icon: string;
    questions: HalfMatchQuestion[];
  }
> = {
  fruits: {
    label: 'Trái cây',
    icon: '🍎',
    questions: [
      {
        id: 'fruits-1',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành quả táo hoàn chỉnh',
        level: 'easy',
        category: 'fruits',
        leftHalf: '🍎',
        correct: '🍎',
        fullLabel: 'Quả táo',
        options: ['🍎', '🍊', '🍋', '🍓'],
      },
      {
        id: 'fruits-2',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần ghép đúng của quả cam',
        level: 'easy',
        category: 'fruits',
        leftHalf: '🍊',
        correct: '🍊',
        fullLabel: 'Quả cam',
        options: ['🍊', '🍎', '🥝', '🍇'],
      },
      {
        id: 'fruits-3',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành quả chuối',
        level: 'medium',
        category: 'fruits',
        leftHalf: '🍌',
        correct: '🍌',
        fullLabel: 'Quả chuối',
        options: ['🍌', '🍍', '🍐', '🍒'],
      },
      {
        id: 'fruits-4',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần còn lại của quả dâu',
        level: 'medium',
        category: 'fruits',
        leftHalf: '🍓',
        correct: '🍓',
        fullLabel: 'Quả dâu',
        options: ['🍓', '🍉', '🍋', '🍎'],
      },
      {
        id: 'fruits-5',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành quả nho',
        level: 'hard',
        category: 'fruits',
        leftHalf: '🍇',
        correct: '🍇',
        fullLabel: 'Chùm nho',
        options: ['🍇', '🥥', '🍊', '🥭'],
      },
      {
        id: 'fruits-6',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần ghép đúng của quả dứa',
        level: 'hard',
        category: 'fruits',
        leftHalf: '🍍',
        correct: '🍍',
        fullLabel: 'Quả dứa',
        options: ['🍍', '🍎', '🍋', '🍒'],
      },
    ],
  },

  animals: {
    label: 'Con vật',
    icon: '🐻',
    questions: [
      {
        id: 'animals-1',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành con mèo',
        level: 'easy',
        category: 'animals',
        leftHalf: '🐱',
        correct: '🐱',
        fullLabel: 'Con mèo',
        options: ['🐱', '🐶', '🐰', '🐻'],
      },
      {
        id: 'animals-2',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần ghép đúng của con chó',
        level: 'easy',
        category: 'animals',
        leftHalf: '🐶',
        correct: '🐶',
        fullLabel: 'Con chó',
        options: ['🐶', '🐱', '🐵', '🐯'],
      },
      {
        id: 'animals-3',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành con thỏ',
        level: 'medium',
        category: 'animals',
        leftHalf: '🐰',
        correct: '🐰',
        fullLabel: 'Con thỏ',
        options: ['🐰', '🐻', '🦁', '🐸'],
      },
      {
        id: 'animals-4',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần đúng của con gấu',
        level: 'medium',
        category: 'animals',
        leftHalf: '🐻',
        correct: '🐻',
        fullLabel: 'Con gấu',
        options: ['🐻', '🐹', '🐷', '🐔'],
      },
      {
        id: 'animals-5',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành con cá',
        level: 'hard',
        category: 'animals',
        leftHalf: '🐟',
        correct: '🐟',
        fullLabel: 'Con cá',
        options: ['🐟', '🦆', '🐘', '🐢'],
      },
      {
        id: 'animals-6',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần ghép đúng của con voi',
        level: 'hard',
        category: 'animals',
        leftHalf: '🐘',
        correct: '🐘',
        fullLabel: 'Con voi',
        options: ['🐘', '🦒', '🦓', '🐄'],
      },
    ],
  },

  objects: {
    label: 'Đồ vật',
    icon: '🧸',
    questions: [
      {
        id: 'objects-1',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành quả bóng',
        level: 'easy',
        category: 'objects',
        leftHalf: '⚽',
        correct: '⚽',
        fullLabel: 'Quả bóng',
        options: ['⚽', '🏀', '🎾', '🧸'],
      },
      {
        id: 'objects-2',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần ghép đúng của chiếc cặp',
        level: 'easy',
        category: 'objects',
        leftHalf: '🎒',
        correct: '🎒',
        fullLabel: 'Cái cặp',
        options: ['🎒', '👜', '👟', '🪑'],
      },
      {
        id: 'objects-3',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành cái bút',
        level: 'medium',
        category: 'objects',
        leftHalf: '🖊️',
        correct: '🖊️',
        fullLabel: 'Cái bút',
        options: ['🖊️', '✏️', '📏', '✂️'],
      },
      {
        id: 'objects-4',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần còn lại của cái kéo',
        level: 'medium',
        category: 'objects',
        leftHalf: '✂️',
        correct: '✂️',
        fullLabel: 'Cái kéo',
        options: ['✂️', '📘', '🧃', '🪥'],
      },
      {
        id: 'objects-5',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành quyển sách',
        level: 'hard',
        category: 'objects',
        leftHalf: '📘',
        correct: '📘',
        fullLabel: 'Quyển sách',
        options: ['📘', '📱', '🛏️', '⏰'],
      },
      {
        id: 'objects-6',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần ghép đúng của đồng hồ',
        level: 'hard',
        category: 'objects',
        leftHalf: '⏰',
        correct: '⏰',
        fullLabel: 'Cái đồng hồ',
        options: ['⏰', '🪑', '🧸', '🪄'],
      },
    ],
  },

  faces: {
    label: 'Biểu cảm',
    icon: '😊',
    questions: [
      {
        id: 'faces-1',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành khuôn mặt vui',
        level: 'easy',
        category: 'faces',
        leftHalf: '😊',
        correct: '😊',
        fullLabel: 'Mặt vui',
        options: ['😊', '😢', '😡', '😴'],
      },
      {
        id: 'faces-2',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần ghép đúng của mặt buồn',
        level: 'easy',
        category: 'faces',
        leftHalf: '😢',
        correct: '😢',
        fullLabel: 'Mặt buồn',
        options: ['😢', '😊', '😮', '😡'],
      },
      {
        id: 'faces-3',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành khuôn mặt ngạc nhiên',
        level: 'medium',
        category: 'faces',
        leftHalf: '😮',
        correct: '😮',
        fullLabel: 'Mặt ngạc nhiên',
        options: ['😮', '😴', '😊', '😢'],
      },
      {
        id: 'faces-4',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần đúng của mặt giận',
        level: 'medium',
        category: 'faces',
        leftHalf: '😡',
        correct: '😡',
        fullLabel: 'Mặt giận',
        options: ['😡', '😄', '😇', '😴'],
      },
      {
        id: 'faces-5',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành khuôn mặt ngủ',
        level: 'hard',
        category: 'faces',
        leftHalf: '😴',
        correct: '😴',
        fullLabel: 'Mặt ngủ',
        options: ['😴', '🥳', '😎', '🤒'],
      },
      {
        id: 'faces-6',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm phần ghép đúng của mặt cười lớn',
        level: 'hard',
        category: 'faces',
        leftHalf: '😄',
        correct: '😄',
        fullLabel: 'Mặt cười',
        options: ['😄', '😢', '😠', '😶'],
      },
    ],
  },

  mixed: {
    label: 'Tổng hợp',
    icon: '✨',
    questions: [
      {
        id: 'mixed-1',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành hình đúng',
        level: 'easy',
        category: 'mixed',
        leftHalf: '🍎',
        correct: '🍎',
        fullLabel: 'Quả táo',
        options: ['🍎', '🐶', '⚽', '😊'],
      },
      {
        id: 'mixed-2',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Tìm nửa hình khớp với mẫu',
        level: 'easy',
        category: 'mixed',
        leftHalf: '🐱',
        correct: '🐱',
        fullLabel: 'Con mèo',
        options: ['🐱', '🍌', '🎒', '😮'],
      },
      {
        id: 'mixed-3',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Quan sát thật kỹ để ghép đúng',
        level: 'medium',
        category: 'mixed',
        leftHalf: '🖊️',
        correct: '🖊️',
        fullLabel: 'Cái bút',
        options: ['🖊️', '🐰', '🍓', '😢'],
      },
      {
        id: 'mixed-4',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Ghép để thành hình hoàn chỉnh',
        level: 'medium',
        category: 'mixed',
        leftHalf: '😡',
        correct: '😡',
        fullLabel: 'Mặt giận',
        options: ['😡', '🍍', '🐻', '📘'],
      },
      {
        id: 'mixed-5',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Có nhiều loại hình khác nhau',
        level: 'hard',
        category: 'mixed',
        leftHalf: '⏰',
        correct: '⏰',
        fullLabel: 'Cái đồng hồ',
        options: ['⏰', '🍇', '🐘', '😴'],
      },
      {
        id: 'mixed-6',
        prompt: 'Hãy chọn nửa còn lại đúng',
        hint: 'Bé chọn đúng phần còn thiếu',
        level: 'hard',
        category: 'mixed',
        leftHalf: '🐟',
        correct: '🐟',
        fullLabel: 'Con cá',
        options: ['🐟', '📘', '😊', '🍊'],
      },
    ],
  },
};
