export type QuestionType = 'missing-middle' | 'missing-first' | 'missing-last' | 'missing-multiple' | 'scramble';

export type Question = {
  id: number;
  word: string;
  type: QuestionType;
  instruction: string;
  hint: string;
  mnemonic?: string;
  emoji: string;
  question: string | string[];
  answer: string | string[];
  choices: string[];
};

export type MissingLetterLevel = {
  id: number;
  name: string;
  description: string;
  difficulty: 'easy' | 'medium' | 'hard';
  questions: Question[];
};

export const missingLetterLevels: MissingLetterLevel[] = [
  // Level 1: Easy - Missing middle letter (20 questions)
  {
    id: 1,
    name: 'Cấp 1',
    description: 'Điền chữ bị mất ở giữa từ',
    difficulty: 'easy',
    questions: [
      {
        id: 101,
        word: 'Táo',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: T_O',
        hint: 'Quả táo đỏ',
        emoji: '🍎',
        question: 'T_O',
        answer: 'Á',
        choices: ['A', 'Á', 'O', 'E'],
      },
      {
        id: 102,
        word: 'Mèo',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: M_O',
        hint: 'Con mèo mướp',
        emoji: '🐱',
        question: 'M_O',
        answer: 'È',
        choices: ['E', 'È', 'Ê', 'O'],
      },
      {
        id: 103,
        word: 'Cá',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: C_',
        hint: 'Con cá bơi trong nước',
        emoji: '🐟',
        question: 'C_',
        answer: 'Á',
        choices: ['A', 'Á', 'Ă', 'O'],
      },
      {
        id: 104,
        word: 'Hoa',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: H_A',
        hint: 'Bông hoa đẹp',
        emoji: '🌸',
        question: 'H_A',
        answer: 'O',
        choices: ['O', 'A', 'U', 'E'],
      },
      {
        id: 105,
        word: 'Chó',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: CH_',
        hint: 'Con chó trung thành',
        emoji: '🐶',
        question: 'CH_',
        answer: 'Ó',
        choices: ['O', 'Ó', 'Ô', 'U'],
      },
      {
        id: 106,
        word: 'Chuối',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: CHU_I',
        hint: 'Quả chuối vàng',
        emoji: '🍌',
        question: 'CHU_I',
        answer: 'Ố',
        choices: ['O', 'Ố', 'Ớ', 'U'],
      },
      {
        id: 107,
        word: 'Dưa',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: D_A',
        hint: 'Quả dưa xanh',
        emoji: '🍈',
        question: 'D_A',
        answer: 'Ư',
        choices: ['U', 'Ư', 'O', 'A'],
      },
      {
        id: 108,
        word: 'Đũa',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: Đ_A',
        hint: 'Dụng cụ ăn cơm',
        emoji: '🥢',
        question: 'Đ_A',
        answer: 'U',
        choices: ['U', 'Ư', 'O', 'A'],
      },
      {
        id: 109,
        word: 'Nón',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: N_N',
        hint: 'Mũ che đầu',
        emoji: '👒',
        question: 'N_N',
        answer: 'Ô',
        choices: ['O', 'Ô', 'U', 'A'],
      },
      {
        id: 110,
        word: 'Tay',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: TA_',
        hint: 'Bộ phận trên cánh tay',
        emoji: '🤚',
        question: 'TA_',
        answer: 'Y',
        choices: ['I', 'Y', 'E', 'A'],
      },
      {
        id: 111,
        word: 'Chân',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: CH_N',
        hint: 'Bộ phận đi bộ',
        emoji: '🦶',
        question: 'CH_N',
        answer: 'Â',
        choices: ['A', 'Â', 'Ă', 'U'],
      },
      {
        id: 112,
        word: 'Mũi',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: M_I',
        hint: 'Bộ phận trên mặt',
        emoji: '👃',
        question: 'M_I',
        answer: 'U',
        choices: ['U', 'Ư', 'O', 'A'],
      },
      {
        id: 113,
        word: 'Tai',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: T_I',
        hint: 'Dùng để nghe',
        emoji: '👂',
        question: 'T_I',
        answer: 'A',
        choices: ['A', 'Á', 'Ă', 'O'],
      },
      {
        id: 114,
        word: 'Mắt',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: M_T',
        hint: 'Dùng để nhìn',
        emoji: '👁️',
        question: 'M_T',
        answer: 'Ă',
        choices: ['A', 'Ă', 'Á', 'U'],
      },
      {
        id: 115,
        word: 'Giếc',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: GI_C',
        hint: 'Khi ngủ',
        emoji: '😴',
        question: 'GI_C',
        answer: 'Ấ',
        choices: ['A', 'Ấ', 'Á', 'O'],
      },
      {
        id: 116,
        word: 'Súp',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: S_P',
        hint: 'Món ăn nóng',
        emoji: '🍲',
        question: 'S_P',
        answer: 'Ú',
        choices: ['U', 'Ú', 'Ư', 'O'],
      },
      {
        id: 117,
        word: 'Cơm',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: C_M',
        hint: 'Thức ăn chính',
        emoji: '🍚',
        question: 'C_M',
        answer: 'Ơ',
        choices: ['O', 'Ơ', 'U', 'A'],
      },
      {
        id: 118,
        word: 'Bánh',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: B_NH',
        hint: 'Tráng miệng',
        emoji: '🎂',
        question: 'B_NH',
        answer: 'Á',
        choices: ['A', 'Á', 'Ă', 'O'],
      },
      {
        id: 119,
        word: 'Nước',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _ƯỜC',
        hint: 'Cần uống',
        emoji: '💧',
        question: '_ƯỜC',
        answer: 'N',
        choices: ['D', 'N', 'T', 'L'],
      },
      {
        id: 120,
        word: 'Trứng',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _RỨNG',
        hint: 'Gà đẻ ra',
        emoji: '🥚',
        question: '_RỨNG',
        answer: 'T',
        choices: ['D', 'T', 'K', 'R'],
      },
    ],
  },

  // Level 2: Easy-Medium - Missing first/last letter (20 questions)
  {
    id: 2,
    name: 'Cấp 2',
    description: 'Điền chữ bị mất ở đầu hoặc cuối từ',
    difficulty: 'easy',
    questions: [
      {
        id: 201,
        word: 'Xe',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _E',
        hint: 'Phương tiện di chuyển',
        emoji: '🚗',
        question: '_E',
        answer: 'X',
        choices: ['S', 'X', 'C', 'T'],
      },
      {
        id: 202,
        word: 'Nhà',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: NH_',
        hint: 'Nơi ở của con người',
        emoji: '🏠',
        question: 'NH_',
        answer: 'À',
        choices: ['A', 'À', 'Á', 'E'],
      },
      {
        id: 203,
        word: 'Rau',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _AU',
        hint: 'Rau xanh bổ dưỡng',
        emoji: '🥬',
        question: '_AU',
        answer: 'R',
        choices: ['D', 'R', 'T', 'L'],
      },
      {
        id: 204,
        word: 'Gà',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: G_',
        hint: 'Con vật đẻ trứng',
        emoji: '🐔',
        question: 'G_',
        answer: 'À',
        choices: ['A', 'À', 'Á', 'Ă'],
      },
      {
        id: 205,
        word: 'Tôi',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _ÔI',
        hint: 'Đại từ nhân xưng',
        emoji: '👤',
        question: '_ÔI',
        answer: 'T',
        choices: ['B', 'T', 'D', 'K'],
      },
      {
        id: 206,
        word: 'Bạn',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: B_N',
        hint: 'Người bạn',
        emoji: '👫',
        question: 'B_N',
        answer: 'Ạ',
        choices: ['A', 'Ạ', 'Á', 'U'],
      },
      {
        id: 207,
        word: 'Khán',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _HÁN',
        hint: 'Người xem',
        emoji: '👥',
        question: '_HÁN',
        answer: 'K',
        choices: ['G', 'K', 'C', 'H'],
      },
      {
        id: 208,
        word: 'Lớp',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: L_P',
        hint: 'Nơi học',
        emoji: '🏫',
        question: 'L_P',
        answer: 'Ớ',
        choices: ['O', 'Ớ', 'Ô', 'U'],
      },
      {
        id: 209,
        word: 'Sách',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: S_CH',
        hint: 'Để học',
        emoji: '📖',
        question: 'S_CH',
        answer: 'Á',
        choices: ['A', 'Á', 'Ă', 'O'],
      },
      {
        id: 210,
        word: 'Bút',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _ÚT',
        hint: 'Dùng để viết',
        emoji: '✏️',
        question: '_ÚT',
        answer: 'B',
        choices: ['D', 'B', 'T', 'L'],
      },
      {
        id: 211,
        word: 'Dòng',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: D_NG',
        hint: 'Dòng chữ',
        emoji: '📝',
        question: 'D_NG',
        answer: 'Ò',
        choices: ['O', 'Ò', 'Ô', 'U'],
      },
      {
        id: 212,
        word: 'Thơ',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _HƠ',
        hint: 'Văn học',
        emoji: '📜',
        question: '_HƠ',
        answer: 'T',
        choices: ['D', 'T', 'K', 'R'],
      },
      {
        id: 213,
        word: 'Truyện',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: TRUY_N',
        hint: 'Câu chuyện',
        emoji: '📚',
        question: 'TRUY_N',
        answer: 'Ệ',
        choices: ['E', 'Ệ', 'Ê', 'I'],
      },
      {
        id: 214,
        word: 'Tâm',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _ÂM',
        hint: 'Trái tim',
        emoji: '❤️',
        question: '_ÂM',
        answer: 'T',
        choices: ['D', 'T', 'K', 'R'],
      },
      {
        id: 215,
        word: 'Linh',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: LI_H',
        hint: 'Linh hồn',
        emoji: '👻',
        question: 'LI_H',
        answer: 'N',
        choices: ['M', 'N', 'T', 'K'],
      },
      {
        id: 216,
        word: 'Sáng',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _ÁNG',
        hint: 'Buổi sáng',
        emoji: '🌅',
        question: '_ÁNG',
        answer: 'S',
        choices: ['C', 'S', 'T', 'K'],
      },
      {
        id: 217,
        word: 'Chiều',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: CHI_U',
        hint: 'Buổi chiều',
        emoji: '🌤️',
        question: 'CHI_U',
        answer: 'Ề',
        choices: ['E', 'Ề', 'Ê', 'I'],
      },
      {
        id: 218,
        word: 'Đêm',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _ÊM',
        hint: 'Ban đêm',
        emoji: '🌙',
        question: '_ÊM',
        answer: 'Đ',
        choices: ['D', 'Đ', 'T', 'K'],
      },
      {
        id: 219,
        word: 'Năng',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: N_NG',
        hint: 'Năng lực',
        emoji: '💪',
        question: 'N_NG',
        answer: 'Ă',
        choices: ['A', 'Ă', 'Á', 'U'],
      },
      {
        id: 220,
        word: 'Việc',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _IỆC',
        hint: 'Công việc',
        emoji: '💼',
        question: '_IỆC',
        answer: 'V',
        choices: ['D', 'V', 'T', 'L'],
      },
    ],
  },

  // Level 3: Medium - Missing multiple letters (20 questions)
  {
    id: 3,
    name: 'Cấp 3',
    description: 'Điền các chữ bị mất (2-3 chữ)',
    difficulty: 'medium',
    questions: [
      {
        id: 301,
        word: 'Sách',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: S_C_',
        hint: 'Vật để học',
        emoji: '📖',
        question: 'S_C_',
        answer: ['Á', 'H'],
        choices: ['A', 'Á', 'H', 'C', 'O'],
      },
      {
        id: 302,
        word: 'Trường',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: TR__NG',
        hint: 'Nơi học tập',
        emoji: '🏫',
        question: 'TR__NG',
        answer: ['Ư', 'Ờ'],
        choices: ['U', 'Ư', 'O', 'Ờ', 'Ô'],
      },
      {
        id: 303,
        word: 'Nước',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: N__C',
        hint: 'Thứ cần uống',
        emoji: '💧',
        question: 'N__C',
        answer: ['Ư', 'Ờ'],
        choices: ['U', 'Ư', 'O', 'Ờ', 'A'],
      },
      {
        id: 304,
        word: 'Tiếng',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: TI_NG',
        hint: 'Âm thanh',
        emoji: '🔊',
        question: 'TI_NG',
        answer: ['ẾN'],
        choices: ['E', 'Ế', 'Ê', 'I', 'A'],
      },
      {
        id: 305,
        word: 'Kiến',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: KI_N',
        hint: 'Con kiến',
        emoji: '🐜',
        question: 'KI_N',
        answer: ['ẾN'],
        choices: ['E', 'Ế', 'Ê', 'I', 'A'],
      },
      {
        id: 306,
        word: 'Biển',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: BI_N',
        hint: 'Đại dương',
        emoji: '🌊',
        question: 'BI_N',
        answer: ['ẾN'],
        choices: ['E', 'Ế', 'Ê', 'I', 'A'],
      },
      {
        id: 307,
        word: 'Điều',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: ĐI_U',
        hint: 'Sự việc',
        emoji: '💭',
        question: 'ĐI_U',
        answer: ['ỀU'],
        choices: ['E', 'Ề', 'Ê', 'I', 'A'],
      },
      {
        id: 308,
        word: 'Mưa',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: M_A',
        hint: 'Nước rơi từ trời',
        emoji: '🌧️',
        question: 'M_A',
        answer: ['Ư'],
        choices: ['U', 'Ư', 'O', 'A', 'Ơ'],
      },
      {
        id: 309,
        word: 'Gió',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: GI_',
        hint: 'Luồng không khí',
        emoji: '💨',
        question: 'GI_',
        answer: ['Ó'],
        choices: ['O', 'Ó', 'Ô', 'U', 'A'],
      },
      {
        id: 310,
        word: 'Lửa',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: L_A',
        hint: 'Ngọn lửa',
        emoji: '🔥',
        question: 'L_A',
        answer: ['Ữ'],
        choices: ['U', 'Ữ', 'O', 'A', 'I'],
      },
      {
        id: 311,
        word: 'Ánh',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: _NH',
        hint: 'Ánh sáng',
        emoji: '💡',
        question: '_NH',
        answer: ['Á'],
        choices: ['A', 'Á', 'Ă', 'O', 'U'],
      },
      {
        id: 312,
        word: 'Nắng',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: N_NG',
        hint: 'Ánh sáng mặt trời',
        emoji: '☀️',
        question: 'N_NG',
        answer: ['Ắ'],
        choices: ['A', 'Ắ', 'Á', 'O', 'U'],
      },
      {
        id: 313,
        word: 'Tối',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: T_I',
        hint: 'Thời gian tối tăm',
        emoji: '🌑',
        question: 'T_I',
        answer: ['Ố'],
        choices: ['O', 'Ố', 'Ô', 'U', 'A'],
      },
      {
        id: 314,
        word: 'Sao',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: S_O',
        hint: 'Sao trong trời',
        emoji: '⭐',
        question: 'S_O',
        answer: ['A'],
        choices: ['A', 'Á', 'Ă', 'O', 'U'],
      },
      {
        id: 315,
        word: 'Mây',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: M_Y',
        hint: 'Mây trên trời',
        emoji: '☁️',
        question: 'M_Y',
        answer: ['Â'],
        choices: ['A', 'Â', 'Ă', 'O', 'U'],
      },
      {
        id: 316,
        word: 'Cầu',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: C_U',
        hint: 'Cậu bé',
        emoji: '👦',
        question: 'C_U',
        answer: ['Ầ'],
        choices: ['A', 'Ầ', 'Á', 'O', 'U'],
      },
      {
        id: 317,
        word: 'Gái',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: G_I',
        hint: 'Cô gái',
        emoji: '👧',
        question: 'G_I',
        answer: ['Á'],
        choices: ['A', 'Á', 'Ă', 'O', 'U'],
      },
      {
        id: 318,
        word: 'Trai',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: TR_I',
        hint: 'Con trai',
        emoji: '🧒',
        question: 'TR_I',
        answer: ['A'],
        choices: ['A', 'Á', 'Ă', 'O', 'U'],
      },
      {
        id: 319,
        word: 'Khách',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: KH_CH',
        hint: 'Người khách',
        emoji: '🚪',
        question: 'KH_CH',
        answer: ['Á'],
        choices: ['A', 'Á', 'Ă', 'O', 'U'],
      },
      {
        id: 320,
        word: 'Chủ',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: CH_',
        hint: 'Chủ nhân',
        emoji: '👔',
        question: 'CH_',
        answer: ['Ủ'],
        choices: ['U', 'Ủ', 'Ư', 'O', 'A'],
      },
    ],
  },

  // Level 4: Medium-Hard - Scramble words (20 questions)
  {
    id: 4,
    name: 'Cấp 4',
    description: 'Sắp xếp chữ cái để tạo từ',
    difficulty: 'medium',
    questions: [
      {
        id: 401,
        word: 'Rác',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Rác thải',
        emoji: '🗑️',
        question: ['R', 'Á', 'C'],
        answer: 'RÁC',
        choices: ['RÁC', 'CÁR', 'ÁRC', 'CAR'],
      },
      {
        id: 402,
        word: 'Tối',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Thời gian tối tăm',
        emoji: '🌙',
        question: ['T', 'Ố', 'I'],
        answer: 'TỐI',
        choices: ['TỐI', 'ÍT', 'ÍTO', 'OIT'],
      },
      {
        id: 403,
        word: 'Nắng',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Ánh sáng',
        emoji: '☀️',
        question: ['N', 'Ắ', 'N', 'G'],
        answer: 'NẮNG',
        choices: ['NẮNG', 'GNAN', 'NGAN', 'NNGA'],
      },
      {
        id: 404,
        word: 'Mưa',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Nước rơi',
        emoji: '🌧️',
        question: ['M', 'Ư', 'A'],
        answer: 'MƯA',
        choices: ['MƯA', 'AUM', 'UMA', 'AMU'],
      },
      {
        id: 405,
        word: 'Gió',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Luồng không khí',
        emoji: '💨',
        question: ['G', 'I', 'Ó'],
        answer: 'GIÓ',
        choices: ['GIÓ', 'ÓGI', 'IGÓ', 'OGI'],
      },
      {
        id: 406,
        word: 'Lửa',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Ngọn lửa',
        emoji: '🔥',
        question: ['L', 'Ữ', 'A'],
        answer: 'LỮA',
        choices: ['LỮA', 'ALU', 'ULA', 'ALU'],
      },
      {
        id: 407,
        word: 'Anh',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Anh trai',
        emoji: '👨',
        question: ['A', 'N', 'H'],
        answer: 'ANH',
        choices: ['ANH', 'HAN', 'NAH', 'AHN'],
      },
      {
        id: 408,
        word: 'Chị',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Chị gái',
        emoji: '👩',
        question: ['C', 'H', 'Ị'],
        answer: 'CHỊ',
        choices: ['CHỊ', 'HCH', 'HIC', 'ICH'],
      },
      {
        id: 409,
        word: 'Em',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Anh em',
        emoji: '👧',
        question: ['E', 'M'],
        answer: 'EM',
        choices: ['EM', 'ME', 'MEM', 'EEM'],
      },
      {
        id: 410,
        word: 'Bố',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Cha ruột',
        emoji: '👨‍🦱',
        question: ['B', 'Ố'],
        answer: 'BỐ',
        choices: ['BỐ', 'ÓB', 'BON', 'OB'],
      },
      {
        id: 411,
        word: 'Mẹ',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Mẹ ruột',
        emoji: '👩‍🦱',
        question: ['M', 'Ẹ'],
        answer: 'MẸ',
        choices: ['MẸ', 'ẸM', 'MEN', 'EM'],
      },
      {
        id: 412,
        word: 'Ông',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Ông ngoại',
        emoji: '👴',
        question: ['Ô', 'N', 'G'],
        answer: 'ÔNG',
        choices: ['ÔNG', 'NGO', 'GON', 'OGN'],
      },
      {
        id: 413,
        word: 'Bà',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Bà ngoại',
        emoji: '👵',
        question: ['B', 'À'],
        answer: 'BÀ',
        choices: ['BÀ', 'ÀB', 'BA', 'AB'],
      },
      {
        id: 414,
        word: 'Bia',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Thức uống',
        emoji: '🍺',
        question: ['B', 'I', 'A'],
        answer: 'BIA',
        choices: ['BIA', 'AIB', 'IBA', 'ABI'],
      },
      {
        id: 415,
        word: 'Rau',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Rau xanh',
        emoji: '🥬',
        question: ['R', 'A', 'U'],
        answer: 'RAU',
        choices: ['RAU', 'ARU', 'URA', 'AUR'],
      },
      {
        id: 416,
        word: 'Tứ',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Số 4',
        emoji: '4️⃣',
        question: ['T', 'Ứ'],
        answer: 'TỨ',
        choices: ['TỨ', 'ỨT', 'TUT', 'UT'],
      },
      {
        id: 417,
        word: 'Năm',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Số 5',
        emoji: '5️⃣',
        question: ['N', 'Ă', 'M'],
        answer: 'NĂM',
        choices: ['NĂM', 'MAN', 'NAM', 'AMN'],
      },
      {
        id: 418,
        word: 'Sáu',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Số 6',
        emoji: '6️⃣',
        question: ['S', 'Á', 'U'],
        answer: 'SÁU',
        choices: ['SÁU', 'AUS', 'USA', 'ASU'],
      },
      {
        id: 419,
        word: 'Bảy',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Số 7',
        emoji: '7️⃣',
        question: ['B', 'Ả', 'Y'],
        answer: 'BẢY',
        choices: ['BẢY', 'YAB', 'ABY', 'BYA'],
      },
      {
        id: 420,
        word: 'Tám',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Số 8',
        emoji: '8️⃣',
        question: ['T', 'Á', 'M'],
        answer: 'TÁM',
        choices: ['TÁM', 'MAT', 'TAM', 'ATM'],
      },
    ],
  },

  // Level 5: Hard - All types mixed (20 questions)
  {
    id: 5,
    name: 'Cấp 5',
    description: 'Thử thách cao - Trộn lẫn mọi dạng',
    difficulty: 'hard',
    questions: [
      {
        id: 501,
        word: 'Hạnh phúc',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất',
        hint: 'Trạng thái vui vẻ',
        emoji: '😊',
        question: 'H_NH PH_C',
        answer: ['Ạ', 'Ú'],
        choices: ['A', 'Ạ', 'U', 'Ú', 'O'],
      },
      {
        id: 502,
        word: 'Thường',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: TH__NG',
        hint: 'Lúc nào cũng',
        emoji: '⏰',
        question: 'TH__NG',
        answer: ['Ư', 'Ờ'],
        choices: ['U', 'Ư', 'O', 'Ờ', 'Ô'],
      },
      {
        id: 503,
        word: 'Quốc gia',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: QU_C GI_',
        hint: 'Đất nước',
        emoji: '🏳️',
        question: 'QU_C GI_',
        answer: ['Ố', 'Á'],
        choices: ['O', 'Ố', 'U', 'Á', 'I'],
      },
      {
        id: 504,
        word: 'Tuyên bố',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: TUY_N B_',
        hint: 'Công bố',
        emoji: '📢',
        question: 'TUY_N B_',
        answer: ['ê', 'Ố'],
        choices: ['E', 'Ê', 'O', 'Ố', 'U'],
      },
      {
        id: 505,
        word: 'Kiến thức',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: KI_N TH_C',
        hint: 'Sự hiểu biết',
        emoji: '📚',
        question: 'KI_N TH_C',
        answer: ['ế', 'Ứ'],
        choices: ['E', 'Ế', 'U', 'Ứ', 'O'],
      },
      {
        id: 506,
        word: 'Tương lai',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: T__NG L_I',
        hint: 'Thời gian sắp tới',
        emoji: '🔮',
        question: 'T__NG L_I',
        answer: ['Ư', 'Ơ', 'A'],
        choices: ['U', 'Ư', 'O', 'Ơ', 'A'],
      },
      {
        id: 507,
        word: 'Liên kết',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Kết nối',
        emoji: '🔗',
        question: ['L', 'I', 'Ê', 'N'],
        answer: 'LIÊN',
        choices: ['LIÊN', 'NEIL', 'ENLI', 'ILEN'],
      },
      {
        id: 508,
        word: 'Hợp tác',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Cùng làm',
        emoji: '🤝',
        question: ['H', 'Ợ', 'P'],
        answer: 'HỢP',
        choices: ['HỢP', 'PHO', 'OPH', 'POH'],
      },
      {
        id: 509,
        word: 'Chứng minh',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _HỨNG',
        hint: 'Bằng chứng',
        emoji: '✔️',
        question: '_HỨNG',
        answer: 'C',
        choices: ['D', 'C', 'T', 'K'],
      },
      {
        id: 510,
        word: 'Thể hiện',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: TH_ HI_N',
        hint: 'Biểu lộ',
        emoji: '🎭',
        question: 'TH_ HI_N',
        answer: ['E', 'Ề'],
        choices: ['E', 'Ê', 'Ề', 'I', 'A'],
      },
      {
        id: 511,
        word: 'Giải quyết',
        type: 'missing-middle',
        instruction: 'Điền chữ bị mất: GI_I QUY_T',
        hint: 'Xử lý',
        emoji: '⚙️',
        question: 'GI_I QUY_T',
        answer: ['Ả', 'Ế'],
        choices: ['A', 'Ả', 'U', 'Ế', 'O'],
      },
      {
        id: 512,
        word: 'Tính cách',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: T_NH C_CH',
        hint: 'Đặc điểm của người',
        emoji: '👤',
        question: 'T_NH C_CH',
        answer: ['Í', 'Á'],
        choices: ['I', 'Í', 'A', 'Á', 'U'],
      },
      {
        id: 513,
        word: 'Lợi ích',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _ỢI',
        hint: 'Cái lợi',
        emoji: '💎',
        question: '_ỢI',
        answer: 'L',
        choices: ['D', 'L', 'T', 'K'],
      },
      {
        id: 514,
        word: 'Yêu cầu',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: Y_U C_U',
        hint: 'Đòi hỏi',
        emoji: '⛔',
        question: 'Y_U C_U',
        answer: ['Ê', 'Ầ'],
        choices: ['E', 'Ê', 'A', 'Ầ', 'I'],
      },
      {
        id: 515,
        word: 'Hướng dẫn',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Chỉ dẫn',
        emoji: '🧭',
        question: ['H', 'Ư', 'Ớ', 'N', 'G'],
        answer: 'HƯỚNG',
        choices: ['HƯỚNG', 'NHUOG', 'GHUON', 'ONHUG'],
      },
      {
        id: 516,
        word: 'Sáng kiến',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: S_NG KI_N',
        hint: 'Ý tưởng mới',
        emoji: '💡',
        question: 'S_NG KI_N',
        answer: ['Á', 'ế'],
        choices: ['A', 'Á', 'E', 'Ế', 'I'],
      },
      {
        id: 517,
        word: 'Phát triển',
        type: 'missing-first',
        instruction: 'Điền chữ bị mất ở đầu: _HÁT',
        hint: 'Lớn lên',
        emoji: '🌱',
        question: '_HÁT',
        answer: 'P',
        choices: ['B', 'P', 'T', 'K'],
      },
      {
        id: 518,
        word: 'Đạo tạo',
        type: 'missing-last',
        instruction: 'Điền chữ bị mất ở cuối: _ẠO T_O',
        hint: 'Huấn luyện',
        emoji: '🎓',
        question: '_ẠO T_O',
        answer: ['Đ', 'A'],
        choices: ['D', 'Đ', 'T', 'A', 'Á'],
      },
      {
        id: 519,
        word: 'Nghiên cứu',
        type: 'scramble',
        instruction: 'Sắp xếp để tạo từ',
        hint: 'Tìm hiểu sâu',
        emoji: '🔬',
        question: ['N', 'G', 'H', 'I', 'ÊN'],
        answer: 'NGHIÊN',
        choices: ['NGHIÊN', 'ENHIG', 'GHNEI', 'IHNEG'],
      },
      {
        id: 520,
        word: 'Công nghệ',
        type: 'missing-multiple',
        instruction: 'Điền các chữ bị mất: C_NG NGH_',
        hint: 'Công nghệ số',
        emoji: '💻',
        question: 'C_NG NGH_',
        answer: ['Ô', 'Ệ'],
        choices: ['O', 'Ô', 'E', 'Ệ', 'U'],
      },
    ],
  },
];