export type GameLevel = 'easy' | 'medium' | 'hard';

export type ToneQuestion = {
  id: number;
  bareWord: string;
  answer: string;
  hint: string;
  image?: string;
  distractors: string[];
  explanation: string;
  category: string;
  level: GameLevel;
};

// ─── Category 1: Hỏi vs Ngã ───────────────────────────────────────────────────
const hoiNgaQuestions: ToneQuestion[] = [
  {
    id: 101,
    bareWord: 've',
    answer: 'vẽ',
    hint: 'Bạn ___ một bông hoa thật đẹp.',
    image: '🖍️',
    distractors: ['vẻ', 'vè', 'vế'],
    explanation: '"Vẽ" (dấu ngã) là hành động dùng bút tạo hình. "Vẻ" (dấu hỏi) là vẻ đẹp.',
    category: 'hoi-nga',
    level: 'easy',
  },
  {
    id: 102,
    bareWord: 'nga',
    answer: 'ngã',
    hint: 'Em bé ___ xuống đất, khóc ầm ĩ.',
    image: '😢',
    distractors: ['ngả', 'ngà', 'ngá'],
    explanation: '"Ngã" (dấu ngã) là bị té ngã. "Ngả" (dấu hỏi) có nghĩa là nghiêng, ngả màu.',
    category: 'hoi-nga',
    level: 'easy',
  },
  {
    id: 103,
    bareWord: 'bao',
    answer: 'bảo',
    hint: 'Mẹ ___ em phải học bài trước khi đi chơi.',
    image: '📚',
    distractors: ['bão', 'bào', 'báo'],
    explanation: '"Bảo" (dấu hỏi) là nói, dặn dò. "Bão" (dấu ngã) là cơn bão thời tiết.',
    category: 'hoi-nga',
    level: 'easy',
  },
  {
    id: 104,
    bareWord: 'se',
    answer: 'sẽ',
    hint: 'Em ___ đi học vào ngày mai.',
    image: '🏫',
    distractors: ['sẻ', 'sề', 'sế'],
    explanation: '"Sẽ" (dấu ngã) chỉ sự việc ở tương lai. "Sẻ" (dấu hỏi) là con chim sẻ.',
    category: 'hoi-nga',
    level: 'easy',
  },
  {
    id: 105,
    bareWord: 'mau',
    answer: 'mẫu',
    hint: 'Trường ___ giáo có rất nhiều đồ chơi.',
    image: '🧸',
    distractors: ['mẩu', 'mấu', 'màu'],
    explanation: '"Mẫu giáo" (dấu ngã) là trường mầm non. "Mẩu" (dấu hỏi) là mẩu nhỏ, mẩu giấy.',
    category: 'hoi-nga',
    level: 'medium',
  },
  {
    id: 106,
    bareWord: 'tinh',
    answer: 'tỉnh',
    hint: 'Làng ___ yên bình, cây cối xanh tươi.',
    image: '🌿',
    distractors: ['tĩnh', 'tính', 'tình'],
    explanation: '"Tỉnh" (dấu hỏi) là tỉnh thành, địa phương. "Tĩnh" (dấu ngã) là yên tĩnh.',
    category: 'hoi-nga',
    level: 'medium',
  },
  {
    id: 107,
    bareWord: 'le',
    answer: 'lễ',
    hint: 'Hôm nay là ngày ___ Quốc khánh.',
    image: '🎉',
    distractors: ['lẻ', 'lề', 'lế'],
    explanation: '"Lễ" (dấu ngã) là ngày lễ, lễ hội. "Lẻ" (dấu hỏi) là số lẻ hoặc tiền lẻ.',
    category: 'hoi-nga',
    level: 'medium',
  },
  {
    id: 108,
    bareWord: 'ngu',
    answer: 'ngủ',
    hint: 'Ban đêm em ___ rất ngon giấc.',
    image: '😴',
    distractors: ['ngũ', 'ngù', 'ngú'],
    explanation: '"Ngủ" (dấu hỏi) là nghỉ ngơi ban đêm. "Ngũ" (dấu ngã) là số năm trong Hán Việt.',
    category: 'hoi-nga',
    level: 'easy',
  },
  {
    id: 109,
    bareWord: 'mo',
    answer: 'mỡ',
    hint: 'Mẹ mua ___ về để nấu ăn.',
    image: '🍳',
    distractors: ['mổ', 'mờ', 'mớ'],
    explanation: '"Mỡ" (dấu ngã) là chất béo dùng để nấu ăn. "Mổ" (dấu hỏi) là mổ xẻ, phẫu thuật.',
    category: 'hoi-nga',
    level: 'hard',
  },
  {
    id: 110,
    bareWord: 'nho',
    answer: 'nhỏ',
    hint: 'Con kiến rất ___, bé hơn hạt gạo.',
    image: '🐜',
    distractors: ['nhõ', 'nhò', 'nhó'],
    explanation: '"Nhỏ" (dấu hỏi) là kích thước bé. "Nhõ" (dấu ngã) ít dùng hơn trong tiếng Việt phổ thông.',
    category: 'hoi-nga',
    level: 'easy',
  },
  {
    id: 111,
    bareWord: 'bo',
    answer: 'bổ',
    hint: 'Rau củ rất ___ dưỡng cho cơ thể.',
    image: '🥦',
    distractors: ['bỗ', 'bồ', 'bố'],
    explanation: '"Bổ" (dấu hỏi) là bổ dưỡng, có lợi cho sức khỏe. "Bỗ" (dấu ngã) ít phổ biến hơn.',
    category: 'hoi-nga',
    level: 'medium',
  },
  {
    id: 112,
    bareWord: 'giu',
    answer: 'giữ',
    hint: 'Em ___ cẩn thận quyển sách mới.',
    image: '📗',
    distractors: ['giủ', 'giù', 'giú'],
    explanation: '"Giữ" (dấu ngã) là bảo quản, cất giữ. "Giủ" (dấu hỏi) ít dùng trong tiếng Việt hiện đại.',
    category: 'hoi-nga',
    level: 'medium',
  },
];

// ─── Category 2: Sắc vs Huyền ─────────────────────────────────────────────────
const sacHuyenQuestions: ToneQuestion[] = [
  {
    id: 201,
    bareWord: 'ba',
    answer: 'bà',
    hint: 'Đây là ___ nội của em, bà rất hiền.',
    image: '👵',
    distractors: ['bá', 'ba', 'bả'],
    explanation: '"Bà" (dấu huyền) là bà nội, bà ngoại. "Bá" (dấu sắc) là bá chủ, bác cả.',
    category: 'sac-huyen',
    level: 'easy',
  },
  {
    id: 202,
    bareWord: 'co',
    answer: 'có',
    hint: 'Em ___ một quyển sách rất hay.',
    image: '📖',
    distractors: ['cò', 'cỏ', 'cọ'],
    explanation: '"Có" (dấu sắc) là sở hữu, tồn tại. "Cò" (dấu huyền) là con chim cò.',
    category: 'sac-huyen',
    level: 'easy',
  },
  {
    id: 203,
    bareWord: 'la',
    answer: 'lá',
    hint: 'Chiếc ___ cây màu xanh mướt.',
    image: '🍃',
    distractors: ['là', 'lả', 'lạ'],
    explanation: '"Lá" (dấu sắc) là lá cây. "Là" (dấu huyền) là từ liên kết, ví dụ "bạn là học sinh".',
    category: 'sac-huyen',
    level: 'easy',
  },
  {
    id: 204,
    bareWord: 'me',
    answer: 'mẹ',
    hint: 'Con yêu ___ nhất trên đời.',
    image: '👩',
    distractors: ['mè', 'mẻ', 'mế'],
    explanation: '"Mẹ" (dấu nặng) là người mẹ. "Mè" (dấu huyền) là hạt mè (vừng).',
    category: 'sac-huyen',
    level: 'easy',
  },
  {
    id: 205,
    bareWord: 'ca',
    answer: 'cá',
    hint: '___ vàng bơi lội trong bể nước trong vắt.',
    image: '🐟',
    distractors: ['cà', 'cả', 'cạ'],
    explanation: '"Cá" (dấu sắc) là loài vật sống dưới nước. "Cà" (dấu huyền) là quả cà, hoặc màu cà phê.',
    category: 'sac-huyen',
    level: 'easy',
  },
  {
    id: 206,
    bareWord: 'be',
    answer: 'bé',
    hint: 'Em ___ đang học lớp hai trường tiểu học.',
    image: '🧒',
    distractors: ['bè', 'bẻ', 'bề'],
    explanation: '"Bé" (dấu sắc) là nhỏ bé, trẻ nhỏ. "Bè" (dấu huyền) là bè gỗ hoặc bạn bè.',
    category: 'sac-huyen',
    level: 'easy',
  },
  {
    id: 207,
    bareWord: 'hoa',
    answer: 'hóa',
    hint: 'Sâu bướm ___ thành con bướm xinh đẹp.',
    image: '🦋',
    distractors: ['hòa', 'hỏa', 'họa'],
    explanation: '"Hóa" (dấu sắc) là biến hóa, thay đổi. "Hòa" (dấu huyền) là hòa bình, hòa thuận.',
    category: 'sac-huyen',
    level: 'medium',
  },
  {
    id: 208,
    bareWord: 'qua',
    answer: 'quà',
    hint: 'Bố mua ___ sinh nhật cho em.',
    image: '🎁',
    distractors: ['quá', 'quả', 'quạ'],
    explanation: '"Quà" (dấu huyền) là món quà tặng. "Quá" (dấu sắc) là vượt quá, quá nhiều.',
    category: 'sac-huyen',
    level: 'easy',
  },
  {
    id: 209,
    bareWord: 'nha',
    answer: 'nhà',
    hint: 'Em về ___ sau khi tan học.',
    image: '🏠',
    distractors: ['nhá', 'nhả', 'nhạ'],
    explanation: '"Nhà" (dấu huyền) là nơi ở, gia đình. "Nhá" (dấu sắc) là nhá tạm, thử nếm.',
    category: 'sac-huyen',
    level: 'easy',
  },
  {
    id: 210,
    bareWord: 'toi',
    answer: 'tối',
    hint: 'Ban ___ em thường đọc sách trước khi ngủ.',
    image: '🌙',
    distractors: ['tồi', 'tổi', 'tội'],
    explanation: '"Tối" (dấu sắc) là ban tối, trời tối. "Tồi" (dấu huyền) là xấu, kém chất lượng.',
    category: 'sac-huyen',
    level: 'medium',
  },
  {
    id: 211,
    bareWord: 'mua',
    answer: 'mùa',
    hint: '___ hè em được nghỉ học và đi biển.',
    image: '☀️',
    distractors: ['múa', 'mủa', 'mụa'],
    explanation: '"Mùa" (dấu huyền) là mùa trong năm. "Múa" (dấu sắc) là động tác biểu diễn múa.',
    category: 'sac-huyen',
    level: 'easy',
  },
  {
    id: 212,
    bareWord: 'den',
    answer: 'đèn',
    hint: 'Chiếc ___ bàn sáng giúp em học bài.',
    image: '💡',
    distractors: ['đến', 'đển', 'đện'],
    explanation: '"Đèn" (dấu huyền) là thiết bị chiếu sáng. "Đến" (dấu sắc) là đến nơi, đến lúc.',
    category: 'sac-huyen',
    level: 'easy',
  },
];

// ─── Category 3: Thanh điệu cơ bản (all 6 tones) ────────────────────────────
const thanhDieuCobanQuestions: ToneQuestion[] = [
  {
    id: 301,
    bareWord: 'ma',
    answer: 'ma',
    hint: 'Con ___ trong truyện cổ tích làm em sợ.',
    image: '👻',
    distractors: ['má', 'mà', 'mã'],
    explanation: '"Ma" (không dấu) là con ma trong truyện. "Má" (dấu sắc) là má (mẹ, miền Nam) hoặc má mặt.',
    category: 'thanh-dieu-co-ban',
    level: 'easy',
  },
  {
    id: 302,
    bareWord: 'bo',
    answer: 'bò',
    hint: 'Con ___ ăn cỏ trên đồng xanh.',
    image: '🐄',
    distractors: ['bó', 'bỏ', 'bọ'],
    explanation: '"Bò" (dấu huyền) là con bò. "Bó" (dấu sắc) là bó rau, bó hoa.',
    category: 'thanh-dieu-co-ban',
    level: 'easy',
  },
  {
    id: 303,
    bareWord: 'ga',
    answer: 'gà',
    hint: 'Con ___ trống gáy vang vào mỗi buổi sáng.',
    image: '🐓',
    distractors: ['ga', 'gá', 'gả'],
    explanation: '"Gà" (dấu huyền) là con gà. "Ga" (không dấu) là nhà ga tàu hỏa.',
    category: 'thanh-dieu-co-ban',
    level: 'easy',
  },
  {
    id: 304,
    bareWord: 'mu',
    answer: 'mũ',
    hint: 'Em đội ___ bảo hiểm khi đi xe máy.',
    image: '⛑️',
    distractors: ['mụ', 'mú', 'mù'],
    explanation: '"Mũ" (dấu ngã) là mũ đội đầu. "Mù" (dấu huyền) là bị mù mắt, không nhìn thấy.',
    category: 'thanh-dieu-co-ban',
    level: 'easy',
  },
  {
    id: 305,
    bareWord: 'com',
    answer: 'cơm',
    hint: 'Bữa trưa em ăn ___ với canh rau.',
    image: '🍚',
    distractors: ['cớm', 'cởm', 'cợm'],
    explanation: '"Cơm" (không dấu trên nguyên âm đôi) là hạt gạo nấu chín, thức ăn hàng ngày.',
    category: 'thanh-dieu-co-ban',
    level: 'easy',
  },
  {
    id: 306,
    bareWord: 'tay',
    answer: 'tay',
    hint: 'Em dùng ___ phải để viết chữ.',
    image: '✋',
    distractors: ['tày', 'táy', 'tảy'],
    explanation: '"Tay" (không dấu) là bộ phận cơ thể. "Tày" (dấu huyền) là ngang bằng, dân tộc Tày.',
    category: 'thanh-dieu-co-ban',
    level: 'easy',
  },
  {
    id: 307,
    bareWord: 'mat',
    answer: 'mắt',
    hint: '___ em sáng và to tròn.',
    image: '👁️',
    distractors: ['mặt', 'mất', 'mát'],
    explanation: '"Mắt" (dấu sắc trên â) là cơ quan nhìn thấy. "Mặt" (dấu nặng trên â) là khuôn mặt.',
    category: 'thanh-dieu-co-ban',
    level: 'medium',
  },
  {
    id: 308,
    bareWord: 'hoa',
    answer: 'hoa',
    hint: 'Vườn ___ nhà em nở rộ mùa xuân.',
    image: '🌸',
    distractors: ['họa', 'hóa', 'hòa'],
    explanation: '"Hoa" (không dấu) là loài thực vật có hoa. "Họa" (dấu nặng) là tai họa, tranh họa.',
    category: 'thanh-dieu-co-ban',
    level: 'easy',
  },
  {
    id: 309,
    bareWord: 'bap',
    answer: 'bắp',
    hint: 'Em thích ăn ___ ngô luộc.',
    image: '🌽',
    distractors: ['bặp', 'bấp', 'bạp'],
    explanation: '"Bắp" (dấu sắc trên â) là bắp ngô. "Bặp" (dấu nặng) không phải từ thông dụng.',
    category: 'thanh-dieu-co-ban',
    level: 'medium',
  },
  {
    id: 310,
    bareWord: 'ruoi',
    answer: 'ruồi',
    hint: 'Con ___ đậu lên thức ăn rất mất vệ sinh.',
    image: '🪰',
    distractors: ['ruổi', 'ruỗi', 'ruối'],
    explanation: '"Ruồi" (dấu huyền) là loài côn trùng mang mầm bệnh. "Ruổi" (dấu hỏi) là rong ruổi.',
    category: 'thanh-dieu-co-ban',
    level: 'medium',
  },
  {
    id: 311,
    bareWord: 'buom',
    answer: 'bướm',
    hint: 'Con ___ xinh đẹp đậu trên cánh hoa.',
    image: '🦋',
    distractors: ['bưởm', 'bướm', 'buởm'],
    explanation: '"Bướm" (dấu sắc) là loài côn trùng có cánh đẹp. Đây là từ quen thuộc với trẻ em.',
    category: 'thanh-dieu-co-ban',
    level: 'easy',
  },
  {
    id: 312,
    bareWord: 'sao',
    answer: 'sao',
    hint: 'Bầu trời đêm có nhiều ___ lấp lánh.',
    image: '⭐',
    distractors: ['sáo', 'sào', 'sảo'],
    explanation: '"Sao" (không dấu) là ngôi sao trên bầu trời. "Sáo" (dấu sắc) là cây sáo thổi, hoặc con sáo.',
    category: 'thanh-dieu-co-ban',
    level: 'easy',
  },
];

// ─── Exports ──────────────────────────────────────────────────────────────────
export const dienDauCategories: { key: string; label: string; icon: string }[] = [
  { key: 'hoi-nga', label: 'Hỏi và Ngã', icon: '?' },
  { key: 'sac-huyen', label: 'Sắc và Huyền', icon: '´' },
  { key: 'thanh-dieu-co-ban', label: 'Thanh điệu cơ bản', icon: '~' },
];

export const dienDauData: Record<
  string,
  { label: string; icon: string; questions: ToneQuestion[] }
> = {
  'hoi-nga': {
    label: 'Hỏi và Ngã',
    icon: '?',
    questions: hoiNgaQuestions,
  },
  'sac-huyen': {
    label: 'Sắc và Huyền',
    icon: '´',
    questions: sacHuyenQuestions,
  },
  'thanh-dieu-co-ban': {
    label: 'Thanh điệu cơ bản',
    icon: '~',
    questions: thanhDieuCobanQuestions,
  },
};
