export type BubbleColor = "pink" | "orange" | "purple" | "blue" | "green";

export interface VocabularyItem {
  id: string;
  word: string;
  speakText: string;
  emoji: string;
  color: BubbleColor;
}

export interface VocabularyLesson {
  id: string;
  title: string;
  subtitle: string;
  items: VocabularyItem[];
}

export const lessons: VocabularyLesson[] = [
  {
    id: "animals-1",
    title: "Con vật đáng yêu 1",
    subtitle: "Nghe tên con vật rồi bắt đúng bong bóng!",
    items: [
      { id: "animals-1-meo", word: "mèo", speakText: "mèo", emoji: "🐱", color: "pink" },
      { id: "animals-1-cho", word: "chó", speakText: "chó", emoji: "🐶", color: "orange" },
      { id: "animals-1-ca", word: "cá", speakText: "cá", emoji: "🐟", color: "purple" },
      { id: "animals-1-ga", word: "gà", speakText: "gà", emoji: "🐔", color: "blue" },
      { id: "animals-1-tho", word: "thỏ", speakText: "thỏ", emoji: "🐰", color: "green" },
      { id: "animals-1-vit", word: "vịt", speakText: "vịt", emoji: "🦆", color: "pink" },
      { id: "animals-1-bo", word: "bò", speakText: "bò", emoji: "🐮", color: "orange" },
      { id: "animals-1-de", word: "dê", speakText: "dê", emoji: "🐐", color: "purple" },
    ],
  },
  {
    id: "animals-2",
    title: "Con vật đáng yêu 2",
    subtitle: "Bé nhận biết thêm các con vật quen thuộc!",
    items: [
      { id: "animals-2-voi", word: "voi", speakText: "voi", emoji: "🐘", color: "pink" },
      { id: "animals-2-huou", word: "hươu", speakText: "hươu", emoji: "🦌", color: "orange" },
      { id: "animals-2-khi", word: "khỉ", speakText: "khỉ", emoji: "🐵", color: "purple" },
      { id: "animals-2-gau", word: "gấu", speakText: "gấu", emoji: "🐻", color: "blue" },
      { id: "animals-2-chim", word: "chim", speakText: "chim", emoji: "🐦", color: "green" },
      { id: "animals-2-ong", word: "ong", speakText: "ong", emoji: "🐝", color: "pink" },
      { id: "animals-2-buom", word: "bướm", speakText: "bướm", emoji: "🦋", color: "orange" },
      { id: "animals-2-rua", word: "rùa", speakText: "rùa", emoji: "🐢", color: "purple" },
    ],
  },
  {
    id: "fruit-1",
    title: "Trái cây 1",
    subtitle: "Bé nghe tên quả và chọn hình đúng nhé!",
    items: [
      { id: "fruit-1-tao", word: "táo", speakText: "táo", emoji: "🍎", color: "pink" },
      { id: "fruit-1-chuoi", word: "chuối", speakText: "chuối", emoji: "🍌", color: "orange" },
      { id: "fruit-1-nho", word: "nho", speakText: "nho", emoji: "🍇", color: "purple" },
      { id: "fruit-1-dau", word: "dâu", speakText: "dâu", emoji: "🍓", color: "blue" },
      { id: "fruit-1-cam", word: "cam", speakText: "cam", emoji: "🍊", color: "green" },
      { id: "fruit-1-dua-hau", word: "dưa hấu", speakText: "dưa hấu", emoji: "🍉", color: "pink" },
      { id: "fruit-1-le", word: "lê", speakText: "lê", emoji: "🍐", color: "orange" },
      { id: "fruit-1-dao", word: "đào", speakText: "đào", emoji: "🍑", color: "purple" },
    ],
  },
  {
    id: "fruit-2",
    title: "Trái cây 2",
    subtitle: "Luyện thêm tên các loại quả gần gũi!",
    items: [
      { id: "fruit-2-xoai", word: "xoài", speakText: "xoài", emoji: "🥭", color: "pink" },
      { id: "fruit-2-dua", word: "dứa", speakText: "dứa", emoji: "🍍", color: "orange" },
      { id: "fruit-2-dua-3", word: "dừa", speakText: "dừa", emoji: "🥥", color: "purple" },
      { id: "fruit-2-kiwi", word: "kiwi", speakText: "kiwi", emoji: "🥝", color: "blue" },
      { id: "fruit-2-chanh", word: "chanh", speakText: "chanh", emoji: "🍋", color: "green" },
      { id: "fruit-2-viet-quat", word: "việt quất", speakText: "việt quất", emoji: "🫐", color: "pink" },
      { id: "fruit-2-bo", word: "bơ", speakText: "bơ", emoji: "🥑", color: "orange" },
      { id: "fruit-2-ca-chua", word: "cà chua", speakText: "cà chua", emoji: "🍅", color: "purple" },
    ],
  },
  {
    id: "vegetables",
    title: "Rau củ",
    subtitle: "Bé nhận biết rau củ qua hình ảnh!",
    items: [
      { id: "vegetables-ca-rot", word: "cà rốt", speakText: "cà rốt", emoji: "🥕", color: "pink" },
      { id: "vegetables-bap-ngo", word: "bắp ngô", speakText: "bắp ngô", emoji: "🌽", color: "orange" },
      { id: "vegetables-khoai", word: "khoai", speakText: "khoai", emoji: "🥔", color: "purple" },
      { id: "vegetables-rau-xanh", word: "rau xanh", speakText: "rau xanh", emoji: "🥬", color: "blue" },
      { id: "vegetables-bong-cai", word: "bông cải", speakText: "bông cải", emoji: "🥦", color: "green" },
      { id: "vegetables-dua-leo", word: "dưa leo", speakText: "dưa leo", emoji: "🥒", color: "pink" },
      { id: "vegetables-nam", word: "nấm", speakText: "nấm", emoji: "🍄", color: "orange" },
      { id: "vegetables-ot-chuong", word: "ớt chuông", speakText: "ớt chuông", emoji: "🫑", color: "purple" },
    ],
  },
  {
    id: "school",
    title: "Đồ dùng học tập",
    subtitle: "Bé bắt đúng bong bóng đồ dùng trong lớp!",
    items: [
      { id: "school-sach", word: "sách", speakText: "sách", emoji: "📚", color: "pink" },
      { id: "school-but", word: "bút", speakText: "bút", emoji: "✏️", color: "orange" },
      { id: "school-cap", word: "cặp", speakText: "cặp", emoji: "🎒", color: "purple" },
      { id: "school-vo", word: "vở", speakText: "vở", emoji: "📒", color: "blue" },
      { id: "school-bang", word: "bảng", speakText: "bảng", emoji: "🧾", color: "green" },
      { id: "school-thuoc", word: "thước", speakText: "thước", emoji: "📏", color: "pink" },
      { id: "school-keo", word: "kéo", speakText: "kéo", emoji: "✂️", color: "orange" },
      { id: "school-mau-ve", word: "màu vẽ", speakText: "màu vẽ", emoji: "🖍️", color: "purple" },
    ],
  },
  {
    id: "classroom",
    title: "Trong lớp học",
    subtitle: "Bé nghe và chọn đồ vật trong lớp!",
    items: [
      { id: "classroom-ban", word: "bàn", speakText: "bàn", emoji: "🪑", color: "pink" },
      { id: "classroom-ghe", word: "ghế", speakText: "ghế", emoji: "🪑", color: "orange" },
      { id: "classroom-den", word: "đèn", speakText: "đèn", emoji: "💡", color: "purple" },
      { id: "classroom-chuong", word: "chuông", speakText: "chuông", emoji: "🔔", color: "blue" },
      { id: "classroom-may-tinh", word: "máy tính", speakText: "máy tính", emoji: "💻", color: "green" },
      { id: "classroom-dong-ho", word: "đồng hồ", speakText: "đồng hồ", emoji: "🕘", color: "pink" },
      { id: "classroom-hop-but", word: "hộp bút", speakText: "hộp bút", emoji: "🖊️", color: "orange" },
      { id: "classroom-bang-chu", word: "bảng chữ", speakText: "bảng chữ", emoji: "🔤", color: "purple" },
    ],
  },
  {
    id: "nature-1",
    title: "Thiên nhiên 1",
    subtitle: "Nghe từ về thiên nhiên rồi chọn hình đúng!",
    items: [
      { id: "nature-1-hoa", word: "hoa", speakText: "hoa", emoji: "🌸", color: "pink" },
      { id: "nature-1-la", word: "lá", speakText: "lá", emoji: "🍃", color: "orange" },
      { id: "nature-1-mat-troi", word: "mặt trời", speakText: "mặt trời", emoji: "☀️", color: "purple" },
      { id: "nature-1-may", word: "mây", speakText: "mây", emoji: "☁️", color: "blue" },
      { id: "nature-1-nui", word: "núi", speakText: "núi", emoji: "⛰️", color: "green" },
      { id: "nature-1-cay", word: "cây", speakText: "cây", emoji: "🌳", color: "pink" },
      { id: "nature-1-co", word: "cỏ", speakText: "cỏ", emoji: "🌿", color: "orange" },
      { id: "nature-1-song", word: "sông", speakText: "sông", emoji: "🏞️", color: "purple" },
    ],
  },
  {
    id: "nature-2",
    title: "Thiên nhiên 2",
    subtitle: "Bé khám phá thêm cảnh vật quanh mình!",
    items: [
      { id: "nature-2-bien", word: "biển", speakText: "biển", emoji: "🌊", color: "pink" },
      { id: "nature-2-sao", word: "sao", speakText: "sao", emoji: "⭐", color: "orange" },
      { id: "nature-2-trang", word: "trăng", speakText: "trăng", emoji: "🌙", color: "purple" },
      { id: "nature-2-cau-vong", word: "cầu vồng", speakText: "cầu vồng", emoji: "🌈", color: "blue" },
      { id: "nature-2-mua", word: "mưa", speakText: "mưa", emoji: "🌧️", color: "green" },
      { id: "nature-2-tuyet", word: "tuyết", speakText: "tuyết", emoji: "❄️", color: "pink" },
      { id: "nature-2-gio", word: "gió", speakText: "gió", emoji: "💨", color: "orange" },
      { id: "nature-2-lua", word: "lửa", speakText: "lửa", emoji: "🔥", color: "purple" },
    ],
  },
  {
    id: "colors-1",
    title: "Màu sắc 1",
    subtitle: "Bé nghe màu và bắt bong bóng đúng!",
    items: [
      { id: "colors-1-do", word: "đỏ", speakText: "đỏ", emoji: "🔴", color: "pink" },
      { id: "colors-1-vang", word: "vàng", speakText: "vàng", emoji: "🟡", color: "orange" },
      { id: "colors-1-xanh-la", word: "xanh lá", speakText: "xanh lá", emoji: "🟢", color: "purple" },
      { id: "colors-1-xanh-duong", word: "xanh dương", speakText: "xanh dương", emoji: "🔵", color: "blue" },
      { id: "colors-1-tim", word: "tím", speakText: "tím", emoji: "🟣", color: "green" },
      { id: "colors-1-cam", word: "cam", speakText: "cam", emoji: "🟠", color: "pink" },
      { id: "colors-1-den", word: "đen", speakText: "đen", emoji: "⚫", color: "orange" },
      { id: "colors-1-trang", word: "trắng", speakText: "trắng", emoji: "⚪", color: "purple" },
    ],
  },
  {
    id: "colors-2",
    title: "Màu sắc 2",
    subtitle: "Luyện thêm các màu bé thường gặp!",
    items: [
      { id: "colors-2-hong", word: "hồng", speakText: "hồng", emoji: "💗", color: "pink" },
      { id: "colors-2-nau", word: "nâu", speakText: "nâu", emoji: "🟤", color: "orange" },
      { id: "colors-2-xam", word: "xám", speakText: "xám", emoji: "🔘", color: "purple" },
      { id: "colors-2-xanh-ngoc", word: "xanh ngọc", speakText: "xanh ngọc", emoji: "🟦", color: "blue" },
      { id: "colors-2-vang-nhat", word: "vàng nhạt", speakText: "vàng nhạt", emoji: "🌼", color: "green" },
      { id: "colors-2-do-tuoi", word: "đỏ tươi", speakText: "đỏ tươi", emoji: "🍎", color: "pink" },
      { id: "colors-2-xanh-troi", word: "xanh trời", speakText: "xanh trời", emoji: "🩵", color: "orange" },
      { id: "colors-2-nhieu-mau", word: "nhiều màu", speakText: "nhiều màu", emoji: "🌈", color: "purple" },
    ],
  },
  {
    id: "family",
    title: "Gia đình",
    subtitle: "Bé chọn đúng từ về người thân!",
    items: [
      { id: "family-ba", word: "bà", speakText: "bà", emoji: "👵", color: "pink" },
      { id: "family-ong", word: "ông", speakText: "ông", emoji: "👴", color: "orange" },
      { id: "family-bo", word: "bố", speakText: "bố", emoji: "👨", color: "purple" },
      { id: "family-me", word: "mẹ", speakText: "mẹ", emoji: "👩", color: "blue" },
      { id: "family-be", word: "bé", speakText: "bé", emoji: "👧", color: "green" },
      { id: "family-anh", word: "anh", speakText: "anh", emoji: "👦", color: "pink" },
      { id: "family-chi", word: "chị", speakText: "chị", emoji: "👧", color: "orange" },
      { id: "family-co-giao", word: "cô giáo", speakText: "cô giáo", emoji: "👩‍🏫", color: "purple" },
    ],
  },
  {
    id: "body",
    title: "Cơ thể của bé",
    subtitle: "Bé nhận biết các bộ phận cơ thể!",
    items: [
      { id: "body-mat", word: "mắt", speakText: "mắt", emoji: "👀", color: "pink" },
      { id: "body-tai", word: "tai", speakText: "tai", emoji: "👂", color: "orange" },
      { id: "body-mui", word: "mũi", speakText: "mũi", emoji: "👃", color: "purple" },
      { id: "body-mieng", word: "miệng", speakText: "miệng", emoji: "👄", color: "blue" },
      { id: "body-tay", word: "tay", speakText: "tay", emoji: "🤚", color: "green" },
      { id: "body-chan", word: "chân", speakText: "chân", emoji: "🦶", color: "pink" },
      { id: "body-toc", word: "tóc", speakText: "tóc", emoji: "💇", color: "orange" },
      { id: "body-rang", word: "răng", speakText: "răng", emoji: "🦷", color: "purple" },
    ],
  },
  {
    id: "clothes",
    title: "Trang phục",
    subtitle: "Bé đọc tên đồ mặc hằng ngày!",
    items: [
      { id: "clothes-ao", word: "áo", speakText: "áo", emoji: "👕", color: "pink" },
      { id: "clothes-quan", word: "quần", speakText: "quần", emoji: "👖", color: "orange" },
      { id: "clothes-vay", word: "váy", speakText: "váy", emoji: "👗", color: "purple" },
      { id: "clothes-mu", word: "mũ", speakText: "mũ", emoji: "🧢", color: "blue" },
      { id: "clothes-giay", word: "giày", speakText: "giày", emoji: "👟", color: "green" },
      { id: "clothes-tat", word: "tất", speakText: "tất", emoji: "🧦", color: "pink" },
      { id: "clothes-khan", word: "khăn", speakText: "khăn", emoji: "🧣", color: "orange" },
      { id: "clothes-kinh", word: "kính", speakText: "kính", emoji: "👓", color: "purple" },
    ],
  },
  {
    id: "food-1",
    title: "Món ăn 1",
    subtitle: "Bé nghe tên món ăn rồi chọn đúng!",
    items: [
      { id: "food-1-com", word: "cơm", speakText: "cơm", emoji: "🍚", color: "pink" },
      { id: "food-1-banh", word: "bánh", speakText: "bánh", emoji: "🍞", color: "orange" },
      { id: "food-1-sua", word: "sữa", speakText: "sữa", emoji: "🥛", color: "purple" },
      { id: "food-1-pho", word: "phở", speakText: "phở", emoji: "🍜", color: "blue" },
      { id: "food-1-bun", word: "bún", speakText: "bún", emoji: "🍜", color: "green" },
      { id: "food-1-chao", word: "cháo", speakText: "cháo", emoji: "🥣", color: "pink" },
      { id: "food-1-trung", word: "trứng", speakText: "trứng", emoji: "🥚", color: "orange" },
      { id: "food-1-kem", word: "kem", speakText: "kem", emoji: "🍦", color: "purple" },
    ],
  },
  {
    id: "food-2",
    title: "Món ăn 2",
    subtitle: "Thêm nhiều món ăn gần gũi với bé!",
    items: [
      { id: "food-2-mi", word: "mì", speakText: "mì", emoji: "🍝", color: "pink" },
      { id: "food-2-rau", word: "rau", speakText: "rau", emoji: "🥬", color: "orange" },
      { id: "food-2-ca", word: "cá", speakText: "cá", emoji: "🐟", color: "purple" },
      { id: "food-2-tom", word: "tôm", speakText: "tôm", emoji: "🦐", color: "blue" },
      { id: "food-2-ngo", word: "ngô", speakText: "ngô", emoji: "🌽", color: "green" },
      { id: "food-2-keo", word: "kẹo", speakText: "kẹo", emoji: "🍬", color: "pink" },
      { id: "food-2-banh-quy", word: "bánh quy", speakText: "bánh quy", emoji: "🍪", color: "orange" },
      { id: "food-2-nuoc", word: "nước", speakText: "nước", emoji: "💧", color: "purple" },
    ],
  },
  {
    id: "house",
    title: "Ngôi nhà",
    subtitle: "Bé chọn đúng đồ vật trong nhà!",
    items: [
      { id: "house-nha", word: "nhà", speakText: "nhà", emoji: "🏠", color: "pink" },
      { id: "house-cua", word: "cửa", speakText: "cửa", emoji: "🚪", color: "orange" },
      { id: "house-giuong", word: "giường", speakText: "giường", emoji: "🛏️", color: "purple" },
      { id: "house-ghe", word: "ghế", speakText: "ghế", emoji: "🪑", color: "blue" },
      { id: "house-bep", word: "bếp", speakText: "bếp", emoji: "🍳", color: "green" },
      { id: "house-den", word: "đèn", speakText: "đèn", emoji: "💡", color: "pink" },
      { id: "house-goi", word: "gối", speakText: "gối", emoji: "🛌", color: "orange" },
      { id: "house-chia-khoa", word: "chìa khóa", speakText: "chìa khóa", emoji: "🔑", color: "purple" },
    ],
  },
  {
    id: "vehicles",
    title: "Phương tiện",
    subtitle: "Bé nhận biết các phương tiện quen thuộc!",
    items: [
      { id: "vehicles-xe-dap", word: "xe đạp", speakText: "xe đạp", emoji: "🚲", color: "pink" },
      { id: "vehicles-xe-buyt", word: "xe buýt", speakText: "xe buýt", emoji: "🚌", color: "orange" },
      { id: "vehicles-o-to", word: "ô tô", speakText: "ô tô", emoji: "🚗", color: "purple" },
      { id: "vehicles-tau-hoa", word: "tàu hỏa", speakText: "tàu hỏa", emoji: "🚆", color: "blue" },
      { id: "vehicles-may-bay", word: "máy bay", speakText: "máy bay", emoji: "✈️", color: "green" },
      { id: "vehicles-thuyen", word: "thuyền", speakText: "thuyền", emoji: "⛵", color: "pink" },
      { id: "vehicles-xe-may", word: "xe máy", speakText: "xe máy", emoji: "🛵", color: "orange" },
      { id: "vehicles-tau-thuy", word: "tàu thủy", speakText: "tàu thủy", emoji: "🚢", color: "purple" },
    ],
  },
  {
    id: "shapes-1",
    title: "Hình dạng 1",
    subtitle: "Bé nghe tên hình rồi chọn đúng!",
    items: [
      { id: "shapes-1-hinh-tron", word: "hình tròn", speakText: "hình tròn", emoji: "⚪", color: "pink" },
      { id: "shapes-1-hinh-vuong", word: "hình vuông", speakText: "hình vuông", emoji: "◼️", color: "orange" },
      { id: "shapes-1-tam-giac", word: "tam giác", speakText: "tam giác", emoji: "🔺", color: "purple" },
      { id: "shapes-1-chu-nhat", word: "chữ nhật", speakText: "chữ nhật", emoji: "▭", color: "blue" },
      { id: "shapes-1-ngoi-sao", word: "ngôi sao", speakText: "ngôi sao", emoji: "⭐", color: "green" },
      { id: "shapes-1-trai-tim", word: "trái tim", speakText: "trái tim", emoji: "❤️", color: "pink" },
      { id: "shapes-1-hinh-thoi", word: "hình thoi", speakText: "hình thoi", emoji: "🔷", color: "orange" },
      { id: "shapes-1-bau-duc", word: "bầu dục", speakText: "bầu dục", emoji: "🥚", color: "purple" },
    ],
  },
  {
    id: "shapes-2",
    title: "Hình dạng 2",
    subtitle: "Luyện thêm các hình khó hơn một chút!",
    items: [
      { id: "shapes-2-luc-giac", word: "lục giác", speakText: "lục giác", emoji: "⬡", color: "pink" },
      { id: "shapes-2-ban-nguyet", word: "bán nguyệt", speakText: "bán nguyệt", emoji: "🌙", color: "orange" },
      { id: "shapes-2-mui-ten", word: "mũi tên", speakText: "mũi tên", emoji: "➡️", color: "purple" },
      { id: "shapes-2-dau-cong", word: "dấu cộng", speakText: "dấu cộng", emoji: "➕", color: "blue" },
      { id: "shapes-2-dau-tru", word: "dấu trừ", speakText: "dấu trừ", emoji: "➖", color: "green" },
      { id: "shapes-2-dau-bang", word: "dấu bằng", speakText: "dấu bằng", emoji: "🟰", color: "pink" },
      { id: "shapes-2-dau-nhan", word: "dấu nhân", speakText: "dấu nhân", emoji: "✖️", color: "orange" },
      { id: "shapes-2-dau-hoi", word: "dấu hỏi", speakText: "dấu hỏi", emoji: "❓", color: "purple" },
    ],
  },
  {
    id: "numbers-1",
    title: "Số đếm 1",
    subtitle: "Bé nghe số và chọn bong bóng đúng!",
    items: [
      { id: "numbers-1-mot", word: "một", speakText: "một", emoji: "1️⃣", color: "pink" },
      { id: "numbers-1-hai", word: "hai", speakText: "hai", emoji: "2️⃣", color: "orange" },
      { id: "numbers-1-ba", word: "ba", speakText: "ba", emoji: "3️⃣", color: "purple" },
      { id: "numbers-1-bon", word: "bốn", speakText: "bốn", emoji: "4️⃣", color: "blue" },
      { id: "numbers-1-nam", word: "năm", speakText: "năm", emoji: "5️⃣", color: "green" },
      { id: "numbers-1-sau", word: "sáu", speakText: "sáu", emoji: "6️⃣", color: "pink" },
      { id: "numbers-1-bay", word: "bảy", speakText: "bảy", emoji: "7️⃣", color: "orange" },
      { id: "numbers-1-tam", word: "tám", speakText: "tám", emoji: "8️⃣", color: "purple" },
    ],
  },
  {
    id: "numbers-2",
    title: "Số đếm 2",
    subtitle: "Bé luyện thêm các số lớn hơn!",
    items: [
      { id: "numbers-2-chin", word: "chín", speakText: "chín", emoji: "9️⃣", color: "pink" },
      { id: "numbers-2-muoi", word: "mười", speakText: "mười", emoji: "🔟", color: "orange" },
      { id: "numbers-2-muoi-mot", word: "mười một", speakText: "mười một", emoji: "1️⃣1️⃣", color: "purple" },
      { id: "numbers-2-muoi-hai", word: "mười hai", speakText: "mười hai", emoji: "1️⃣2️⃣", color: "blue" },
      { id: "numbers-2-hai-muoi", word: "hai mươi", speakText: "hai mươi", emoji: "2️⃣0️⃣", color: "green" },
      { id: "numbers-2-ba-muoi", word: "ba mươi", speakText: "ba mươi", emoji: "3️⃣0️⃣", color: "pink" },
      { id: "numbers-2-mot-tram", word: "một trăm", speakText: "một trăm", emoji: "💯", color: "orange" },
      { id: "numbers-2-so-khong", word: "số không", speakText: "số không", emoji: "0️⃣", color: "purple" },
    ],
  },
  {
    id: "actions-1",
    title: "Hoạt động vui 1",
    subtitle: "Bé nghe tên hoạt động rồi chọn đúng!",
    items: [
      { id: "actions-1-doc", word: "đọc", speakText: "đọc", emoji: "📖", color: "pink" },
      { id: "actions-1-viet", word: "viết", speakText: "viết", emoji: "✍️", color: "orange" },
      { id: "actions-1-ve", word: "vẽ", speakText: "vẽ", emoji: "🎨", color: "purple" },
      { id: "actions-1-hat", word: "hát", speakText: "hát", emoji: "🎤", color: "blue" },
      { id: "actions-1-dem", word: "đếm", speakText: "đếm", emoji: "🔢", color: "green" },
      { id: "actions-1-choi", word: "chơi", speakText: "chơi", emoji: "🧸", color: "pink" },
      { id: "actions-1-nghe", word: "nghe", speakText: "nghe", emoji: "👂", color: "orange" },
      { id: "actions-1-nhin", word: "nhìn", speakText: "nhìn", emoji: "👀", color: "purple" },
    ],
  },
  {
    id: "actions-2",
    title: "Hoạt động vui 2",
    subtitle: "Bé học thêm các hoạt động tích cực!",
    items: [
      { id: "actions-2-cuoi", word: "cười", speakText: "cười", emoji: "😊", color: "pink" },
      { id: "actions-2-chao", word: "chào", speakText: "chào", emoji: "👋", color: "orange" },
      { id: "actions-2-moi", word: "mời", speakText: "mời", emoji: "🙋", color: "purple" },
      { id: "actions-2-to-mau", word: "tô màu", speakText: "tô màu", emoji: "🖍️", color: "blue" },
      { id: "actions-2-nhay", word: "nhảy", speakText: "nhảy", emoji: "💃", color: "green" },
      { id: "actions-2-di-bo", word: "đi bộ", speakText: "đi bộ", emoji: "🚶", color: "pink" },
      { id: "actions-2-rua-tay", word: "rửa tay", speakText: "rửa tay", emoji: "🧼", color: "orange" },
      { id: "actions-2-uong-nuoc", word: "uống nước", speakText: "uống nước", emoji: "🥤", color: "purple" },
    ],
  },
  {
    id: "emotions",
    title: "Cảm xúc tích cực",
    subtitle: "Bé nhận biết cảm xúc vui vẻ!",
    items: [
      { id: "emotions-vui", word: "vui", speakText: "vui", emoji: "😊", color: "pink" },
      { id: "emotions-yeu", word: "yêu", speakText: "yêu", emoji: "🥰", color: "orange" },
      { id: "emotions-ngoan", word: "ngoan", speakText: "ngoan", emoji: "😇", color: "purple" },
      { id: "emotions-binh-tinh", word: "bình tĩnh", speakText: "bình tĩnh", emoji: "🙂", color: "blue" },
      { id: "emotions-tu-tin", word: "tự tin", speakText: "tự tin", emoji: "😄", color: "green" },
      { id: "emotions-thich", word: "thích", speakText: "thích", emoji: "😍", color: "pink" },
      { id: "emotions-cam-on", word: "cảm ơn", speakText: "cảm ơn", emoji: "🙏", color: "orange" },
      { id: "emotions-xin-chao", word: "xin chào", speakText: "xin chào", emoji: "👋", color: "purple" },
    ],
  },
  {
    id: "weather",
    title: "Thời tiết",
    subtitle: "Bé nghe tên thời tiết và chọn đúng!",
    items: [
      { id: "weather-nang", word: "nắng", speakText: "nắng", emoji: "☀️", color: "pink" },
      { id: "weather-mua", word: "mưa", speakText: "mưa", emoji: "🌧️", color: "orange" },
      { id: "weather-gio", word: "gió", speakText: "gió", emoji: "💨", color: "purple" },
      { id: "weather-may", word: "mây", speakText: "mây", emoji: "☁️", color: "blue" },
      { id: "weather-lanh", word: "lạnh", speakText: "lạnh", emoji: "🧣", color: "green" },
      { id: "weather-am", word: "ấm", speakText: "ấm", emoji: "🌤️", color: "pink" },
      { id: "weather-cau-vong", word: "cầu vồng", speakText: "cầu vồng", emoji: "🌈", color: "orange" },
      { id: "weather-tuyet", word: "tuyết", speakText: "tuyết", emoji: "❄️", color: "purple" },
    ],
  },
  {
    id: "time",
    title: "Thời gian",
    subtitle: "Bé nhận biết các thời điểm trong ngày!",
    items: [
      { id: "time-sang", word: "sáng", speakText: "sáng", emoji: "🌅", color: "pink" },
      { id: "time-trua", word: "trưa", speakText: "trưa", emoji: "🏙️", color: "orange" },
      { id: "time-chieu", word: "chiều", speakText: "chiều", emoji: "🌇", color: "purple" },
      { id: "time-toi", word: "tối", speakText: "tối", emoji: "🌙", color: "blue" },
      { id: "time-hom-nay", word: "hôm nay", speakText: "hôm nay", emoji: "📅", color: "green" },
      { id: "time-ngay-mai", word: "ngày mai", speakText: "ngày mai", emoji: "🗓️", color: "pink" },
      { id: "time-dong-ho", word: "đồng hồ", speakText: "đồng hồ", emoji: "🕘", color: "orange" },
      { id: "time-lich", word: "lịch", speakText: "lịch", emoji: "📆", color: "purple" },
    ],
  },
  {
    id: "places",
    title: "Nơi chốn",
    subtitle: "Bé chọn đúng địa điểm quen thuộc!",
    items: [
      { id: "places-nha", word: "nhà", speakText: "nhà", emoji: "🏠", color: "pink" },
      { id: "places-lop-hoc", word: "lớp học", speakText: "lớp học", emoji: "🏫", color: "orange" },
      { id: "places-san-choi", word: "sân chơi", speakText: "sân chơi", emoji: "🛝", color: "purple" },
      { id: "places-vuon", word: "vườn", speakText: "vườn", emoji: "🌳", color: "blue" },
      { id: "places-cong-vien", word: "công viên", speakText: "công viên", emoji: "🏞️", color: "green" },
      { id: "places-sieu-thi", word: "siêu thị", speakText: "siêu thị", emoji: "🛒", color: "pink" },
      { id: "places-thu-vien", word: "thư viện", speakText: "thư viện", emoji: "📚", color: "orange" },
      { id: "places-bai-bien", word: "bãi biển", speakText: "bãi biển", emoji: "🏖️", color: "purple" },
    ],
  },
  {
    id: "music",
    title: "Âm nhạc",
    subtitle: "Bé nghe và chọn nhạc cụ đúng!",
    items: [
      { id: "music-dan", word: "đàn", speakText: "đàn", emoji: "🎸", color: "pink" },
      { id: "music-trong", word: "trống", speakText: "trống", emoji: "🥁", color: "orange" },
      { id: "music-piano", word: "piano", speakText: "piano", emoji: "🎹", color: "purple" },
      { id: "music-sao", word: "sáo", speakText: "sáo", emoji: "🎶", color: "blue" },
      { id: "music-micro", word: "micro", speakText: "micro", emoji: "🎤", color: "green" },
      { id: "music-not-nhac", word: "nốt nhạc", speakText: "nốt nhạc", emoji: "🎵", color: "pink" },
      { id: "music-chuong", word: "chuông", speakText: "chuông", emoji: "🔔", color: "orange" },
      { id: "music-tai-nghe", word: "tai nghe", speakText: "tai nghe", emoji: "🎧", color: "purple" },
    ],
  },
  {
    id: "sports",
    title: "Vận động",
    subtitle: "Bé nhận biết đồ chơi và vận động!",
    items: [
      { id: "sports-bong-da", word: "bóng đá", speakText: "bóng đá", emoji: "⚽", color: "pink" },
      { id: "sports-bong-ro", word: "bóng rổ", speakText: "bóng rổ", emoji: "🏀", color: "orange" },
      { id: "sports-cau-long", word: "cầu lông", speakText: "cầu lông", emoji: "🏸", color: "purple" },
      { id: "sports-boi", word: "bơi", speakText: "bơi", emoji: "🏊", color: "blue" },
      { id: "sports-chay", word: "chạy", speakText: "chạy", emoji: "🏃", color: "green" },
      { id: "sports-dap-xe", word: "đạp xe", speakText: "đạp xe", emoji: "🚴", color: "pink" },
      { id: "sports-nhay-day", word: "nhảy dây", speakText: "nhảy dây", emoji: "🪢", color: "orange" },
      { id: "sports-huy-chuong", word: "huy chương", speakText: "huy chương", emoji: "🏅", color: "purple" },
    ],
  },
  {
    id: "toys",
    title: "Đồ chơi",
    subtitle: "Bé chọn đúng đồ chơi yêu thích!",
    items: [
      { id: "toys-gau-bong", word: "gấu bông", speakText: "gấu bông", emoji: "🧸", color: "pink" },
      { id: "toys-bong", word: "bóng", speakText: "bóng", emoji: "⚽", color: "orange" },
      { id: "toys-xep-hinh", word: "xếp hình", speakText: "xếp hình", emoji: "🧩", color: "purple" },
      { id: "toys-o-to-do-choi", word: "ô tô đồ chơi", speakText: "ô tô đồ chơi", emoji: "🚗", color: "blue" },
      { id: "toys-bup-be", word: "búp bê", speakText: "búp bê", emoji: "🎎", color: "green" },
      { id: "toys-dieu", word: "diều", speakText: "diều", emoji: "🪁", color: "pink" },
      { id: "toys-robot", word: "robot", speakText: "robot", emoji: "🤖", color: "orange" },
      { id: "toys-tau-do-choi", word: "tàu đồ chơi", speakText: "tàu đồ chơi", emoji: "🚂", color: "purple" },
    ],
  },
  {
    id: "kitchen",
    title: "Trong bếp",
    subtitle: "Bé nhận biết đồ dùng nhà bếp!",
    items: [
      { id: "kitchen-bat", word: "bát", speakText: "bát", emoji: "🥣", color: "pink" },
      { id: "kitchen-coc", word: "cốc", speakText: "cốc", emoji: "🥤", color: "orange" },
      { id: "kitchen-thia", word: "thìa", speakText: "thìa", emoji: "🥄", color: "purple" },
      { id: "kitchen-dia", word: "đĩa", speakText: "đĩa", emoji: "🍽️", color: "blue" },
      { id: "kitchen-noi", word: "nồi", speakText: "nồi", emoji: "🍲", color: "green" },
      { id: "kitchen-chao", word: "chảo", speakText: "chảo", emoji: "🍳", color: "pink" },
      { id: "kitchen-am-nuoc", word: "ấm nước", speakText: "ấm nước", emoji: "🫖", color: "orange" },
      { id: "kitchen-tu-lanh", word: "tủ lạnh", speakText: "tủ lạnh", emoji: "🧊", color: "purple" },
    ],
  },
  {
    id: "clean",
    title: "Sạch sẽ",
    subtitle: "Bé học các đồ dùng vệ sinh quen thuộc!",
    items: [
      { id: "clean-xa-phong", word: "xà phòng", speakText: "xà phòng", emoji: "🧼", color: "pink" },
      { id: "clean-khan", word: "khăn", speakText: "khăn", emoji: "🧻", color: "orange" },
      { id: "clean-ban-chai", word: "bàn chải", speakText: "bàn chải", emoji: "🪥", color: "purple" },
      { id: "clean-nuoc", word: "nước", speakText: "nước", emoji: "💧", color: "blue" },
      { id: "clean-chau", word: "chậu", speakText: "chậu", emoji: "🪣", color: "green" },
      { id: "clean-luoc", word: "lược", speakText: "lược", emoji: "💇", color: "pink" },
      { id: "clean-guong", word: "gương", speakText: "gương", emoji: "🪞", color: "orange" },
      { id: "clean-ao-sach", word: "áo sạch", speakText: "áo sạch", emoji: "👕", color: "purple" },
    ],
  },
  {
    id: "farm",
    title: "Nông trại nhỏ",
    subtitle: "Bé nghe tên đồ vật và con vật ở nông trại!",
    items: [
      { id: "farm-ga", word: "gà", speakText: "gà", emoji: "🐔", color: "pink" },
      { id: "farm-vit", word: "vịt", speakText: "vịt", emoji: "🦆", color: "orange" },
      { id: "farm-bo", word: "bò", speakText: "bò", emoji: "🐮", color: "purple" },
      { id: "farm-de", word: "dê", speakText: "dê", emoji: "🐐", color: "blue" },
      { id: "farm-ngo", word: "ngô", speakText: "ngô", emoji: "🌽", color: "green" },
      { id: "farm-cay", word: "cây", speakText: "cây", emoji: "🌳", color: "pink" },
      { id: "farm-nha-kho", word: "nhà kho", speakText: "nhà kho", emoji: "🏚️", color: "orange" },
      { id: "farm-may-keo", word: "máy kéo", speakText: "máy kéo", emoji: "🚜", color: "purple" },
    ],
  },
  {
    id: "sea",
    title: "Biển xanh",
    subtitle: "Bé khám phá các hình ảnh ở biển!",
    items: [
      { id: "sea-bien", word: "biển", speakText: "biển", emoji: "🌊", color: "pink" },
      { id: "sea-ca", word: "cá", speakText: "cá", emoji: "🐟", color: "orange" },
      { id: "sea-sao-bien", word: "sao biển", speakText: "sao biển", emoji: "⭐", color: "purple" },
      { id: "sea-oc-bien", word: "ốc biển", speakText: "ốc biển", emoji: "🐚", color: "blue" },
      { id: "sea-thuyen", word: "thuyền", speakText: "thuyền", emoji: "⛵", color: "green" },
      { id: "sea-mat-troi", word: "mặt trời", speakText: "mặt trời", emoji: "☀️", color: "pink" },
      { id: "sea-cat", word: "cát", speakText: "cát", emoji: "🏖️", color: "orange" },
      { id: "sea-dua", word: "dừa", speakText: "dừa", emoji: "🥥", color: "purple" },
    ],
  },
  {
    id: "sky",
    title: "Bầu trời",
    subtitle: "Bé chọn hình trên bầu trời!",
    items: [
      { id: "sky-may", word: "mây", speakText: "mây", emoji: "☁️", color: "pink" },
      { id: "sky-mat-troi", word: "mặt trời", speakText: "mặt trời", emoji: "☀️", color: "orange" },
      { id: "sky-trang", word: "trăng", speakText: "trăng", emoji: "🌙", color: "purple" },
      { id: "sky-sao", word: "sao", speakText: "sao", emoji: "⭐", color: "blue" },
      { id: "sky-cau-vong", word: "cầu vồng", speakText: "cầu vồng", emoji: "🌈", color: "green" },
      { id: "sky-may-bay", word: "máy bay", speakText: "máy bay", emoji: "✈️", color: "pink" },
      { id: "sky-chim", word: "chim", speakText: "chim", emoji: "🐦", color: "orange" },
      { id: "sky-dieu", word: "diều", speakText: "diều", emoji: "🪁", color: "purple" },
    ],
  },
  {
    id: "opposites-1",
    title: "Cặp từ đơn giản 1",
    subtitle: "Bé làm quen với các cặp từ đối lập dễ hiểu!",
    items: [
      { id: "opposites-1-to", word: "to", speakText: "to", emoji: "🔵", color: "pink" },
      { id: "opposites-1-nho", word: "nhỏ", speakText: "nhỏ", emoji: "🔹", color: "orange" },
      { id: "opposites-1-cao", word: "cao", speakText: "cao", emoji: "⬆️", color: "purple" },
      { id: "opposites-1-thap", word: "thấp", speakText: "thấp", emoji: "⬇️", color: "blue" },
      { id: "opposites-1-dai", word: "dài", speakText: "dài", emoji: "📏", color: "green" },
      { id: "opposites-1-ngan", word: "ngắn", speakText: "ngắn", emoji: "📐", color: "pink" },
      { id: "opposites-1-mo", word: "mở", speakText: "mở", emoji: "🔓", color: "orange" },
      { id: "opposites-1-dong", word: "đóng", speakText: "đóng", emoji: "🔒", color: "purple" },
    ],
  },
  {
    id: "opposites-2",
    title: "Cặp từ đơn giản 2",
    subtitle: "Bé nghe và nhận biết thêm cặp từ!",
    items: [
      { id: "opposites-2-tren", word: "trên", speakText: "trên", emoji: "⬆️", color: "pink" },
      { id: "opposites-2-duoi", word: "dưới", speakText: "dưới", emoji: "⬇️", color: "orange" },
      { id: "opposites-2-trong", word: "trong", speakText: "trong", emoji: "📥", color: "purple" },
      { id: "opposites-2-ngoai", word: "ngoài", speakText: "ngoài", emoji: "📤", color: "blue" },
      { id: "opposites-2-trai", word: "trái", speakText: "trái", emoji: "⬅️", color: "green" },
      { id: "opposites-2-phai", word: "phải", speakText: "phải", emoji: "➡️", color: "pink" },
      { id: "opposites-2-truoc", word: "trước", speakText: "trước", emoji: "⏩", color: "orange" },
      { id: "opposites-2-sau", word: "sau", speakText: "sau", emoji: "⏪", color: "purple" },
    ],
  },
  {
    id: "review-1",
    title: "Ôn tập 1",
    subtitle: "Bé ôn lại từ vựng thật quen thuộc!",
    items: [
      { id: "review-1-meo", word: "mèo", speakText: "mèo", emoji: "🐱", color: "pink" },
      { id: "review-1-tao", word: "táo", speakText: "táo", emoji: "🍎", color: "orange" },
      { id: "review-1-sach", word: "sách", speakText: "sách", emoji: "📚", color: "purple" },
      { id: "review-1-hoa", word: "hoa", speakText: "hoa", emoji: "🌸", color: "blue" },
      { id: "review-1-do", word: "đỏ", speakText: "đỏ", emoji: "🔴", color: "green" },
      { id: "review-1-bo", word: "bố", speakText: "bố", emoji: "👨", color: "pink" },
      { id: "review-1-hinh-tron", word: "hình tròn", speakText: "hình tròn", emoji: "⚪", color: "orange" },
      { id: "review-1-mot", word: "một", speakText: "một", emoji: "1️⃣", color: "purple" },
    ],
  },
  {
    id: "review-2",
    title: "Ôn tập 2",
    subtitle: "Bé nghe và chọn nhanh các từ đã học!",
    items: [
      { id: "review-2-cho", word: "chó", speakText: "chó", emoji: "🐶", color: "pink" },
      { id: "review-2-chuoi", word: "chuối", speakText: "chuối", emoji: "🍌", color: "orange" },
      { id: "review-2-but", word: "bút", speakText: "bút", emoji: "✏️", color: "purple" },
      { id: "review-2-mat-troi", word: "mặt trời", speakText: "mặt trời", emoji: "☀️", color: "blue" },
      { id: "review-2-xanh-la", word: "xanh lá", speakText: "xanh lá", emoji: "🟢", color: "green" },
      { id: "review-2-me", word: "mẹ", speakText: "mẹ", emoji: "👩", color: "pink" },
      { id: "review-2-tam-giac", word: "tam giác", speakText: "tam giác", emoji: "🔺", color: "orange" },
      { id: "review-2-hai", word: "hai", speakText: "hai", emoji: "2️⃣", color: "purple" },
    ],
  },
  {
    id: "review-3",
    title: "Ôn tập 3",
    subtitle: "Bé luyện trí nhớ qua nhiều chủ đề!",
    items: [
      { id: "review-3-ca", word: "cá", speakText: "cá", emoji: "🐟", color: "pink" },
      { id: "review-3-nho", word: "nho", speakText: "nho", emoji: "🍇", color: "orange" },
      { id: "review-3-cap", word: "cặp", speakText: "cặp", emoji: "🎒", color: "purple" },
      { id: "review-3-may", word: "mây", speakText: "mây", emoji: "☁️", color: "blue" },
      { id: "review-3-vang", word: "vàng", speakText: "vàng", emoji: "🟡", color: "green" },
      { id: "review-3-be", word: "bé", speakText: "bé", emoji: "👧", color: "pink" },
      { id: "review-3-ngoi-sao", word: "ngôi sao", speakText: "ngôi sao", emoji: "⭐", color: "orange" },
      { id: "review-3-ba", word: "ba", speakText: "ba", emoji: "3️⃣", color: "purple" },
    ],
  },
  {
    id: "review-4",
    title: "Ôn tập 4",
    subtitle: "Bé thử sức với bài tổng hợp cuối!",
    items: [
      { id: "review-4-tho", word: "thỏ", speakText: "thỏ", emoji: "🐰", color: "pink" },
      { id: "review-4-cam", word: "cam", speakText: "cam", emoji: "🍊", color: "orange" },
      { id: "review-4-vo", word: "vở", speakText: "vở", emoji: "📒", color: "purple" },
      { id: "review-4-nui", word: "núi", speakText: "núi", emoji: "⛰️", color: "blue" },
      { id: "review-4-tim", word: "tím", speakText: "tím", emoji: "🟣", color: "green" },
      { id: "review-4-co-giao", word: "cô giáo", speakText: "cô giáo", emoji: "👩‍🏫", color: "pink" },
      { id: "review-4-trai-tim", word: "trái tim", speakText: "trái tim", emoji: "❤️", color: "orange" },
      { id: "review-4-bon", word: "bốn", speakText: "bốn", emoji: "4️⃣", color: "purple" },
    ],
  },
];

export const bubbleLayout = [
  { left: "8%", top: "58%", delay: "0s", duration: "5.8s" },
  { left: "21%", top: "39%", delay: ".25s", duration: "6.2s" },
  { left: "34%", top: "61%", delay: ".1s", duration: "5.6s" },
  { left: "48%", top: "42%", delay: ".38s", duration: "6.4s" },
  { left: "62%", top: "60%", delay: ".16s", duration: "5.9s" },
  { left: "76%", top: "40%", delay: ".48s", duration: "6.1s" },
  { left: "90%", top: "57%", delay: ".2s", duration: "5.7s" },
  { left: "50%", top: "73%", delay: ".55s", duration: "6.6s" },
];
