export type ColorType = 'pink' | 'orange' | 'purple' | 'blue' | 'green';

export interface Tile {
  text: string;
  color: ColorType;
}

export interface Row {
  id: string;
  first: string;
  answer: string;
  result: string;
  speakText: string;
  color: ColorType;
}

export interface Lesson {
  id: string;
  title: string;
  subtitle: string;
  scoreStart: number;
  tiles: Tile[];
  rows: Row[];
  readWords: string[];
}

export const lessons: Lesson[] = [
  {
    id: 'level-1',
    title: 'Chữ B - Ghép với nguyên âm',
    subtitle: 'Bé kéo nguyên âm để ghép với chữ b nhé!',
    scoreStart: 100,
    tiles: [
      { text: 'a', color: 'pink' },
      { text: 'e', color: 'orange' },
      { text: 'ê', color: 'purple' },
      { text: 'i', color: 'blue' },
      { text: 'o', color: 'green' },
    ],
    rows: [
      { id: 'level-1-1', first: 'b', answer: 'a', result: 'ba', speakText: 'ba', color: 'pink' },
      { id: 'level-1-2', first: 'b', answer: 'e', result: 'be', speakText: 'be', color: 'orange' },
      { id: 'level-1-3', first: 'b', answer: 'ê', result: 'bê', speakText: 'bê', color: 'purple' },
      { id: 'level-1-4', first: 'b', answer: 'i', result: 'bi', speakText: 'bi', color: 'blue' },
      { id: 'level-1-5', first: 'b', answer: 'o', result: 'bo', speakText: 'bo', color: 'green' },
    ],
    readWords: ['ba', 'be', 'bê', 'bi', 'bo'],
  },
  {
    id: 'level-2',
    title: 'Chữ B - Tiếng có dấu',
    subtitle: 'Bé làm quen với các tiếng gần gũi có dấu!',
    scoreStart: 105,
    tiles: [
      { text: 'à', color: 'pink' },
      { text: 'é', color: 'orange' },
      { text: 'ố', color: 'purple' },
      { text: 'ờ', color: 'blue' },
      { text: 'ế', color: 'green' },
    ],
    rows: [
      { id: 'level-2-1', first: 'b', answer: 'à', result: 'bà', speakText: 'bà', color: 'pink' },
      { id: 'level-2-2', first: 'b', answer: 'é', result: 'bé', speakText: 'bé', color: 'orange' },
      { id: 'level-2-3', first: 'b', answer: 'ố', result: 'bố', speakText: 'bố', color: 'purple' },
      { id: 'level-2-4', first: 'b', answer: 'ờ', result: 'bờ', speakText: 'bờ', color: 'blue' },
      { id: 'level-2-5', first: 'b', answer: 'ế', result: 'bế', speakText: 'bế', color: 'green' },
    ],
    readWords: ['bà', 'bé', 'bố', 'bờ', 'bế'],
  },
  {
    id: 'level-3',
    title: 'Chữ C - Ghép với nguyên âm',
    subtitle: 'Bé ghép chữ c với các nguyên âm quen thuộc!',
    scoreStart: 110,
    tiles: [
      { text: 'a', color: 'pink' },
      { text: 'o', color: 'orange' },
      { text: 'ô', color: 'purple' },
      { text: 'ơ', color: 'blue' },
      { text: 'ua', color: 'green' },
    ],
    rows: [
      { id: 'level-3-1', first: 'c', answer: 'a', result: 'ca', speakText: 'ca', color: 'pink' },
      { id: 'level-3-2', first: 'c', answer: 'o', result: 'co', speakText: 'co', color: 'orange' },
      { id: 'level-3-3', first: 'c', answer: 'ô', result: 'cô', speakText: 'cô', color: 'purple' },
      { id: 'level-3-4', first: 'c', answer: 'ơ', result: 'cơ', speakText: 'cơ', color: 'blue' },
      { id: 'level-3-5', first: 'c', answer: 'ua', result: 'cua', speakText: 'cua', color: 'green' },
    ],
    readWords: ['ca', 'co', 'cô', 'cơ', 'cua'],
  },
  {
    id: 'level-4',
    title: 'Chữ D, Đ',
    subtitle: 'Bé phân biệt d và đ khi ghép tiếng!',
    scoreStart: 115,
    tiles: [
      { text: 'a', color: 'pink' },
      { text: 'e', color: 'orange' },
      { text: 'ê', color: 'purple' },
      { text: 'i', color: 'blue' },
      { text: 'ô', color: 'green' },
    ],
    rows: [
      { id: 'level-4-1', first: 'd', answer: 'a', result: 'da', speakText: 'da', color: 'pink' },
      { id: 'level-4-2', first: 'd', answer: 'e', result: 'de', speakText: 'de', color: 'orange' },
      { id: 'level-4-3', first: 'd', answer: 'ê', result: 'dê', speakText: 'dê', color: 'purple' },
      { id: 'level-4-4', first: 'đ', answer: 'i', result: 'đi', speakText: 'đi', color: 'blue' },
      { id: 'level-4-5', first: 'đ', answer: 'ô', result: 'đô', speakText: 'đô', color: 'green' },
    ],
    readWords: ['da', 'de', 'dê', 'đi', 'đô'],
  },
  {
    id: 'level-5',
    title: 'Chữ G, GH',
    subtitle: 'Bé chú ý: gh thường đi với e, ê, i!',
    scoreStart: 120,
    tiles: [
      { text: 'a', color: 'pink' },
      { text: 'à', color: 'orange' },
      { text: 'ỗ', color: 'purple' },
      { text: 'e', color: 'blue' },
      { text: 'ế', color: 'green' },
    ],
    rows: [
      { id: 'level-5-1', first: 'g', answer: 'a', result: 'ga', speakText: 'ga', color: 'pink' },
      { id: 'level-5-2', first: 'g', answer: 'à', result: 'gà', speakText: 'gà', color: 'orange' },
      { id: 'level-5-3', first: 'g', answer: 'ỗ', result: 'gỗ', speakText: 'gỗ', color: 'purple' },
      { id: 'level-5-4', first: 'gh', answer: 'e', result: 'ghe', speakText: 'ghe', color: 'blue' },
      { id: 'level-5-5', first: 'gh', answer: 'ế', result: 'ghế', speakText: 'ghế', color: 'green' },
    ],
    readWords: ['ga', 'gà', 'gỗ', 'ghe', 'ghế'],
  },
  {
    id: 'level-6',
    title: 'Chữ H',
    subtitle: 'Ghép chữ h với các vần dễ đọc!',
    scoreStart: 125,
    tiles: [
      { text: 'a', color: 'pink' },
      { text: 'e', color: 'orange' },
      { text: 'è', color: 'purple' },
      { text: 'oa', color: 'blue' },
      { text: 'ươu', color: 'green' },
    ],
    rows: [
      { id: 'level-6-1', first: 'h', answer: 'a', result: 'ha', speakText: 'ha', color: 'pink' },
      { id: 'level-6-2', first: 'h', answer: 'e', result: 'he', speakText: 'he', color: 'orange' },
      { id: 'level-6-3', first: 'h', answer: 'è', result: 'hè', speakText: 'hè', color: 'purple' },
      { id: 'level-6-4', first: 'h', answer: 'oa', result: 'hoa', speakText: 'hoa', color: 'blue' },
      { id: 'level-6-5', first: 'h', answer: 'ươu', result: 'hươu', speakText: 'hươu', color: 'green' },
    ],
    readWords: ['ha', 'he', 'hè', 'hoa', 'hươu'],
  },
  {
    id: 'level-7',
    title: 'Chữ K, L',
    subtitle: 'Ghép k, l với nguyên âm đơn!',
    scoreStart: 130,
    tiles: [
      { text: 'e', color: 'pink' },
      { text: 'ê', color: 'orange' },
      { text: 'i', color: 'purple' },
      { text: 'á', color: 'blue' },
      { text: 'a', color: 'green' },
    ],
    rows: [
      { id: 'level-7-1', first: 'k', answer: 'e', result: 'ke', speakText: 'ke', color: 'pink' },
      { id: 'level-7-2', first: 'k', answer: 'ê', result: 'kê', speakText: 'kê', color: 'orange' },
      { id: 'level-7-3', first: 'k', answer: 'i', result: 'ki', speakText: 'ki', color: 'purple' },
      { id: 'level-7-4', first: 'l', answer: 'á', result: 'lá', speakText: 'lá', color: 'blue' },
      { id: 'level-7-5', first: 'l', answer: 'a', result: 'la', speakText: 'la', color: 'green' },
    ],
    readWords: ['ke', 'kê', 'ki', 'lá', 'la'],
  },
  {
    id: 'level-8',
    title: 'Chữ M, N',
    subtitle: 'Bé ghép m, n với tiếng quen thuộc!',
    scoreStart: 135,
    tiles: [
      { text: 'e', color: 'pink' },
      { text: 'ẹ', color: 'orange' },
      { text: 'ơ', color: 'purple' },
      { text: 'a', color: 'blue' },
      { text: 'o', color: 'green' },
    ],
    rows: [
      { id: 'level-8-1', first: 'm', answer: 'e', result: 'me', speakText: 'me', color: 'pink' },
      { id: 'level-8-2', first: 'm', answer: 'ẹ', result: 'mẹ', speakText: 'mẹ', color: 'orange' },
      { id: 'level-8-3', first: 'm', answer: 'ơ', result: 'mơ', speakText: 'mơ', color: 'purple' },
      { id: 'level-8-4', first: 'n', answer: 'a', result: 'na', speakText: 'na', color: 'blue' },
      { id: 'level-8-5', first: 'n', answer: 'ơ', result: 'nơ', speakText: 'nơ', color: 'green' },
    ],
    readWords: ['me', 'mẹ', 'mơ', 'na', 'nơ'],
  },
  {
    id: 'level-9',
    title: 'Chữ PH',
    subtitle: 'Luyện âm đầu ph với các tiếng thân quen!',
    scoreStart: 140,
    tiles: [
      { text: 'ở', color: 'pink' },
      { text: 'ố', color: 'orange' },
      { text: 'a', color: 'purple' },
      { text: 'i', color: 'blue' },
      { text: 'ím', color: 'green' },
    ],
    rows: [
      { id: 'level-9-1', first: 'ph', answer: 'ở', result: 'phở', speakText: 'phở', color: 'pink' },
      { id: 'level-9-2', first: 'ph', answer: 'ố', result: 'phố', speakText: 'phố', color: 'orange' },
      { id: 'level-9-3', first: 'ph', answer: 'a', result: 'pha', speakText: 'pha', color: 'purple' },
      { id: 'level-9-4', first: 'ph', answer: 'i', result: 'phi', speakText: 'phi', color: 'blue' },
      { id: 'level-9-5', first: 'ph', answer: 'ím', result: 'phím', speakText: 'phím', color: 'green' },
    ],
    readWords: ['phở', 'phố', 'pha', 'phi', 'phím'],
  },
  {
    id: 'level-10',
    title: 'Chữ T, TH',
    subtitle: 'Bé ghép t và th để đọc tiếng!',
    scoreStart: 145,
    tiles: [
      { text: 'a', color: 'pink' },
      { text: 'o', color: 'orange' },
      { text: 'ô', color: 'purple' },
      { text: 'ỏ', color: 'blue' },
      { text: 'ơ', color: 'green' },
    ],
    rows: [
      { id: 'level-10-1', first: 't', answer: 'a', result: 'ta', speakText: 'ta', color: 'pink' },
      { id: 'level-10-2', first: 't', answer: 'o', result: 'to', speakText: 'to', color: 'orange' },
      { id: 'level-10-3', first: 't', answer: 'ô', result: 'tô', speakText: 'tô', color: 'purple' },
      { id: 'level-10-4', first: 'th', answer: 'ỏ', result: 'thỏ', speakText: 'thỏ', color: 'blue' },
      { id: 'level-10-5', first: 'th', answer: 'ơ', result: 'thơ', speakText: 'thơ', color: 'green' },
    ],
    readWords: ['ta', 'to', 'tô', 'thỏ', 'thơ'],
  },
  {
    id: 'level-11',
    title: 'Chữ CH, TR',
    subtitle: 'Luyện các âm đầu có hai chữ cái!',
    scoreStart: 150,
    tiles: [
      { text: 'a', color: 'pink' },
      { text: 'è', color: 'orange' },
      { text: 'ở', color: 'purple' },
      { text: 'ẻ', color: 'blue' },
      { text: 'âu', color: 'green' },
    ],
    rows: [
      { id: 'level-11-1', first: 'ch', answer: 'a', result: 'cha', speakText: 'cha', color: 'pink' },
      { id: 'level-11-2', first: 'ch', answer: 'è', result: 'chè', speakText: 'chè', color: 'orange' },
      { id: 'level-11-3', first: 'ch', answer: 'ở', result: 'chở', speakText: 'chở', color: 'purple' },
      { id: 'level-11-4', first: 'tr', answer: 'ẻ', result: 'trẻ', speakText: 'trẻ', color: 'blue' },
      { id: 'level-11-5', first: 'tr', answer: 'âu', result: 'trâu', speakText: 'trâu', color: 'green' },
    ],
    readWords: ['cha', 'chè', 'chở', 'trẻ', 'trâu'],
  },
  {
    id: 'level-12',
    title: 'Chữ NH, NG, NGH',
    subtitle: 'Bé ghép các âm đầu nh, ng, ngh!',
    scoreStart: 155,
    tiles: [
      { text: 'à', color: 'pink' },
      { text: 'o', color: 'orange' },
      { text: 'e', color: 'purple' },
      { text: 'ỉ', color: 'blue' },
      { text: 'ô', color: 'green' },
    ],
    rows: [
      { id: 'level-12-1', first: 'nh', answer: 'à', result: 'nhà', speakText: 'nhà', color: 'pink' },
      { id: 'level-12-2', first: 'nh', answer: 'o', result: 'nho', speakText: 'nho', color: 'orange' },
      { id: 'level-12-3', first: 'ngh', answer: 'e', result: 'nghe', speakText: 'nghe', color: 'purple' },
      { id: 'level-12-4', first: 'ngh', answer: 'ỉ', result: 'nghỉ', speakText: 'nghỉ', color: 'blue' },
      { id: 'level-12-5', first: 'ng', answer: 'ô', result: 'ngô', speakText: 'ngô', color: 'green' },
    ],
    readWords: ['nhà', 'nho', 'nghe', 'nghỉ', 'ngô'],
  },
  {
    id: 'level-13',
    title: 'Chữ QU, R, S',
    subtitle: 'Bé nhớ: q thường đi cùng u thành qu!',
    scoreStart: 160,
    tiles: [
      { text: 'à', color: 'pink' },
      { text: 'e', color: 'orange' },
      { text: 'ê', color: 'purple' },
      { text: 'a', color: 'blue' },
      { text: 'ao', color: 'green' },
    ],
    rows: [
      { id: 'level-13-1', first: 'qu', answer: 'à', result: 'quà', speakText: 'quà', color: 'pink' },
      { id: 'level-13-2', first: 'qu', answer: 'e', result: 'que', speakText: 'que', color: 'orange' },
      { id: 'level-13-3', first: 'qu', answer: 'ê', result: 'quê', speakText: 'quê', color: 'purple' },
      { id: 'level-13-4', first: 'r', answer: 'a', result: 'ra', speakText: 'ra', color: 'blue' },
      { id: 'level-13-5', first: 's', answer: 'ao', result: 'sao', speakText: 'sao', color: 'green' },
    ],
    readWords: ['quà', 'que', 'quê', 'ra', 'sao'],
  },
  {
    id: 'level-14',
    title: 'Chữ V, X',
    subtitle: 'Ghép v và x với tiếng dễ đọc!',
    scoreStart: 165,
    tiles: [
      { text: 'a', color: 'pink' },
      { text: 'ề', color: 'orange' },
      { text: 'ở', color: 'purple' },
      { text: 'e', color: 'blue' },
      { text: 'ôi', color: 'green' },
    ],
    rows: [
      { id: 'level-14-1', first: 'v', answer: 'a', result: 'va', speakText: 'va', color: 'pink' },
      { id: 'level-14-2', first: 'v', answer: 'ề', result: 'về', speakText: 'về', color: 'orange' },
      { id: 'level-14-3', first: 'v', answer: 'ở', result: 'vở', speakText: 'vở', color: 'purple' },
      { id: 'level-14-4', first: 'x', answer: 'e', result: 'xe', speakText: 'xe', color: 'blue' },
      { id: 'level-14-5', first: 'x', answer: 'ôi', result: 'xôi', speakText: 'xôi', color: 'green' },
    ],
    readWords: ['va', 'về', 'vở', 'xe', 'xôi'],
  },
  {
    id: 'level-15',
    title: 'Gia đình thân yêu',
    subtitle: 'Ghép tiếng về người thân trong gia đình!',
    scoreStart: 170,
    tiles: [
      { text: 'à', color: 'pink' },
      { text: 'ố', color: 'orange' },
      { text: 'ẹ', color: 'purple' },
      { text: 'é', color: 'blue' },
      { text: 'ô', color: 'green' },
    ],
    rows: [
      { id: 'level-15-1', first: 'b', answer: 'à', result: 'bà', speakText: 'bà', color: 'pink' },
      { id: 'level-15-2', first: 'b', answer: 'ố', result: 'bố', speakText: 'bố', color: 'orange' },
      { id: 'level-15-3', first: 'm', answer: 'ẹ', result: 'mẹ', speakText: 'mẹ', color: 'purple' },
      { id: 'level-15-4', first: 'b', answer: 'é', result: 'bé', speakText: 'bé', color: 'blue' },
      { id: 'level-15-5', first: 'c', answer: 'ô', result: 'cô', speakText: 'cô', color: 'green' },
    ],
    readWords: ['bà', 'bố', 'mẹ', 'bé', 'cô'],
  },
  {
    id: 'level-16',
    title: 'Con vật đáng yêu 1',
    subtitle: 'Bé ghép tiếng tên con vật quen thuộc!',
    scoreStart: 175,
    tiles: [
      { text: 'á', color: 'pink' },
      { text: 'à', color: 'orange' },
      { text: 'ò', color: 'purple' },
      { text: 'èo', color: 'blue' },
      { text: 'ỏ', color: 'green' },
    ],
    rows: [
      { id: 'level-16-1', first: 'c', answer: 'á', result: 'cá', speakText: 'cá', color: 'pink' },
      { id: 'level-16-2', first: 'g', answer: 'à', result: 'gà', speakText: 'gà', color: 'orange' },
      { id: 'level-16-3', first: 'b', answer: 'ò', result: 'bò', speakText: 'bò', color: 'purple' },
      { id: 'level-16-4', first: 'm', answer: 'èo', result: 'mèo', speakText: 'mèo', color: 'blue' },
      { id: 'level-16-5', first: 'th', answer: 'ỏ', result: 'thỏ', speakText: 'thỏ', color: 'green' },
    ],
    readWords: ['cá', 'gà', 'bò', 'mèo', 'thỏ'],
  },
  {
    id: 'level-17',
    title: 'Con vật đáng yêu 2',
    subtitle: 'Bé đọc thêm tên các con vật hiền lành!',
    scoreStart: 180,
    tiles: [
      { text: 'ươu', color: 'pink' },
      { text: 'oi', color: 'orange' },
      { text: 'ai', color: 'purple' },
      { text: 'óc', color: 'blue' },
      { text: 'ừu', color: 'green' },
    ],
    rows: [
      { id: 'level-17-1', first: 'h', answer: 'ươu', result: 'hươu', speakText: 'hươu', color: 'pink' },
      { id: 'level-17-2', first: 'v', answer: 'oi', result: 'voi', speakText: 'voi', color: 'orange' },
      { id: 'level-17-3', first: 'n', answer: 'ai', result: 'nai', speakText: 'nai', color: 'purple' },
      { id: 'level-17-4', first: 's', answer: 'óc', result: 'sóc', speakText: 'sóc', color: 'blue' },
      { id: 'level-17-5', first: 'c', answer: 'ừu', result: 'cừu', speakText: 'cừu', color: 'green' },
    ],
    readWords: ['hươu', 'voi', 'nai', 'sóc', 'cừu'],
  },
  {
    id: 'level-18',
    title: 'Đồ dùng học tập',
    subtitle: 'Bé ghép tiếng về lớp học và đồ dùng!',
    scoreStart: 185,
    tiles: [
      { text: 'àn', color: 'pink' },
      { text: 'út', color: 'orange' },
      { text: 'ách', color: 'purple' },
      { text: 'ở', color: 'blue' },
      { text: 'ặp', color: 'green' },
    ],
    rows: [
      { id: 'level-18-1', first: 'b', answer: 'àn', result: 'bàn', speakText: 'bàn', color: 'pink' },
      { id: 'level-18-2', first: 'b', answer: 'út', result: 'bút', speakText: 'bút', color: 'orange' },
      { id: 'level-18-3', first: 's', answer: 'ách', result: 'sách', speakText: 'sách', color: 'purple' },
      { id: 'level-18-4', first: 'v', answer: 'ở', result: 'vở', speakText: 'vở', color: 'blue' },
      { id: 'level-18-5', first: 'c', answer: 'ặp', result: 'cặp', speakText: 'cặp', color: 'green' },
    ],
    readWords: ['bàn', 'bút', 'sách', 'vở', 'cặp'],
  },
  {
    id: 'level-19',
    title: 'Trang phục của bé',
    subtitle: 'Bé đọc tên đồ dùng mặc hằng ngày!',
    scoreStart: 190,
    tiles: [
      { text: 'ũ', color: 'pink' },
      { text: 'ơ', color: 'orange' },
      { text: 'ất', color: 'purple' },
      { text: 'áy', color: 'blue' },
      { text: 'ón', color: 'green' },
    ],
    rows: [
      { id: 'level-19-1', first: 'm', answer: 'ũ', result: 'mũ', speakText: 'mũ', color: 'pink' },
      { id: 'level-19-2', first: 'n', answer: 'ơ', result: 'nơ', speakText: 'nơ', color: 'orange' },
      { id: 'level-19-3', first: 't', answer: 'ất', result: 'tất', speakText: 'tất', color: 'purple' },
      { id: 'level-19-4', first: 'v', answer: 'áy', result: 'váy', speakText: 'váy', color: 'blue' },
      { id: 'level-19-5', first: 'n', answer: 'ón', result: 'nón', speakText: 'nón', color: 'green' },
    ],
    readWords: ['mũ', 'nơ', 'tất', 'váy', 'nón'],
  },
  {
    id: 'level-20',
    title: 'Ngôi nhà của bé',
    subtitle: 'Ghép tiếng về những đồ vật trong nhà!',
    scoreStart: 195,
    tiles: [
      { text: 'à', color: 'pink' },
      { text: 'ửa', color: 'orange' },
      { text: 'ếp', color: 'purple' },
      { text: 'èn', color: 'blue' },
      { text: 'ế', color: 'green' },
    ],
    rows: [
      { id: 'level-20-1', first: 'nh', answer: 'à', result: 'nhà', speakText: 'nhà', color: 'pink' },
      { id: 'level-20-2', first: 'c', answer: 'ửa', result: 'cửa', speakText: 'cửa', color: 'orange' },
      { id: 'level-20-3', first: 'b', answer: 'ếp', result: 'bếp', speakText: 'bếp', color: 'purple' },
      { id: 'level-20-4', first: 'đ', answer: 'èn', result: 'đèn', speakText: 'đèn', color: 'blue' },
      { id: 'level-20-5', first: 'gh', answer: 'ế', result: 'ghế', speakText: 'ghế', color: 'green' },
    ],
    readWords: ['nhà', 'cửa', 'bếp', 'đèn', 'ghế'],
  },
  {
    id: 'level-21',
    title: 'Món ăn quen thuộc',
    subtitle: 'Bé đọc tên các món ăn gần gũi!',
    scoreStart: 200,
    tiles: [
      { text: 'ơm', color: 'pink' },
      { text: 'á', color: 'orange' },
      { text: 'au', color: 'purple' },
      { text: 'em', color: 'blue' },
      { text: 'ẹo', color: 'green' },
    ],
    rows: [
      { id: 'level-21-1', first: 'c', answer: 'ơm', result: 'cơm', speakText: 'cơm', color: 'pink' },
      { id: 'level-21-2', first: 'c', answer: 'á', result: 'cá', speakText: 'cá', color: 'orange' },
      { id: 'level-21-3', first: 'r', answer: 'au', result: 'rau', speakText: 'rau', color: 'purple' },
      { id: 'level-21-4', first: 'k', answer: 'em', result: 'kem', speakText: 'kem', color: 'blue' },
      { id: 'level-21-5', first: 'k', answer: 'ẹo', result: 'kẹo', speakText: 'kẹo', color: 'green' },
    ],
    readWords: ['cơm', 'cá', 'rau', 'kem', 'kẹo'],
  },
  {
    id: 'level-22',
    title: 'Trái cây quen thuộc',
    subtitle: 'Bé đọc tên các loại quả gần gũi!',
    scoreStart: 205,
    tiles: [
      { text: 'a', color: 'pink' },
      { text: 'ho', color: 'orange' },
      { text: 'am', color: 'purple' },
      { text: 'áo', color: 'blue' },
      { text: 'âu', color: 'green' },
    ],
    rows: [
      { id: 'level-22-1', first: 'n', answer: 'a', result: 'na', speakText: 'na', color: 'pink' },
      { id: 'level-22-2', first: 'n', answer: 'ho', result: 'nho', speakText: 'nho', color: 'orange' },
      { id: 'level-22-3', first: 'c', answer: 'am', result: 'cam', speakText: 'cam', color: 'purple' },
      { id: 'level-22-4', first: 't', answer: 'áo', result: 'táo', speakText: 'táo', color: 'blue' },
      { id: 'level-22-5', first: 'd', answer: 'âu', result: 'dâu', speakText: 'dâu', color: 'green' },
    ],
    readWords: ['na', 'nho', 'cam', 'táo', 'dâu'],
  },
  {
    id: 'level-23',
    title: 'Thiên nhiên quanh bé',
    subtitle: 'Ghép tiếng về hoa lá, mây trời!',
    scoreStart: 210,
    tiles: [
      { text: 'oa', color: 'pink' },
      { text: 'á', color: 'orange' },
      { text: 'ây', color: 'purple' },
      { text: 'úi', color: 'blue' },
      { text: 'uối', color: 'green' },
    ],
    rows: [
      { id: 'level-23-1', first: 'h', answer: 'oa', result: 'hoa', speakText: 'hoa', color: 'pink' },
      { id: 'level-23-2', first: 'l', answer: 'á', result: 'lá', speakText: 'lá', color: 'orange' },
      { id: 'level-23-3', first: 'm', answer: 'ây', result: 'mây', speakText: 'mây', color: 'purple' },
      { id: 'level-23-4', first: 'n', answer: 'úi', result: 'núi', speakText: 'núi', color: 'blue' },
      { id: 'level-23-5', first: 's', answer: 'uối', result: 'suối', speakText: 'suối', color: 'green' },
    ],
    readWords: ['hoa', 'lá', 'mây', 'núi', 'suối'],
  },
  {
    id: 'level-24',
    title: 'Màu sắc',
    subtitle: 'Bé ghép tiếng chỉ màu sắc!',
    scoreStart: 215,
    tiles: [
      { text: 'ỏ', color: 'pink' },
      { text: 'àng', color: 'orange' },
      { text: 'anh', color: 'purple' },
      { text: 'ím', color: 'blue' },
      { text: 'âu', color: 'green' },
    ],
    rows: [
      { id: 'level-24-1', first: 'đ', answer: 'ỏ', result: 'đỏ', speakText: 'đỏ', color: 'pink' },
      { id: 'level-24-2', first: 'v', answer: 'àng', result: 'vàng', speakText: 'vàng', color: 'orange' },
      { id: 'level-24-3', first: 'x', answer: 'anh', result: 'xanh', speakText: 'xanh', color: 'purple' },
      { id: 'level-24-4', first: 't', answer: 'ím', result: 'tím', speakText: 'tím', color: 'blue' },
      { id: 'level-24-5', first: 'n', answer: 'âu', result: 'nâu', speakText: 'nâu', color: 'green' },
    ],
    readWords: ['đỏ', 'vàng', 'xanh', 'tím', 'nâu'],
  },
  {
    id: 'level-25',
    title: 'Số đếm đơn giản',
    subtitle: 'Bé đọc các số quen thuộc!',
    scoreStart: 220,
    tiles: [
      { text: 'ột', color: 'pink' },
      { text: 'ai', color: 'orange' },
      { text: 'a', color: 'purple' },
      { text: 'ốn', color: 'blue' },
      { text: 'ăm', color: 'green' },
    ],
    rows: [
      { id: 'level-25-1', first: 'm', answer: 'ột', result: 'một', speakText: 'một', color: 'pink' },
      { id: 'level-25-2', first: 'h', answer: 'ai', result: 'hai', speakText: 'hai', color: 'orange' },
      { id: 'level-25-3', first: 'b', answer: 'a', result: 'ba', speakText: 'ba', color: 'purple' },
      { id: 'level-25-4', first: 'b', answer: 'ốn', result: 'bốn', speakText: 'bốn', color: 'blue' },
      { id: 'level-25-5', first: 'n', answer: 'ăm', result: 'năm', speakText: 'năm', color: 'green' },
    ],
    readWords: ['một', 'hai', 'ba', 'bốn', 'năm'],
  },
  {
    id: 'level-26',
    title: 'Hoạt động vui',
    subtitle: 'Bé ghép tiếng chỉ hoạt động tích cực!',
    scoreStart: 225,
    tiles: [
      { text: 'ọc', color: 'pink' },
      { text: 'ẽ', color: 'orange' },
      { text: 'ô', color: 'purple' },
      { text: 'ếm', color: 'blue' },
      { text: 'át', color: 'green' },
    ],
    rows: [
      { id: 'level-26-1', first: 'đ', answer: 'ọc', result: 'đọc', speakText: 'đọc', color: 'pink' },
      { id: 'level-26-2', first: 'v', answer: 'ẽ', result: 'vẽ', speakText: 'vẽ', color: 'orange' },
      { id: 'level-26-3', first: 't', answer: 'ô', result: 'tô', speakText: 'tô', color: 'purple' },
      { id: 'level-26-4', first: 'đ', answer: 'ếm', result: 'đếm', speakText: 'đếm', color: 'blue' },
      { id: 'level-26-5', first: 'h', answer: 'át', result: 'hát', speakText: 'hát', color: 'green' },
    ],
    readWords: ['đọc', 'vẽ', 'tô', 'đếm', 'hát'],
  },
  {
    id: 'level-27',
    title: 'Cơ thể của bé',
    subtitle: 'Bé đọc các tiếng chỉ bộ phận quen thuộc!',
    scoreStart: 230,
    tiles: [
      { text: 'ay', color: 'pink' },
      { text: 'ai', color: 'orange' },
      { text: 'ắt', color: 'purple' },
      { text: 'ũi', color: 'blue' },
      { text: 'óc', color: 'green' },
    ],
    rows: [
      { id: 'level-27-1', first: 't', answer: 'ay', result: 'tay', speakText: 'tay', color: 'pink' },
      { id: 'level-27-2', first: 't', answer: 'ai', result: 'tai', speakText: 'tai', color: 'orange' },
      { id: 'level-27-3', first: 'm', answer: 'ắt', result: 'mắt', speakText: 'mắt', color: 'purple' },
      { id: 'level-27-4', first: 'm', answer: 'ũi', result: 'mũi', speakText: 'mũi', color: 'blue' },
      { id: 'level-27-5', first: 't', answer: 'óc', result: 'tóc', speakText: 'tóc', color: 'green' },
    ],
    readWords: ['tay', 'tai', 'mắt', 'mũi', 'tóc'],
  },
  {
    id: 'level-28',
    title: 'Cảm xúc tích cực',
    subtitle: 'Bé đọc các tiếng vui vẻ, thân thiện!',
    scoreStart: 235,
    tiles: [
      { text: 'ui', color: 'pink' },
      { text: 'ười', color: 'orange' },
      { text: 'êu', color: 'purple' },
      { text: 'ến', color: 'blue' },
      { text: 'oan', color: 'green' },
    ],
    rows: [
      { id: 'level-28-1', first: 'v', answer: 'ui', result: 'vui', speakText: 'vui', color: 'pink' },
      { id: 'level-28-2', first: 'c', answer: 'ười', result: 'cười', speakText: 'cười', color: 'orange' },
      { id: 'level-28-3', first: 'y', answer: 'êu', result: 'yêu', speakText: 'yêu', color: 'purple' },
      { id: 'level-28-4', first: 'm', answer: 'ến', result: 'mến', speakText: 'mến', color: 'blue' },
      { id: 'level-28-5', first: 'ng', answer: 'oan', result: 'ngoan', speakText: 'ngoan', color: 'green' },
    ],
    readWords: ['vui', 'cười', 'yêu', 'mến', 'ngoan'],
  },
  {
    id: 'level-29',
    title: 'Vần ai, ay, ao, au, eo',
    subtitle: 'Bé ghép âm đầu với vần đôi!',
    scoreStart: 240,
    tiles: [
      { text: 'ai', color: 'pink' },
      { text: 'ay', color: 'orange' },
      { text: 'ao', color: 'purple' },
      { text: 'au', color: 'blue' },
      { text: 'èo', color: 'green' },
    ],
    rows: [
      { id: 'level-29-1', first: 't', answer: 'ai', result: 'tai', speakText: 'tai', color: 'pink' },
      { id: 'level-29-2', first: 't', answer: 'ay', result: 'tay', speakText: 'tay', color: 'orange' },
      { id: 'level-29-3', first: 's', answer: 'ao', result: 'sao', speakText: 'sao', color: 'purple' },
      { id: 'level-29-4', first: 'r', answer: 'au', result: 'rau', speakText: 'rau', color: 'blue' },
      { id: 'level-29-5', first: 'm', answer: 'èo', result: 'mèo', speakText: 'mèo', color: 'green' },
    ],
    readWords: ['tai', 'tay', 'sao', 'rau', 'mèo'],
  },
  {
    id: 'level-30',
    title: 'Vần iêu, êu, ưu, ươu, ừu',
    subtitle: 'Luyện các vần dài hơn một chút!',
    scoreStart: 245,
    tiles: [
      { text: 'iều', color: 'pink' },
      { text: 'êu', color: 'orange' },
      { text: 'ưu', color: 'purple' },
      { text: 'ươu', color: 'blue' },
      { text: 'ừu', color: 'green' },
    ],
    rows: [
      { id: 'level-30-1', first: 'd', answer: 'iều', result: 'diều', speakText: 'diều', color: 'pink' },
      { id: 'level-30-2', first: 'n', answer: 'êu', result: 'nêu', speakText: 'nêu', color: 'orange' },
      { id: 'level-30-3', first: 'l', answer: 'ưu', result: 'lưu', speakText: 'lưu', color: 'purple' },
      { id: 'level-30-4', first: 'h', answer: 'ươu', result: 'hươu', speakText: 'hươu', color: 'blue' },
      { id: 'level-30-5', first: 'c', answer: 'ừu', result: 'cừu', speakText: 'cừu', color: 'green' },
    ],
    readWords: ['diều', 'nêu', 'lưu', 'hươu', 'cừu'],
  },
  {
    id: 'level-31',
    title: 'Vần ia, ưa, ua, ươ, uôi',
    subtitle: 'Bé đọc các vần có nhiều chữ cái!',
    scoreStart: 250,
    tiles: [
      { text: 'ia', color: 'pink' },
      { text: 'ưa', color: 'orange' },
      { text: 'ua', color: 'purple' },
      { text: 'ửa', color: 'blue' },
      { text: 'uối', color: 'green' },
    ],
    rows: [
      { id: 'level-31-1', first: 'k', answer: 'ia', result: 'kia', speakText: 'kia', color: 'pink' },
      { id: 'level-31-2', first: 'm', answer: 'ưa', result: 'mưa', speakText: 'mưa', color: 'orange' },
      { id: 'level-31-3', first: 'c', answer: 'ua', result: 'cua', speakText: 'cua', color: 'purple' },
      { id: 'level-31-4', first: 'c', answer: 'ửa', result: 'cửa', speakText: 'cửa', color: 'blue' },
      { id: 'level-31-5', first: 'ch', answer: 'uối', result: 'chuối', speakText: 'chuối', color: 'green' },
    ],
    readWords: ['kia', 'mưa', 'cua', 'cửa', 'chuối'],
  },
  {
    id: 'level-32',
    title: 'Vần oi, ôi, ơi, ui, ưi',
    subtitle: 'Bé luyện đọc các vần tròn môi!',
    scoreStart: 255,
    tiles: [
      { text: 'oi', color: 'pink' },
      { text: 'ôi', color: 'orange' },
      { text: 'ơi', color: 'purple' },
      { text: 'ui', color: 'blue' },
      { text: 'ửi', color: 'green' },
    ],
    rows: [
      { id: 'level-32-1', first: 'v', answer: 'oi', result: 'voi', speakText: 'voi', color: 'pink' },
      { id: 'level-32-2', first: 'x', answer: 'ôi', result: 'xôi', speakText: 'xôi', color: 'orange' },
      { id: 'level-32-3', first: 'ch', answer: 'ơi', result: 'chơi', speakText: 'chơi', color: 'purple' },
      { id: 'level-32-4', first: 'v', answer: 'ui', result: 'vui', speakText: 'vui', color: 'blue' },
      { id: 'level-32-5', first: 'g', answer: 'ửi', result: 'gửi', speakText: 'gửi', color: 'green' },
    ],
    readWords: ['voi', 'xôi', 'chơi', 'vui', 'gửi'],
  },
  {
    id: 'level-33',
    title: 'Vần an, ang, anh',
    subtitle: 'Bé ghép vần có âm cuối n, ng, nh!',
    scoreStart: 260,
    tiles: [
      { text: 'an', color: 'pink' },
      { text: 'àn', color: 'orange' },
      { text: 'ạn', color: 'purple' },
      { text: 'àng', color: 'blue' },
      { text: 'anh', color: 'green' },
    ],
    rows: [
      { id: 'level-33-1', first: 'l', answer: 'an', result: 'lan', speakText: 'lan', color: 'pink' },
      { id: 'level-33-2', first: 'b', answer: 'àn', result: 'bàn', speakText: 'bàn', color: 'orange' },
      { id: 'level-33-3', first: 'b', answer: 'ạn', result: 'bạn', speakText: 'bạn', color: 'purple' },
      { id: 'level-33-4', first: 'v', answer: 'àng', result: 'vàng', speakText: 'vàng', color: 'blue' },
      { id: 'level-33-5', first: 'x', answer: 'anh', result: 'xanh', speakText: 'xanh', color: 'green' },
    ],
    readWords: ['lan', 'bàn', 'bạn', 'vàng', 'xanh'],
  },
  {
    id: 'level-34',
    title: 'Vần at, ăt, ât',
    subtitle: 'Bé ghép vần và đọc tiếng thật rõ!',
    scoreStart: 265,
    tiles: [
      { text: 'át', color: 'pink' },
      { text: 'ắt', color: 'orange' },
      { text: 'ất', color: 'purple' },
      { text: 'ặt', color: 'blue' },
      { text: 'ột', color: 'green' },
    ],
    rows: [
      { id: 'level-34-1', first: 'c', answer: 'át', result: 'cát', speakText: 'cát', color: 'pink' },
      { id: 'level-34-2', first: 'm', answer: 'ắt', result: 'mắt', speakText: 'mắt', color: 'orange' },
      { id: 'level-34-3', first: 'đ', answer: 'ất', result: 'đất', speakText: 'đất', color: 'purple' },
      { id: 'level-34-4', first: 't', answer: 'ất', result: 'tất', speakText: 'tất', color: 'blue' },
      { id: 'level-34-5', first: 'm', answer: 'ặt', result: 'mặt', speakText: 'mặt', color: 'green' },
    ],
    readWords: ['cát', 'mắt', 'đất', 'tất', 'mặt'],
  },
  {
    id: 'level-35',
    title: 'Vần ac, ach',
    subtitle: 'Bé đọc các tiếng có âm cuối c, ch!',
    scoreStart: 270,
    tiles: [
      { text: 'ác', color: 'pink' },
      { text: 'ách', color: 'orange' },
      { text: 'ạch', color: 'purple' },
      { text: 'ạc', color: 'blue' },
      { text: 'an', color: 'green' },
    ],
    rows: [
      { id: 'level-35-1', first: 'b', answer: 'ác', result: 'bác', speakText: 'bác', color: 'pink' },
      { id: 'level-35-2', first: 's', answer: 'ách', result: 'sách', speakText: 'sách', color: 'orange' },
      { id: 'level-35-3', first: 'g', answer: 'ạch', result: 'gạch', speakText: 'gạch', color: 'purple' },
      { id: 'level-35-4', first: 'nh', answer: 'ạc', result: 'nhạc', speakText: 'nhạc', color: 'blue' },
      { id: 'level-35-5', first: 'l', answer: 'ạc', result: 'lạc', speakText: 'lạc', color: 'green' },
    ],
    readWords: ['bác', 'sách', 'gạch', 'nhạc', 'lạc'],
  },
  {
    id: 'level-36',
    title: 'Vần am, ăm, âm',
    subtitle: 'Bé đọc các tiếng có âm cuối m!',
    scoreStart: 275,
    tiles: [
      { text: 'am', color: 'pink' },
      { text: 'ăm', color: 'orange' },
      { text: 'âm', color: 'purple' },
      { text: 'ấm', color: 'blue' },
      { text: 'om', color: 'green' },
    ],
    rows: [
      { id: 'level-36-1', first: 'c', answer: 'am', result: 'cam', speakText: 'cam', color: 'pink' },
      { id: 'level-36-2', first: 'n', answer: 'ăm', result: 'năm', speakText: 'năm', color: 'orange' },
      { id: 'level-36-3', first: 'm', answer: 'âm', result: 'mâm', speakText: 'mâm', color: 'purple' },
      { id: 'level-36-4', first: 't', answer: 'ấm', result: 'tấm', speakText: 'tấm', color: 'blue' },
      { id: 'level-36-5', first: 'n', answer: 'ấm', result: 'nấm', speakText: 'nấm', color: 'green' },
    ],
    readWords: ['cam', 'năm', 'mâm', 'tấm', 'nấm'],
  },
  {
    id: 'level-37',
    title: 'Vần ap, ăp, âp, op, ôp',
    subtitle: 'Luyện đọc tiếng có âm cuối p!',
    scoreStart: 280,
    tiles: [
      { text: 'ặp', color: 'pink' },
      { text: 'ắp', color: 'orange' },
      { text: 'ập', color: 'purple' },
      { text: 'ộp', color: 'blue' },
      { text: 'ớp', color: 'green' },
    ],
    rows: [
      { id: 'level-37-1', first: 'c', answer: 'ặp', result: 'cặp', speakText: 'cặp', color: 'pink' },
      { id: 'level-37-2', first: 'n', answer: 'ắp', result: 'nắp', speakText: 'nắp', color: 'orange' },
      { id: 'level-37-3', first: 't', answer: 'ập', result: 'tập', speakText: 'tập', color: 'purple' },
      { id: 'level-37-4', first: 'h', answer: 'ộp', result: 'hộp', speakText: 'hộp', color: 'blue' },
      { id: 'level-37-5', first: 'l', answer: 'ớp', result: 'lớp', speakText: 'lớp', color: 'green' },
    ],
    readWords: ['cặp', 'nắp', 'tập', 'hộp', 'lớp'],
  },
  {
    id: 'level-38',
    title: 'Vần en, em, êm, ên, ênh',
    subtitle: 'Bé đọc các tiếng có vần e, ê!',
    scoreStart: 285,
    tiles: [
      { text: 'en', color: 'pink' },
      { text: 'em', color: 'orange' },
      { text: 'êm', color: 'purple' },
      { text: 'ến', color: 'blue' },
      { text: 'ênh', color: 'green' },
    ],
    rows: [
      { id: 'level-38-1', first: 's', answer: 'en', result: 'sen', speakText: 'sen', color: 'pink' },
      { id: 'level-38-2', first: 'k', answer: 'em', result: 'kem', speakText: 'kem', color: 'orange' },
      { id: 'level-38-3', first: 'đ', answer: 'êm', result: 'đêm', speakText: 'đêm', color: 'purple' },
      { id: 'level-38-4', first: 'b', answer: 'ến', result: 'bến', speakText: 'bến', color: 'blue' },
      { id: 'level-38-5', first: 'k', answer: 'ênh', result: 'kênh', speakText: 'kênh', color: 'green' },
    ],
    readWords: ['sen', 'kem', 'đêm', 'bến', 'kênh'],
  },
  {
    id: 'level-39',
    title: 'Vần et, êt, it, inh, im',
    subtitle: 'Bé luyện các vần ngắn, dễ đọc!',
    scoreStart: 290,
    tiles: [
      { text: 'ết', color: 'pink' },
      { text: 'iết', color: 'orange' },
      { text: 'ít', color: 'purple' },
      { text: 'inh', color: 'blue' },
      { text: 'im', color: 'green' },
    ],
    rows: [
      { id: 'level-39-1', first: 't', answer: 'ết', result: 'tết', speakText: 'tết', color: 'pink' },
      { id: 'level-39-2', first: 'v', answer: 'iết', result: 'viết', speakText: 'viết', color: 'orange' },
      { id: 'level-39-3', first: 'm', answer: 'ít', result: 'mít', speakText: 'mít', color: 'purple' },
      { id: 'level-39-4', first: 'x', answer: 'inh', result: 'xinh', speakText: 'xinh', color: 'blue' },
      { id: 'level-39-5', first: 't', answer: 'im', result: 'tim', speakText: 'tim', color: 'green' },
    ],
    readWords: ['tết', 'viết', 'mít', 'xinh', 'tim'],
  },
  {
    id: 'level-40',
    title: 'Vần on, ong, ông, ơn',
    subtitle: 'Ghép âm đầu với các vần tròn môi!',
    scoreStart: 295,
    tiles: [
      { text: 'on', color: 'pink' },
      { text: 'óng', color: 'orange' },
      { text: 'ông', color: 'purple' },
      { text: 'ốn', color: 'blue' },
      { text: 'ơn', color: 'green' },
    ],
    rows: [
      { id: 'level-40-1', first: 'c', answer: 'on', result: 'con', speakText: 'con', color: 'pink' },
      { id: 'level-40-2', first: 'b', answer: 'óng', result: 'bóng', speakText: 'bóng', color: 'orange' },
      { id: 'level-40-3', first: 's', answer: 'ông', result: 'sông', speakText: 'sông', color: 'purple' },
      { id: 'level-40-4', first: 'b', answer: 'ốn', result: 'bốn', speakText: 'bốn', color: 'blue' },
      { id: 'level-40-5', first: 's', answer: 'ơn', result: 'sơn', speakText: 'sơn', color: 'green' },
    ],
    readWords: ['con', 'bóng', 'sông', 'bốn', 'sơn'],
  },
  {
    id: 'level-41',
    title: 'Vần om, ôm, ơm',
    subtitle: 'Bé đọc tiếng về món ăn và đồ vật!',
    scoreStart: 300,
    tiles: [
      { text: 'ôm', color: 'pink' },
      { text: 'ơm', color: 'orange' },
      { text: 'em', color: 'purple' },
      { text: 'am', color: 'blue' },
      { text: 'im', color: 'green' },
    ],
    rows: [
      { id: 'level-41-1', first: 't', answer: 'ôm', result: 'tôm', speakText: 'tôm', color: 'pink' },
      { id: 'level-41-2', first: 'c', answer: 'ơm', result: 'cơm', speakText: 'cơm', color: 'orange' },
      { id: 'level-41-3', first: 'g', answer: 'ôm', result: 'gôm', speakText: 'gôm', color: 'purple' },
      { id: 'level-41-4', first: 'r', answer: 'ơm', result: 'rơm', speakText: 'rơm', color: 'blue' },
      { id: 'level-41-5', first: 'th', answer: 'ơm', result: 'thơm', speakText: 'thơm', color: 'green' },
    ],
    readWords: ['tôm', 'cơm', 'gôm', 'rơm', 'thơm'],
  },
  {
    id: 'level-42',
    title: 'Vần un, ung, ưng, uông, ương',
    subtitle: 'Luyện vần có âm cuối ng!',
    scoreStart: 305,
    tiles: [
      { text: 'ún', color: 'pink' },
      { text: 'ừng', color: 'orange' },
      { text: 'uông', color: 'purple' },
      { text: 'ương', color: 'blue' },
      { text: 'ung', color: 'green' },
    ],
    rows: [
      { id: 'level-42-1', first: 'b', answer: 'ún', result: 'bún', speakText: 'bún', color: 'pink' },
      { id: 'level-42-2', first: 'r', answer: 'ừng', result: 'rừng', speakText: 'rừng', color: 'orange' },
      { id: 'level-42-3', first: 'm', answer: 'ừng', result: 'mừng', speakText: 'mừng', color: 'purple' },
      { id: 'level-42-4', first: 'ch', answer: 'uông', result: 'chuông', speakText: 'chuông', color: 'blue' },
      { id: 'level-42-5', first: 'g', answer: 'ương', result: 'gương', speakText: 'gương', color: 'green' },
    ],
    readWords: ['bún', 'rừng', 'mừng', 'chuông', 'gương'],
  },
  {
    id: 'level-43',
    title: 'Vần oc, ôc, uc, ưc',
    subtitle: 'Bé đọc các tiếng quen thuộc ở nhà và lớp!',
    scoreStart: 310,
    tiles: [
      { text: 'ốc', color: 'pink' },
      { text: 'óc', color: 'orange' },
      { text: 'úc', color: 'purple' },
      { text: 'ục', color: 'blue' },
      { text: 'ực', color: 'green' },
    ],
    rows: [
      { id: 'level-43-1', first: 'c', answer: 'ốc', result: 'cốc', speakText: 'cốc', color: 'pink' },
      { id: 'level-43-2', first: 'g', answer: 'óc', result: 'góc', speakText: 'góc', color: 'orange' },
      { id: 'level-43-3', first: 'c', answer: 'úc', result: 'cúc', speakText: 'cúc', color: 'purple' },
      { id: 'level-43-4', first: 'b', answer: 'ục', result: 'bục', speakText: 'bục', color: 'blue' },
      { id: 'level-43-5', first: 'm', answer: 'ực', result: 'mực', speakText: 'mực', color: 'green' },
    ],
    readWords: ['cốc', 'góc', 'cúc', 'bục', 'mực'],
  },
  {
    id: 'level-44',
    title: 'Vần ich, ach',
    subtitle: 'Luyện đọc các vần có âm cuối ch!',
    scoreStart: 315,
    tiles: [
      { text: 'ách', color: 'pink' },
      { text: 'ạch', color: 'orange' },
      { text: 'ịch', color: 'purple' },
      { text: 'ích', color: 'blue' },
      { text: 'êm', color: 'green' },
    ],
    rows: [
      { id: 'level-44-1', first: 's', answer: 'ách', result: 'sách', speakText: 'sách', color: 'pink' },
      { id: 'level-44-2', first: 'g', answer: 'ạch', result: 'gạch', speakText: 'gạch', color: 'orange' },
      { id: 'level-44-3', first: 'l', answer: 'ịch', result: 'lịch', speakText: 'lịch', color: 'purple' },
      { id: 'level-44-4', first: 'th', answer: 'ích', result: 'thích', speakText: 'thích', color: 'blue' },
      { id: 'level-44-5', first: 'k', answer: 'ịch', result: 'kịch', speakText: 'kịch', color: 'green' },
    ],
    readWords: ['sách', 'gạch', 'lịch', 'thích', 'kịch'],
  },
  {
    id: 'level-45',
    title: 'Vần ong, ông, ăng, âng',
    subtitle: 'Bé đọc tiếng về thiên nhiên và lớp học!',
    scoreStart: 320,
    tiles: [
      { text: 'ông', color: 'pink' },
      { text: 'ăng', color: 'orange' },
      { text: 'ầng', color: 'purple' },
      { text: 'ân', color: 'blue' },
      { text: 'ong', color: 'green' },
    ],
    rows: [
      { id: 'level-45-1', first: 'b', answer: 'ông', result: 'bông', speakText: 'bông', color: 'pink' },
      { id: 'level-45-2', first: 'c', answer: 'ông', result: 'công', speakText: 'công', color: 'orange' },
      { id: 'level-45-3', first: 'tr', answer: 'ăng', result: 'trăng', speakText: 'trăng', color: 'purple' },
      { id: 'level-45-4', first: 't', answer: 'ầng', result: 'tầng', speakText: 'tầng', color: 'blue' },
      { id: 'level-45-5', first: 's', answer: 'ân', result: 'sân', speakText: 'sân', color: 'green' },
    ],
    readWords: ['bông', 'công', 'trăng', 'tầng', 'sân'],
  },
  {
    id: 'level-46',
    title: 'Vần oa, oe, uê, uy',
    subtitle: 'Bé luyện các vần có âm đệm!',
    scoreStart: 325,
    tiles: [
      { text: 'oa', color: 'pink' },
      { text: 'òe', color: 'orange' },
      { text: 'ê', color: 'purple' },
      { text: 'uy', color: 'blue' },
      { text: 'eo', color: 'green' },
    ],
    rows: [
      { id: 'level-46-1', first: 'h', answer: 'oa', result: 'hoa', speakText: 'hoa', color: 'pink' },
      { id: 'level-46-2', first: 'l', answer: 'oa', result: 'loa', speakText: 'loa', color: 'orange' },
      { id: 'level-46-3', first: 'x', answer: 'òe', result: 'xòe', speakText: 'xòe', color: 'purple' },
      { id: 'level-46-4', first: 'qu', answer: 'ê', result: 'quê', speakText: 'quê', color: 'blue' },
      { id: 'level-46-5', first: 'h', answer: 'uy', result: 'huy', speakText: 'huy', color: 'green' },
    ],
    readWords: ['hoa', 'loa', 'xòe', 'quê', 'huy'],
  },
  {
    id: 'level-47',
    title: 'Vần oan, oang, anh',
    subtitle: 'Bé đọc các vần dài hơn!',
    scoreStart: 330,
    tiles: [
      { text: 'oan', color: 'pink' },
      { text: 'oán', color: 'orange' },
      { text: 'oang', color: 'purple' },
      { text: 'anh', color: 'blue' },
      { text: 'uôn', color: 'green' },
    ],
    rows: [
      { id: 'level-47-1', first: 'ng', answer: 'oan', result: 'ngoan', speakText: 'ngoan', color: 'pink' },
      { id: 'level-47-2', first: 't', answer: 'oán', result: 'toán', speakText: 'toán', color: 'orange' },
      { id: 'level-47-3', first: 'x', answer: 'oan', result: 'xoan', speakText: 'xoan', color: 'purple' },
      { id: 'level-47-4', first: 'kh', answer: 'oang', result: 'khoang', speakText: 'khoang', color: 'blue' },
      { id: 'level-47-5', first: 'qu', answer: 'anh', result: 'quanh', speakText: 'quanh', color: 'green' },
    ],
    readWords: ['ngoan', 'toán', 'xoan', 'khoang', 'quanh'],
  },
  {
    id: 'level-48',
    title: 'Vần uyên, uyêt',
    subtitle: 'Bé đọc tiếng có vần nâng cao!',
    scoreStart: 335,
    tiles: [
      { text: 'uyền', color: 'pink' },
      { text: 'yển', color: 'orange' },
      { text: 'uyện', color: 'purple' },
      { text: 'uyết', color: 'blue' },
      { text: 'uyên', color: 'green' },
    ],
    rows: [
      { id: 'level-48-1', first: 'th', answer: 'uyền', result: 'thuyền', speakText: 'thuyền', color: 'pink' },
      { id: 'level-48-2', first: 'qu', answer: 'yển', result: 'quyển', speakText: 'quyển', color: 'orange' },
      { id: 'level-48-3', first: 'ch', answer: 'uyện', result: 'chuyện', speakText: 'chuyện', color: 'purple' },
      { id: 'level-48-4', first: 't', answer: 'uyết', result: 'tuyết', speakText: 'tuyết', color: 'blue' },
      { id: 'level-48-5', first: 'h', answer: 'uyền', result: 'huyền', speakText: 'huyền', color: 'green' },
    ],
    readWords: ['thuyền', 'quyển', 'chuyện', 'tuyết', 'huyền'],
  },
  {
    id: 'level-49',
    title: 'Vần iên, iêng, ươn',
    subtitle: 'Bé luyện đọc các vần dài!',
    scoreStart: 340,
    tiles: [
      { text: 'iên', color: 'pink' },
      { text: 'iển', color: 'orange' },
      { text: 'iền', color: 'purple' },
      { text: 'ườn', color: 'blue' },
      { text: 'iêng', color: 'green' },
    ],
    rows: [
      { id: 'level-49-1', first: 't', answer: 'iên', result: 'tiên', speakText: 'tiên', color: 'pink' },
      { id: 'level-49-2', first: 'b', answer: 'iển', result: 'biển', speakText: 'biển', color: 'orange' },
      { id: 'level-49-3', first: 'h', answer: 'iền', result: 'hiền', speakText: 'hiền', color: 'purple' },
      { id: 'level-49-4', first: 'v', answer: 'ườn', result: 'vườn', speakText: 'vườn', color: 'blue' },
      { id: 'level-49-5', first: 'ch', answer: 'iêng', result: 'chiêng', speakText: 'chiêng', color: 'green' },
    ],
    readWords: ['tiên', 'biển', 'hiền', 'vườn', 'chiêng'],
  },
  {
    id: 'level-50',
    title: 'Vần iêt, ươt, uôt',
    subtitle: 'Bé đọc các tiếng nâng cao hơn!',
    scoreStart: 345,
    tiles: [
      { text: 'iết', color: 'pink' },
      { text: 'ượt', color: 'orange' },
      { text: 'uột', color: 'purple' },
      { text: 'iệc', color: 'blue' },
      { text: 'ươt', color: 'green' },
    ],
    rows: [
      { id: 'level-50-1', first: 'v', answer: 'iết', result: 'viết', speakText: 'viết', color: 'pink' },
      { id: 'level-50-2', first: 'b', answer: 'iết', result: 'biết', speakText: 'biết', color: 'orange' },
      { id: 'level-50-3', first: 't', answer: 'iết', result: 'tiết', speakText: 'tiết', color: 'purple' },
      { id: 'level-50-4', first: 'tr', answer: 'ượt', result: 'trượt', speakText: 'trượt', color: 'blue' },
      { id: 'level-50-5', first: 'ch', answer: 'uột', result: 'chuột', speakText: 'chuột', color: 'green' },
    ],
    readWords: ['viết', 'biết', 'tiết', 'trượt', 'chuột'],
  },
  {
    id: 'level-51',
    title: 'Vần iêc, ươc, uôc',
    subtitle: 'Luyện các vần có nhiều chữ cái!',
    scoreStart: 350,
    tiles: [
      { text: 'iệc', color: 'pink' },
      { text: 'ược', color: 'orange' },
      { text: 'ước', color: 'purple' },
      { text: 'iếc', color: 'blue' },
      { text: 'uốc', color: 'green' },
    ],
    rows: [
      { id: 'level-51-1', first: 'v', answer: 'iệc', result: 'việc', speakText: 'việc', color: 'pink' },
      { id: 'level-51-2', first: 'đ', answer: 'ược', result: 'được', speakText: 'được', color: 'orange' },
      { id: 'level-51-3', first: 'n', answer: 'ước', result: 'nước', speakText: 'nước', color: 'purple' },
      { id: 'level-51-4', first: 'th', answer: 'ước', result: 'thước', speakText: 'thước', color: 'blue' },
      { id: 'level-51-5', first: 'ch', answer: 'iếc', result: 'chiếc', speakText: 'chiếc', color: 'green' },
    ],
    readWords: ['việc', 'được', 'nước', 'thước', 'chiếc'],
  },
  {
    id: 'level-52',
    title: 'Lớp học vui',
    subtitle: 'Bé ghép các tiếng thường gặp ở lớp!',
    scoreStart: 355,
    tiles: [
      { text: 'ớp', color: 'pink' },
      { text: 'ảng', color: 'orange' },
      { text: 'ấn', color: 'purple' },
      { text: 'uông', color: 'blue' },
      { text: 'ống', color: 'green' },
    ],
    rows: [
      { id: 'level-52-1', first: 'l', answer: 'ớp', result: 'lớp', speakText: 'lớp', color: 'pink' },
      { id: 'level-52-2', first: 'b', answer: 'ảng', result: 'bảng', speakText: 'bảng', color: 'orange' },
      { id: 'level-52-3', first: 'ph', answer: 'ấn', result: 'phấn', speakText: 'phấn', color: 'purple' },
      { id: 'level-52-4', first: 'ch', answer: 'uông', result: 'chuông', speakText: 'chuông', color: 'blue' },
      { id: 'level-52-5', first: 'tr', answer: 'ống', result: 'trống', speakText: 'trống', color: 'green' },
    ],
    readWords: ['lớp', 'bảng', 'phấn', 'chuông', 'trống'],
  },
  {
    id: 'level-53',
    title: 'Món ăn 2',
    subtitle: 'Bé đọc tên món ăn quen thuộc!',
    scoreStart: 360,
    tiles: [
      { text: 'ánh', color: 'pink' },
      { text: 'ữa', color: 'orange' },
      { text: 'áo', color: 'purple' },
      { text: 'ở', color: 'blue' },
      { text: 'ún', color: 'green' },
    ],
    rows: [
      { id: 'level-53-1', first: 'b', answer: 'ánh', result: 'bánh', speakText: 'bánh', color: 'pink' },
      { id: 'level-53-2', first: 's', answer: 'ữa', result: 'sữa', speakText: 'sữa', color: 'orange' },
      { id: 'level-53-3', first: 'ch', answer: 'áo', result: 'cháo', speakText: 'cháo', color: 'purple' },
      { id: 'level-53-4', first: 'ph', answer: 'ở', result: 'phở', speakText: 'phở', color: 'blue' },
      { id: 'level-53-5', first: 'b', answer: 'ún', result: 'bún', speakText: 'bún', color: 'green' },
    ],
    readWords: ['bánh', 'sữa', 'cháo', 'phở', 'bún'],
  },
  {
    id: 'level-54',
    title: 'Trái cây 2',
    subtitle: 'Luyện đọc thêm tên các loại quả!',
    scoreStart: 365,
    tiles: [
      { text: 'áo', color: 'pink' },
      { text: 'am', color: 'orange' },
      { text: 'âu', color: 'purple' },
      { text: 'oài', color: 'blue' },
      { text: 'uối', color: 'green' },
    ],
    rows: [
      { id: 'level-54-1', first: 't', answer: 'áo', result: 'táo', speakText: 'táo', color: 'pink' },
      { id: 'level-54-2', first: 'c', answer: 'am', result: 'cam', speakText: 'cam', color: 'orange' },
      { id: 'level-54-3', first: 'd', answer: 'âu', result: 'dâu', speakText: 'dâu', color: 'purple' },
      { id: 'level-54-4', first: 'x', answer: 'oài', result: 'xoài', speakText: 'xoài', color: 'blue' },
      { id: 'level-54-5', first: 'ch', answer: 'uối', result: 'chuối', speakText: 'chuối', color: 'green' },
    ],
    readWords: ['táo', 'cam', 'dâu', 'xoài', 'chuối'],
  },
  {
    id: 'level-55',
    title: 'Phương tiện',
    subtitle: 'Bé đọc tên các phương tiện quen thuộc!',
    scoreStart: 370,
    tiles: [
      { text: 'e', color: 'pink' },
      { text: 'àu', color: 'orange' },
      { text: 'ò', color: 'purple' },
      { text: 'uyền', color: 'blue' },
      { text: 'uýt', color: 'green' },
    ],
    rows: [
      { id: 'level-55-1', first: 'x', answer: 'e', result: 'xe', speakText: 'xe', color: 'pink' },
      { id: 'level-55-2', first: 't', answer: 'àu', result: 'tàu', speakText: 'tàu', color: 'orange' },
      { id: 'level-55-3', first: 'đ', answer: 'ò', result: 'đò', speakText: 'đò', color: 'purple' },
      { id: 'level-55-4', first: 'th', answer: 'uyền', result: 'thuyền', speakText: 'thuyền', color: 'blue' },
      { id: 'level-55-5', first: 'b', answer: 'uýt', result: 'buýt', speakText: 'buýt', color: 'green' },
    ],
    readWords: ['xe', 'tàu', 'đò', 'thuyền', 'buýt'],
  },
  {
    id: 'level-56',
    title: 'Nơi chốn quanh bé',
    subtitle: 'Bé đọc tên các nơi quen thuộc!',
    scoreStart: 375,
    tiles: [
      { text: 'ớp', color: 'pink' },
      { text: 'à', color: 'orange' },
      { text: 'ân', color: 'purple' },
      { text: 'ườn', color: 'blue' },
      { text: 'ố', color: 'green' },
    ],
    rows: [
      { id: 'level-56-1', first: 'l', answer: 'ớp', result: 'lớp', speakText: 'lớp', color: 'pink' },
      { id: 'level-56-2', first: 'nh', answer: 'à', result: 'nhà', speakText: 'nhà', color: 'orange' },
      { id: 'level-56-3', first: 's', answer: 'ân', result: 'sân', speakText: 'sân', color: 'purple' },
      { id: 'level-56-4', first: 'v', answer: 'ườn', result: 'vườn', speakText: 'vườn', color: 'blue' },
      { id: 'level-56-5', first: 'ph', answer: 'ố', result: 'phố', speakText: 'phố', color: 'green' },
    ],
    readWords: ['lớp', 'nhà', 'sân', 'vườn', 'phố'],
  },
  {
    id: 'level-57',
    title: 'Lời nói lịch sự',
    subtitle: 'Bé luyện các tiếng dùng khi giao tiếp lễ phép!',
    scoreStart: 380,
    tiles: [
      { text: 'ào', color: 'pink' },
      { text: 'ời', color: 'orange' },
      { text: 'in', color: 'purple' },
      { text: 'âng', color: 'blue' },
      { text: 'ạ', color: 'green' },
    ],
    rows: [
      { id: 'level-57-1', first: 'ch', answer: 'ào', result: 'chào', speakText: 'chào', color: 'pink' },
      { id: 'level-57-2', first: 'm', answer: 'ời', result: 'mời', speakText: 'mời', color: 'orange' },
      { id: 'level-57-3', first: 'x', answer: 'in', result: 'xin', speakText: 'xin', color: 'purple' },
      { id: 'level-57-4', first: 'v', answer: 'âng', result: 'vâng', speakText: 'vâng', color: 'blue' },
      { id: 'level-57-5', first: 'd', answer: 'ạ', result: 'dạ', speakText: 'dạ', color: 'green' },
    ],
    readWords: ['chào', 'mời', 'xin', 'vâng', 'dạ'],
  },
  {
    id: 'level-58',
    title: 'Ôn tập 1 - Tiếng dễ đọc',
    subtitle: 'Bé ôn lại các tiếng quen thuộc!',
    scoreStart: 385,
    tiles: [
      { text: 'é', color: 'pink' },
      { text: 'ô', color: 'orange' },
      { text: 'á', color: 'purple' },
      { text: 'oa', color: 'blue' },
      { text: 'út', color: 'green' },
    ],
    rows: [
      { id: 'level-58-1', first: 'b', answer: 'é', result: 'bé', speakText: 'bé', color: 'pink' },
      { id: 'level-58-2', first: 'c', answer: 'ô', result: 'cô', speakText: 'cô', color: 'orange' },
      { id: 'level-58-3', first: 'c', answer: 'á', result: 'cá', speakText: 'cá', color: 'purple' },
      { id: 'level-58-4', first: 'h', answer: 'oa', result: 'hoa', speakText: 'hoa', color: 'blue' },
      { id: 'level-58-5', first: 'b', answer: 'út', result: 'bút', speakText: 'bút', color: 'green' },
    ],
    readWords: ['bé', 'cô', 'cá', 'hoa', 'bút'],
  },
  {
    id: 'level-59',
    title: 'Ôn tập 2 - Từ quanh bé',
    subtitle: 'Bé ghép và đọc các tiếng đã học!',
    scoreStart: 390,
    tiles: [
      { text: 'à', color: 'pink' },
      { text: 'ách', color: 'orange' },
      { text: 'èo', color: 'purple' },
      { text: 'àng', color: 'blue' },
      { text: 'uối', color: 'green' },
    ],
    rows: [
      { id: 'level-59-1', first: 'nh', answer: 'à', result: 'nhà', speakText: 'nhà', color: 'pink' },
      { id: 'level-59-2', first: 's', answer: 'ách', result: 'sách', speakText: 'sách', color: 'orange' },
      { id: 'level-59-3', first: 'm', answer: 'èo', result: 'mèo', speakText: 'mèo', color: 'purple' },
      { id: 'level-59-4', first: 'v', answer: 'àng', result: 'vàng', speakText: 'vàng', color: 'blue' },
      { id: 'level-59-5', first: 's', answer: 'uối', result: 'suối', speakText: 'suối', color: 'green' },
    ],
    readWords: ['nhà', 'sách', 'mèo', 'vàng', 'suối'],
  },
  {
    id: 'level-60',
    title: 'Ôn tập 3 - Vần nâng cao',
    subtitle: 'Bé thử sức với các tiếng dài hơn!',
    scoreStart: 395,
    tiles: [
      { text: 'ỏ', color: 'pink' },
      { text: 'ở', color: 'orange' },
      { text: 'âu', color: 'purple' },
      { text: 'ô', color: 'blue' },
      { text: 'à', color: 'green' },
    ],
    rows: [
      { id: 'level-60-1', first: 'th', answer: 'ỏ', result: 'thỏ', speakText: 'thỏ', color: 'pink' },
      { id: 'level-60-2', first: 'ph', answer: 'ở', result: 'phở', speakText: 'phở', color: 'orange' },
      { id: 'level-60-3', first: 'tr', answer: 'âu', result: 'trâu', speakText: 'trâu', color: 'purple' },
      { id: 'level-60-4', first: 'ng', answer: 'ô', result: 'ngô', speakText: 'ngô', color: 'blue' },
      { id: 'level-60-5', first: 'qu', answer: 'à', result: 'quà', speakText: 'quà', color: 'green' },
    ],
    readWords: ['thỏ', 'phở', 'trâu', 'ngô', 'quà'],
  },
];
