export type ConnectNumberCategory =
  | 'one-to-five'
  | 'one-to-seven'
  | 'one-to-ten'
  | 'even-odd-mix'
  | 'mixed';

export type ConnectNumberLevel = 'easy' | 'medium' | 'hard';

export type ConnectNumberPoint = {
  id: string;
  value: number;
  top: string;
  left: string;
};

export type ConnectNumberQuestion = {
  id: string;
  prompt: string;
  hint: string;
  level: ConnectNumberLevel;
  category: ConnectNumberCategory;
  points: ConnectNumberPoint[];
  startNumber: number;
  endNumber: number;
};

export const connectNumberCategories = [
  { key: 'one-to-five', label: 'Từ 1 đến 5', icon: '1️⃣', total: 6 },
  { key: 'one-to-seven', label: 'Từ 1 đến 7', icon: '7️⃣', total: 6 },
  { key: 'one-to-ten', label: 'Từ 1 đến 10', icon: '🔟', total: 6 },
  { key: 'even-odd-mix', label: 'Số chẵn lẻ', icon: '🔢', total: 6 },
  { key: 'mixed', label: 'Tổng hợp', icon: '✨', total: 6 },
] as const;

export const connectNumberData: Record<
  ConnectNumberCategory,
  {
    label: string;
    icon: string;
    questions: ConnectNumberQuestion[];
  }
> = {
  'one-to-five': {
    label: 'Từ 1 đến 5',
    icon: '1️⃣',
    questions: [
      {
        id: 'one-to-five-1',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Bắt đầu từ 1 rồi đến 2, 3, 4, 5',
        level: 'easy',
        category: 'one-to-five',
        startNumber: 1,
        endNumber: 5,
        points: [
          { id: 'a1', value: 3, top: '18%', left: '52%' },
          { id: 'a2', value: 1, top: '65%', left: '12%' },
          { id: 'a3', value: 5, top: '72%', left: '78%' },
          { id: 'a4', value: 2, top: '34%', left: '22%' },
          { id: 'a5', value: 4, top: '30%', left: '76%' },
        ],
      },
      {
        id: 'one-to-five-2',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Bé bấm theo thứ tự tăng dần',
        level: 'easy',
        category: 'one-to-five',
        startNumber: 1,
        endNumber: 5,
        points: [
          { id: 'b1', value: 4, top: '20%', left: '70%' },
          { id: 'b2', value: 2, top: '28%', left: '18%' },
          { id: 'b3', value: 5, top: '74%', left: '62%' },
          { id: 'b4', value: 1, top: '70%', left: '10%' },
          { id: 'b5', value: 3, top: '50%', left: '44%' },
        ],
      },
      {
        id: 'one-to-five-3',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Tìm đúng số tiếp theo mỗi lần',
        level: 'medium',
        category: 'one-to-five',
        startNumber: 1,
        endNumber: 5,
        points: [
          { id: 'c1', value: 2, top: '16%', left: '30%' },
          { id: 'c2', value: 5, top: '68%', left: '82%' },
          { id: 'c3', value: 1, top: '64%', left: '16%' },
          { id: 'c4', value: 4, top: '26%', left: '72%' },
          { id: 'c5', value: 3, top: '46%', left: '50%' },
        ],
      },
      {
        id: 'one-to-five-4',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Quan sát kỹ vị trí các số',
        level: 'medium',
        category: 'one-to-five',
        startNumber: 1,
        endNumber: 5,
        points: [
          { id: 'd1', value: 3, top: '42%', left: '46%' },
          { id: 'd2', value: 5, top: '78%', left: '74%' },
          { id: 'd3', value: 1, top: '18%', left: '14%' },
          { id: 'd4', value: 4, top: '18%', left: '78%' },
          { id: 'd5', value: 2, top: '70%', left: '26%' },
        ],
      },
      {
        id: 'one-to-five-5',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Bé nối thật chính xác',
        level: 'hard',
        category: 'one-to-five',
        startNumber: 1,
        endNumber: 5,
        points: [
          { id: 'e1', value: 4, top: '22%', left: '64%' },
          { id: 'e2', value: 1, top: '52%', left: '14%' },
          { id: 'e3', value: 3, top: '38%', left: '40%' },
          { id: 'e4', value: 5, top: '74%', left: '82%' },
          { id: 'e5', value: 2, top: '16%', left: '16%' },
        ],
      },
      {
        id: 'one-to-five-6',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Nối từ 1 đến 5',
        level: 'hard',
        category: 'one-to-five',
        startNumber: 1,
        endNumber: 5,
        points: [
          { id: 'f1', value: 2, top: '26%', left: '24%' },
          { id: 'f2', value: 4, top: '28%', left: '80%' },
          { id: 'f3', value: 5, top: '72%', left: '60%' },
          { id: 'f4', value: 1, top: '66%', left: '12%' },
          { id: 'f5', value: 3, top: '48%', left: '48%' },
        ],
      },
    ],
  },

  'one-to-seven': {
    label: 'Từ 1 đến 7',
    icon: '7️⃣',
    questions: [
      {
        id: 'one-to-seven-1',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Bắt đầu từ 1 rồi đi tiếp đến 7',
        level: 'easy',
        category: 'one-to-seven',
        startNumber: 1,
        endNumber: 7,
        points: [
          { id: 'g1', value: 1, top: '72%', left: '10%' },
          { id: 'g2', value: 4, top: '20%', left: '46%' },
          { id: 'g3', value: 6, top: '54%', left: '82%' },
          { id: 'g4', value: 2, top: '26%', left: '16%' },
          { id: 'g5', value: 7, top: '76%', left: '62%' },
          { id: 'g6', value: 3, top: '52%', left: '34%' },
          { id: 'g7', value: 5, top: '18%', left: '74%' },
        ],
      },
      {
        id: 'one-to-seven-2',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Nối từ 1 đến 7 theo thứ tự',
        level: 'easy',
        category: 'one-to-seven',
        startNumber: 1,
        endNumber: 7,
        points: [
          { id: 'h1', value: 5, top: '18%', left: '78%' },
          { id: 'h2', value: 1, top: '64%', left: '14%' },
          { id: 'h3', value: 3, top: '40%', left: '38%' },
          { id: 'h4', value: 7, top: '74%', left: '80%' },
          { id: 'h5', value: 2, top: '20%', left: '18%' },
          { id: 'h6', value: 6, top: '50%', left: '62%' },
          { id: 'h7', value: 4, top: '34%', left: '58%' },
        ],
      },
      {
        id: 'one-to-seven-3',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Quan sát kỹ vị trí từng số',
        level: 'medium',
        category: 'one-to-seven',
        startNumber: 1,
        endNumber: 7,
        points: [
          { id: 'i1', value: 2, top: '16%', left: '28%' },
          { id: 'i2', value: 6, top: '28%', left: '82%' },
          { id: 'i3', value: 4, top: '46%', left: '54%' },
          { id: 'i4', value: 7, top: '72%', left: '66%' },
          { id: 'i5', value: 1, top: '70%', left: '12%' },
          { id: 'i6', value: 5, top: '18%', left: '62%' },
          { id: 'i7', value: 3, top: '46%', left: '22%' },
        ],
      },
      {
        id: 'one-to-seven-4',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Nối thật cẩn thận để không nhầm',
        level: 'medium',
        category: 'one-to-seven',
        startNumber: 1,
        endNumber: 7,
        points: [
          { id: 'j1', value: 3, top: '24%', left: '42%' },
          { id: 'j2', value: 1, top: '60%', left: '10%' },
          { id: 'j3', value: 7, top: '72%', left: '84%' },
          { id: 'j4', value: 4, top: '14%', left: '68%' },
          { id: 'j5', value: 6, top: '48%', left: '70%' },
          { id: 'j6', value: 2, top: '28%', left: '16%' },
          { id: 'j7', value: 5, top: '68%', left: '44%' },
        ],
      },
      {
        id: 'one-to-seven-5',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Bé chú ý số tiếp theo mỗi lần',
        level: 'hard',
        category: 'one-to-seven',
        startNumber: 1,
        endNumber: 7,
        points: [
          { id: 'k1', value: 4, top: '20%', left: '52%' },
          { id: 'k2', value: 2, top: '18%', left: '20%' },
          { id: 'k3', value: 1, top: '64%', left: '14%' },
          { id: 'k4', value: 6, top: '42%', left: '82%' },
          { id: 'k5', value: 5, top: '70%', left: '56%' },
          { id: 'k6', value: 3, top: '46%', left: '36%' },
          { id: 'k7', value: 7, top: '78%', left: '82%' },
        ],
      },
      {
        id: 'one-to-seven-6',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Đi lần lượt từ 1 tới 7',
        level: 'hard',
        category: 'one-to-seven',
        startNumber: 1,
        endNumber: 7,
        points: [
          { id: 'l1', value: 5, top: '20%', left: '74%' },
          { id: 'l2', value: 7, top: '74%', left: '64%' },
          { id: 'l3', value: 3, top: '46%', left: '44%' },
          { id: 'l4', value: 1, top: '72%', left: '10%' },
          { id: 'l5', value: 2, top: '22%', left: '14%' },
          { id: 'l6', value: 4, top: '18%', left: '50%' },
          { id: 'l7', value: 6, top: '50%', left: '84%' },
        ],
      },
    ],
  },

  'one-to-ten': {
    label: 'Từ 1 đến 10',
    icon: '🔟',
    questions: [
      {
        id: 'one-to-ten-1',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Nối từ 1 đến 10',
        level: 'easy',
        category: 'one-to-ten',
        startNumber: 1,
        endNumber: 10,
        points: [
          { id: 'm1', value: 1, top: '72%', left: '8%' },
          { id: 'm2', value: 2, top: '18%', left: '12%' },
          { id: 'm3', value: 3, top: '52%', left: '24%' },
          { id: 'm4', value: 4, top: '16%', left: '34%' },
          { id: 'm5', value: 5, top: '68%', left: '42%' },
          { id: 'm6', value: 6, top: '18%', left: '54%' },
          { id: 'm7', value: 7, top: '54%', left: '64%' },
          { id: 'm8', value: 8, top: '16%', left: '74%' },
          { id: 'm9', value: 9, top: '52%', left: '84%' },
          { id: 'm10', value: 10, top: '76%', left: '72%' },
        ],
      },
      {
        id: 'one-to-ten-2',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Tìm đúng số tiếp theo đến 10',
        level: 'easy',
        category: 'one-to-ten',
        startNumber: 1,
        endNumber: 10,
        points: [
          { id: 'n1', value: 4, top: '18%', left: '42%' },
          { id: 'n2', value: 8, top: '20%', left: '82%' },
          { id: 'n3', value: 1, top: '66%', left: '10%' },
          { id: 'n4', value: 6, top: '48%', left: '60%' },
          { id: 'n5', value: 10, top: '76%', left: '78%' },
          { id: 'n6', value: 2, top: '18%', left: '16%' },
          { id: 'n7', value: 9, top: '50%', left: '84%' },
          { id: 'n8', value: 5, top: '74%', left: '42%' },
          { id: 'n9', value: 3, top: '48%', left: '26%' },
          { id: 'n10', value: 7, top: '74%', left: '62%' },
        ],
      },
      {
        id: 'one-to-ten-3',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Quan sát thật kỹ vì có nhiều số hơn',
        level: 'medium',
        category: 'one-to-ten',
        startNumber: 1,
        endNumber: 10,
        points: [
          { id: 'o1', value: 2, top: '18%', left: '18%' },
          { id: 'o2', value: 5, top: '18%', left: '58%' },
          { id: 'o3', value: 9, top: '54%', left: '84%' },
          { id: 'o4', value: 1, top: '72%', left: '8%' },
          { id: 'o5', value: 7, top: '70%', left: '58%' },
          { id: 'o6', value: 6, top: '44%', left: '68%' },
          { id: 'o7', value: 4, top: '44%', left: '36%' },
          { id: 'o8', value: 8, top: '18%', left: '82%' },
          { id: 'o9', value: 10, top: '78%', left: '80%' },
          { id: 'o10', value: 3, top: '48%', left: '16%' },
        ],
      },
      {
        id: 'one-to-ten-4',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Bé nối thật cẩn thận từ 1 đến 10',
        level: 'medium',
        category: 'one-to-ten',
        startNumber: 1,
        endNumber: 10,
        points: [
          { id: 'p1', value: 3, top: '44%', left: '24%' },
          { id: 'p2', value: 6, top: '46%', left: '66%' },
          { id: 'p3', value: 10, top: '76%', left: '70%' },
          { id: 'p4', value: 1, top: '64%', left: '10%' },
          { id: 'p5', value: 4, top: '18%', left: '40%' },
          { id: 'p6', value: 9, top: '48%', left: '84%' },
          { id: 'p7', value: 8, top: '18%', left: '82%' },
          { id: 'p8', value: 5, top: '72%', left: '44%' },
          { id: 'p9', value: 2, top: '18%', left: '14%' },
          { id: 'p10', value: 7, top: '72%', left: '58%' },
        ],
      },
      {
        id: 'one-to-ten-5',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Chú ý số tiếp theo ở mỗi bước',
        level: 'hard',
        category: 'one-to-ten',
        startNumber: 1,
        endNumber: 10,
        points: [
          { id: 'q1', value: 5, top: '16%', left: '56%' },
          { id: 'q2', value: 2, top: '20%', left: '18%' },
          { id: 'q3', value: 7, top: '68%', left: '60%' },
          { id: 'q4', value: 10, top: '76%', left: '84%' },
          { id: 'q5', value: 1, top: '70%', left: '10%' },
          { id: 'q6', value: 6, top: '44%', left: '70%' },
          { id: 'q7', value: 3, top: '44%', left: '30%' },
          { id: 'q8', value: 8, top: '18%', left: '82%' },
          { id: 'q9', value: 4, top: '18%', left: '40%' },
          { id: 'q10', value: 9, top: '52%', left: '86%' },
        ],
      },
      {
        id: 'one-to-ten-6',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Nối lần lượt cho đến số 10',
        level: 'hard',
        category: 'one-to-ten',
        startNumber: 1,
        endNumber: 10,
        points: [
          { id: 'r1', value: 4, top: '18%', left: '36%' },
          { id: 'r2', value: 8, top: '16%', left: '78%' },
          { id: 'r3', value: 3, top: '44%', left: '18%' },
          { id: 'r4', value: 6, top: '44%', left: '62%' },
          { id: 'r5', value: 10, top: '76%', left: '76%' },
          { id: 'r6', value: 2, top: '18%', left: '12%' },
          { id: 'r7', value: 5, top: '70%', left: '42%' },
          { id: 'r8', value: 9, top: '48%', left: '86%' },
          { id: 'r9', value: 1, top: '70%', left: '8%' },
          { id: 'r10', value: 7, top: '72%', left: '60%' },
        ],
      },
    ],
  },

  'even-odd-mix': {
    label: 'Số chẵn lẻ',
    icon: '🔢',
    questions: [
      {
        id: 'even-odd-mix-1',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Có cả số chẵn và số lẻ',
        level: 'easy',
        category: 'even-odd-mix',
        startNumber: 1,
        endNumber: 6,
        points: [
          { id: 's1', value: 2, top: '18%', left: '18%' },
          { id: 's2', value: 5, top: '70%', left: '64%' },
          { id: 's3', value: 1, top: '68%', left: '10%' },
          { id: 's4', value: 4, top: '20%', left: '64%' },
          { id: 's5', value: 6, top: '48%', left: '84%' },
          { id: 's6', value: 3, top: '46%', left: '36%' },
        ],
      },
      {
        id: 'even-odd-mix-2',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Bé chú ý số tăng dần',
        level: 'easy',
        category: 'even-odd-mix',
        startNumber: 1,
        endNumber: 6,
        points: [
          { id: 't1', value: 3, top: '46%', left: '28%' },
          { id: 't2', value: 1, top: '70%', left: '10%' },
          { id: 't3', value: 6, top: '46%', left: '82%' },
          { id: 't4', value: 2, top: '18%', left: '16%' },
          { id: 't5', value: 5, top: '72%', left: '58%' },
          { id: 't6', value: 4, top: '20%', left: '58%' },
        ],
      },
      {
        id: 'even-odd-mix-3',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Quan sát kỹ vị trí các số',
        level: 'medium',
        category: 'even-odd-mix',
        startNumber: 2,
        endNumber: 8,
        points: [
          { id: 'u1', value: 2, top: '66%', left: '10%' },
          { id: 'u2', value: 5, top: '44%', left: '36%' },
          { id: 'u3', value: 8, top: '18%', left: '82%' },
          { id: 'u4', value: 4, top: '18%', left: '24%' },
          { id: 'u5', value: 7, top: '70%', left: '74%' },
          { id: 'u6', value: 3, top: '42%', left: '16%' },
          { id: 'u7', value: 6, top: '20%', left: '56%' },
        ],
      },
      {
        id: 'even-odd-mix-4',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Bé nối từ số nhỏ tới số lớn',
        level: 'medium',
        category: 'even-odd-mix',
        startNumber: 2,
        endNumber: 8,
        points: [
          { id: 'v1', value: 6, top: '42%', left: '68%' },
          { id: 'v2', value: 2, top: '68%', left: '12%' },
          { id: 'v3', value: 4, top: '18%', left: '30%' },
          { id: 'v4', value: 8, top: '18%', left: '84%' },
          { id: 'v5', value: 5, top: '72%', left: '48%' },
          { id: 'v6', value: 3, top: '42%', left: '18%' },
          { id: 'v7', value: 7, top: '70%', left: '76%' },
        ],
      },
      {
        id: 'even-odd-mix-5',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Chú ý số bắt đầu không phải lúc nào cũng là 1',
        level: 'hard',
        category: 'even-odd-mix',
        startNumber: 3,
        endNumber: 9,
        points: [
          { id: 'w1', value: 3, top: '70%', left: '10%' },
          { id: 'w2', value: 6, top: '20%', left: '48%' },
          { id: 'w3', value: 9, top: '72%', left: '84%' },
          { id: 'w4', value: 4, top: '18%', left: '14%' },
          { id: 'w5', value: 5, top: '42%', left: '28%' },
          { id: 'w6', value: 7, top: '44%', left: '68%' },
          { id: 'w7', value: 8, top: '18%', left: '82%' },
        ],
      },
      {
        id: 'even-odd-mix-6',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Bé nối lần lượt cho đúng',
        level: 'hard',
        category: 'even-odd-mix',
        startNumber: 3,
        endNumber: 9,
        points: [
          { id: 'x1', value: 4, top: '18%', left: '18%' },
          { id: 'x2', value: 8, top: '18%', left: '78%' },
          { id: 'x3', value: 3, top: '68%', left: '10%' },
          { id: 'x4', value: 7, top: '70%', left: '60%' },
          { id: 'x5', value: 5, top: '44%', left: '26%' },
          { id: 'x6', value: 6, top: '20%', left: '48%' },
          { id: 'x7', value: 9, top: '46%', left: '86%' },
        ],
      },
    ],
  },

  mixed: {
    label: 'Tổng hợp',
    icon: '✨',
    questions: [
      {
        id: 'mixed-1',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Nối lần lượt thật chính xác',
        level: 'easy',
        category: 'mixed',
        startNumber: 1,
        endNumber: 5,
        points: [
          { id: 'y1', value: 3, top: '18%', left: '48%' },
          { id: 'y2', value: 1, top: '66%', left: '10%' },
          { id: 'y3', value: 5, top: '72%', left: '76%' },
          { id: 'y4', value: 2, top: '28%', left: '16%' },
          { id: 'y5', value: 4, top: '28%', left: '74%' },
        ],
      },
      {
        id: 'mixed-2',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Tìm đúng số tiếp theo',
        level: 'easy',
        category: 'mixed',
        startNumber: 1,
        endNumber: 6,
        points: [
          { id: 'z1', value: 2, top: '18%', left: '18%' },
          { id: 'z2', value: 4, top: '18%', left: '62%' },
          { id: 'z3', value: 1, top: '68%', left: '10%' },
          { id: 'z4', value: 6, top: '48%', left: '82%' },
          { id: 'z5', value: 3, top: '46%', left: '32%' },
          { id: 'z6', value: 5, top: '72%', left: '58%' },
        ],
      },
      {
        id: 'mixed-3',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Quan sát kỹ vị trí từng số',
        level: 'medium',
        category: 'mixed',
        startNumber: 1,
        endNumber: 7,
        points: [
          { id: 'aa1', value: 1, top: '68%', left: '10%' },
          { id: 'aa2', value: 3, top: '42%', left: '30%' },
          { id: 'aa3', value: 5, top: '18%', left: '64%' },
          { id: 'aa4', value: 7, top: '74%', left: '78%' },
          { id: 'aa5', value: 2, top: '20%', left: '18%' },
          { id: 'aa6', value: 4, top: '20%', left: '44%' },
          { id: 'aa7', value: 6, top: '46%', left: '72%' },
        ],
      },
      {
        id: 'mixed-4',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Nối từ nhỏ đến lớn cho đúng',
        level: 'medium',
        category: 'mixed',
        startNumber: 2,
        endNumber: 8,
        points: [
          { id: 'ab1', value: 2, top: '68%', left: '12%' },
          { id: 'ab2', value: 4, top: '18%', left: '26%' },
          { id: 'ab3', value: 6, top: '18%', left: '58%' },
          { id: 'ab4', value: 8, top: '20%', left: '84%' },
          { id: 'ab5', value: 3, top: '44%', left: '18%' },
          { id: 'ab6', value: 5, top: '46%', left: '42%' },
          { id: 'ab7', value: 7, top: '70%', left: '64%' },
        ],
      },
      {
        id: 'mixed-5',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Chú ý chuỗi số dài hơn',
        level: 'hard',
        category: 'mixed',
        startNumber: 1,
        endNumber: 10,
        points: [
          { id: 'ac1', value: 1, top: '70%', left: '8%' },
          { id: 'ac2', value: 2, top: '18%', left: '12%' },
          { id: 'ac3', value: 3, top: '46%', left: '18%' },
          { id: 'ac4', value: 4, top: '18%', left: '36%' },
          { id: 'ac5', value: 5, top: '70%', left: '42%' },
          { id: 'ac6', value: 6, top: '18%', left: '54%' },
          { id: 'ac7', value: 7, top: '72%', left: '58%' },
          { id: 'ac8', value: 8, top: '18%', left: '78%' },
          { id: 'ac9', value: 9, top: '48%', left: '84%' },
          { id: 'ac10', value: 10, top: '76%', left: '72%' },
        ],
      },
      {
        id: 'mixed-6',
        prompt: 'Hãy nối số theo thứ tự từ bé đến lớn',
        hint: 'Bé nối thật cẩn thận từ đầu tới cuối',
        level: 'hard',
        category: 'mixed',
        startNumber: 3,
        endNumber: 9,
        points: [
          { id: 'ad1', value: 3, top: '68%', left: '10%' },
          { id: 'ad2', value: 4, top: '18%', left: '16%' },
          { id: 'ad3', value: 5, top: '44%', left: '28%' },
          { id: 'ad4', value: 6, top: '18%', left: '50%' },
          { id: 'ad5', value: 7, top: '70%', left: '58%' },
          { id: 'ad6', value: 8, top: '18%', left: '80%' },
          { id: 'ad7', value: 9, top: '48%', left: '86%' },
        ],
      },
    ],
  },
};
