export type FishingQuestion = {
  id: number;
  target: string;
  instruction: string;
  fishes: string[];
  mnemonic?: string; // Story/hint để nhớ (e.g., "M như Mèo - giống tai mèo")
  difficulty?: "easy" | "medium" | "hard"; // Adaptive
};

export type FishingLevel = {
  id: string;
  name: string;
  label: string;
  description: string;
  requiredScoreToUpgrade: number;
  questions: FishingQuestion[];
};

export const fishingLevels: FishingLevel[] = [
  {
    id: "level-1",
    name: "Cấp 1",
    label: "Chữ hoa",
    description: "Nhận diện chữ cái in hoa.",
    requiredScoreToUpgrade: 5,
    questions: [
      {
        id: 101,
        target: "B",
        instruction: "Hãy câu con cá có chữ B.",
        fishes: ["A", "B", "C", "D"],
        mnemonic: "B như Bóng - có 2 vòng tròn (B = 2 bóng)",
        difficulty: "easy",
      },
      {
        id: 102,
        target: "M",
        instruction: "Hãy câu con cá có chữ M.",
        fishes: ["N", "M", "H", "K"],
        mnemonic: "M như Mèo - 2 tai nhọn (M = 2 đỉnh)",
        difficulty: "easy",
      },
      {
        id: 103,
        target: "T",
        instruction: "Hãy câu con cá có chữ T.",
        fishes: ["L", "I", "T", "E"],
        mnemonic: "T như cây Tùng - có 1 gốc 1 cành (T = gốc ngang)",
        difficulty: "easy",
      },
      {
        id: 104,
        target: "Đ",
        instruction: "Hãy câu con cá có chữ Đ.",
        fishes: ["D", "Đ", "B", "P"],
        mnemonic: "Đ như Đất - có gạch ngang Đ (D không gạch)",
        difficulty: "easy",
      },
      {
        id: 105,
        target: "A",
        instruction: "Hãy câu con cá có chữ A.",
        fishes: ["A", "B", "C", "D"],
      },
      {
        id: 106,
        target: "C",
        instruction: "Hãy câu con cá có chữ C.",
        fishes: ["C", "G", "O", "Q"],
      },
      {
        id: 107,
        target: "G",
        instruction: "Hãy câu con cá có chữ G.",
        fishes: ["G", "C", "Q", "O"],
      },
      {
        id: 108,
        target: "H",
        instruction: "Hãy câu con cá có chữ H.",
        fishes: ["N", "H", "K", "R"],
      },
      {
        id: 109,
        target: "E",
        instruction: "Hãy câu con cá có chữ E.",
        fishes: ["E", "F", "L", "T"],
      },
      {
        id: 110,
        target: "S",
        instruction: "Hãy câu con cá có chữ S.",
        fishes: ["S", "Z", "5", "8"],
      },
      {
        id: 111,
        target: "V",
        instruction: "Hãy câu con cá có chữ V.",
        fishes: ["V", "U", "W", "Y"],
      },
      {
        id: 112,
        target: "P",
        instruction: "Hãy câu con cá có chữ P.",
        fishes: ["P", "B", "R", "D"],
      },
      {
        id: 113,
        target: "N",
        instruction: "Hãy câu con cá có chữ N.",
        fishes: ["N", "M", "H", "Z"],
      },
      {
        id: 114,
        target: "L",
        instruction: "Hãy câu con cá có chữ L.",
        fishes: ["L", "T", "I", "J"],
      },
      {
        id: 115,
        target: "O",
        instruction: "Hãy câu con cá có chữ O.",
        fishes: ["O", "Q", "D", "C"],
      },
      {
        id: 116,
        target: "R",
        instruction: "Hãy câu con cá có chữ R.",
        fishes: ["R", "P", "B", "K"],
      },
      {
        id: 117,
        target: "U",
        instruction: "Hãy câu con cá có chữ U.",
        fishes: ["U", "V", "W", "Y"],
      },
      {
        id: 118,
        target: "K",
        instruction: "Hãy câu con cá có chữ K.",
        fishes: ["K", "H", "N", "R"],
      },
      {
        id: 119,
        target: "X",
        instruction: "Hãy câu con cá có chữ X.",
        fishes: ["X", "Z", "Y", "K"],
      },
      {
        id: 120,
        target: "W",
        instruction: "Hãy câu con cá có chữ W.",
        fishes: ["W", "V", "U", "M"],
      },
    ],
  },
  {
    id: "level-2",
    name: "Cấp 2",
    label: "Chữ hoa - chữ thường",
    description: "Phân biệt chữ hoa và chữ thường.",
    requiredScoreToUpgrade: 7,
    questions: [
      {
        id: 201,
        target: "A",
        instruction: "Hãy câu chữ A hoa.",
        fishes: ["A", "a", "B", "b"],
      },
      {
        id: 202,
        target: "m",
        instruction: "Hãy câu chữ m thường.",
        fishes: ["M", "m", "N", "n"],
      },
      {
        id: 203,
        target: "e",
        instruction: "Hãy câu chữ e thường.",
        fishes: ["E", "e", "Ê", "ê"],
      },
      {
        id: 204,
        target: "đ",
        instruction: "Hãy câu chữ đ thường.",
        fishes: ["D", "d", "Đ", "đ"],
      },
      {
        id: 205,
        target: "T",
        instruction: "Hãy câu chữ T hoa.",
        fishes: ["T", "t", "L", "l"],
      },
      {
        id: 206,
        target: "c",
        instruction: "Hãy câu chữ c thường.",
        fishes: ["C", "c", "G", "g"],
      },
      {
        id: 207,
        target: "G",
        instruction: "Hãy câu chữ G hoa.",
        fishes: ["G", "g", "C", "c"],
      },
      {
        id: 208,
        target: "h",
        instruction: "Hãy câu chữ h thường.",
        fishes: ["H", "h", "N", "n"],
      },
      {
        id: 209,
        target: "O",
        instruction: "Hãy câu chữ O hoa.",
        fishes: ["O", "o", "Q", "q"],
      },
      {
        id: 210,
        target: "s",
        instruction: "Hãy câu chữ s thường.",
        fishes: ["S", "s", "Z", "z"],
      },
      {
        id: 211,
        target: "V",
        instruction: "Hãy câu chữ V hoa.",
        fishes: ["V", "v", "U", "u"],
      },
      {
        id: 212,
        target: "p",
        instruction: "Hãy câu chữ p thường.",
        fishes: ["P", "p", "B", "b"],
      },
      {
        id: 213,
        target: "N",
        instruction: "Hãy câu chữ N hoa.",
        fishes: ["N", "n", "M", "m"],
      },
      {
        id: 214,
        target: "l",
        instruction: "Hãy câu chữ l thường.",
        fishes: ["L", "l", "T", "t"],
      },
      {
        id: 215,
        target: "R",
        instruction: "Hãy câu chữ R hoa.",
        fishes: ["R", "r", "P", "p"],
      },
      {
        id: 216,
        target: "u",
        instruction: "Hãy câu chữ u thường.",
        fishes: ["U", "u", "V", "v"],
      },
      {
        id: 217,
        target: "K",
        instruction: "Hãy câu chữ K hoa.",
        fishes: ["K", "k", "H", "h"],
      },
      {
        id: 218,
        target: "x",
        instruction: "Hãy câu chữ x thường.",
        fishes: ["X", "x", "Z", "z"],
      },
      {
        id: 219,
        target: "B",
        instruction: "Hãy câu chữ B hoa.",
        fishes: ["B", "b", "P", "p"],
      },
      {
        id: 220,
        target: "w",
        instruction: "Hãy câu chữ w thường.",
        fishes: ["W", "w", "V", "v"],
      },
    ],
  },
  {
    id: "level-3",
    name: "Cấp 3",
    label: "Chữ đầu của từ",
    description: "Tìm chữ cái bắt đầu của từ.",
    requiredScoreToUpgrade: 7,
    questions: [
      {
        id: 301,
        target: "M",
        instruction: "Hãy câu chữ bắt đầu của từ Mèo.",
        fishes: ["M", "B", "C", "T"],
      },
      {
        id: 302,
        target: "C",
        instruction: "Hãy câu chữ bắt đầu của từ Cá.",
        fishes: ["G", "C", "K", "H"],
      },
      {
        id: 303,
        target: "B",
        instruction: "Hãy câu chữ bắt đầu của từ Bóng.",
        fishes: ["P", "D", "B", "Đ"],
      },
      {
        id: 304,
        target: "G",
        instruction: "Hãy câu chữ bắt đầu của từ Gà.",
        fishes: ["C", "G", "K", "Q"],
      },
      {
        id: 305,
        target: "D",
        instruction: "Hãy câu chữ bắt đầu của từ Dâu.",
        fishes: ["D", "T", "B", "Đ"],
      },
      {
        id: 306,
        target: "H",
        instruction: "Hãy câu chữ bắt đầu của từ Hoa.",
        fishes: ["H", "N", "K", "R"],
      },
      {
        id: 307,
        target: "S",
        instruction: "Hãy câu chữ bắt đầu của từ Sách.",
        fishes: ["S", "Z", "T", "X"],
      },
      {
        id: 308,
        target: "T",
        instruction: "Hãy câu chữ bắt đầu của từ Trường.",
        fishes: ["T", "L", "I", "P"],
      },
      {
        id: 309,
        target: "N",
        instruction: "Hãy câu chữ bắt đầu của từ Nhà.",
        fishes: ["N", "M", "H", "K"],
      },
      {
        id: 310,
        target: "V",
        instruction: "Hãy câu chữ bắt đầu của từ Vườn.",
        fishes: ["V", "U", "W", "Y"],
      },
      {
        id: 311,
        target: "L",
        instruction: "Hãy câu chữ bắt đầu của từ Lá.",
        fishes: ["L", "T", "I", "E"],
      },
      {
        id: 312,
        target: "P",
        instruction: "Hãy câu chữ bắt đầu của từ Phần.",
        fishes: ["P", "B", "R", "D"],
      },
      {
        id: 313,
        target: "R",
        instruction: "Hãy câu chữ bắt đầu của từ Rau.",
        fishes: ["R", "P", "B", "K"],
      },
      {
        id: 314,
        target: "Đ",
        instruction: "Hãy câu chữ bắt đầu của từ Đất.",
        fishes: ["Đ", "D", "B", "P"],
      },
      {
        id: 315,
        target: "O",
        instruction: "Hãy câu chữ bắt đầu của từ Ốc.",
        fishes: ["O", "Q", "D", "C"],
      },
      {
        id: 316,
        target: "K",
        instruction: "Hãy câu chữ bắt đầu của từ Kính.",
        fishes: ["K", "H", "N", "R"],
      },
      {
        id: 317,
        target: "A",
        instruction: "Hãy câu chữ bắt đầu của từ Áo.",
        fishes: ["A", "Â", "B", "C"],
      },
      {
        id: 318,
        target: "E",
        instruction: "Hãy câu chữ bắt đầu của từ Ếu.",
        fishes: ["E", "Ê", "A", "Â"],
      },
      {
        id: 319,
        target: "U",
        instruction: "Hãy câu chữ bắt đầu của từ Ưu.",
        fishes: ["U", "Ư", "V", "W"],
      },
      {
        id: 320,
        target: "Â",
        instruction: "Hãy câu chữ bắt đầu của từ Âu.",
        fishes: ["Â", "A", "Ă", "E"],
      },
    ],
  },
  {
    id: "level-4",
    name: "Cấp 4",
    label: "Từ hoàn chỉnh",
    description: "Tìm từ hoàn chỉnh.",
    requiredScoreToUpgrade: 8,
    questions: [
      {
        id: 401,
        target: "MÈO",
        instruction: "Hãy câu từ Mèo.",
        fishes: ["MÈO", "CHÓ", "CÁ", "CHIM"],
      },
      {
        id: 402,
        target: "NHÀ",
        instruction: "Hãy câu từ Nhà.",
        fishes: ["NHÀ", "CÓC", "SÔNG", "NÚI"],
      },
      {
        id: 403,
        target: "CÓM",
        instruction: "Hãy câu từ Cóm.",
        fishes: ["BÚN", "CHÁO", "CÓM", "BÁNH"],
      },
      {
        id: 404,
        target: "SÁCH",
        instruction: "Hãy câu từ Sách.",
        fishes: ["SÁCH", "BÚT", "BÀI", "LỚP"],
      },
      {
        id: 405,
        target: "TRƯỜNG",
        instruction: "Hãy câu từ Trường.",
        fishes: ["TRƯỜNG", "NHÀ", "LỚPKHOA", "PHÒNG"],
      },
      {
        id: 406,
        target: "HỌC",
        instruction: "Hãy câu từ Học.",
        fishes: ["HỌC", "CHƠI", "NGỦ", "LÀM"],
      },
      {
        id: 407,
        target: "CHÓ",
        instruction: "Hãy câu từ Chó.",
        fishes: ["CHÓ", "MÈO", "CÁ", "MỒI"],
      },
      {
        id: 408,
        target: "CHIM",
        instruction: "Hãy câu từ Chim.",
        fishes: ["CHIM", "MÈO", "CÁ", "CHÓ"],
      },
      {
        id: 409,
        target: "CÁ",
        instruction: "Hãy câu từ Cá.",
        fishes: ["CÁ", "CHÓ", "MÈO", "TÔNGÔM"],
      },
      {
        id: 410,
        target: "CHUỐI",
        instruction: "Hãy câu từ Chuối.",
        fishes: ["CHUỐI", "DỨA", "TÁOƯU", "CAM"],
      },
      {
        id: 411,
        target: "ÉT",
        instruction: "Hãy câu từ Táo.",
        fishes: ["TÁODT", "CHUỐI", "DỨA", "CAM"],
      },
      {
        id: 412,
        target: "DỨA",
        instruction: "Hãy câu từ Dứa.",
        fishes: ["DỨA", "CHUỐI", "TÁODT", "CAM"],
      },
      {
        id: 413,
        target: "CAM",
        instruction: "Hãy câu từ Cam.",
        fishes: ["CAM", "DỨA", "CHUỐI", "TÁODT"],
      },
      {
        id: 414,
        target: "NƯỚC",
        instruction: "Hãy câu từ Nước.",
        fishes: ["NƯỚC", "NƯỚC", "NƯỚC", "MÁU"],
      },
      {
        id: 415,
        target: "TRỜ",
        instruction: "Hãy câu từ Trơi.",
        fishes: ["TRƠI", "TRỜI", "TRỜ", "TROI"],
      },
      {
        id: 416,
        target: "TRỜI",
        instruction: "Hãy câu từ Trời.",
        fishes: ["TRỜI", "TRƠI", "TROI", "TRỜ"],
      },
      {
        id: 417,
        target: "ĐẤT",
        instruction: "Hãy câu từ Đất.",
        fishes: ["ĐẤT", "TRỜI", "SÔNG", "NÚITỮ"],
      },
      {
        id: 418,
        target: "LÀ",
        instruction: "Hãy câu từ Lá.",
        fishes: ["LÀ", "CÂY", "CÀNH", "GỐC"],
      },
      {
        id: 419,
        target: "CÂY",
        instruction: "Hãy câu từ Cây.",
        fishes: ["CÂY", "LÀ", "GỐC", "CÀNH"],
      },
      {
        id: 420,
        target: "SÔNG",
        instruction: "Hãy câu từ Sông.",
        fishes: ["SÔNG", "SUỐI", "HỒ", "NƯỚC"],
      },
    ],
  },
  {
    id: "level-5",
    name: "Cấp 5",
    label: "Thử thách cao",
    description: "Từ vựng nâng cao, tốc độ nhanh.",
    requiredScoreToUpgrade: 10,
    questions: [
      {
        id: 501,
        target: "PHẦN",
        instruction: "Hãy câu từ Phần.",
        fishes: ["PHẦN", "NGƯỜI", "VẬT", "ĐÔNG"],
      },
      {
        id: 502,
        target: "THỜI",
        instruction: "Hãy câu từ Thời.",
        fishes: ["THỜI", "ĐẤT", "CÂY", "NỖI"],
      },
      {
        id: 503,
        target: "ĐỘNG",
        instruction: "Hãy câu từ Động.",
        fishes: ["ĐỘNG", "ĐỨNG", "CHUYỂN", "NGỒI"],
      },
      {
        id: 504,
        target: "SẮC",
        instruction: "Hãy câu từ Sắc.",
        fishes: ["SẮC", "ĐẸP", "MÀU", "NHÌN"],
      },
      {
        id: 505,
        target: "ĐÍCH",
        instruction: "Hãy câu từ Đích.",
        fishes: ["ĐÍCH", "CẦU", "HỌC", "HOÀN"],
      },
      {
        id: 506,
        target: "TƯƠNG",
        instruction: "Hãy câu từ Tương.",
        fishes: ["TƯƠNG", "GẬP", "HÌNH", "GIÁC"],
      },
      {
        id: 507,
        target: "NGƯỜI",
        instruction: "Hãy câu từ Người.",
        fishes: ["NGƯỜI", "PHẦN", "VẬT", "ĐỘNG"],
      },
      {
        id: 508,
        target: "THÔNG",
        instruction: "Hãy câu từ Thông.",
        fishes: ["THÔNG", "CHƠI", "ĐẾN", "TRƯỚC"],
      },
      {
        id: 509,
        target: "NGANG",
        instruction: "Hãy câu từ Ngang.",
        fishes: ["NGANG", "DẶC", "MẠNH", "VỮNG"],
      },
      {
        id: 510,
        target: "KHÔNG",
        instruction: "Hãy câu từ Không.",
        fishes: ["KHÔNG", "CÓ", "CÁC", "CỬA"],
      },
      {
        id: 511,
        target: "VẬT",
        instruction: "Hãy câu từ Vật.",
        fishes: ["VẬT", "NGƯỜI", "PHẦN", "ĐỘNG"],
      },
      {
        id: 512,
        target: "NGÔN",
        instruction: "Hãy câu từ Ngôn.",
        fishes: ["NGÔN", "NGÔI", "NỘI", "NGOÀI"],
      },
      {
        id: 513,
        target: "HÌNH",
        instruction: "Hãy câu từ Hình.",
        fishes: ["HÌNH", "TƯƠNG", "GẬP", "GIÁC"],
      },
      {
        id: 514,
        target: "CHƯƠNG",
        instruction: "Hãy câu từ Chương.",
        fishes: ["CHƯƠNG", "TRÌNH", "KỲ", "LỚP"],
      },
      {
        id: 515,
        target: "TRÌNH",
        instruction: "Hãy câu từ Trình.",
        fishes: ["TRÌNH", "CHƯƠNG", "BẬC", "LỚP"],
      },
      {
        id: 516,
        target: "TOÀN",
        instruction: "Hãy câu từ Toàn.",
        fishes: ["TOÀN", "BỘ", "CẢ", "HẾT"],
      },
      {
        id: 517,
        target: "TIỂU",
        instruction: "Hãy câu từ Tiểu.",
        fishes: ["TIỂU", "NHỎ", "CÓT", "BÉ"],
      },
      {
        id: 518,
        target: "TUYỆT",
        instruction: "Hãy câu từ Tuyệt.",
        fishes: ["TUYỆT", "LẠ", "KỲTƯƠNG", "DIỆU"],
      },
      {
        id: 519,
        target: "VỮNG",
        instruction: "Hãy câu từ Vững.",
        fishes: ["VỮNG", "CHẮC", "MẠNH", "CỨNG"],
      },
      {
        id: 520,
        target: "HIỆN",
        instruction: "Hãy câu từ Hiện.",
        fishes: ["HIỆN", "TƯƠI", "SÁNG", "ĐẠI"],
      },
    ],
  },
];
