export type RhymeMatchCategory =
  | 'an'
  | 'at'
  | 'ang'
  | 'on'
  | 'mixed';

export type RhymeMatchLevel = 'easy' | 'medium' | 'hard';

export type RhymeMatchOption = {
  id: string;
  word: string;
  emoji: string;
};

export type RhymeMatchQuestion = {
  id: string;
  prompt: string;
  hint: string;
  level: RhymeMatchLevel;
  category: RhymeMatchCategory;
  targetWord: string;
  targetEmoji: string;
  rhymeKey: string;
  correct: string;
  options: RhymeMatchOption[];
};

export const rhymeMatchCategories = [
  { key: 'an', label: 'Vần an', icon: '🌟', total: 6 },
  { key: 'at', label: 'Vần at', icon: '🎯', total: 6 },
  { key: 'ang', label: 'Vần ang', icon: '🌈', total: 6 },
  { key: 'on', label: 'Vần on', icon: '🎵', total: 6 },
  { key: 'mixed', label: 'Tổng hợp', icon: '✨', total: 6 },
] as const;

export const rhymeMatchData: Record<
  RhymeMatchCategory,
  {
    label: string;
    icon: string;
    questions: RhymeMatchQuestion[];
  }
> = {
  an: {
    label: 'Vần an',
    icon: '🌟',
    questions: [
      {
        id: 'an-1',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Từ cần tìm có vần giống với từ mẫu',
        level: 'easy',
        category: 'an',
        targetWord: 'bàn',
        targetEmoji: '🪑',
        rhymeKey: 'an',
        correct: 'lan',
        options: [
          { id: 'an1', word: 'lan', emoji: '🌸' },
          { id: 'an2', word: 'bút', emoji: '🖊️' },
          { id: 'an3', word: 'mèo', emoji: '🐱' },
          { id: 'an4', word: 'cam', emoji: '🍊' },
        ],
      },
      {
        id: 'an-2',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Nghe và nhìn từ mẫu thật kỹ',
        level: 'easy',
        category: 'an',
        targetWord: 'can',
        targetEmoji: '🥫',
        rhymeKey: 'an',
        correct: 'đan',
        options: [
          { id: 'an5', word: 'đan', emoji: '🧶' },
          { id: 'an6', word: 'bé', emoji: '🧒' },
          { id: 'an7', word: 'gấu', emoji: '🐻' },
          { id: 'an8', word: 'cốc', emoji: '🥤' },
        ],
      },
      {
        id: 'an-3',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Bé chọn từ có vần an',
        level: 'medium',
        category: 'an',
        targetWord: 'san',
        targetEmoji: '🧹',
        rhymeKey: 'an',
        correct: 'tan',
        options: [
          { id: 'an9', word: 'tan', emoji: '🫧' },
          { id: 'an10', word: 'voi', emoji: '🐘' },
          { id: 'an11', word: 'nhà', emoji: '🏠' },
          { id: 'an12', word: 'kem', emoji: '🍦' },
        ],
      },
      {
        id: 'an-4',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Tìm từ có âm cuối giống với từ mẫu',
        level: 'medium',
        category: 'an',
        targetWord: 'van',
        targetEmoji: '🪭',
        rhymeKey: 'an',
        correct: 'ngan',
        options: [
          { id: 'an13', word: 'ngan', emoji: '🦆' },
          { id: 'an14', word: 'kẹo', emoji: '🍬' },
          { id: 'an15', word: 'ly', emoji: '🥛' },
          { id: 'an16', word: 'tủ', emoji: '🗄️' },
        ],
      },
      {
        id: 'an-5',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Nghe kỹ vần ở cuối từ',
        level: 'hard',
        category: 'an',
        targetWord: 'đàn',
        targetEmoji: '🎸',
        rhymeKey: 'an',
        correct: 'tràn',
        options: [
          { id: 'an17', word: 'tràn', emoji: '💧' },
          { id: 'an18', word: 'sách', emoji: '📚' },
          { id: 'an19', word: 'cá', emoji: '🐟' },
          { id: 'an20', word: 'mũ', emoji: '🧢' },
        ],
      },
      {
        id: 'an-6',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Chú ý phần vần giống nhau',
        level: 'hard',
        category: 'an',
        targetWord: 'hàn',
        targetEmoji: '🔥',
        rhymeKey: 'an',
        correct: 'bàn',
        options: [
          { id: 'an21', word: 'bàn', emoji: '🪑' },
          { id: 'an22', word: 'xe', emoji: '🚗' },
          { id: 'an23', word: 'nón', emoji: '👒' },
          { id: 'an24', word: 'gà', emoji: '🐔' },
        ],
      },
    ],
  },

  at: {
    label: 'Vần at',
    icon: '🎯',
    questions: [
      {
        id: 'at-1',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Tìm từ có vần at',
        level: 'easy',
        category: 'at',
        targetWord: 'bát',
        targetEmoji: '🥣',
        rhymeKey: 'at',
        correct: 'cát',
        options: [
          { id: 'at1', word: 'cát', emoji: '🏖️' },
          { id: 'at2', word: 'cam', emoji: '🍊' },
          { id: 'at3', word: 'mèo', emoji: '🐱' },
          { id: 'at4', word: 'bàn', emoji: '🪑' },
        ],
      },
      {
        id: 'at-2',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Từ cần tìm có âm cuối giống từ mẫu',
        level: 'easy',
        category: 'at',
        targetWord: 'hạt',
        targetEmoji: '🌰',
        rhymeKey: 'at',
        correct: 'mắt',
        options: [
          { id: 'at5', word: 'mắt', emoji: '👀' },
          { id: 'at6', word: 'gấu', emoji: '🐻' },
          { id: 'at7', word: 'đèn', emoji: '💡' },
          { id: 'at8', word: 'ly', emoji: '🥛' },
        ],
      },
      {
        id: 'at-3',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Bé tìm từ có vần at',
        level: 'medium',
        category: 'at',
        targetWord: 'mát',
        targetEmoji: '🍃',
        rhymeKey: 'at',
        correct: 'phát',
        options: [
          { id: 'at9', word: 'phát', emoji: '📢' },
          { id: 'at10', word: 'voi', emoji: '🐘' },
          { id: 'at11', word: 'nhà', emoji: '🏠' },
          { id: 'at12', word: 'kẹo', emoji: '🍬' },
        ],
      },
      {
        id: 'at-4',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Nghe kỹ phần cuối của từ',
        level: 'medium',
        category: 'at',
        targetWord: 'chát',
        targetEmoji: '🍋',
        rhymeKey: 'at',
        correct: 'đạt',
        options: [
          { id: 'at13', word: 'đạt', emoji: '🏆' },
          { id: 'at14', word: 'gà', emoji: '🐔' },
          { id: 'at15', word: 'sữa', emoji: '🥛' },
          { id: 'at16', word: 'cặp', emoji: '🎒' },
        ],
      },
      {
        id: 'at-5',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Tìm từ cùng vần với từ mẫu',
        level: 'hard',
        category: 'at',
        targetWord: 'khát',
        targetEmoji: '🥵',
        rhymeKey: 'at',
        correct: 'ngạt',
        options: [
          { id: 'at17', word: 'ngạt', emoji: '😮‍💨' },
          { id: 'at18', word: 'bút', emoji: '🖊️' },
          { id: 'at19', word: 'cam', emoji: '🍊' },
          { id: 'at20', word: 'mũ', emoji: '🧢' },
        ],
      },
      {
        id: 'at-6',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Bé chú ý phần vần cuối',
        level: 'hard',
        category: 'at',
        targetWord: 'nhặt',
        targetEmoji: '🧺',
        rhymeKey: 'at',
        correct: 'thắt',
        options: [
          { id: 'at21', word: 'thắt', emoji: '🎀' },
          { id: 'at22', word: 'nho', emoji: '🍇' },
          { id: 'at23', word: 'bò', emoji: '🐮' },
          { id: 'at24', word: 'sách', emoji: '📘' },
        ],
      },
    ],
  },

  ang: {
    label: 'Vần ang',
    icon: '🌈',
    questions: [
      {
        id: 'ang-1',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Tìm từ có vần ang',
        level: 'easy',
        category: 'ang',
        targetWord: 'mang',
        targetEmoji: '🎒',
        rhymeKey: 'ang',
        correct: 'sang',
        options: [
          { id: 'ang1', word: 'sang', emoji: '✨' },
          { id: 'ang2', word: 'mèo', emoji: '🐱' },
          { id: 'ang3', word: 'bát', emoji: '🥣' },
          { id: 'ang4', word: 'cam', emoji: '🍊' },
        ],
      },
      {
        id: 'ang-2',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Nghe và chọn từ có vần giống',
        level: 'easy',
        category: 'ang',
        targetWord: 'vang',
        targetEmoji: '🔔',
        rhymeKey: 'ang',
        correct: 'trang',
        options: [
          { id: 'ang5', word: 'trang', emoji: '📄' },
          { id: 'ang6', word: 'bút', emoji: '🖊️' },
          { id: 'ang7', word: 'cá', emoji: '🐟' },
          { id: 'ang8', word: 'ly', emoji: '🥛' },
        ],
      },
      {
        id: 'ang-3',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Bé chọn từ cùng vần ang',
        level: 'medium',
        category: 'ang',
        targetWord: 'thang',
        targetEmoji: '🪜',
        rhymeKey: 'ang',
        correct: 'giang',
        options: [
          { id: 'ang9', word: 'giang', emoji: '🌿' },
          { id: 'ang10', word: 'voi', emoji: '🐘' },
          { id: 'ang11', word: 'kẹo', emoji: '🍬' },
          { id: 'ang12', word: 'đèn', emoji: '💡' },
        ],
      },
      {
        id: 'ang-4',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Nghe kỹ phần cuối của từ',
        level: 'medium',
        category: 'ang',
        targetWord: 'nắng',
        targetEmoji: '☀️',
        rhymeKey: 'ang',
        correct: 'trắng',
        options: [
          { id: 'ang13', word: 'trắng', emoji: '⬜' },
          { id: 'ang14', word: 'gấu', emoji: '🐻' },
          { id: 'ang15', word: 'cặp', emoji: '🎒' },
          { id: 'ang16', word: 'bàn', emoji: '🪑' },
        ],
      },
      {
        id: 'ang-5',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Tìm từ có âm cuối giống với từ mẫu',
        level: 'hard',
        category: 'ang',
        targetWord: 'hang',
        targetEmoji: '🕳️',
        rhymeKey: 'ang',
        correct: 'giăng',
        options: [
          { id: 'ang17', word: 'giăng', emoji: '🕸️' },
          { id: 'ang18', word: 'mũ', emoji: '🧢' },
          { id: 'ang19', word: 'sách', emoji: '📚' },
          { id: 'ang20', word: 'nho', emoji: '🍇' },
        ],
      },
      {
        id: 'ang-6',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Bé để ý phần vần cuối',
        level: 'hard',
        category: 'ang',
        targetWord: 'đang',
        targetEmoji: '🏃',
        rhymeKey: 'ang',
        correct: 'hoang',
        options: [
          { id: 'ang21', word: 'hoang', emoji: '🌾' },
          { id: 'ang22', word: 'bò', emoji: '🐮' },
          { id: 'ang23', word: 'thước', emoji: '📏' },
          { id: 'ang24', word: 'cam', emoji: '🍊' },
        ],
      },
    ],
  },

  on: {
    label: 'Vần on',
    icon: '🎵',
    questions: [
      {
        id: 'on-1',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Tìm từ có vần on',
        level: 'easy',
        category: 'on',
        targetWord: 'con',
        targetEmoji: '🐣',
        rhymeKey: 'on',
        correct: 'son',
        options: [
          { id: 'on1', word: 'son', emoji: '💄' },
          { id: 'on2', word: 'cam', emoji: '🍊' },
          { id: 'on3', word: 'mèo', emoji: '🐱' },
          { id: 'on4', word: 'bút', emoji: '🖊️' },
        ],
      },
      {
        id: 'on-2',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Nghe kỹ âm cuối của từ',
        level: 'easy',
        category: 'on',
        targetWord: 'non',
        targetEmoji: '🌱',
        rhymeKey: 'on',
        correct: 'tròn',
        options: [
          { id: 'on5', word: 'tròn', emoji: '⚪' },
          { id: 'on6', word: 'gấu', emoji: '🐻' },
          { id: 'on7', word: 'ly', emoji: '🥛' },
          { id: 'on8', word: 'kẹo', emoji: '🍬' },
        ],
      },
      {
        id: 'on-3',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Bé chọn từ cùng vần on',
        level: 'medium',
        category: 'on',
        targetWord: 'mòn',
        targetEmoji: '🪵',
        rhymeKey: 'on',
        correct: 'giòn',
        options: [
          { id: 'on9', word: 'giòn', emoji: '🍘' },
          { id: 'on10', word: 'voi', emoji: '🐘' },
          { id: 'on11', word: 'bàn', emoji: '🪑' },
          { id: 'on12', word: 'đèn', emoji: '💡' },
        ],
      },
      {
        id: 'on-4',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Tìm từ có phần vần giống',
        level: 'medium',
        category: 'on',
        targetWord: 'thôn',
        targetEmoji: '🏡',
        rhymeKey: 'on',
        correct: 'cồn',
        options: [
          { id: 'on13', word: 'cồn', emoji: '🏝️' },
          { id: 'on14', word: 'mũ', emoji: '🧢' },
          { id: 'on15', word: 'sách', emoji: '📘' },
          { id: 'on16', word: 'nho', emoji: '🍇' },
        ],
      },
      {
        id: 'on-5',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Nghe thật kỹ vần ở cuối',
        level: 'hard',
        category: 'on',
        targetWord: 'khôn',
        targetEmoji: '🧠',
        rhymeKey: 'on',
        correct: 'lớn',
        options: [
          { id: 'on17', word: 'lớn', emoji: '📈' },
          { id: 'on18', word: 'cá', emoji: '🐟' },
          { id: 'on19', word: 'cam', emoji: '🍊' },
          { id: 'on20', word: 'bút', emoji: '🖊️' },
        ],
      },
      {
        id: 'on-6',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Bé chú ý phần cuối từ mẫu',
        level: 'hard',
        category: 'on',
        targetWord: 'dọn',
        targetEmoji: '🧹',
        rhymeKey: 'on',
        correct: 'chọn',
        options: [
          { id: 'on21', word: 'chọn', emoji: '✅' },
          { id: 'on22', word: 'xe', emoji: '🚗' },
          { id: 'on23', word: 'gà', emoji: '🐔' },
          { id: 'on24', word: 'bàn', emoji: '🪑' },
        ],
      },
    ],
  },

  mixed: {
    label: 'Tổng hợp',
    icon: '✨',
    questions: [
      {
        id: 'mixed-1',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Nghe từ mẫu rồi tìm từ có vần giống',
        level: 'easy',
        category: 'mixed',
        targetWord: 'bàn',
        targetEmoji: '🪑',
        rhymeKey: 'an',
        correct: 'lan',
        options: [
          { id: 'm1', word: 'lan', emoji: '🌸' },
          { id: 'm2', word: 'bút', emoji: '🖊️' },
          { id: 'm3', word: 'mèo', emoji: '🐱' },
          { id: 'm4', word: 'cá', emoji: '🐟' },
        ],
      },
      {
        id: 'mixed-2',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Tìm từ có phần cuối giống với từ mẫu',
        level: 'easy',
        category: 'mixed',
        targetWord: 'bát',
        targetEmoji: '🥣',
        rhymeKey: 'at',
        correct: 'cát',
        options: [
          { id: 'm5', word: 'cát', emoji: '🏖️' },
          { id: 'm6', word: 'cam', emoji: '🍊' },
          { id: 'm7', word: 'ly', emoji: '🥛' },
          { id: 'm8', word: 'gấu', emoji: '🐻' },
        ],
      },
      {
        id: 'mixed-3',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Bé chọn từ cùng vần với từ mẫu',
        level: 'medium',
        category: 'mixed',
        targetWord: 'mang',
        targetEmoji: '🎒',
        rhymeKey: 'ang',
        correct: 'sang',
        options: [
          { id: 'm9', word: 'sang', emoji: '✨' },
          { id: 'm10', word: 'kẹo', emoji: '🍬' },
          { id: 'm11', word: 'voi', emoji: '🐘' },
          { id: 'm12', word: 'sách', emoji: '📘' },
        ],
      },
      {
        id: 'mixed-4',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Nghe kỹ âm cuối của từ mẫu',
        level: 'medium',
        category: 'mixed',
        targetWord: 'con',
        targetEmoji: '🐣',
        rhymeKey: 'on',
        correct: 'son',
        options: [
          { id: 'm13', word: 'son', emoji: '💄' },
          { id: 'm14', word: 'cam', emoji: '🍊' },
          { id: 'm15', word: 'bút', emoji: '🖊️' },
          { id: 'm16', word: 'mèo', emoji: '🐱' },
        ],
      },
      {
        id: 'mixed-5',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Chú ý phần vần của từ mẫu',
        level: 'hard',
        category: 'mixed',
        targetWord: 'hạt',
        targetEmoji: '🌰',
        rhymeKey: 'at',
        correct: 'mắt',
        options: [
          { id: 'm17', word: 'mắt', emoji: '👀' },
          { id: 'm18', word: 'gà', emoji: '🐔' },
          { id: 'm19', word: 'sách', emoji: '📚' },
          { id: 'm20', word: 'cam', emoji: '🍊' },
        ],
      },
      {
        id: 'mixed-6',
        prompt: 'Hãy chọn từ có vần giống nhau',
        hint: 'Bé tìm từ có vần giống với từ mẫu',
        level: 'hard',
        category: 'mixed',
        targetWord: 'non',
        targetEmoji: '🌱',
        rhymeKey: 'on',
        correct: 'tròn',
        options: [
          { id: 'm21', word: 'tròn', emoji: '⚪' },
          { id: 'm22', word: 'bàn', emoji: '🪑' },
          { id: 'm23', word: 'mũ', emoji: '🧢' },
          { id: 'm24', word: 'cá', emoji: '🐟' },
        ],
      },
    ],
  },
};
